In [7]:
import pandas as pd
import os
import numpy as np
import scipy as sp
import torch

In [8]:
from scipy.stats import uniform, norm
import seaborn as sns; sns.set()
import matplotlib.pyplot as plt

In [9]:
A = 1.2
b = -0.3
sigma = 0.2
N = 100

In [10]:
X = torch.from_numpy(uniform.rvs(size=N))
X.detach()
X = X.float()

In [11]:
e = torch.from_numpy(norm.rvs(loc=0, scale=sigma, size=N)).float()

In [12]:
y = A*X + b + e

In [13]:
y.detach()
y = y.float()

In [14]:
def sigma_to_rho(sigma):
    rho = torch.log(torch.exp(sigma) - 1)
    return rho

In [15]:
def rho_to_sigma(rho):
    sigma = torch.log(1 + torch.exp(rho))
    return sigma

In [16]:
def log_q_pdf(w, theta):
    (mu_A, mu_b, rho_A, rho_b) = theta 
    
    sigma_A = rho_to_sigma(rho_A)
    qA = torch.distributions.normal.Normal(mu_A, sigma_A)
    
    sigma_b = rho_to_sigma(rho_b)
    qb = torch.distributions.normal.Normal(mu_b, sigma_b)
    
    lp = qA.log_prob(w[0]) + qb.log_prob(w[1])
    return lp

In [17]:
def log_p_pdf(w):
    prior_mu_A = torch.tensor(0.0) 
    prior_sigma_A = torch.tensor(1.0)
    pA = torch.distributions.normal.Normal(prior_mu_A, prior_sigma_A)
    
    prior_mu_b = torch.tensor(0.0) 
    prior_sigma_b = torch.tensor(1.0)
    pb = torch.distributions.normal.Normal(prior_mu_b, prior_sigma_b)
    
    lp = pA.log_prob(w[0]) + pb.log_prob(w[1])
    return lp

In [18]:
def likelihood(y,X,w):
    A = w[0]
    b = w[1]
    
    y_pred = A*X + b
    lp = torch.distributions.normal.Normal(y_pred, 0.2).log_prob(y).sum()
    return lp

In [19]:
def f(w, theta):
    v = log_q_pdf(w, theta) - log_p_pdf(w) - likelihood(y,X,w)
    return v

In [20]:
mu_A = torch.tensor(1.0)
sigma_A = torch.tensor(0.1)
rho_A = sigma_to_rho(sigma_A)
mu_b = torch.tensor(-0.4)
sigma_b = torch.tensor(0.1)
rho_b = sigma_to_rho(sigma_b)

theta = torch.tensor([mu_A, mu_b, rho_A, rho_b], requires_grad=True)

In [21]:

lst_grad_mu = []
lst_grad_rho = []
for j in range(0,5000):
    epsilon = torch.distributions.normal.Normal(torch.tensor(0.0) , torch.tensor(1.0)).sample(torch.Size([2,]))

    with torch.no_grad():
        w = theta[0:2].clone().detach() + torch.log(1 + torch.exp(theta[2:4].clone().detach()))*epsilon
    w.requires_grad = True

    v = f(w, theta)   
    v.backward()
    v = torch.tensor([])

    with torch.no_grad():
        grad_mu = w.grad + theta.grad[0:2]
        grad_rho = w.grad*epsilon/(1 + torch.exp(-theta[2:4])) + -theta.grad[2:4]


    lst_grad_mu.append(grad_mu)
    lst_grad_rho.append(grad_rho)

    theta.grad.zero_()
    w.grad.zero_()
    v.detach()
grad_mu = torch.stack(lst_grad_mu).mean(dim=0)
grad_rho = torch.stack(lst_grad_rho).mean(dim=0)
        
 



In [22]:
grad_mu

tensor([-327.6238, -497.1631])

In [23]:
grad_rho

tensor([ 7.3430, 22.6629])

In [24]:
alpha = torch.tensor(10e-5)

In [25]:
for i in range(0,10000):
    lst_grad_mu = []
    lst_grad_rho = []
    for j in range(0,10):
        epsilon = torch.distributions.normal.Normal(torch.tensor(0.0) , torch.tensor(1.0)).sample(torch.Size([2,]))

        with torch.no_grad():
            w = theta[0:2].clone().detach() + torch.log(1 + torch.exp(theta[2:4].clone().detach()))*epsilon
        w.requires_grad = True

        v = f(w, theta)   
        v.backward()
        v = torch.tensor([])

        with torch.no_grad():
            grad_mu = w.grad + theta.grad[0:2]
            grad_rho = w.grad*epsilon/(1 + torch.exp(-theta[2:4])) + -theta.grad[2:4]


        lst_grad_mu.append(grad_mu)
        lst_grad_rho.append(grad_rho)

        theta.grad.zero_()
        w.grad.zero_()
        v.detach()
    grad_mu = torch.stack(lst_grad_mu).mean(dim=0)
    grad_rho = torch.stack(lst_grad_rho).mean(dim=0)
    
    #print(grad_mu)
    #print(grad_rho)
        
    with torch.no_grad():
        theta[0:2] -= alpha*grad_mu
        theta[2:4] -= alpha*grad_rho
    
    print(theta)



tensor([ 1.0318, -0.3514, -2.2528, -2.2545], requires_grad=True)
tensor([ 1.0583, -0.3136, -2.2547, -2.2566], requires_grad=True)
tensor([ 1.0719, -0.2981, -2.2551, -2.2571], requires_grad=True)
tensor([ 1.0782, -0.2972, -2.2554, -2.2592], requires_grad=True)
tensor([ 1.0988, -0.2715, -2.2579, -2.2620], requires_grad=True)
tensor([ 1.1124, -0.2561, -2.2581, -2.2662], requires_grad=True)
tensor([ 1.1139, -0.2624, -2.2590, -2.2687], requires_grad=True)
tensor([ 1.1188, -0.2616, -2.2595, -2.2711], requires_grad=True)
tensor([ 1.1206, -0.2670, -2.2596, -2.2737], requires_grad=True)
tensor([ 1.1340, -0.2506, -2.2610, -2.2761], requires_grad=True)
tensor([ 1.1377, -0.2503, -2.2617, -2.2783], requires_grad=True)
tensor([ 1.1399, -0.2547, -2.2626, -2.2801], requires_grad=True)
tensor([ 1.1370, -0.2713, -2.2632, -2.2848], requires_grad=True)
tensor([ 1.1383, -0.2757, -2.2639, -2.2861], requires_grad=True)
tensor([ 1.1500, -0.2621, -2.2648, -2.2894], requires_grad=True)
tensor([ 1.1671, -0.2404,

tensor([ 1.3035, -0.3547, -2.3557, -2.5001], requires_grad=True)
tensor([ 1.3071, -0.3488, -2.3564, -2.5010], requires_grad=True)
tensor([ 1.3054, -0.3528, -2.3566, -2.5024], requires_grad=True)
tensor([ 1.3051, -0.3540, -2.3569, -2.5031], requires_grad=True)
tensor([ 1.3071, -0.3509, -2.3571, -2.5035], requires_grad=True)
tensor([ 1.3046, -0.3566, -2.3572, -2.5047], requires_grad=True)
tensor([ 1.3047, -0.3567, -2.3577, -2.5058], requires_grad=True)
tensor([ 1.3065, -0.3543, -2.3594, -2.5090], requires_grad=True)
tensor([ 1.3044, -0.3587, -2.3597, -2.5094], requires_grad=True)
tensor([ 1.3036, -0.3601, -2.3598, -2.5100], requires_grad=True)
tensor([ 1.3078, -0.3533, -2.3606, -2.5117], requires_grad=True)
tensor([ 1.3067, -0.3553, -2.3610, -2.5124], requires_grad=True)
tensor([ 1.3010, -0.3657, -2.3621, -2.5141], requires_grad=True)
tensor([ 1.3011, -0.3656, -2.3624, -2.5150], requires_grad=True)
tensor([ 1.3103, -0.3509, -2.3628, -2.5159], requires_grad=True)
tensor([ 1.3064, -0.3585,

tensor([ 1.3206, -0.3708, -2.4263, -2.6582], requires_grad=True)
tensor([ 1.3207, -0.3694, -2.4265, -2.6584], requires_grad=True)
tensor([ 1.3218, -0.3663, -2.4274, -2.6592], requires_grad=True)
tensor([ 1.3159, -0.3765, -2.4280, -2.6605], requires_grad=True)
tensor([ 1.3213, -0.3670, -2.4283, -2.6611], requires_grad=True)
tensor([ 1.3260, -0.3580, -2.4288, -2.6615], requires_grad=True)
tensor([ 1.3285, -0.3545, -2.4294, -2.6622], requires_grad=True)
tensor([ 1.3273, -0.3567, -2.4302, -2.6632], requires_grad=True)
tensor([ 1.3247, -0.3620, -2.4306, -2.6642], requires_grad=True)
tensor([ 1.3249, -0.3606, -2.4304, -2.6653], requires_grad=True)
tensor([ 1.3231, -0.3640, -2.4312, -2.6670], requires_grad=True)
tensor([ 1.3307, -0.3509, -2.4316, -2.6682], requires_grad=True)
tensor([ 1.3259, -0.3593, -2.4327, -2.6691], requires_grad=True)
tensor([ 1.3220, -0.3660, -2.4327, -2.6703], requires_grad=True)
tensor([ 1.3181, -0.3734, -2.4332, -2.6710], requires_grad=True)
tensor([ 1.3175, -0.3745,

tensor([ 1.3246, -0.3581, -2.4908, -2.7689], requires_grad=True)
tensor([ 1.3200, -0.3667, -2.4909, -2.7693], requires_grad=True)
tensor([ 1.3189, -0.3679, -2.4912, -2.7700], requires_grad=True)
tensor([ 1.3204, -0.3660, -2.4916, -2.7710], requires_grad=True)
tensor([ 1.3231, -0.3617, -2.4921, -2.7731], requires_grad=True)
tensor([ 1.3278, -0.3547, -2.4924, -2.7737], requires_grad=True)
tensor([ 1.3246, -0.3614, -2.4930, -2.7754], requires_grad=True)
tensor([ 1.3251, -0.3614, -2.4933, -2.7765], requires_grad=True)
tensor([ 1.3225, -0.3671, -2.4935, -2.7769], requires_grad=True)
tensor([ 1.3255, -0.3615, -2.4937, -2.7783], requires_grad=True)
tensor([ 1.3203, -0.3715, -2.4940, -2.7794], requires_grad=True)
tensor([ 1.3200, -0.3705, -2.4942, -2.7801], requires_grad=True)
tensor([ 1.3300, -0.3535, -2.4956, -2.7816], requires_grad=True)
tensor([ 1.3260, -0.3612, -2.4962, -2.7821], requires_grad=True)
tensor([ 1.3252, -0.3627, -2.4970, -2.7828], requires_grad=True)
tensor([ 1.3280, -0.3592,

tensor([ 1.3174, -0.3778, -2.5460, -2.8661], requires_grad=True)
tensor([ 1.3232, -0.3674, -2.5461, -2.8670], requires_grad=True)
tensor([ 1.3261, -0.3625, -2.5463, -2.8673], requires_grad=True)
tensor([ 1.3155, -0.3812, -2.5470, -2.8682], requires_grad=True)
tensor([ 1.3154, -0.3818, -2.5474, -2.8692], requires_grad=True)
tensor([ 1.3187, -0.3765, -2.5480, -2.8702], requires_grad=True)
tensor([ 1.3215, -0.3713, -2.5485, -2.8713], requires_grad=True)
tensor([ 1.3239, -0.3668, -2.5486, -2.8719], requires_grad=True)
tensor([ 1.3180, -0.3763, -2.5491, -2.8727], requires_grad=True)
tensor([ 1.3240, -0.3669, -2.5495, -2.8731], requires_grad=True)
tensor([ 1.3252, -0.3649, -2.5500, -2.8734], requires_grad=True)
tensor([ 1.3235, -0.3688, -2.5502, -2.8738], requires_grad=True)
tensor([ 1.3279, -0.3616, -2.5513, -2.8749], requires_grad=True)
tensor([ 1.3281, -0.3612, -2.5516, -2.8753], requires_grad=True)
tensor([ 1.3314, -0.3547, -2.5518, -2.8762], requires_grad=True)
tensor([ 1.3323, -0.3526,

tensor([ 1.3269, -0.3603, -2.5963, -2.9455], requires_grad=True)
tensor([ 1.3265, -0.3610, -2.5967, -2.9460], requires_grad=True)
tensor([ 1.3231, -0.3671, -2.5974, -2.9468], requires_grad=True)
tensor([ 1.3240, -0.3667, -2.5978, -2.9474], requires_grad=True)
tensor([ 1.3267, -0.3614, -2.5981, -2.9480], requires_grad=True)
tensor([ 1.3256, -0.3631, -2.5984, -2.9483], requires_grad=True)
tensor([ 1.3253, -0.3640, -2.5989, -2.9488], requires_grad=True)
tensor([ 1.3254, -0.3647, -2.5992, -2.9489], requires_grad=True)
tensor([ 1.3258, -0.3636, -2.5996, -2.9494], requires_grad=True)
tensor([ 1.3245, -0.3661, -2.5998, -2.9501], requires_grad=True)
tensor([ 1.3290, -0.3594, -2.6001, -2.9503], requires_grad=True)
tensor([ 1.3245, -0.3677, -2.6004, -2.9509], requires_grad=True)
tensor([ 1.3266, -0.3632, -2.6005, -2.9517], requires_grad=True)
tensor([ 1.3303, -0.3561, -2.6008, -2.9525], requires_grad=True)
tensor([ 1.3268, -0.3618, -2.6009, -2.9529], requires_grad=True)
tensor([ 1.3249, -0.3648,

tensor([ 1.3273, -0.3634, -2.6374, -3.0123], requires_grad=True)
tensor([ 1.3219, -0.3730, -2.6377, -3.0129], requires_grad=True)
tensor([ 1.3230, -0.3707, -2.6380, -3.0137], requires_grad=True)
tensor([ 1.3223, -0.3709, -2.6384, -3.0140], requires_grad=True)
tensor([ 1.3195, -0.3760, -2.6387, -3.0146], requires_grad=True)
tensor([ 1.3145, -0.3852, -2.6394, -3.0157], requires_grad=True)
tensor([ 1.3206, -0.3743, -2.6401, -3.0163], requires_grad=True)
tensor([ 1.3193, -0.3772, -2.6403, -3.0168], requires_grad=True)
tensor([ 1.3208, -0.3749, -2.6404, -3.0170], requires_grad=True)
tensor([ 1.3286, -0.3623, -2.6410, -3.0175], requires_grad=True)
tensor([ 1.3269, -0.3643, -2.6411, -3.0179], requires_grad=True)
tensor([ 1.3240, -0.3690, -2.6414, -3.0184], requires_grad=True)
tensor([ 1.3269, -0.3647, -2.6417, -3.0187], requires_grad=True)
tensor([ 1.3229, -0.3714, -2.6420, -3.0192], requires_grad=True)
tensor([ 1.3268, -0.3652, -2.6422, -3.0196], requires_grad=True)
tensor([ 1.3256, -0.3684,

tensor([ 1.3290, -0.3596, -2.6787, -3.0719], requires_grad=True)
tensor([ 1.3263, -0.3640, -2.6789, -3.0724], requires_grad=True)
tensor([ 1.3278, -0.3623, -2.6791, -3.0729], requires_grad=True)
tensor([ 1.3289, -0.3598, -2.6796, -3.0734], requires_grad=True)
tensor([ 1.3255, -0.3653, -2.6800, -3.0741], requires_grad=True)
tensor([ 1.3270, -0.3631, -2.6804, -3.0745], requires_grad=True)
tensor([ 1.3273, -0.3634, -2.6807, -3.0748], requires_grad=True)
tensor([ 1.3320, -0.3558, -2.6812, -3.0752], requires_grad=True)
tensor([ 1.3276, -0.3645, -2.6813, -3.0757], requires_grad=True)
tensor([ 1.3284, -0.3621, -2.6816, -3.0759], requires_grad=True)
tensor([ 1.3284, -0.3619, -2.6819, -3.0762], requires_grad=True)
tensor([ 1.3229, -0.3720, -2.6822, -3.0768], requires_grad=True)
tensor([ 1.3247, -0.3694, -2.6822, -3.0768], requires_grad=True)
tensor([ 1.3237, -0.3710, -2.6824, -3.0771], requires_grad=True)
tensor([ 1.3251, -0.3689, -2.6825, -3.0775], requires_grad=True)
tensor([ 1.3279, -0.3642,

tensor([ 1.3280, -0.3591, -2.7151, -3.1249], requires_grad=True)
tensor([ 1.3229, -0.3682, -2.7154, -3.1251], requires_grad=True)
tensor([ 1.3243, -0.3667, -2.7157, -3.1255], requires_grad=True)
tensor([ 1.3225, -0.3705, -2.7159, -3.1258], requires_grad=True)
tensor([ 1.3268, -0.3637, -2.7163, -3.1262], requires_grad=True)
tensor([ 1.3259, -0.3652, -2.7164, -3.1265], requires_grad=True)
tensor([ 1.3265, -0.3645, -2.7166, -3.1268], requires_grad=True)
tensor([ 1.3247, -0.3671, -2.7168, -3.1270], requires_grad=True)
tensor([ 1.3271, -0.3636, -2.7171, -3.1273], requires_grad=True)
tensor([ 1.3238, -0.3701, -2.7174, -3.1277], requires_grad=True)
tensor([ 1.3215, -0.3743, -2.7176, -3.1280], requires_grad=True)
tensor([ 1.3217, -0.3734, -2.7177, -3.1282], requires_grad=True)
tensor([ 1.3190, -0.3764, -2.7179, -3.1286], requires_grad=True)
tensor([ 1.3225, -0.3705, -2.7182, -3.1289], requires_grad=True)
tensor([ 1.3224, -0.3703, -2.7186, -3.1294], requires_grad=True)
tensor([ 1.3209, -0.3721,

tensor([ 1.3194, -0.3705, -2.7496, -3.1712], requires_grad=True)
tensor([ 1.3190, -0.3728, -2.7498, -3.1714], requires_grad=True)
tensor([ 1.3186, -0.3734, -2.7502, -3.1718], requires_grad=True)
tensor([ 1.3213, -0.3686, -2.7504, -3.1720], requires_grad=True)
tensor([ 1.3229, -0.3657, -2.7505, -3.1723], requires_grad=True)
tensor([ 1.3248, -0.3621, -2.7508, -3.1725], requires_grad=True)
tensor([ 1.3242, -0.3643, -2.7508, -3.1728], requires_grad=True)
tensor([ 1.3207, -0.3703, -2.7510, -3.1733], requires_grad=True)
tensor([ 1.3213, -0.3683, -2.7512, -3.1735], requires_grad=True)
tensor([ 1.3233, -0.3654, -2.7514, -3.1740], requires_grad=True)
tensor([ 1.3264, -0.3593, -2.7516, -3.1746], requires_grad=True)
tensor([ 1.3280, -0.3566, -2.7520, -3.1749], requires_grad=True)
tensor([ 1.3255, -0.3612, -2.7523, -3.1756], requires_grad=True)
tensor([ 1.3244, -0.3639, -2.7527, -3.1761], requires_grad=True)
tensor([ 1.3252, -0.3614, -2.7529, -3.1762], requires_grad=True)
tensor([ 1.3235, -0.3649,

tensor([ 1.3249, -0.3646, -2.7792, -3.2114], requires_grad=True)
tensor([ 1.3269, -0.3606, -2.7795, -3.2116], requires_grad=True)
tensor([ 1.3241, -0.3657, -2.7797, -3.2119], requires_grad=True)
tensor([ 1.3237, -0.3667, -2.7799, -3.2123], requires_grad=True)
tensor([ 1.3209, -0.3721, -2.7799, -3.2124], requires_grad=True)
tensor([ 1.3225, -0.3692, -2.7803, -3.2129], requires_grad=True)
tensor([ 1.3215, -0.3708, -2.7804, -3.2131], requires_grad=True)
tensor([ 1.3226, -0.3687, -2.7807, -3.2135], requires_grad=True)
tensor([ 1.3230, -0.3677, -2.7809, -3.2137], requires_grad=True)
tensor([ 1.3195, -0.3738, -2.7811, -3.2140], requires_grad=True)
tensor([ 1.3231, -0.3667, -2.7813, -3.2142], requires_grad=True)
tensor([ 1.3227, -0.3674, -2.7817, -3.2147], requires_grad=True)
tensor([ 1.3215, -0.3698, -2.7819, -3.2148], requires_grad=True)
tensor([ 1.3214, -0.3704, -2.7821, -3.2151], requires_grad=True)
tensor([ 1.3196, -0.3730, -2.7824, -3.2155], requires_grad=True)
tensor([ 1.3201, -0.3727,

tensor([ 1.3271, -0.3612, -2.8053, -3.2466], requires_grad=True)
tensor([ 1.3256, -0.3641, -2.8053, -3.2468], requires_grad=True)
tensor([ 1.3271, -0.3612, -2.8055, -3.2472], requires_grad=True)
tensor([ 1.3241, -0.3663, -2.8057, -3.2475], requires_grad=True)
tensor([ 1.3275, -0.3604, -2.8061, -3.2479], requires_grad=True)
tensor([ 1.3210, -0.3715, -2.8065, -3.2483], requires_grad=True)
tensor([ 1.3208, -0.3714, -2.8068, -3.2486], requires_grad=True)
tensor([ 1.3198, -0.3732, -2.8070, -3.2489], requires_grad=True)
tensor([ 1.3227, -0.3685, -2.8071, -3.2490], requires_grad=True)
tensor([ 1.3250, -0.3646, -2.8072, -3.2491], requires_grad=True)
tensor([ 1.3245, -0.3654, -2.8075, -3.2495], requires_grad=True)
tensor([ 1.3250, -0.3652, -2.8077, -3.2497], requires_grad=True)
tensor([ 1.3203, -0.3734, -2.8079, -3.2501], requires_grad=True)
tensor([ 1.3187, -0.3750, -2.8080, -3.2502], requires_grad=True)
tensor([ 1.3184, -0.3766, -2.8081, -3.2504], requires_grad=True)
tensor([ 1.3174, -0.3773,

tensor([ 1.3212, -0.3718, -2.8310, -3.2804], requires_grad=True)
tensor([ 1.3241, -0.3672, -2.8312, -3.2806], requires_grad=True)
tensor([ 1.3233, -0.3689, -2.8315, -3.2809], requires_grad=True)
tensor([ 1.3233, -0.3691, -2.8318, -3.2812], requires_grad=True)
tensor([ 1.3255, -0.3656, -2.8319, -3.2814], requires_grad=True)
tensor([ 1.3231, -0.3692, -2.8320, -3.2815], requires_grad=True)
tensor([ 1.3270, -0.3623, -2.8322, -3.2817], requires_grad=True)
tensor([ 1.3280, -0.3598, -2.8324, -3.2819], requires_grad=True)
tensor([ 1.3247, -0.3654, -2.8325, -3.2821], requires_grad=True)
tensor([ 1.3224, -0.3690, -2.8326, -3.2823], requires_grad=True)
tensor([ 1.3222, -0.3685, -2.8328, -3.2825], requires_grad=True)
tensor([ 1.3268, -0.3611, -2.8331, -3.2828], requires_grad=True)
tensor([ 1.3266, -0.3619, -2.8333, -3.2830], requires_grad=True)
tensor([ 1.3251, -0.3650, -2.8334, -3.2831], requires_grad=True)
tensor([ 1.3283, -0.3600, -2.8335, -3.2834], requires_grad=True)
tensor([ 1.3249, -0.3670,

tensor([ 1.3193, -0.3747, -2.8541, -3.3105], requires_grad=True)
tensor([ 1.3185, -0.3756, -2.8543, -3.3107], requires_grad=True)
tensor([ 1.3200, -0.3726, -2.8544, -3.3109], requires_grad=True)
tensor([ 1.3235, -0.3667, -2.8547, -3.3112], requires_grad=True)
tensor([ 1.3239, -0.3656, -2.8548, -3.3113], requires_grad=True)
tensor([ 1.3183, -0.3746, -2.8551, -3.3116], requires_grad=True)
tensor([ 1.3231, -0.3668, -2.8553, -3.3117], requires_grad=True)
tensor([ 1.3219, -0.3687, -2.8555, -3.3118], requires_grad=True)
tensor([ 1.3192, -0.3730, -2.8557, -3.3120], requires_grad=True)
tensor([ 1.3219, -0.3667, -2.8557, -3.3123], requires_grad=True)
tensor([ 1.3183, -0.3734, -2.8559, -3.3126], requires_grad=True)
tensor([ 1.3210, -0.3691, -2.8561, -3.3128], requires_grad=True)
tensor([ 1.3234, -0.3652, -2.8562, -3.3128], requires_grad=True)
tensor([ 1.3217, -0.3676, -2.8563, -3.3130], requires_grad=True)
tensor([ 1.3212, -0.3686, -2.8564, -3.3132], requires_grad=True)
tensor([ 1.3207, -0.3695,

tensor([ 1.3184, -0.3730, -2.8757, -3.3366], requires_grad=True)
tensor([ 1.3181, -0.3731, -2.8757, -3.3369], requires_grad=True)
tensor([ 1.3208, -0.3686, -2.8759, -3.3370], requires_grad=True)
tensor([ 1.3201, -0.3697, -2.8762, -3.3373], requires_grad=True)
tensor([ 1.3189, -0.3723, -2.8763, -3.3374], requires_grad=True)
tensor([ 1.3211, -0.3682, -2.8765, -3.3377], requires_grad=True)
tensor([ 1.3212, -0.3675, -2.8766, -3.3379], requires_grad=True)
tensor([ 1.3195, -0.3697, -2.8768, -3.3382], requires_grad=True)
tensor([ 1.3229, -0.3648, -2.8770, -3.3383], requires_grad=True)
tensor([ 1.3216, -0.3668, -2.8772, -3.3386], requires_grad=True)
tensor([ 1.3202, -0.3699, -2.8772, -3.3387], requires_grad=True)
tensor([ 1.3182, -0.3731, -2.8774, -3.3389], requires_grad=True)
tensor([ 1.3182, -0.3729, -2.8776, -3.3391], requires_grad=True)
tensor([ 1.3190, -0.3714, -2.8777, -3.3393], requires_grad=True)
tensor([ 1.3181, -0.3725, -2.8779, -3.3395], requires_grad=True)
tensor([ 1.3192, -0.3702,

tensor([ 1.3219, -0.3649, -2.8963, -3.3616], requires_grad=True)
tensor([ 1.3203, -0.3675, -2.8964, -3.3618], requires_grad=True)
tensor([ 1.3213, -0.3657, -2.8965, -3.3619], requires_grad=True)
tensor([ 1.3206, -0.3672, -2.8967, -3.3621], requires_grad=True)
tensor([ 1.3208, -0.3669, -2.8969, -3.3623], requires_grad=True)
tensor([ 1.3232, -0.3630, -2.8971, -3.3625], requires_grad=True)
tensor([ 1.3220, -0.3659, -2.8972, -3.3627], requires_grad=True)
tensor([ 1.3220, -0.3662, -2.8972, -3.3627], requires_grad=True)
tensor([ 1.3214, -0.3681, -2.8973, -3.3629], requires_grad=True)
tensor([ 1.3218, -0.3669, -2.8976, -3.3632], requires_grad=True)
tensor([ 1.3249, -0.3613, -2.8977, -3.3634], requires_grad=True)
tensor([ 1.3293, -0.3540, -2.8979, -3.3636], requires_grad=True)
tensor([ 1.3279, -0.3568, -2.8980, -3.3638], requires_grad=True)
tensor([ 1.3252, -0.3612, -2.8982, -3.3640], requires_grad=True)
tensor([ 1.3221, -0.3665, -2.8984, -3.3642], requires_grad=True)
tensor([ 1.3213, -0.3683,

tensor([ 1.3256, -0.3625, -2.9156, -3.3847], requires_grad=True)
tensor([ 1.3237, -0.3657, -2.9157, -3.3848], requires_grad=True)
tensor([ 1.3236, -0.3654, -2.9157, -3.3849], requires_grad=True)
tensor([ 1.3204, -0.3723, -2.9158, -3.3851], requires_grad=True)
tensor([ 1.3247, -0.3650, -2.9160, -3.3852], requires_grad=True)
tensor([ 1.3283, -0.3587, -2.9162, -3.3854], requires_grad=True)
tensor([ 1.3291, -0.3575, -2.9162, -3.3856], requires_grad=True)
tensor([ 1.3249, -0.3650, -2.9165, -3.3858], requires_grad=True)
tensor([ 1.3260, -0.3634, -2.9166, -3.3860], requires_grad=True)
tensor([ 1.3227, -0.3699, -2.9168, -3.3863], requires_grad=True)
tensor([ 1.3232, -0.3693, -2.9170, -3.3865], requires_grad=True)
tensor([ 1.3199, -0.3749, -2.9172, -3.3868], requires_grad=True)
tensor([ 1.3235, -0.3693, -2.9174, -3.3870], requires_grad=True)
tensor([ 1.3250, -0.3669, -2.9176, -3.3872], requires_grad=True)
tensor([ 1.3260, -0.3654, -2.9178, -3.3874], requires_grad=True)
tensor([ 1.3257, -0.3664,

tensor([ 1.3236, -0.3684, -2.9343, -3.4075], requires_grad=True)
tensor([ 1.3229, -0.3694, -2.9345, -3.4077], requires_grad=True)
tensor([ 1.3228, -0.3701, -2.9346, -3.4078], requires_grad=True)
tensor([ 1.3218, -0.3713, -2.9347, -3.4079], requires_grad=True)
tensor([ 1.3234, -0.3688, -2.9348, -3.4081], requires_grad=True)
tensor([ 1.3233, -0.3680, -2.9349, -3.4081], requires_grad=True)
tensor([ 1.3228, -0.3692, -2.9350, -3.4083], requires_grad=True)
tensor([ 1.3233, -0.3677, -2.9351, -3.4084], requires_grad=True)
tensor([ 1.3281, -0.3602, -2.9354, -3.4087], requires_grad=True)
tensor([ 1.3292, -0.3575, -2.9356, -3.4090], requires_grad=True)
tensor([ 1.3304, -0.3563, -2.9358, -3.4093], requires_grad=True)
tensor([ 1.3284, -0.3601, -2.9359, -3.4094], requires_grad=True)
tensor([ 1.3263, -0.3641, -2.9360, -3.4097], requires_grad=True)
tensor([ 1.3264, -0.3642, -2.9362, -3.4099], requires_grad=True)
tensor([ 1.3244, -0.3676, -2.9363, -3.4101], requires_grad=True)
tensor([ 1.3257, -0.3668,

tensor([ 1.3233, -0.3636, -2.9508, -3.4281], requires_grad=True)
tensor([ 1.3214, -0.3666, -2.9510, -3.4282], requires_grad=True)
tensor([ 1.3223, -0.3659, -2.9509, -3.4281], requires_grad=True)
tensor([ 1.3244, -0.3628, -2.9510, -3.4283], requires_grad=True)
tensor([ 1.3204, -0.3698, -2.9511, -3.4284], requires_grad=True)
tensor([ 1.3204, -0.3699, -2.9513, -3.4286], requires_grad=True)
tensor([ 1.3167, -0.3764, -2.9514, -3.4287], requires_grad=True)
tensor([ 1.3182, -0.3739, -2.9515, -3.4288], requires_grad=True)
tensor([ 1.3188, -0.3726, -2.9516, -3.4289], requires_grad=True)
tensor([ 1.3184, -0.3737, -2.9518, -3.4291], requires_grad=True)
tensor([ 1.3177, -0.3749, -2.9518, -3.4292], requires_grad=True)
tensor([ 1.3194, -0.3718, -2.9519, -3.4293], requires_grad=True)
tensor([ 1.3216, -0.3677, -2.9520, -3.4294], requires_grad=True)
tensor([ 1.3211, -0.3676, -2.9522, -3.4296], requires_grad=True)
tensor([ 1.3234, -0.3637, -2.9523, -3.4297], requires_grad=True)
tensor([ 1.3250, -0.3607,

tensor([ 1.3222, -0.3685, -2.9668, -3.4473], requires_grad=True)
tensor([ 1.3233, -0.3671, -2.9671, -3.4476], requires_grad=True)
tensor([ 1.3235, -0.3662, -2.9671, -3.4477], requires_grad=True)
tensor([ 1.3202, -0.3720, -2.9671, -3.4477], requires_grad=True)
tensor([ 1.3246, -0.3651, -2.9672, -3.4478], requires_grad=True)
tensor([ 1.3228, -0.3687, -2.9673, -3.4479], requires_grad=True)
tensor([ 1.3182, -0.3766, -2.9675, -3.4481], requires_grad=True)
tensor([ 1.3230, -0.3687, -2.9676, -3.4483], requires_grad=True)
tensor([ 1.3239, -0.3668, -2.9677, -3.4484], requires_grad=True)
tensor([ 1.3245, -0.3660, -2.9678, -3.4485], requires_grad=True)
tensor([ 1.3275, -0.3609, -2.9680, -3.4487], requires_grad=True)
tensor([ 1.3286, -0.3592, -2.9682, -3.4489], requires_grad=True)
tensor([ 1.3293, -0.3582, -2.9684, -3.4492], requires_grad=True)
tensor([ 1.3287, -0.3587, -2.9686, -3.4493], requires_grad=True)
tensor([ 1.3280, -0.3600, -2.9685, -3.4493], requires_grad=True)
tensor([ 1.3259, -0.3638,

tensor([ 1.3281, -0.3582, -2.9818, -3.4655], requires_grad=True)
tensor([ 1.3266, -0.3607, -2.9819, -3.4656], requires_grad=True)
tensor([ 1.3263, -0.3614, -2.9820, -3.4657], requires_grad=True)
tensor([ 1.3244, -0.3649, -2.9822, -3.4659], requires_grad=True)
tensor([ 1.3233, -0.3668, -2.9824, -3.4661], requires_grad=True)
tensor([ 1.3196, -0.3735, -2.9826, -3.4663], requires_grad=True)
tensor([ 1.3185, -0.3755, -2.9827, -3.4665], requires_grad=True)
tensor([ 1.3200, -0.3724, -2.9828, -3.4666], requires_grad=True)
tensor([ 1.3216, -0.3705, -2.9830, -3.4668], requires_grad=True)
tensor([ 1.3264, -0.3622, -2.9832, -3.4671], requires_grad=True)
tensor([ 1.3241, -0.3655, -2.9833, -3.4672], requires_grad=True)
tensor([ 1.3264, -0.3632, -2.9834, -3.4672], requires_grad=True)
tensor([ 1.3247, -0.3661, -2.9835, -3.4674], requires_grad=True)
tensor([ 1.3242, -0.3664, -2.9836, -3.4675], requires_grad=True)
tensor([ 1.3255, -0.3640, -2.9839, -3.4678], requires_grad=True)
tensor([ 1.3212, -0.3715,

tensor([ 1.3238, -0.3634, -2.9952, -3.4818], requires_grad=True)
tensor([ 1.3210, -0.3675, -2.9953, -3.4819], requires_grad=True)
tensor([ 1.3213, -0.3670, -2.9954, -3.4821], requires_grad=True)
tensor([ 1.3199, -0.3694, -2.9955, -3.4822], requires_grad=True)
tensor([ 1.3195, -0.3697, -2.9955, -3.4822], requires_grad=True)
tensor([ 1.3204, -0.3681, -2.9956, -3.4823], requires_grad=True)
tensor([ 1.3218, -0.3664, -2.9957, -3.4824], requires_grad=True)
tensor([ 1.3207, -0.3685, -2.9959, -3.4826], requires_grad=True)
tensor([ 1.3191, -0.3717, -2.9959, -3.4827], requires_grad=True)
tensor([ 1.3217, -0.3674, -2.9960, -3.4828], requires_grad=True)
tensor([ 1.3211, -0.3682, -2.9962, -3.4829], requires_grad=True)
tensor([ 1.3221, -0.3662, -2.9963, -3.4831], requires_grad=True)
tensor([ 1.3259, -0.3597, -2.9964, -3.4832], requires_grad=True)
tensor([ 1.3227, -0.3656, -2.9965, -3.4834], requires_grad=True)
tensor([ 1.3204, -0.3702, -2.9966, -3.4835], requires_grad=True)
tensor([ 1.3240, -0.3633,

tensor([ 1.3258, -0.3608, -3.0090, -3.4981], requires_grad=True)
tensor([ 1.3260, -0.3619, -3.0090, -3.4981], requires_grad=True)
tensor([ 1.3252, -0.3632, -3.0091, -3.4982], requires_grad=True)
tensor([ 1.3246, -0.3647, -3.0091, -3.4983], requires_grad=True)
tensor([ 1.3255, -0.3635, -3.0091, -3.4983], requires_grad=True)
tensor([ 1.3214, -0.3705, -3.0092, -3.4984], requires_grad=True)
tensor([ 1.3193, -0.3739, -3.0092, -3.4985], requires_grad=True)
tensor([ 1.3200, -0.3719, -3.0094, -3.4987], requires_grad=True)
tensor([ 1.3206, -0.3709, -3.0095, -3.4988], requires_grad=True)
tensor([ 1.3238, -0.3652, -3.0096, -3.4989], requires_grad=True)
tensor([ 1.3238, -0.3651, -3.0096, -3.4990], requires_grad=True)
tensor([ 1.3264, -0.3610, -3.0097, -3.4991], requires_grad=True)
tensor([ 1.3231, -0.3659, -3.0099, -3.4993], requires_grad=True)
tensor([ 1.3241, -0.3633, -3.0100, -3.4994], requires_grad=True)
tensor([ 1.3197, -0.3710, -3.0103, -3.4997], requires_grad=True)
tensor([ 1.3217, -0.3676,

tensor([ 1.3280, -0.3622, -3.0221, -3.5135], requires_grad=True)
tensor([ 1.3294, -0.3598, -3.0222, -3.5137], requires_grad=True)
tensor([ 1.3271, -0.3635, -3.0223, -3.5138], requires_grad=True)
tensor([ 1.3274, -0.3630, -3.0224, -3.5139], requires_grad=True)
tensor([ 1.3291, -0.3607, -3.0225, -3.5140], requires_grad=True)
tensor([ 1.3278, -0.3630, -3.0226, -3.5141], requires_grad=True)
tensor([ 1.3262, -0.3660, -3.0227, -3.5143], requires_grad=True)
tensor([ 1.3248, -0.3686, -3.0228, -3.5144], requires_grad=True)
tensor([ 1.3248, -0.3679, -3.0229, -3.5145], requires_grad=True)
tensor([ 1.3256, -0.3677, -3.0229, -3.5145], requires_grad=True)
tensor([ 1.3273, -0.3647, -3.0230, -3.5147], requires_grad=True)
tensor([ 1.3283, -0.3622, -3.0232, -3.5149], requires_grad=True)
tensor([ 1.3260, -0.3655, -3.0234, -3.5150], requires_grad=True)
tensor([ 1.3239, -0.3690, -3.0234, -3.5151], requires_grad=True)
tensor([ 1.3234, -0.3698, -3.0235, -3.5152], requires_grad=True)
tensor([ 1.3249, -0.3675,

tensor([ 1.3225, -0.3686, -3.0345, -3.5279], requires_grad=True)
tensor([ 1.3268, -0.3611, -3.0346, -3.5281], requires_grad=True)
tensor([ 1.3227, -0.3679, -3.0347, -3.5282], requires_grad=True)
tensor([ 1.3194, -0.3735, -3.0348, -3.5283], requires_grad=True)
tensor([ 1.3243, -0.3651, -3.0350, -3.5285], requires_grad=True)
tensor([ 1.3214, -0.3697, -3.0351, -3.5287], requires_grad=True)
tensor([ 1.3199, -0.3717, -3.0352, -3.5288], requires_grad=True)
tensor([ 1.3239, -0.3647, -3.0353, -3.5289], requires_grad=True)
tensor([ 1.3229, -0.3658, -3.0354, -3.5290], requires_grad=True)
tensor([ 1.3219, -0.3676, -3.0354, -3.5290], requires_grad=True)
tensor([ 1.3181, -0.3733, -3.0356, -3.5292], requires_grad=True)
tensor([ 1.3177, -0.3738, -3.0357, -3.5294], requires_grad=True)
tensor([ 1.3183, -0.3719, -3.0358, -3.5295], requires_grad=True)
tensor([ 1.3204, -0.3688, -3.0358, -3.5295], requires_grad=True)
tensor([ 1.3230, -0.3649, -3.0359, -3.5296], requires_grad=True)
tensor([ 1.3234, -0.3644,

tensor([ 1.3208, -0.3724, -3.0454, -3.5409], requires_grad=True)
tensor([ 1.3206, -0.3715, -3.0454, -3.5410], requires_grad=True)
tensor([ 1.3201, -0.3729, -3.0455, -3.5411], requires_grad=True)
tensor([ 1.3203, -0.3724, -3.0455, -3.5411], requires_grad=True)
tensor([ 1.3214, -0.3708, -3.0457, -3.5413], requires_grad=True)
tensor([ 1.3198, -0.3734, -3.0457, -3.5414], requires_grad=True)
tensor([ 1.3207, -0.3719, -3.0458, -3.5415], requires_grad=True)
tensor([ 1.3211, -0.3717, -3.0459, -3.5415], requires_grad=True)
tensor([ 1.3216, -0.3704, -3.0459, -3.5416], requires_grad=True)
tensor([ 1.3194, -0.3738, -3.0461, -3.5417], requires_grad=True)
tensor([ 1.3208, -0.3719, -3.0461, -3.5418], requires_grad=True)
tensor([ 1.3228, -0.3677, -3.0462, -3.5418], requires_grad=True)
tensor([ 1.3199, -0.3719, -3.0463, -3.5419], requires_grad=True)
tensor([ 1.3195, -0.3720, -3.0463, -3.5421], requires_grad=True)
tensor([ 1.3192, -0.3724, -3.0465, -3.5422], requires_grad=True)
tensor([ 1.3204, -0.3706,

tensor([ 1.3190, -0.3714, -3.0564, -3.5538], requires_grad=True)
tensor([ 1.3150, -0.3781, -3.0565, -3.5539], requires_grad=True)
tensor([ 1.3167, -0.3746, -3.0566, -3.5540], requires_grad=True)
tensor([ 1.3169, -0.3746, -3.0567, -3.5540], requires_grad=True)
tensor([ 1.3186, -0.3709, -3.0568, -3.5542], requires_grad=True)
tensor([ 1.3195, -0.3688, -3.0569, -3.5543], requires_grad=True)
tensor([ 1.3202, -0.3677, -3.0570, -3.5544], requires_grad=True)
tensor([ 1.3197, -0.3675, -3.0570, -3.5545], requires_grad=True)
tensor([ 1.3197, -0.3667, -3.0570, -3.5545], requires_grad=True)
tensor([ 1.3221, -0.3626, -3.0572, -3.5547], requires_grad=True)
tensor([ 1.3207, -0.3651, -3.0573, -3.5548], requires_grad=True)
tensor([ 1.3202, -0.3656, -3.0573, -3.5549], requires_grad=True)
tensor([ 1.3231, -0.3601, -3.0575, -3.5550], requires_grad=True)
tensor([ 1.3220, -0.3617, -3.0575, -3.5550], requires_grad=True)
tensor([ 1.3228, -0.3602, -3.0575, -3.5551], requires_grad=True)
tensor([ 1.3220, -0.3626,

tensor([ 1.3219, -0.3705, -3.0674, -3.5665], requires_grad=True)
tensor([ 1.3251, -0.3657, -3.0676, -3.5666], requires_grad=True)
tensor([ 1.3268, -0.3631, -3.0676, -3.5667], requires_grad=True)
tensor([ 1.3251, -0.3659, -3.0677, -3.5668], requires_grad=True)
tensor([ 1.3271, -0.3625, -3.0677, -3.5668], requires_grad=True)
tensor([ 1.3293, -0.3586, -3.0678, -3.5669], requires_grad=True)
tensor([ 1.3281, -0.3611, -3.0679, -3.5671], requires_grad=True)
tensor([ 1.3257, -0.3647, -3.0681, -3.5672], requires_grad=True)
tensor([ 1.3249, -0.3655, -3.0681, -3.5673], requires_grad=True)
tensor([ 1.3235, -0.3681, -3.0682, -3.5674], requires_grad=True)
tensor([ 1.3245, -0.3671, -3.0683, -3.5675], requires_grad=True)
tensor([ 1.3230, -0.3694, -3.0684, -3.5675], requires_grad=True)
tensor([ 1.3250, -0.3666, -3.0686, -3.5678], requires_grad=True)
tensor([ 1.3274, -0.3625, -3.0687, -3.5679], requires_grad=True)
tensor([ 1.3296, -0.3586, -3.0688, -3.5680], requires_grad=True)
tensor([ 1.3293, -0.3587,

tensor([ 1.3263, -0.3605, -3.0785, -3.5789], requires_grad=True)
tensor([ 1.3255, -0.3617, -3.0786, -3.5790], requires_grad=True)
tensor([ 1.3271, -0.3588, -3.0786, -3.5790], requires_grad=True)
tensor([ 1.3275, -0.3581, -3.0787, -3.5791], requires_grad=True)
tensor([ 1.3239, -0.3645, -3.0788, -3.5792], requires_grad=True)
tensor([ 1.3250, -0.3618, -3.0788, -3.5792], requires_grad=True)
tensor([ 1.3245, -0.3629, -3.0789, -3.5793], requires_grad=True)
tensor([ 1.3242, -0.3630, -3.0790, -3.5794], requires_grad=True)
tensor([ 1.3211, -0.3686, -3.0791, -3.5795], requires_grad=True)
tensor([ 1.3209, -0.3687, -3.0792, -3.5797], requires_grad=True)
tensor([ 1.3219, -0.3670, -3.0793, -3.5798], requires_grad=True)
tensor([ 1.3242, -0.3642, -3.0794, -3.5798], requires_grad=True)
tensor([ 1.3221, -0.3678, -3.0795, -3.5799], requires_grad=True)
tensor([ 1.3215, -0.3682, -3.0795, -3.5800], requires_grad=True)
tensor([ 1.3222, -0.3672, -3.0796, -3.5801], requires_grad=True)
tensor([ 1.3228, -0.3660,

tensor([ 1.3196, -0.3721, -3.0885, -3.5903], requires_grad=True)
tensor([ 1.3210, -0.3694, -3.0885, -3.5904], requires_grad=True)
tensor([ 1.3216, -0.3690, -3.0885, -3.5904], requires_grad=True)
tensor([ 1.3207, -0.3707, -3.0886, -3.5905], requires_grad=True)
tensor([ 1.3222, -0.3682, -3.0887, -3.5905], requires_grad=True)
tensor([ 1.3252, -0.3627, -3.0887, -3.5905], requires_grad=True)
tensor([ 1.3213, -0.3694, -3.0889, -3.5907], requires_grad=True)
tensor([ 1.3224, -0.3679, -3.0889, -3.5908], requires_grad=True)
tensor([ 1.3242, -0.3648, -3.0891, -3.5909], requires_grad=True)
tensor([ 1.3249, -0.3634, -3.0892, -3.5910], requires_grad=True)
tensor([ 1.3246, -0.3640, -3.0893, -3.5911], requires_grad=True)
tensor([ 1.3262, -0.3608, -3.0893, -3.5912], requires_grad=True)
tensor([ 1.3239, -0.3647, -3.0893, -3.5912], requires_grad=True)
tensor([ 1.3222, -0.3677, -3.0894, -3.5913], requires_grad=True)
tensor([ 1.3237, -0.3650, -3.0895, -3.5913], requires_grad=True)
tensor([ 1.3182, -0.3745,

tensor([ 1.3281, -0.3599, -3.0977, -3.6009], requires_grad=True)
tensor([ 1.3284, -0.3598, -3.0977, -3.6010], requires_grad=True)
tensor([ 1.3300, -0.3572, -3.0977, -3.6010], requires_grad=True)
tensor([ 1.3307, -0.3568, -3.0977, -3.6010], requires_grad=True)
tensor([ 1.3287, -0.3606, -3.0977, -3.6011], requires_grad=True)
tensor([ 1.3267, -0.3640, -3.0979, -3.6012], requires_grad=True)
tensor([ 1.3261, -0.3656, -3.0978, -3.6012], requires_grad=True)
tensor([ 1.3247, -0.3679, -3.0980, -3.6014], requires_grad=True)
tensor([ 1.3243, -0.3685, -3.0980, -3.6015], requires_grad=True)
tensor([ 1.3240, -0.3686, -3.0981, -3.6016], requires_grad=True)
tensor([ 1.3243, -0.3677, -3.0982, -3.6016], requires_grad=True)
tensor([ 1.3246, -0.3672, -3.0982, -3.6017], requires_grad=True)
tensor([ 1.3241, -0.3675, -3.0983, -3.6018], requires_grad=True)
tensor([ 1.3239, -0.3677, -3.0984, -3.6019], requires_grad=True)
tensor([ 1.3248, -0.3662, -3.0985, -3.6020], requires_grad=True)
tensor([ 1.3247, -0.3663,

tensor([ 1.3267, -0.3662, -3.1069, -3.6117], requires_grad=True)
tensor([ 1.3265, -0.3673, -3.1070, -3.6118], requires_grad=True)
tensor([ 1.3289, -0.3636, -3.1071, -3.6119], requires_grad=True)
tensor([ 1.3283, -0.3646, -3.1071, -3.6119], requires_grad=True)
tensor([ 1.3289, -0.3641, -3.1072, -3.6121], requires_grad=True)
tensor([ 1.3287, -0.3646, -3.1073, -3.6121], requires_grad=True)
tensor([ 1.3306, -0.3610, -3.1074, -3.6123], requires_grad=True)
tensor([ 1.3310, -0.3603, -3.1075, -3.6124], requires_grad=True)
tensor([ 1.3289, -0.3630, -3.1076, -3.6124], requires_grad=True)
tensor([ 1.3288, -0.3632, -3.1076, -3.6124], requires_grad=True)
tensor([ 1.3266, -0.3676, -3.1077, -3.6125], requires_grad=True)
tensor([ 1.3280, -0.3646, -3.1078, -3.6126], requires_grad=True)
tensor([ 1.3270, -0.3663, -3.1079, -3.6127], requires_grad=True)
tensor([ 1.3251, -0.3696, -3.1080, -3.6128], requires_grad=True)
tensor([ 1.3248, -0.3699, -3.1081, -3.6129], requires_grad=True)
tensor([ 1.3255, -0.3692,

tensor([ 1.3233, -0.3682, -3.1147, -3.6206], requires_grad=True)
tensor([ 1.3256, -0.3646, -3.1148, -3.6207], requires_grad=True)
tensor([ 1.3238, -0.3676, -3.1148, -3.6207], requires_grad=True)
tensor([ 1.3242, -0.3674, -3.1149, -3.6208], requires_grad=True)
tensor([ 1.3229, -0.3691, -3.1150, -3.6209], requires_grad=True)
tensor([ 1.3209, -0.3723, -3.1150, -3.6209], requires_grad=True)
tensor([ 1.3213, -0.3714, -3.1150, -3.6209], requires_grad=True)
tensor([ 1.3255, -0.3644, -3.1151, -3.6210], requires_grad=True)
tensor([ 1.3260, -0.3642, -3.1152, -3.6211], requires_grad=True)
tensor([ 1.3239, -0.3677, -3.1153, -3.6212], requires_grad=True)
tensor([ 1.3273, -0.3621, -3.1153, -3.6213], requires_grad=True)
tensor([ 1.3240, -0.3678, -3.1154, -3.6214], requires_grad=True)
tensor([ 1.3225, -0.3705, -3.1155, -3.6215], requires_grad=True)
tensor([ 1.3225, -0.3710, -3.1156, -3.6217], requires_grad=True)
tensor([ 1.3247, -0.3677, -3.1156, -3.6217], requires_grad=True)
tensor([ 1.3248, -0.3666,

tensor([ 1.3250, -0.3665, -3.1227, -3.6298], requires_grad=True)
tensor([ 1.3235, -0.3691, -3.1228, -3.6299], requires_grad=True)
tensor([ 1.3220, -0.3713, -3.1228, -3.6300], requires_grad=True)
tensor([ 1.3240, -0.3679, -3.1229, -3.6300], requires_grad=True)
tensor([ 1.3237, -0.3692, -3.1229, -3.6301], requires_grad=True)
tensor([ 1.3263, -0.3649, -3.1230, -3.6301], requires_grad=True)
tensor([ 1.3249, -0.3675, -3.1230, -3.6302], requires_grad=True)
tensor([ 1.3236, -0.3695, -3.1231, -3.6303], requires_grad=True)
tensor([ 1.3272, -0.3636, -3.1233, -3.6305], requires_grad=True)
tensor([ 1.3277, -0.3629, -3.1234, -3.6306], requires_grad=True)
tensor([ 1.3293, -0.3599, -3.1235, -3.6306], requires_grad=True)
tensor([ 1.3279, -0.3625, -3.1236, -3.6308], requires_grad=True)
tensor([ 1.3270, -0.3633, -3.1236, -3.6307], requires_grad=True)
tensor([ 1.3281, -0.3616, -3.1237, -3.6308], requires_grad=True)
tensor([ 1.3273, -0.3636, -3.1236, -3.6308], requires_grad=True)
tensor([ 1.3244, -0.3677,

tensor([ 1.3245, -0.3654, -3.1302, -3.6380], requires_grad=True)
tensor([ 1.3226, -0.3687, -3.1303, -3.6381], requires_grad=True)
tensor([ 1.3214, -0.3705, -3.1304, -3.6382], requires_grad=True)
tensor([ 1.3216, -0.3704, -3.1305, -3.6383], requires_grad=True)
tensor([ 1.3213, -0.3708, -3.1306, -3.6384], requires_grad=True)
tensor([ 1.3210, -0.3711, -3.1306, -3.6384], requires_grad=True)
tensor([ 1.3209, -0.3711, -3.1306, -3.6385], requires_grad=True)
tensor([ 1.3208, -0.3715, -3.1306, -3.6384], requires_grad=True)
tensor([ 1.3214, -0.3704, -3.1306, -3.6385], requires_grad=True)
tensor([ 1.3227, -0.3685, -3.1307, -3.6386], requires_grad=True)
tensor([ 1.3231, -0.3678, -3.1308, -3.6386], requires_grad=True)
tensor([ 1.3209, -0.3725, -3.1307, -3.6385], requires_grad=True)
tensor([ 1.3252, -0.3649, -3.1308, -3.6386], requires_grad=True)
tensor([ 1.3243, -0.3663, -3.1308, -3.6387], requires_grad=True)
tensor([ 1.3248, -0.3652, -3.1309, -3.6388], requires_grad=True)
tensor([ 1.3239, -0.3671,

tensor([ 1.3237, -0.3661, -3.1376, -3.6465], requires_grad=True)
tensor([ 1.3241, -0.3653, -3.1377, -3.6465], requires_grad=True)
tensor([ 1.3262, -0.3620, -3.1377, -3.6466], requires_grad=True)
tensor([ 1.3257, -0.3634, -3.1377, -3.6466], requires_grad=True)
tensor([ 1.3253, -0.3642, -3.1377, -3.6467], requires_grad=True)
tensor([ 1.3255, -0.3638, -3.1377, -3.6467], requires_grad=True)
tensor([ 1.3240, -0.3664, -3.1379, -3.6468], requires_grad=True)
tensor([ 1.3247, -0.3654, -3.1378, -3.6468], requires_grad=True)
tensor([ 1.3219, -0.3703, -3.1379, -3.6470], requires_grad=True)
tensor([ 1.3216, -0.3705, -3.1380, -3.6470], requires_grad=True)
tensor([ 1.3228, -0.3687, -3.1380, -3.6471], requires_grad=True)
tensor([ 1.3227, -0.3685, -3.1380, -3.6472], requires_grad=True)
tensor([ 1.3192, -0.3741, -3.1381, -3.6473], requires_grad=True)
tensor([ 1.3232, -0.3671, -3.1383, -3.6474], requires_grad=True)
tensor([ 1.3246, -0.3643, -3.1383, -3.6475], requires_grad=True)
tensor([ 1.3262, -0.3614,

tensor([ 1.3228, -0.3689, -3.1451, -3.6544], requires_grad=True)
tensor([ 1.3209, -0.3719, -3.1451, -3.6545], requires_grad=True)
tensor([ 1.3203, -0.3727, -3.1452, -3.6546], requires_grad=True)
tensor([ 1.3198, -0.3738, -3.1453, -3.6547], requires_grad=True)
tensor([ 1.3206, -0.3726, -3.1453, -3.6547], requires_grad=True)
tensor([ 1.3216, -0.3710, -3.1454, -3.6548], requires_grad=True)
tensor([ 1.3215, -0.3705, -3.1454, -3.6548], requires_grad=True)
tensor([ 1.3220, -0.3698, -3.1455, -3.6549], requires_grad=True)
tensor([ 1.3239, -0.3659, -3.1456, -3.6550], requires_grad=True)
tensor([ 1.3250, -0.3642, -3.1456, -3.6551], requires_grad=True)
tensor([ 1.3244, -0.3646, -3.1457, -3.6551], requires_grad=True)
tensor([ 1.3207, -0.3716, -3.1457, -3.6552], requires_grad=True)
tensor([ 1.3209, -0.3711, -3.1458, -3.6553], requires_grad=True)
tensor([ 1.3234, -0.3667, -3.1459, -3.6554], requires_grad=True)
tensor([ 1.3224, -0.3695, -3.1459, -3.6554], requires_grad=True)
tensor([ 1.3204, -0.3732,

tensor([ 1.3232, -0.3663, -3.1531, -3.6626], requires_grad=True)
tensor([ 1.3240, -0.3652, -3.1532, -3.6627], requires_grad=True)
tensor([ 1.3248, -0.3637, -3.1534, -3.6628], requires_grad=True)
tensor([ 1.3219, -0.3691, -3.1534, -3.6629], requires_grad=True)
tensor([ 1.3212, -0.3698, -3.1535, -3.6629], requires_grad=True)
tensor([ 1.3218, -0.3683, -3.1536, -3.6630], requires_grad=True)
tensor([ 1.3219, -0.3686, -3.1536, -3.6631], requires_grad=True)
tensor([ 1.3189, -0.3737, -3.1537, -3.6631], requires_grad=True)
tensor([ 1.3222, -0.3680, -3.1537, -3.6632], requires_grad=True)
tensor([ 1.3209, -0.3698, -3.1537, -3.6632], requires_grad=True)
tensor([ 1.3190, -0.3737, -3.1538, -3.6633], requires_grad=True)
tensor([ 1.3201, -0.3720, -3.1538, -3.6633], requires_grad=True)
tensor([ 1.3195, -0.3720, -3.1538, -3.6633], requires_grad=True)
tensor([ 1.3232, -0.3660, -3.1539, -3.6634], requires_grad=True)
tensor([ 1.3208, -0.3701, -3.1540, -3.6635], requires_grad=True)
tensor([ 1.3237, -0.3654,

tensor([ 1.3272, -0.3601, -3.1604, -3.6702], requires_grad=True)
tensor([ 1.3263, -0.3617, -3.1605, -3.6703], requires_grad=True)
tensor([ 1.3267, -0.3612, -3.1606, -3.6704], requires_grad=True)
tensor([ 1.3252, -0.3640, -3.1607, -3.6705], requires_grad=True)
tensor([ 1.3231, -0.3676, -3.1607, -3.6705], requires_grad=True)
tensor([ 1.3232, -0.3674, -3.1607, -3.6706], requires_grad=True)
tensor([ 1.3219, -0.3693, -3.1608, -3.6707], requires_grad=True)
tensor([ 1.3220, -0.3694, -3.1609, -3.6708], requires_grad=True)
tensor([ 1.3223, -0.3691, -3.1609, -3.6708], requires_grad=True)
tensor([ 1.3209, -0.3720, -3.1610, -3.6709], requires_grad=True)
tensor([ 1.3230, -0.3685, -3.1611, -3.6709], requires_grad=True)
tensor([ 1.3238, -0.3674, -3.1612, -3.6710], requires_grad=True)
tensor([ 1.3250, -0.3655, -3.1613, -3.6711], requires_grad=True)
tensor([ 1.3239, -0.3673, -3.1614, -3.6712], requires_grad=True)
tensor([ 1.3254, -0.3650, -3.1615, -3.6713], requires_grad=True)
tensor([ 1.3213, -0.3717,

tensor([ 1.3198, -0.3705, -3.1669, -3.6777], requires_grad=True)
tensor([ 1.3228, -0.3664, -3.1670, -3.6777], requires_grad=True)
tensor([ 1.3243, -0.3637, -3.1671, -3.6778], requires_grad=True)
tensor([ 1.3240, -0.3639, -3.1671, -3.6779], requires_grad=True)
tensor([ 1.3274, -0.3581, -3.1673, -3.6780], requires_grad=True)
tensor([ 1.3267, -0.3596, -3.1673, -3.6780], requires_grad=True)
tensor([ 1.3280, -0.3571, -3.1674, -3.6781], requires_grad=True)
tensor([ 1.3263, -0.3602, -3.1674, -3.6781], requires_grad=True)
tensor([ 1.3250, -0.3624, -3.1675, -3.6782], requires_grad=True)
tensor([ 1.3240, -0.3645, -3.1676, -3.6783], requires_grad=True)
tensor([ 1.3244, -0.3637, -3.1676, -3.6783], requires_grad=True)
tensor([ 1.3216, -0.3682, -3.1677, -3.6784], requires_grad=True)
tensor([ 1.3191, -0.3717, -3.1677, -3.6785], requires_grad=True)
tensor([ 1.3193, -0.3709, -3.1678, -3.6785], requires_grad=True)
tensor([ 1.3235, -0.3645, -3.1679, -3.6787], requires_grad=True)
tensor([ 1.3222, -0.3669,

tensor([ 1.3192, -0.3734, -3.1735, -3.6847], requires_grad=True)
tensor([ 1.3208, -0.3705, -3.1735, -3.6847], requires_grad=True)
tensor([ 1.3240, -0.3646, -3.1736, -3.6848], requires_grad=True)
tensor([ 1.3242, -0.3642, -3.1737, -3.6849], requires_grad=True)
tensor([ 1.3242, -0.3646, -3.1736, -3.6850], requires_grad=True)
tensor([ 1.3239, -0.3651, -3.1737, -3.6851], requires_grad=True)
tensor([ 1.3238, -0.3656, -3.1737, -3.6851], requires_grad=True)
tensor([ 1.3215, -0.3701, -3.1737, -3.6852], requires_grad=True)
tensor([ 1.3238, -0.3661, -3.1738, -3.6852], requires_grad=True)
tensor([ 1.3222, -0.3684, -3.1739, -3.6853], requires_grad=True)
tensor([ 1.3224, -0.3682, -3.1739, -3.6853], requires_grad=True)
tensor([ 1.3201, -0.3717, -3.1739, -3.6854], requires_grad=True)
tensor([ 1.3198, -0.3720, -3.1740, -3.6854], requires_grad=True)
tensor([ 1.3202, -0.3708, -3.1741, -3.6855], requires_grad=True)
tensor([ 1.3181, -0.3737, -3.1741, -3.6856], requires_grad=True)
tensor([ 1.3189, -0.3727,

tensor([ 1.3241, -0.3667, -3.1797, -3.6913], requires_grad=True)
tensor([ 1.3239, -0.3673, -3.1798, -3.6914], requires_grad=True)
tensor([ 1.3249, -0.3652, -3.1798, -3.6915], requires_grad=True)
tensor([ 1.3235, -0.3674, -3.1799, -3.6917], requires_grad=True)
tensor([ 1.3225, -0.3684, -3.1800, -3.6918], requires_grad=True)
tensor([ 1.3252, -0.3644, -3.1800, -3.6918], requires_grad=True)
tensor([ 1.3278, -0.3604, -3.1800, -3.6918], requires_grad=True)
tensor([ 1.3260, -0.3644, -3.1800, -3.6919], requires_grad=True)
tensor([ 1.3253, -0.3661, -3.1801, -3.6919], requires_grad=True)
tensor([ 1.3243, -0.3681, -3.1801, -3.6920], requires_grad=True)
tensor([ 1.3251, -0.3669, -3.1802, -3.6921], requires_grad=True)
tensor([ 1.3252, -0.3666, -3.1802, -3.6921], requires_grad=True)
tensor([ 1.3232, -0.3706, -3.1802, -3.6921], requires_grad=True)
tensor([ 1.3225, -0.3716, -3.1803, -3.6922], requires_grad=True)
tensor([ 1.3225, -0.3713, -3.1803, -3.6922], requires_grad=True)
tensor([ 1.3219, -0.3723,

tensor([ 1.3220, -0.3698, -3.1854, -3.6984], requires_grad=True)
tensor([ 1.3244, -0.3658, -3.1854, -3.6984], requires_grad=True)
tensor([ 1.3220, -0.3698, -3.1855, -3.6985], requires_grad=True)
tensor([ 1.3189, -0.3753, -3.1856, -3.6985], requires_grad=True)
tensor([ 1.3193, -0.3745, -3.1856, -3.6986], requires_grad=True)
tensor([ 1.3194, -0.3740, -3.1857, -3.6987], requires_grad=True)
tensor([ 1.3197, -0.3728, -3.1857, -3.6987], requires_grad=True)
tensor([ 1.3225, -0.3683, -3.1857, -3.6987], requires_grad=True)
tensor([ 1.3223, -0.3687, -3.1858, -3.6988], requires_grad=True)
tensor([ 1.3249, -0.3651, -3.1859, -3.6989], requires_grad=True)
tensor([ 1.3243, -0.3666, -3.1859, -3.6989], requires_grad=True)
tensor([ 1.3249, -0.3652, -3.1860, -3.6990], requires_grad=True)
tensor([ 1.3271, -0.3614, -3.1859, -3.6989], requires_grad=True)
tensor([ 1.3260, -0.3638, -3.1860, -3.6990], requires_grad=True)
tensor([ 1.3237, -0.3671, -3.1860, -3.6990], requires_grad=True)
tensor([ 1.3245, -0.3656,

tensor([ 1.3194, -0.3735, -3.1903, -3.7041], requires_grad=True)
tensor([ 1.3221, -0.3686, -3.1904, -3.7041], requires_grad=True)
tensor([ 1.3223, -0.3676, -3.1905, -3.7042], requires_grad=True)
tensor([ 1.3221, -0.3674, -3.1905, -3.7043], requires_grad=True)
tensor([ 1.3221, -0.3678, -3.1906, -3.7044], requires_grad=True)
tensor([ 1.3202, -0.3710, -3.1906, -3.7044], requires_grad=True)
tensor([ 1.3198, -0.3713, -3.1906, -3.7043], requires_grad=True)
tensor([ 1.3190, -0.3733, -3.1907, -3.7043], requires_grad=True)
tensor([ 1.3188, -0.3740, -3.1907, -3.7043], requires_grad=True)
tensor([ 1.3193, -0.3730, -3.1908, -3.7044], requires_grad=True)
tensor([ 1.3191, -0.3729, -3.1908, -3.7045], requires_grad=True)
tensor([ 1.3213, -0.3700, -3.1909, -3.7045], requires_grad=True)
tensor([ 1.3221, -0.3687, -3.1910, -3.7046], requires_grad=True)
tensor([ 1.3209, -0.3716, -3.1910, -3.7045], requires_grad=True)
tensor([ 1.3222, -0.3699, -3.1910, -3.7046], requires_grad=True)
tensor([ 1.3228, -0.3691,

tensor([ 1.3248, -0.3656, -3.1962, -3.7105], requires_grad=True)
tensor([ 1.3237, -0.3679, -3.1962, -3.7105], requires_grad=True)
tensor([ 1.3250, -0.3652, -3.1963, -3.7106], requires_grad=True)
tensor([ 1.3255, -0.3644, -3.1964, -3.7107], requires_grad=True)
tensor([ 1.3245, -0.3659, -3.1964, -3.7107], requires_grad=True)
tensor([ 1.3239, -0.3668, -3.1965, -3.7108], requires_grad=True)
tensor([ 1.3230, -0.3682, -3.1965, -3.7109], requires_grad=True)
tensor([ 1.3254, -0.3644, -3.1965, -3.7109], requires_grad=True)
tensor([ 1.3252, -0.3648, -3.1966, -3.7110], requires_grad=True)
tensor([ 1.3268, -0.3620, -3.1966, -3.7111], requires_grad=True)
tensor([ 1.3251, -0.3653, -3.1966, -3.7112], requires_grad=True)
tensor([ 1.3246, -0.3657, -3.1967, -3.7113], requires_grad=True)
tensor([ 1.3239, -0.3665, -3.1967, -3.7114], requires_grad=True)
tensor([ 1.3244, -0.3660, -3.1968, -3.7114], requires_grad=True)
tensor([ 1.3242, -0.3668, -3.1968, -3.7115], requires_grad=True)
tensor([ 1.3245, -0.3665,

tensor([ 1.3225, -0.3669, -3.2019, -3.7174], requires_grad=True)
tensor([ 1.3237, -0.3650, -3.2019, -3.7174], requires_grad=True)
tensor([ 1.3226, -0.3671, -3.2020, -3.7175], requires_grad=True)
tensor([ 1.3224, -0.3675, -3.2020, -3.7176], requires_grad=True)
tensor([ 1.3229, -0.3670, -3.2020, -3.7176], requires_grad=True)
tensor([ 1.3227, -0.3674, -3.2020, -3.7176], requires_grad=True)
tensor([ 1.3223, -0.3684, -3.2020, -3.7175], requires_grad=True)
tensor([ 1.3254, -0.3632, -3.2021, -3.7176], requires_grad=True)
tensor([ 1.3234, -0.3663, -3.2022, -3.7177], requires_grad=True)
tensor([ 1.3231, -0.3669, -3.2022, -3.7177], requires_grad=True)
tensor([ 1.3227, -0.3675, -3.2022, -3.7176], requires_grad=True)
tensor([ 1.3246, -0.3639, -3.2021, -3.7177], requires_grad=True)
tensor([ 1.3249, -0.3640, -3.2022, -3.7177], requires_grad=True)
tensor([ 1.3249, -0.3633, -3.2022, -3.7177], requires_grad=True)
tensor([ 1.3238, -0.3656, -3.2022, -3.7178], requires_grad=True)
tensor([ 1.3246, -0.3643,

tensor([ 1.3229, -0.3684, -3.2067, -3.7224], requires_grad=True)
tensor([ 1.3254, -0.3640, -3.2067, -3.7224], requires_grad=True)
tensor([ 1.3257, -0.3633, -3.2067, -3.7224], requires_grad=True)
tensor([ 1.3236, -0.3671, -3.2067, -3.7224], requires_grad=True)
tensor([ 1.3211, -0.3715, -3.2067, -3.7224], requires_grad=True)
tensor([ 1.3223, -0.3694, -3.2068, -3.7225], requires_grad=True)
tensor([ 1.3260, -0.3633, -3.2069, -3.7226], requires_grad=True)
tensor([ 1.3287, -0.3588, -3.2069, -3.7226], requires_grad=True)
tensor([ 1.3254, -0.3647, -3.2071, -3.7228], requires_grad=True)
tensor([ 1.3215, -0.3714, -3.2072, -3.7229], requires_grad=True)
tensor([ 1.3207, -0.3722, -3.2071, -3.7228], requires_grad=True)
tensor([ 1.3198, -0.3744, -3.2072, -3.7228], requires_grad=True)
tensor([ 1.3209, -0.3729, -3.2072, -3.7227], requires_grad=True)
tensor([ 1.3191, -0.3756, -3.2072, -3.7228], requires_grad=True)
tensor([ 1.3226, -0.3697, -3.2073, -3.7229], requires_grad=True)
tensor([ 1.3207, -0.3738,

tensor([ 1.3202, -0.3694, -3.2116, -3.7277], requires_grad=True)
tensor([ 1.3214, -0.3672, -3.2116, -3.7277], requires_grad=True)
tensor([ 1.3214, -0.3668, -3.2116, -3.7278], requires_grad=True)
tensor([ 1.3232, -0.3642, -3.2117, -3.7278], requires_grad=True)
tensor([ 1.3220, -0.3663, -3.2117, -3.7279], requires_grad=True)
tensor([ 1.3235, -0.3639, -3.2118, -3.7280], requires_grad=True)
tensor([ 1.3228, -0.3653, -3.2119, -3.7281], requires_grad=True)
tensor([ 1.3232, -0.3654, -3.2119, -3.7281], requires_grad=True)
tensor([ 1.3243, -0.3638, -3.2119, -3.7282], requires_grad=True)
tensor([ 1.3264, -0.3604, -3.2119, -3.7282], requires_grad=True)
tensor([ 1.3225, -0.3674, -3.2120, -3.7282], requires_grad=True)
tensor([ 1.3246, -0.3634, -3.2120, -3.7283], requires_grad=True)
tensor([ 1.3229, -0.3670, -3.2120, -3.7283], requires_grad=True)
tensor([ 1.3209, -0.3702, -3.2120, -3.7284], requires_grad=True)
tensor([ 1.3201, -0.3714, -3.2119, -3.7284], requires_grad=True)
tensor([ 1.3207, -0.3705,

tensor([ 1.3222, -0.3682, -3.2151, -3.7319], requires_grad=True)
tensor([ 1.3228, -0.3665, -3.2150, -3.7319], requires_grad=True)
tensor([ 1.3186, -0.3737, -3.2151, -3.7319], requires_grad=True)
tensor([ 1.3177, -0.3753, -3.2151, -3.7318], requires_grad=True)
tensor([ 1.3206, -0.3706, -3.2152, -3.7319], requires_grad=True)
tensor([ 1.3243, -0.3645, -3.2152, -3.7320], requires_grad=True)
tensor([ 1.3253, -0.3632, -3.2152, -3.7320], requires_grad=True)
tensor([ 1.3257, -0.3626, -3.2153, -3.7321], requires_grad=True)
tensor([ 1.3250, -0.3641, -3.2153, -3.7321], requires_grad=True)
tensor([ 1.3236, -0.3666, -3.2154, -3.7322], requires_grad=True)
tensor([ 1.3252, -0.3643, -3.2154, -3.7322], requires_grad=True)
tensor([ 1.3266, -0.3614, -3.2153, -3.7322], requires_grad=True)
tensor([ 1.3265, -0.3616, -3.2154, -3.7322], requires_grad=True)
tensor([ 1.3264, -0.3617, -3.2154, -3.7322], requires_grad=True)
tensor([ 1.3250, -0.3642, -3.2154, -3.7323], requires_grad=True)
tensor([ 1.3256, -0.3636,

tensor([ 1.3276, -0.3621, -3.2192, -3.7359], requires_grad=True)
tensor([ 1.3274, -0.3621, -3.2193, -3.7359], requires_grad=True)
tensor([ 1.3275, -0.3624, -3.2194, -3.7360], requires_grad=True)
tensor([ 1.3271, -0.3629, -3.2194, -3.7360], requires_grad=True)
tensor([ 1.3301, -0.3574, -3.2194, -3.7360], requires_grad=True)
tensor([ 1.3279, -0.3614, -3.2195, -3.7361], requires_grad=True)
tensor([ 1.3261, -0.3646, -3.2194, -3.7360], requires_grad=True)
tensor([ 1.3245, -0.3680, -3.2194, -3.7361], requires_grad=True)
tensor([ 1.3234, -0.3698, -3.2194, -3.7362], requires_grad=True)
tensor([ 1.3244, -0.3675, -3.2193, -3.7361], requires_grad=True)
tensor([ 1.3259, -0.3650, -3.2193, -3.7362], requires_grad=True)
tensor([ 1.3260, -0.3651, -3.2194, -3.7363], requires_grad=True)
tensor([ 1.3251, -0.3672, -3.2194, -3.7364], requires_grad=True)
tensor([ 1.3249, -0.3675, -3.2195, -3.7364], requires_grad=True)
tensor([ 1.3275, -0.3636, -3.2195, -3.7365], requires_grad=True)
tensor([ 1.3293, -0.3610,

tensor([ 1.3248, -0.3658, -3.2232, -3.7405], requires_grad=True)
tensor([ 1.3243, -0.3669, -3.2233, -3.7406], requires_grad=True)
tensor([ 1.3240, -0.3674, -3.2234, -3.7406], requires_grad=True)
tensor([ 1.3244, -0.3666, -3.2234, -3.7407], requires_grad=True)
tensor([ 1.3258, -0.3650, -3.2234, -3.7408], requires_grad=True)
tensor([ 1.3281, -0.3612, -3.2235, -3.7408], requires_grad=True)
tensor([ 1.3280, -0.3612, -3.2234, -3.7408], requires_grad=True)
tensor([ 1.3275, -0.3617, -3.2234, -3.7408], requires_grad=True)
tensor([ 1.3273, -0.3619, -3.2235, -3.7409], requires_grad=True)
tensor([ 1.3250, -0.3654, -3.2236, -3.7409], requires_grad=True)
tensor([ 1.3251, -0.3648, -3.2237, -3.7409], requires_grad=True)
tensor([ 1.3248, -0.3649, -3.2237, -3.7408], requires_grad=True)
tensor([ 1.3241, -0.3654, -3.2237, -3.7409], requires_grad=True)
tensor([ 1.3253, -0.3634, -3.2237, -3.7409], requires_grad=True)
tensor([ 1.3242, -0.3655, -3.2238, -3.7409], requires_grad=True)
tensor([ 1.3237, -0.3664,

tensor([ 1.3245, -0.3659, -3.2272, -3.7453], requires_grad=True)
tensor([ 1.3226, -0.3687, -3.2272, -3.7453], requires_grad=True)
tensor([ 1.3217, -0.3701, -3.2273, -3.7454], requires_grad=True)
tensor([ 1.3234, -0.3672, -3.2273, -3.7455], requires_grad=True)
tensor([ 1.3224, -0.3691, -3.2274, -3.7455], requires_grad=True)
tensor([ 1.3218, -0.3704, -3.2275, -3.7455], requires_grad=True)
tensor([ 1.3215, -0.3704, -3.2275, -3.7455], requires_grad=True)
tensor([ 1.3219, -0.3702, -3.2275, -3.7455], requires_grad=True)
tensor([ 1.3230, -0.3684, -3.2276, -3.7456], requires_grad=True)
tensor([ 1.3220, -0.3702, -3.2276, -3.7456], requires_grad=True)
tensor([ 1.3245, -0.3665, -3.2276, -3.7456], requires_grad=True)
tensor([ 1.3264, -0.3630, -3.2276, -3.7456], requires_grad=True)
tensor([ 1.3271, -0.3621, -3.2276, -3.7457], requires_grad=True)
tensor([ 1.3248, -0.3659, -3.2277, -3.7457], requires_grad=True)
tensor([ 1.3223, -0.3692, -3.2276, -3.7457], requires_grad=True)
tensor([ 1.3228, -0.3676,

tensor([ 1.3225, -0.3676, -3.2305, -3.7489], requires_grad=True)
tensor([ 1.3231, -0.3669, -3.2305, -3.7489], requires_grad=True)
tensor([ 1.3246, -0.3646, -3.2305, -3.7489], requires_grad=True)
tensor([ 1.3235, -0.3664, -3.2306, -3.7490], requires_grad=True)
tensor([ 1.3241, -0.3660, -3.2306, -3.7490], requires_grad=True)
tensor([ 1.3236, -0.3673, -3.2305, -3.7490], requires_grad=True)
tensor([ 1.3241, -0.3664, -3.2306, -3.7490], requires_grad=True)
tensor([ 1.3230, -0.3678, -3.2306, -3.7491], requires_grad=True)
tensor([ 1.3203, -0.3725, -3.2307, -3.7492], requires_grad=True)
tensor([ 1.3218, -0.3699, -3.2307, -3.7493], requires_grad=True)
tensor([ 1.3228, -0.3678, -3.2308, -3.7493], requires_grad=True)
tensor([ 1.3227, -0.3681, -3.2309, -3.7494], requires_grad=True)
tensor([ 1.3241, -0.3659, -3.2309, -3.7494], requires_grad=True)
tensor([ 1.3220, -0.3697, -3.2310, -3.7495], requires_grad=True)
tensor([ 1.3190, -0.3743, -3.2310, -3.7496], requires_grad=True)
tensor([ 1.3207, -0.3712,

tensor([ 1.3253, -0.3640, -3.2349, -3.7536], requires_grad=True)
tensor([ 1.3260, -0.3632, -3.2349, -3.7536], requires_grad=True)
tensor([ 1.3255, -0.3636, -3.2348, -3.7535], requires_grad=True)
tensor([ 1.3238, -0.3666, -3.2348, -3.7536], requires_grad=True)
tensor([ 1.3249, -0.3649, -3.2348, -3.7536], requires_grad=True)
tensor([ 1.3233, -0.3673, -3.2348, -3.7537], requires_grad=True)
tensor([ 1.3244, -0.3657, -3.2349, -3.7537], requires_grad=True)
tensor([ 1.3271, -0.3608, -3.2349, -3.7538], requires_grad=True)
tensor([ 1.3254, -0.3641, -3.2350, -3.7539], requires_grad=True)
tensor([ 1.3241, -0.3661, -3.2350, -3.7539], requires_grad=True)
tensor([ 1.3259, -0.3637, -3.2350, -3.7539], requires_grad=True)
tensor([ 1.3271, -0.3619, -3.2350, -3.7539], requires_grad=True)
tensor([ 1.3256, -0.3649, -3.2351, -3.7540], requires_grad=True)
tensor([ 1.3232, -0.3686, -3.2351, -3.7541], requires_grad=True)
tensor([ 1.3229, -0.3696, -3.2351, -3.7541], requires_grad=True)
tensor([ 1.3240, -0.3684,

tensor([ 1.3182, -0.3741, -3.2392, -3.7581], requires_grad=True)
tensor([ 1.3165, -0.3767, -3.2392, -3.7581], requires_grad=True)
tensor([ 1.3195, -0.3718, -3.2393, -3.7582], requires_grad=True)
tensor([ 1.3174, -0.3751, -3.2392, -3.7582], requires_grad=True)
tensor([ 1.3203, -0.3696, -3.2393, -3.7582], requires_grad=True)
tensor([ 1.3209, -0.3686, -3.2394, -3.7583], requires_grad=True)
tensor([ 1.3175, -0.3740, -3.2394, -3.7584], requires_grad=True)
tensor([ 1.3161, -0.3758, -3.2394, -3.7585], requires_grad=True)
tensor([ 1.3171, -0.3742, -3.2394, -3.7585], requires_grad=True)
tensor([ 1.3200, -0.3691, -3.2393, -3.7585], requires_grad=True)
tensor([ 1.3211, -0.3671, -3.2394, -3.7585], requires_grad=True)
tensor([ 1.3204, -0.3687, -3.2394, -3.7586], requires_grad=True)
tensor([ 1.3184, -0.3724, -3.2395, -3.7586], requires_grad=True)
tensor([ 1.3213, -0.3677, -3.2396, -3.7586], requires_grad=True)
tensor([ 1.3224, -0.3657, -3.2396, -3.7586], requires_grad=True)
tensor([ 1.3214, -0.3682,

tensor([ 1.3231, -0.3660, -3.2431, -3.7626], requires_grad=True)
tensor([ 1.3224, -0.3671, -3.2431, -3.7626], requires_grad=True)
tensor([ 1.3211, -0.3703, -3.2431, -3.7626], requires_grad=True)
tensor([ 1.3240, -0.3652, -3.2432, -3.7626], requires_grad=True)
tensor([ 1.3246, -0.3639, -3.2431, -3.7626], requires_grad=True)
tensor([ 1.3259, -0.3623, -3.2432, -3.7627], requires_grad=True)
tensor([ 1.3243, -0.3652, -3.2432, -3.7627], requires_grad=True)
tensor([ 1.3262, -0.3618, -3.2433, -3.7627], requires_grad=True)
tensor([ 1.3256, -0.3632, -3.2433, -3.7628], requires_grad=True)
tensor([ 1.3238, -0.3670, -3.2434, -3.7628], requires_grad=True)
tensor([ 1.3258, -0.3641, -3.2434, -3.7629], requires_grad=True)
tensor([ 1.3249, -0.3656, -3.2434, -3.7630], requires_grad=True)
tensor([ 1.3269, -0.3623, -3.2434, -3.7629], requires_grad=True)
tensor([ 1.3261, -0.3633, -3.2435, -3.7630], requires_grad=True)
tensor([ 1.3243, -0.3665, -3.2435, -3.7630], requires_grad=True)
tensor([ 1.3251, -0.3645,

tensor([ 1.3222, -0.3673, -3.2467, -3.7661], requires_grad=True)
tensor([ 1.3217, -0.3679, -3.2468, -3.7662], requires_grad=True)
tensor([ 1.3208, -0.3699, -3.2468, -3.7662], requires_grad=True)
tensor([ 1.3218, -0.3679, -3.2468, -3.7662], requires_grad=True)
tensor([ 1.3222, -0.3675, -3.2469, -3.7662], requires_grad=True)
tensor([ 1.3224, -0.3678, -3.2468, -3.7662], requires_grad=True)
tensor([ 1.3217, -0.3687, -3.2469, -3.7663], requires_grad=True)
tensor([ 1.3237, -0.3656, -3.2470, -3.7664], requires_grad=True)
tensor([ 1.3242, -0.3647, -3.2469, -3.7664], requires_grad=True)
tensor([ 1.3237, -0.3655, -3.2470, -3.7664], requires_grad=True)
tensor([ 1.3229, -0.3667, -3.2470, -3.7664], requires_grad=True)
tensor([ 1.3209, -0.3702, -3.2470, -3.7664], requires_grad=True)
tensor([ 1.3202, -0.3712, -3.2471, -3.7665], requires_grad=True)
tensor([ 1.3223, -0.3672, -3.2472, -3.7665], requires_grad=True)
tensor([ 1.3216, -0.3680, -3.2472, -3.7665], requires_grad=True)
tensor([ 1.3230, -0.3656,

tensor([ 1.3214, -0.3708, -3.2507, -3.7699], requires_grad=True)
tensor([ 1.3194, -0.3739, -3.2506, -3.7698], requires_grad=True)
tensor([ 1.3197, -0.3736, -3.2506, -3.7698], requires_grad=True)
tensor([ 1.3228, -0.3689, -3.2506, -3.7698], requires_grad=True)
tensor([ 1.3225, -0.3692, -3.2506, -3.7698], requires_grad=True)
tensor([ 1.3241, -0.3657, -3.2506, -3.7698], requires_grad=True)
tensor([ 1.3251, -0.3644, -3.2506, -3.7699], requires_grad=True)
tensor([ 1.3257, -0.3637, -3.2507, -3.7700], requires_grad=True)
tensor([ 1.3248, -0.3652, -3.2508, -3.7700], requires_grad=True)
tensor([ 1.3255, -0.3634, -3.2508, -3.7700], requires_grad=True)
tensor([ 1.3256, -0.3634, -3.2508, -3.7700], requires_grad=True)
tensor([ 1.3265, -0.3617, -3.2508, -3.7701], requires_grad=True)
tensor([ 1.3248, -0.3644, -3.2509, -3.7700], requires_grad=True)
tensor([ 1.3226, -0.3683, -3.2508, -3.7699], requires_grad=True)
tensor([ 1.3225, -0.3679, -3.2509, -3.7700], requires_grad=True)
tensor([ 1.3246, -0.3640,

tensor([ 1.3220, -0.3707, -3.2535, -3.7726], requires_grad=True)
tensor([ 1.3241, -0.3672, -3.2536, -3.7727], requires_grad=True)
tensor([ 1.3247, -0.3665, -3.2536, -3.7727], requires_grad=True)
tensor([ 1.3256, -0.3652, -3.2536, -3.7728], requires_grad=True)
tensor([ 1.3230, -0.3703, -3.2536, -3.7728], requires_grad=True)
tensor([ 1.3262, -0.3649, -3.2537, -3.7729], requires_grad=True)
tensor([ 1.3258, -0.3658, -3.2539, -3.7730], requires_grad=True)
tensor([ 1.3275, -0.3632, -3.2539, -3.7731], requires_grad=True)
tensor([ 1.3283, -0.3623, -3.2538, -3.7730], requires_grad=True)
tensor([ 1.3273, -0.3637, -3.2538, -3.7731], requires_grad=True)
tensor([ 1.3284, -0.3619, -3.2538, -3.7732], requires_grad=True)
tensor([ 1.3283, -0.3622, -3.2539, -3.7731], requires_grad=True)
tensor([ 1.3253, -0.3677, -3.2539, -3.7731], requires_grad=True)
tensor([ 1.3245, -0.3685, -3.2539, -3.7731], requires_grad=True)
tensor([ 1.3234, -0.3699, -3.2540, -3.7732], requires_grad=True)
tensor([ 1.3240, -0.3694,

tensor([ 1.3257, -0.3627, -3.2564, -3.7766], requires_grad=True)
tensor([ 1.3233, -0.3670, -3.2564, -3.7766], requires_grad=True)
tensor([ 1.3232, -0.3669, -3.2564, -3.7766], requires_grad=True)
tensor([ 1.3223, -0.3680, -3.2564, -3.7766], requires_grad=True)
tensor([ 1.3216, -0.3691, -3.2565, -3.7767], requires_grad=True)
tensor([ 1.3228, -0.3671, -3.2565, -3.7767], requires_grad=True)
tensor([ 1.3229, -0.3671, -3.2565, -3.7767], requires_grad=True)
tensor([ 1.3223, -0.3682, -3.2565, -3.7767], requires_grad=True)
tensor([ 1.3227, -0.3676, -3.2565, -3.7768], requires_grad=True)
tensor([ 1.3229, -0.3678, -3.2565, -3.7768], requires_grad=True)
tensor([ 1.3207, -0.3719, -3.2566, -3.7768], requires_grad=True)
tensor([ 1.3207, -0.3716, -3.2566, -3.7768], requires_grad=True)
tensor([ 1.3220, -0.3695, -3.2567, -3.7769], requires_grad=True)
tensor([ 1.3223, -0.3691, -3.2567, -3.7769], requires_grad=True)
tensor([ 1.3224, -0.3686, -3.2567, -3.7770], requires_grad=True)
tensor([ 1.3218, -0.3697,

tensor([ 1.3219, -0.3673, -3.2603, -3.7807], requires_grad=True)
tensor([ 1.3232, -0.3647, -3.2604, -3.7807], requires_grad=True)
tensor([ 1.3230, -0.3646, -3.2604, -3.7807], requires_grad=True)
tensor([ 1.3214, -0.3673, -3.2605, -3.7808], requires_grad=True)
tensor([ 1.3210, -0.3683, -3.2605, -3.7808], requires_grad=True)
tensor([ 1.3229, -0.3648, -3.2606, -3.7809], requires_grad=True)
tensor([ 1.3236, -0.3636, -3.2605, -3.7809], requires_grad=True)
tensor([ 1.3244, -0.3621, -3.2605, -3.7809], requires_grad=True)
tensor([ 1.3250, -0.3614, -3.2606, -3.7809], requires_grad=True)
tensor([ 1.3240, -0.3634, -3.2606, -3.7810], requires_grad=True)
tensor([ 1.3257, -0.3608, -3.2606, -3.7810], requires_grad=True)
tensor([ 1.3226, -0.3668, -3.2607, -3.7810], requires_grad=True)
tensor([ 1.3201, -0.3711, -3.2607, -3.7810], requires_grad=True)
tensor([ 1.3199, -0.3713, -3.2608, -3.7811], requires_grad=True)
tensor([ 1.3208, -0.3698, -3.2608, -3.7811], requires_grad=True)
tensor([ 1.3205, -0.3703,

tensor([ 1.3234, -0.3671, -3.2633, -3.7841], requires_grad=True)
tensor([ 1.3223, -0.3691, -3.2633, -3.7842], requires_grad=True)
tensor([ 1.3216, -0.3707, -3.2633, -3.7842], requires_grad=True)
tensor([ 1.3216, -0.3708, -3.2634, -3.7842], requires_grad=True)
tensor([ 1.3221, -0.3701, -3.2634, -3.7841], requires_grad=True)
tensor([ 1.3177, -0.3776, -3.2634, -3.7842], requires_grad=True)
tensor([ 1.3204, -0.3734, -3.2635, -3.7842], requires_grad=True)
tensor([ 1.3192, -0.3746, -3.2636, -3.7841], requires_grad=True)
tensor([ 1.3190, -0.3743, -3.2636, -3.7841], requires_grad=True)
tensor([ 1.3196, -0.3730, -3.2636, -3.7841], requires_grad=True)
tensor([ 1.3204, -0.3721, -3.2636, -3.7840], requires_grad=True)
tensor([ 1.3209, -0.3713, -3.2636, -3.7840], requires_grad=True)
tensor([ 1.3226, -0.3682, -3.2636, -3.7841], requires_grad=True)
tensor([ 1.3206, -0.3712, -3.2636, -3.7841], requires_grad=True)
tensor([ 1.3232, -0.3671, -3.2636, -3.7842], requires_grad=True)
tensor([ 1.3228, -0.3680,

tensor([ 1.3264, -0.3637, -3.2657, -3.7867], requires_grad=True)
tensor([ 1.3289, -0.3600, -3.2657, -3.7868], requires_grad=True)
tensor([ 1.3246, -0.3672, -3.2658, -3.7869], requires_grad=True)
tensor([ 1.3240, -0.3682, -3.2659, -3.7870], requires_grad=True)
tensor([ 1.3255, -0.3661, -3.2658, -3.7870], requires_grad=True)
tensor([ 1.3248, -0.3673, -3.2658, -3.7871], requires_grad=True)
tensor([ 1.3265, -0.3647, -3.2659, -3.7872], requires_grad=True)
tensor([ 1.3261, -0.3651, -3.2659, -3.7872], requires_grad=True)
tensor([ 1.3264, -0.3643, -3.2658, -3.7872], requires_grad=True)
tensor([ 1.3258, -0.3651, -3.2659, -3.7873], requires_grad=True)
tensor([ 1.3256, -0.3649, -3.2660, -3.7874], requires_grad=True)
tensor([ 1.3261, -0.3643, -3.2660, -3.7874], requires_grad=True)
tensor([ 1.3246, -0.3668, -3.2660, -3.7875], requires_grad=True)
tensor([ 1.3245, -0.3670, -3.2661, -3.7876], requires_grad=True)
tensor([ 1.3261, -0.3640, -3.2661, -3.7875], requires_grad=True)
tensor([ 1.3251, -0.3661,

tensor([ 1.3200, -0.3705, -3.2684, -3.7896], requires_grad=True)
tensor([ 1.3213, -0.3684, -3.2684, -3.7897], requires_grad=True)
tensor([ 1.3228, -0.3658, -3.2685, -3.7897], requires_grad=True)
tensor([ 1.3218, -0.3679, -3.2685, -3.7898], requires_grad=True)
tensor([ 1.3207, -0.3695, -3.2685, -3.7897], requires_grad=True)
tensor([ 1.3217, -0.3684, -3.2686, -3.7898], requires_grad=True)
tensor([ 1.3206, -0.3701, -3.2686, -3.7898], requires_grad=True)
tensor([ 1.3237, -0.3648, -3.2686, -3.7898], requires_grad=True)
tensor([ 1.3255, -0.3618, -3.2686, -3.7898], requires_grad=True)
tensor([ 1.3274, -0.3595, -3.2686, -3.7899], requires_grad=True)
tensor([ 1.3275, -0.3591, -3.2685, -3.7899], requires_grad=True)
tensor([ 1.3275, -0.3588, -3.2685, -3.7899], requires_grad=True)
tensor([ 1.3245, -0.3643, -3.2686, -3.7899], requires_grad=True)
tensor([ 1.3245, -0.3641, -3.2686, -3.7899], requires_grad=True)
tensor([ 1.3238, -0.3652, -3.2686, -3.7899], requires_grad=True)
tensor([ 1.3218, -0.3688,

tensor([ 1.3250, -0.3667, -3.2710, -3.7925], requires_grad=True)
tensor([ 1.3237, -0.3693, -3.2709, -3.7924], requires_grad=True)
tensor([ 1.3242, -0.3686, -3.2709, -3.7924], requires_grad=True)
tensor([ 1.3238, -0.3692, -3.2709, -3.7924], requires_grad=True)
tensor([ 1.3233, -0.3698, -3.2709, -3.7924], requires_grad=True)
tensor([ 1.3246, -0.3680, -3.2709, -3.7924], requires_grad=True)
tensor([ 1.3252, -0.3667, -3.2709, -3.7925], requires_grad=True)
tensor([ 1.3257, -0.3662, -3.2709, -3.7924], requires_grad=True)
tensor([ 1.3247, -0.3672, -3.2709, -3.7924], requires_grad=True)
tensor([ 1.3257, -0.3656, -3.2710, -3.7924], requires_grad=True)
tensor([ 1.3258, -0.3659, -3.2710, -3.7924], requires_grad=True)
tensor([ 1.3246, -0.3682, -3.2711, -3.7925], requires_grad=True)
tensor([ 1.3256, -0.3663, -3.2710, -3.7925], requires_grad=True)
tensor([ 1.3265, -0.3651, -3.2710, -3.7926], requires_grad=True)
tensor([ 1.3270, -0.3644, -3.2711, -3.7926], requires_grad=True)
tensor([ 1.3253, -0.3669,

tensor([ 1.3263, -0.3647, -3.2733, -3.7953], requires_grad=True)
tensor([ 1.3267, -0.3641, -3.2734, -3.7953], requires_grad=True)
tensor([ 1.3282, -0.3615, -3.2734, -3.7953], requires_grad=True)
tensor([ 1.3294, -0.3593, -3.2735, -3.7953], requires_grad=True)
tensor([ 1.3280, -0.3621, -3.2735, -3.7954], requires_grad=True)
tensor([ 1.3281, -0.3620, -3.2736, -3.7954], requires_grad=True)
tensor([ 1.3257, -0.3665, -3.2736, -3.7954], requires_grad=True)
tensor([ 1.3257, -0.3661, -3.2735, -3.7954], requires_grad=True)
tensor([ 1.3245, -0.3687, -3.2735, -3.7954], requires_grad=True)
tensor([ 1.3265, -0.3656, -3.2735, -3.7954], requires_grad=True)
tensor([ 1.3283, -0.3627, -3.2734, -3.7954], requires_grad=True)
tensor([ 1.3248, -0.3687, -3.2734, -3.7955], requires_grad=True)
tensor([ 1.3252, -0.3681, -3.2734, -3.7956], requires_grad=True)
tensor([ 1.3245, -0.3696, -3.2735, -3.7956], requires_grad=True)
tensor([ 1.3253, -0.3682, -3.2735, -3.7956], requires_grad=True)
tensor([ 1.3280, -0.3637,

tensor([ 1.3266, -0.3630, -3.2765, -3.7986], requires_grad=True)
tensor([ 1.3253, -0.3649, -3.2766, -3.7986], requires_grad=True)
tensor([ 1.3253, -0.3651, -3.2765, -3.7986], requires_grad=True)
tensor([ 1.3250, -0.3657, -3.2765, -3.7986], requires_grad=True)
tensor([ 1.3266, -0.3630, -3.2766, -3.7987], requires_grad=True)
tensor([ 1.3253, -0.3659, -3.2766, -3.7987], requires_grad=True)
tensor([ 1.3249, -0.3667, -3.2767, -3.7988], requires_grad=True)
tensor([ 1.3218, -0.3720, -3.2767, -3.7988], requires_grad=True)
tensor([ 1.3230, -0.3693, -3.2767, -3.7989], requires_grad=True)
tensor([ 1.3249, -0.3658, -3.2768, -3.7989], requires_grad=True)
tensor([ 1.3240, -0.3672, -3.2768, -3.7990], requires_grad=True)
tensor([ 1.3263, -0.3631, -3.2769, -3.7990], requires_grad=True)
tensor([ 1.3259, -0.3643, -3.2769, -3.7990], requires_grad=True)
tensor([ 1.3252, -0.3656, -3.2770, -3.7990], requires_grad=True)
tensor([ 1.3255, -0.3647, -3.2770, -3.7991], requires_grad=True)
tensor([ 1.3236, -0.3681,

tensor([ 1.3246, -0.3662, -3.2782, -3.8014], requires_grad=True)
tensor([ 1.3274, -0.3615, -3.2782, -3.8014], requires_grad=True)
tensor([ 1.3265, -0.3640, -3.2782, -3.8014], requires_grad=True)
tensor([ 1.3259, -0.3648, -3.2782, -3.8015], requires_grad=True)
tensor([ 1.3252, -0.3659, -3.2783, -3.8015], requires_grad=True)
tensor([ 1.3261, -0.3650, -3.2781, -3.8015], requires_grad=True)
tensor([ 1.3257, -0.3656, -3.2782, -3.8014], requires_grad=True)
tensor([ 1.3234, -0.3695, -3.2782, -3.8015], requires_grad=True)
tensor([ 1.3209, -0.3737, -3.2782, -3.8015], requires_grad=True)
tensor([ 1.3233, -0.3693, -3.2783, -3.8016], requires_grad=True)
tensor([ 1.3245, -0.3674, -3.2783, -3.8016], requires_grad=True)
tensor([ 1.3268, -0.3630, -3.2784, -3.8016], requires_grad=True)
tensor([ 1.3256, -0.3654, -3.2784, -3.8016], requires_grad=True)
tensor([ 1.3245, -0.3673, -3.2784, -3.8017], requires_grad=True)
tensor([ 1.3259, -0.3644, -3.2785, -3.8017], requires_grad=True)
tensor([ 1.3244, -0.3670,

tensor([ 1.3230, -0.3675, -3.2809, -3.8046], requires_grad=True)
tensor([ 1.3229, -0.3678, -3.2810, -3.8045], requires_grad=True)
tensor([ 1.3232, -0.3670, -3.2811, -3.8046], requires_grad=True)
tensor([ 1.3211, -0.3707, -3.2811, -3.8047], requires_grad=True)
tensor([ 1.3207, -0.3713, -3.2811, -3.8046], requires_grad=True)
tensor([ 1.3245, -0.3648, -3.2812, -3.8046], requires_grad=True)
tensor([ 1.3250, -0.3639, -3.2811, -3.8046], requires_grad=True)
tensor([ 1.3251, -0.3635, -3.2811, -3.8047], requires_grad=True)
tensor([ 1.3267, -0.3610, -3.2811, -3.8047], requires_grad=True)
tensor([ 1.3241, -0.3655, -3.2812, -3.8047], requires_grad=True)
tensor([ 1.3237, -0.3664, -3.2813, -3.8048], requires_grad=True)
tensor([ 1.3230, -0.3682, -3.2813, -3.8048], requires_grad=True)
tensor([ 1.3195, -0.3741, -3.2814, -3.8048], requires_grad=True)
tensor([ 1.3198, -0.3734, -3.2814, -3.8049], requires_grad=True)
tensor([ 1.3213, -0.3704, -3.2814, -3.8048], requires_grad=True)
tensor([ 1.3202, -0.3719,

tensor([ 1.3243, -0.3701, -3.2839, -3.8074], requires_grad=True)
tensor([ 1.3250, -0.3691, -3.2838, -3.8074], requires_grad=True)
tensor([ 1.3273, -0.3648, -3.2839, -3.8075], requires_grad=True)
tensor([ 1.3261, -0.3672, -3.2839, -3.8075], requires_grad=True)
tensor([ 1.3244, -0.3698, -3.2840, -3.8076], requires_grad=True)
tensor([ 1.3275, -0.3648, -3.2839, -3.8076], requires_grad=True)
tensor([ 1.3263, -0.3672, -3.2840, -3.8076], requires_grad=True)
tensor([ 1.3254, -0.3689, -3.2840, -3.8076], requires_grad=True)
tensor([ 1.3261, -0.3674, -3.2841, -3.8077], requires_grad=True)
tensor([ 1.3263, -0.3666, -3.2840, -3.8075], requires_grad=True)
tensor([ 1.3252, -0.3681, -3.2840, -3.8075], requires_grad=True)
tensor([ 1.3252, -0.3674, -3.2840, -3.8075], requires_grad=True)
tensor([ 1.3233, -0.3703, -3.2840, -3.8075], requires_grad=True)
tensor([ 1.3241, -0.3691, -3.2841, -3.8076], requires_grad=True)
tensor([ 1.3233, -0.3704, -3.2841, -3.8076], requires_grad=True)
tensor([ 1.3222, -0.3725,

tensor([ 1.3238, -0.3659, -3.2867, -3.8097], requires_grad=True)
tensor([ 1.3244, -0.3650, -3.2868, -3.8098], requires_grad=True)
tensor([ 1.3238, -0.3658, -3.2868, -3.8098], requires_grad=True)
tensor([ 1.3255, -0.3624, -3.2869, -3.8098], requires_grad=True)
tensor([ 1.3243, -0.3642, -3.2869, -3.8098], requires_grad=True)
tensor([ 1.3234, -0.3658, -3.2869, -3.8098], requires_grad=True)
tensor([ 1.3235, -0.3650, -3.2868, -3.8097], requires_grad=True)
tensor([ 1.3253, -0.3624, -3.2869, -3.8098], requires_grad=True)
tensor([ 1.3244, -0.3640, -3.2869, -3.8098], requires_grad=True)
tensor([ 1.3222, -0.3668, -3.2868, -3.8098], requires_grad=True)
tensor([ 1.3238, -0.3644, -3.2868, -3.8098], requires_grad=True)
tensor([ 1.3233, -0.3653, -3.2868, -3.8099], requires_grad=True)
tensor([ 1.3236, -0.3651, -3.2867, -3.8099], requires_grad=True)
tensor([ 1.3221, -0.3679, -3.2868, -3.8099], requires_grad=True)
tensor([ 1.3220, -0.3678, -3.2869, -3.8100], requires_grad=True)
tensor([ 1.3195, -0.3718,

tensor([ 1.3245, -0.3652, -3.2891, -3.8123], requires_grad=True)
tensor([ 1.3225, -0.3692, -3.2891, -3.8122], requires_grad=True)
tensor([ 1.3232, -0.3677, -3.2892, -3.8123], requires_grad=True)
tensor([ 1.3241, -0.3665, -3.2891, -3.8122], requires_grad=True)
tensor([ 1.3221, -0.3699, -3.2892, -3.8123], requires_grad=True)
tensor([ 1.3221, -0.3702, -3.2892, -3.8123], requires_grad=True)
tensor([ 1.3232, -0.3682, -3.2893, -3.8124], requires_grad=True)
tensor([ 1.3242, -0.3662, -3.2893, -3.8124], requires_grad=True)
tensor([ 1.3234, -0.3681, -3.2893, -3.8124], requires_grad=True)
tensor([ 1.3236, -0.3673, -3.2894, -3.8125], requires_grad=True)
tensor([ 1.3235, -0.3675, -3.2894, -3.8125], requires_grad=True)
tensor([ 1.3247, -0.3653, -3.2894, -3.8126], requires_grad=True)
tensor([ 1.3251, -0.3646, -3.2895, -3.8127], requires_grad=True)
tensor([ 1.3251, -0.3645, -3.2895, -3.8127], requires_grad=True)
tensor([ 1.3239, -0.3661, -3.2895, -3.8128], requires_grad=True)
tensor([ 1.3246, -0.3649,

tensor([ 1.3270, -0.3659, -3.2913, -3.8146], requires_grad=True)
tensor([ 1.3239, -0.3714, -3.2914, -3.8146], requires_grad=True)
tensor([ 1.3245, -0.3700, -3.2914, -3.8145], requires_grad=True)
tensor([ 1.3261, -0.3673, -3.2915, -3.8145], requires_grad=True)
tensor([ 1.3234, -0.3717, -3.2916, -3.8146], requires_grad=True)
tensor([ 1.3255, -0.3678, -3.2916, -3.8146], requires_grad=True)
tensor([ 1.3261, -0.3668, -3.2916, -3.8147], requires_grad=True)
tensor([ 1.3273, -0.3650, -3.2916, -3.8147], requires_grad=True)
tensor([ 1.3262, -0.3672, -3.2917, -3.8146], requires_grad=True)
tensor([ 1.3254, -0.3685, -3.2917, -3.8146], requires_grad=True)
tensor([ 1.3252, -0.3690, -3.2917, -3.8147], requires_grad=True)
tensor([ 1.3279, -0.3644, -3.2918, -3.8147], requires_grad=True)
tensor([ 1.3280, -0.3644, -3.2918, -3.8148], requires_grad=True)
tensor([ 1.3285, -0.3636, -3.2918, -3.8148], requires_grad=True)
tensor([ 1.3277, -0.3653, -3.2919, -3.8149], requires_grad=True)
tensor([ 1.3238, -0.3719,

tensor([ 1.3225, -0.3646, -3.2939, -3.8168], requires_grad=True)
tensor([ 1.3247, -0.3611, -3.2939, -3.8169], requires_grad=True)
tensor([ 1.3243, -0.3620, -3.2939, -3.8169], requires_grad=True)
tensor([ 1.3238, -0.3630, -3.2939, -3.8169], requires_grad=True)
tensor([ 1.3237, -0.3630, -3.2940, -3.8170], requires_grad=True)
tensor([ 1.3230, -0.3640, -3.2939, -3.8169], requires_grad=True)
tensor([ 1.3231, -0.3638, -3.2939, -3.8169], requires_grad=True)
tensor([ 1.3212, -0.3672, -3.2940, -3.8169], requires_grad=True)
tensor([ 1.3203, -0.3691, -3.2940, -3.8169], requires_grad=True)
tensor([ 1.3219, -0.3668, -3.2940, -3.8170], requires_grad=True)
tensor([ 1.3204, -0.3694, -3.2940, -3.8170], requires_grad=True)
tensor([ 1.3189, -0.3715, -3.2940, -3.8170], requires_grad=True)
tensor([ 1.3206, -0.3693, -3.2939, -3.8170], requires_grad=True)
tensor([ 1.3208, -0.3685, -3.2940, -3.8170], requires_grad=True)
tensor([ 1.3200, -0.3698, -3.2940, -3.8171], requires_grad=True)
tensor([ 1.3218, -0.3668,

tensor([ 1.3254, -0.3629, -3.2956, -3.8187], requires_grad=True)
tensor([ 1.3221, -0.3692, -3.2956, -3.8187], requires_grad=True)
tensor([ 1.3243, -0.3663, -3.2956, -3.8187], requires_grad=True)
tensor([ 1.3249, -0.3656, -3.2957, -3.8188], requires_grad=True)
tensor([ 1.3242, -0.3664, -3.2957, -3.8188], requires_grad=True)
tensor([ 1.3249, -0.3650, -3.2956, -3.8186], requires_grad=True)
tensor([ 1.3253, -0.3639, -3.2957, -3.8187], requires_grad=True)
tensor([ 1.3255, -0.3638, -3.2957, -3.8188], requires_grad=True)
tensor([ 1.3268, -0.3617, -3.2956, -3.8188], requires_grad=True)
tensor([ 1.3262, -0.3628, -3.2956, -3.8188], requires_grad=True)
tensor([ 1.3267, -0.3617, -3.2957, -3.8187], requires_grad=True)
tensor([ 1.3254, -0.3640, -3.2957, -3.8188], requires_grad=True)
tensor([ 1.3248, -0.3648, -3.2957, -3.8188], requires_grad=True)
tensor([ 1.3244, -0.3658, -3.2957, -3.8188], requires_grad=True)
tensor([ 1.3239, -0.3667, -3.2958, -3.8188], requires_grad=True)
tensor([ 1.3215, -0.3711,

tensor([ 1.3230, -0.3658, -3.2973, -3.8210], requires_grad=True)
tensor([ 1.3240, -0.3648, -3.2973, -3.8210], requires_grad=True)
tensor([ 1.3226, -0.3665, -3.2972, -3.8210], requires_grad=True)
tensor([ 1.3230, -0.3664, -3.2971, -3.8210], requires_grad=True)
tensor([ 1.3233, -0.3660, -3.2970, -3.8210], requires_grad=True)
tensor([ 1.3255, -0.3620, -3.2971, -3.8209], requires_grad=True)
tensor([ 1.3234, -0.3660, -3.2971, -3.8209], requires_grad=True)
tensor([ 1.3222, -0.3682, -3.2971, -3.8209], requires_grad=True)
tensor([ 1.3244, -0.3640, -3.2971, -3.8209], requires_grad=True)
tensor([ 1.3220, -0.3683, -3.2971, -3.8210], requires_grad=True)
tensor([ 1.3202, -0.3720, -3.2972, -3.8210], requires_grad=True)
tensor([ 1.3209, -0.3707, -3.2972, -3.8209], requires_grad=True)
tensor([ 1.3207, -0.3711, -3.2973, -3.8210], requires_grad=True)
tensor([ 1.3215, -0.3700, -3.2973, -3.8210], requires_grad=True)
tensor([ 1.3234, -0.3669, -3.2973, -3.8210], requires_grad=True)
tensor([ 1.3244, -0.3661,

tensor([ 1.3226, -0.3656, -3.2986, -3.8224], requires_grad=True)
tensor([ 1.3204, -0.3694, -3.2987, -3.8225], requires_grad=True)
tensor([ 1.3206, -0.3689, -3.2988, -3.8225], requires_grad=True)
tensor([ 1.3213, -0.3677, -3.2987, -3.8226], requires_grad=True)
tensor([ 1.3208, -0.3680, -3.2987, -3.8226], requires_grad=True)
tensor([ 1.3211, -0.3674, -3.2986, -3.8225], requires_grad=True)
tensor([ 1.3208, -0.3682, -3.2986, -3.8225], requires_grad=True)
tensor([ 1.3228, -0.3651, -3.2986, -3.8226], requires_grad=True)
tensor([ 1.3228, -0.3650, -3.2986, -3.8226], requires_grad=True)


In [170]:
rho_to_sigma(torch.tensor(0.5488))

tensor(1.0047)