In [1]:
import pandas as pd
import os
import numpy as np
import scipy as sp
import torch

In [2]:
from scipy.stats import uniform, norm
import seaborn as sns; sns.set()
import matplotlib.pyplot as plt

In [3]:
A = 1.2
b = -0.3
sigma = 0.2
N = 100

In [4]:
X = torch.from_numpy(uniform.rvs(size=N))
X.detach()
X = X.float()

In [5]:
e = torch.from_numpy(norm.rvs(loc=0, scale=sigma, size=N)).float()

In [6]:
y = A*X + b + e

In [7]:
y.detach()
y = y.float()

In [8]:
def sigma_to_rho(sigma):
    rho = torch.log(torch.exp(sigma) - 1)
    return rho

In [9]:
def rho_to_sigma(rho):
    sigma = torch.log(1 + torch.exp(rho))
    return sigma

In [10]:
def log_q_pdf(w, theta):
    (mu_A, mu_b, rho_A, rho_b) = theta 
    
    sigma_A = rho_to_sigma(rho_A)
    qA = torch.distributions.normal.Normal(mu_A, sigma_A)
    
    sigma_b = rho_to_sigma(rho_b)
    qb = torch.distributions.normal.Normal(mu_b, sigma_b)
    
    lp = qA.log_prob(w[0]) + qb.log_prob(w[1])
    return lp

In [11]:
def log_p_pdf(w):
    prior_mu_A = torch.tensor(0.0) 
    prior_sigma_A = torch.tensor(1.0)
    pA = torch.distributions.normal.Normal(prior_mu_A, prior_sigma_A)
    
    prior_mu_b = torch.tensor(0.0) 
    prior_sigma_b = torch.tensor(1.0)
    pb = torch.distributions.normal.Normal(prior_mu_b, prior_sigma_b)
    
    lp = pA.log_prob(w[0]) + pb.log_prob(w[1])
    return lp

In [12]:
def likelihood(y,X,w):
    A = w[0]
    b = w[1]
    
    y_pred = A*X + b
    lp = torch.distributions.normal.Normal(y_pred, 0.2).log_prob(y).sum()
    return lp

In [13]:
def f(w, theta):
    v = log_q_pdf(w, theta) - log_p_pdf(w) - likelihood(y,X,w)
    return v

In [14]:
mu_A = torch.tensor(0.0)
sigma_A = torch.tensor(0.1)
rho_A = sigma_to_rho(sigma_A)
mu_b = torch.tensor(0.0)
sigma_b = torch.tensor(0.1)
rho_b = sigma_to_rho(sigma_b)

theta = torch.tensor([mu_A, mu_b, rho_A, rho_b], requires_grad=True)

In [15]:

lst_grad_mu = []
lst_grad_rho = []
for j in range(0,5000):
    epsilon = torch.distributions.normal.Normal(torch.tensor(0.0) , torch.tensor(1.0)).sample(torch.Size([2,]))

    with torch.no_grad():
        w = theta[0:2].clone().detach() + torch.log(1 + torch.exp(theta[2:4].clone().detach()))*epsilon
    w.requires_grad = True

    v = f(w, theta)   
    v.backward()
    v = torch.tensor([])

    with torch.no_grad():
        grad_mu = w.grad + theta.grad[0:2]
        grad_rho = w.grad*epsilon/(1 + torch.exp(-theta[2:4])) + -theta.grad[2:4]


    lst_grad_mu.append(grad_mu)
    lst_grad_rho.append(grad_rho)

    theta.grad.zero_()
    w.grad.zero_()
    v.detach()
grad_mu = torch.stack(lst_grad_mu).mean(dim=0)
grad_rho = torch.stack(lst_grad_rho).mean(dim=0)
        
 



In [16]:
grad_mu

tensor([-301.9706, -498.8301])

In [17]:
grad_rho

tensor([ 6.5926, 22.0693])

In [18]:
alpha = torch.tensor(10e-5)

In [19]:
for i in range(0,10000):
    lst_grad_mu = []
    lst_grad_rho = []
    for j in range(0,10):
        epsilon = torch.distributions.normal.Normal(torch.tensor(0.0) , torch.tensor(1.0)).sample(torch.Size([2,]))

        with torch.no_grad():
            w = theta[0:2].clone().detach() + torch.log(1 + torch.exp(theta[2:4].clone().detach()))*epsilon
        w.requires_grad = True

        v = f(w, theta)   
        v.backward()
        v = torch.tensor([])

        with torch.no_grad():
            grad_mu = w.grad + theta.grad[0:2]
            grad_rho = w.grad*epsilon/(1 + torch.exp(-theta[2:4])) + -theta.grad[2:4]


        lst_grad_mu.append(grad_mu)
        lst_grad_rho.append(grad_rho)

        theta.grad.zero_()
        w.grad.zero_()
        v.detach()
    grad_mu = torch.stack(lst_grad_mu).mean(dim=0)
    grad_rho = torch.stack(lst_grad_rho).mean(dim=0)
    
    #print(grad_mu)
    #print(grad_rho)
        
    with torch.no_grad():
        theta[0:2] -= alpha*grad_mu
        theta[2:4] -= alpha*grad_rho
    
    print(theta)



tensor([ 1.0310, -0.3495, -2.2532, -2.2538], requires_grad=True)
tensor([ 1.0409, -0.3362, -2.2528, -2.2547], requires_grad=True)
tensor([ 1.0588, -0.3098, -2.2544, -2.2567], requires_grad=True)
tensor([ 1.0756, -0.2842, -2.2546, -2.2594], requires_grad=True)
tensor([ 1.0757, -0.2904, -2.2552, -2.2618], requires_grad=True)
tensor([ 1.0844, -0.2795, -2.2560, -2.2654], requires_grad=True)
tensor([ 1.0925, -0.2700, -2.2560, -2.2673], requires_grad=True)
tensor([ 1.0928, -0.2756, -2.2570, -2.2710], requires_grad=True)
tensor([ 1.1031, -0.2636, -2.2579, -2.2724], requires_grad=True)
tensor([ 1.1142, -0.2497, -2.2586, -2.2740], requires_grad=True)
tensor([ 1.1235, -0.2389, -2.2599, -2.2777], requires_grad=True)
tensor([ 1.1267, -0.2390, -2.2603, -2.2800], requires_grad=True)
tensor([ 1.1232, -0.2494, -2.2603, -2.2831], requires_grad=True)
tensor([ 1.1264, -0.2500, -2.2607, -2.2841], requires_grad=True)
tensor([ 1.1252, -0.2583, -2.2620, -2.2859], requires_grad=True)
tensor([ 1.1244, -0.2644,

tensor([ 1.2379, -0.3234, -2.3375, -2.5041], requires_grad=True)
tensor([ 1.2377, -0.3239, -2.3380, -2.5048], requires_grad=True)
tensor([ 1.2391, -0.3219, -2.3386, -2.5053], requires_grad=True)
tensor([ 1.2432, -0.3150, -2.3390, -2.5061], requires_grad=True)
tensor([ 1.2489, -0.3038, -2.3394, -2.5069], requires_grad=True)
tensor([ 1.2443, -0.3119, -2.3404, -2.5073], requires_grad=True)
tensor([ 1.2538, -0.2956, -2.3413, -2.5086], requires_grad=True)
tensor([ 1.2485, -0.3068, -2.3419, -2.5111], requires_grad=True)
tensor([ 1.2569, -0.2933, -2.3432, -2.5134], requires_grad=True)
tensor([ 1.2443, -0.3168, -2.3446, -2.5159], requires_grad=True)
tensor([ 1.2423, -0.3221, -2.3451, -2.5167], requires_grad=True)
tensor([ 1.2455, -0.3153, -2.3455, -2.5178], requires_grad=True)
tensor([ 1.2431, -0.3189, -2.3464, -2.5189], requires_grad=True)
tensor([ 1.2398, -0.3257, -2.3466, -2.5202], requires_grad=True)
tensor([ 1.2382, -0.3295, -2.3473, -2.5230], requires_grad=True)
tensor([ 1.2510, -0.3082,

tensor([ 1.2499, -0.3245, -2.4106, -2.6618], requires_grad=True)
tensor([ 1.2474, -0.3300, -2.4114, -2.6635], requires_grad=True)
tensor([ 1.2475, -0.3297, -2.4117, -2.6644], requires_grad=True)
tensor([ 1.2502, -0.3246, -2.4123, -2.6652], requires_grad=True)
tensor([ 1.2461, -0.3322, -2.4126, -2.6661], requires_grad=True)
tensor([ 1.2501, -0.3237, -2.4124, -2.6679], requires_grad=True)
tensor([ 1.2469, -0.3306, -2.4130, -2.6686], requires_grad=True)
tensor([ 1.2413, -0.3399, -2.4137, -2.6701], requires_grad=True)
tensor([ 1.2394, -0.3436, -2.4142, -2.6708], requires_grad=True)
tensor([ 1.2442, -0.3355, -2.4150, -2.6727], requires_grad=True)
tensor([ 1.2422, -0.3404, -2.4153, -2.6739], requires_grad=True)
tensor([ 1.2446, -0.3356, -2.4159, -2.6741], requires_grad=True)
tensor([ 1.2442, -0.3369, -2.4162, -2.6746], requires_grad=True)
tensor([ 1.2469, -0.3315, -2.4167, -2.6761], requires_grad=True)
tensor([ 1.2493, -0.3266, -2.4174, -2.6771], requires_grad=True)
tensor([ 1.2462, -0.3334,

tensor([ 1.2521, -0.3276, -2.4724, -2.7928], requires_grad=True)
tensor([ 1.2581, -0.3174, -2.4729, -2.7930], requires_grad=True)
tensor([ 1.2585, -0.3161, -2.4732, -2.7936], requires_grad=True)
tensor([ 1.2627, -0.3089, -2.4741, -2.7942], requires_grad=True)
tensor([ 1.2573, -0.3185, -2.4745, -2.7946], requires_grad=True)
tensor([ 1.2544, -0.3227, -2.4751, -2.7956], requires_grad=True)
tensor([ 1.2548, -0.3215, -2.4756, -2.7964], requires_grad=True)
tensor([ 1.2589, -0.3150, -2.4759, -2.7970], requires_grad=True)
tensor([ 1.2575, -0.3173, -2.4763, -2.7974], requires_grad=True)
tensor([ 1.2512, -0.3284, -2.4768, -2.7981], requires_grad=True)
tensor([ 1.2459, -0.3378, -2.4776, -2.8000], requires_grad=True)
tensor([ 1.2459, -0.3392, -2.4787, -2.8015], requires_grad=True)
tensor([ 1.2459, -0.3392, -2.4791, -2.8022], requires_grad=True)
tensor([ 1.2551, -0.3227, -2.4796, -2.8033], requires_grad=True)
tensor([ 1.2485, -0.3348, -2.4801, -2.8041], requires_grad=True)
tensor([ 1.2527, -0.3264,

tensor([ 1.2594, -0.3173, -2.5287, -2.8865], requires_grad=True)
tensor([ 1.2569, -0.3217, -2.5290, -2.8869], requires_grad=True)
tensor([ 1.2588, -0.3192, -2.5293, -2.8871], requires_grad=True)
tensor([ 1.2517, -0.3324, -2.5298, -2.8881], requires_grad=True)
tensor([ 1.2561, -0.3237, -2.5301, -2.8886], requires_grad=True)
tensor([ 1.2525, -0.3288, -2.5302, -2.8892], requires_grad=True)
tensor([ 1.2525, -0.3279, -2.5304, -2.8903], requires_grad=True)
tensor([ 1.2583, -0.3173, -2.5308, -2.8911], requires_grad=True)
tensor([ 1.2616, -0.3108, -2.5313, -2.8921], requires_grad=True)
tensor([ 1.2557, -0.3219, -2.5315, -2.8929], requires_grad=True)
tensor([ 1.2503, -0.3316, -2.5320, -2.8939], requires_grad=True)
tensor([ 1.2487, -0.3352, -2.5325, -2.8954], requires_grad=True)
tensor([ 1.2506, -0.3311, -2.5327, -2.8960], requires_grad=True)
tensor([ 1.2506, -0.3299, -2.5330, -2.8969], requires_grad=True)
tensor([ 1.2536, -0.3237, -2.5334, -2.8974], requires_grad=True)
tensor([ 1.2519, -0.3266,

tensor([ 1.2555, -0.3184, -2.5724, -2.9637], requires_grad=True)
tensor([ 1.2513, -0.3258, -2.5732, -2.9644], requires_grad=True)
tensor([ 1.2515, -0.3258, -2.5736, -2.9649], requires_grad=True)
tensor([ 1.2506, -0.3278, -2.5739, -2.9654], requires_grad=True)
tensor([ 1.2508, -0.3262, -2.5742, -2.9660], requires_grad=True)
tensor([ 1.2498, -0.3281, -2.5746, -2.9664], requires_grad=True)
tensor([ 1.2499, -0.3287, -2.5748, -2.9670], requires_grad=True)
tensor([ 1.2473, -0.3343, -2.5750, -2.9675], requires_grad=True)
tensor([ 1.2488, -0.3322, -2.5754, -2.9677], requires_grad=True)
tensor([ 1.2486, -0.3338, -2.5761, -2.9684], requires_grad=True)
tensor([ 1.2479, -0.3358, -2.5765, -2.9688], requires_grad=True)
tensor([ 1.2507, -0.3302, -2.5770, -2.9696], requires_grad=True)
tensor([ 1.2558, -0.3215, -2.5772, -2.9700], requires_grad=True)
tensor([ 1.2546, -0.3231, -2.5776, -2.9704], requires_grad=True)
tensor([ 1.2492, -0.3327, -2.5780, -2.9710], requires_grad=True)
tensor([ 1.2513, -0.3273,

tensor([ 1.2599, -0.3137, -2.6181, -3.0260], requires_grad=True)
tensor([ 1.2602, -0.3145, -2.6184, -3.0264], requires_grad=True)
tensor([ 1.2588, -0.3167, -2.6187, -3.0267], requires_grad=True)
tensor([ 1.2538, -0.3265, -2.6189, -3.0274], requires_grad=True)
tensor([ 1.2515, -0.3304, -2.6197, -3.0284], requires_grad=True)
tensor([ 1.2458, -0.3403, -2.6201, -3.0289], requires_grad=True)
tensor([ 1.2450, -0.3399, -2.6205, -3.0294], requires_grad=True)
tensor([ 1.2460, -0.3364, -2.6206, -3.0298], requires_grad=True)
tensor([ 1.2479, -0.3337, -2.6210, -3.0304], requires_grad=True)
tensor([ 1.2506, -0.3286, -2.6211, -3.0307], requires_grad=True)
tensor([ 1.2574, -0.3161, -2.6217, -3.0317], requires_grad=True)
tensor([ 1.2537, -0.3224, -2.6219, -3.0321], requires_grad=True)
tensor([ 1.2489, -0.3312, -2.6223, -3.0326], requires_grad=True)
tensor([ 1.2460, -0.3377, -2.6223, -3.0330], requires_grad=True)
tensor([ 1.2445, -0.3400, -2.6226, -3.0334], requires_grad=True)
tensor([ 1.2481, -0.3340,

tensor([ 1.2551, -0.3207, -2.6574, -3.0823], requires_grad=True)
tensor([ 1.2568, -0.3181, -2.6577, -3.0829], requires_grad=True)
tensor([ 1.2563, -0.3184, -2.6579, -3.0833], requires_grad=True)
tensor([ 1.2519, -0.3267, -2.6584, -3.0838], requires_grad=True)
tensor([ 1.2553, -0.3204, -2.6586, -3.0841], requires_grad=True)
tensor([ 1.2529, -0.3248, -2.6590, -3.0844], requires_grad=True)
tensor([ 1.2511, -0.3274, -2.6593, -3.0849], requires_grad=True)
tensor([ 1.2533, -0.3234, -2.6598, -3.0855], requires_grad=True)
tensor([ 1.2505, -0.3287, -2.6601, -3.0858], requires_grad=True)
tensor([ 1.2533, -0.3245, -2.6606, -3.0862], requires_grad=True)
tensor([ 1.2526, -0.3245, -2.6610, -3.0866], requires_grad=True)
tensor([ 1.2481, -0.3334, -2.6613, -3.0870], requires_grad=True)
tensor([ 1.2501, -0.3282, -2.6617, -3.0876], requires_grad=True)
tensor([ 1.2473, -0.3336, -2.6619, -3.0879], requires_grad=True)
tensor([ 1.2526, -0.3235, -2.6620, -3.0883], requires_grad=True)
tensor([ 1.2515, -0.3247,

tensor([ 1.2496, -0.3291, -2.6927, -3.1293], requires_grad=True)
tensor([ 1.2510, -0.3269, -2.6929, -3.1299], requires_grad=True)
tensor([ 1.2510, -0.3272, -2.6930, -3.1300], requires_grad=True)
tensor([ 1.2564, -0.3177, -2.6933, -3.1306], requires_grad=True)
tensor([ 1.2535, -0.3232, -2.6935, -3.1308], requires_grad=True)
tensor([ 1.2533, -0.3231, -2.6940, -3.1313], requires_grad=True)
tensor([ 1.2545, -0.3219, -2.6942, -3.1315], requires_grad=True)
tensor([ 1.2548, -0.3205, -2.6943, -3.1317], requires_grad=True)
tensor([ 1.2540, -0.3206, -2.6945, -3.1318], requires_grad=True)
tensor([ 1.2508, -0.3251, -2.6946, -3.1321], requires_grad=True)
tensor([ 1.2503, -0.3261, -2.6949, -3.1325], requires_grad=True)
tensor([ 1.2522, -0.3234, -2.6951, -3.1328], requires_grad=True)
tensor([ 1.2513, -0.3248, -2.6953, -3.1332], requires_grad=True)
tensor([ 1.2521, -0.3223, -2.6956, -3.1335], requires_grad=True)
tensor([ 1.2508, -0.3242, -2.6960, -3.1341], requires_grad=True)
tensor([ 1.2521, -0.3218,

tensor([ 1.2539, -0.3228, -2.7229, -3.1731], requires_grad=True)
tensor([ 1.2508, -0.3277, -2.7232, -3.1734], requires_grad=True)
tensor([ 1.2476, -0.3330, -2.7233, -3.1736], requires_grad=True)
tensor([ 1.2529, -0.3236, -2.7236, -3.1738], requires_grad=True)
tensor([ 1.2542, -0.3216, -2.7238, -3.1742], requires_grad=True)
tensor([ 1.2559, -0.3188, -2.7239, -3.1743], requires_grad=True)
tensor([ 1.2536, -0.3236, -2.7241, -3.1745], requires_grad=True)
tensor([ 1.2554, -0.3215, -2.7242, -3.1747], requires_grad=True)
tensor([ 1.2537, -0.3249, -2.7244, -3.1751], requires_grad=True)
tensor([ 1.2535, -0.3253, -2.7245, -3.1754], requires_grad=True)
tensor([ 1.2542, -0.3234, -2.7248, -3.1757], requires_grad=True)
tensor([ 1.2496, -0.3316, -2.7250, -3.1761], requires_grad=True)
tensor([ 1.2530, -0.3259, -2.7252, -3.1763], requires_grad=True)
tensor([ 1.2507, -0.3295, -2.7254, -3.1767], requires_grad=True)
tensor([ 1.2474, -0.3352, -2.7257, -3.1770], requires_grad=True)
tensor([ 1.2460, -0.3384,

tensor([ 1.2462, -0.3338, -2.7533, -3.2144], requires_grad=True)
tensor([ 1.2471, -0.3321, -2.7535, -3.2147], requires_grad=True)
tensor([ 1.2460, -0.3342, -2.7538, -3.2149], requires_grad=True)
tensor([ 1.2448, -0.3360, -2.7539, -3.2151], requires_grad=True)
tensor([ 1.2459, -0.3330, -2.7541, -3.2154], requires_grad=True)
tensor([ 1.2474, -0.3305, -2.7543, -3.2157], requires_grad=True)
tensor([ 1.2470, -0.3299, -2.7544, -3.2158], requires_grad=True)
tensor([ 1.2496, -0.3263, -2.7545, -3.2159], requires_grad=True)
tensor([ 1.2502, -0.3243, -2.7545, -3.2161], requires_grad=True)
tensor([ 1.2525, -0.3206, -2.7548, -3.2163], requires_grad=True)
tensor([ 1.2526, -0.3206, -2.7549, -3.2165], requires_grad=True)
tensor([ 1.2509, -0.3237, -2.7551, -3.2168], requires_grad=True)
tensor([ 1.2551, -0.3171, -2.7555, -3.2170], requires_grad=True)
tensor([ 1.2560, -0.3161, -2.7557, -3.2172], requires_grad=True)
tensor([ 1.2555, -0.3171, -2.7559, -3.2176], requires_grad=True)
tensor([ 1.2515, -0.3231,

tensor([ 1.2560, -0.3245, -2.7806, -3.2487], requires_grad=True)
tensor([ 1.2588, -0.3206, -2.7809, -3.2490], requires_grad=True)
tensor([ 1.2588, -0.3209, -2.7812, -3.2491], requires_grad=True)
tensor([ 1.2564, -0.3249, -2.7815, -3.2495], requires_grad=True)
tensor([ 1.2545, -0.3281, -2.7816, -3.2497], requires_grad=True)
tensor([ 1.2485, -0.3383, -2.7819, -3.2501], requires_grad=True)
tensor([ 1.2527, -0.3305, -2.7820, -3.2504], requires_grad=True)
tensor([ 1.2514, -0.3322, -2.7824, -3.2510], requires_grad=True)
tensor([ 1.2505, -0.3331, -2.7825, -3.2511], requires_grad=True)
tensor([ 1.2527, -0.3285, -2.7828, -3.2514], requires_grad=True)
tensor([ 1.2529, -0.3280, -2.7830, -3.2515], requires_grad=True)
tensor([ 1.2530, -0.3270, -2.7833, -3.2518], requires_grad=True)
tensor([ 1.2526, -0.3281, -2.7833, -3.2520], requires_grad=True)
tensor([ 1.2517, -0.3296, -2.7834, -3.2523], requires_grad=True)
tensor([ 1.2557, -0.3218, -2.7836, -3.2525], requires_grad=True)
tensor([ 1.2572, -0.3195,

tensor([ 1.2562, -0.3195, -2.8051, -3.2811], requires_grad=True)
tensor([ 1.2541, -0.3229, -2.8053, -3.2812], requires_grad=True)
tensor([ 1.2555, -0.3205, -2.8054, -3.2815], requires_grad=True)
tensor([ 1.2556, -0.3204, -2.8056, -3.2817], requires_grad=True)
tensor([ 1.2551, -0.3219, -2.8057, -3.2818], requires_grad=True)
tensor([ 1.2543, -0.3229, -2.8058, -3.2821], requires_grad=True)
tensor([ 1.2555, -0.3212, -2.8060, -3.2824], requires_grad=True)
tensor([ 1.2564, -0.3196, -2.8062, -3.2827], requires_grad=True)
tensor([ 1.2537, -0.3238, -2.8064, -3.2829], requires_grad=True)
tensor([ 1.2544, -0.3223, -2.8065, -3.2830], requires_grad=True)
tensor([ 1.2525, -0.3248, -2.8067, -3.2832], requires_grad=True)
tensor([ 1.2517, -0.3266, -2.8069, -3.2834], requires_grad=True)
tensor([ 1.2506, -0.3284, -2.8070, -3.2837], requires_grad=True)
tensor([ 1.2446, -0.3389, -2.8073, -3.2840], requires_grad=True)
tensor([ 1.2492, -0.3295, -2.8073, -3.2844], requires_grad=True)
tensor([ 1.2483, -0.3305,

tensor([ 1.2533, -0.3235, -2.8291, -3.3109], requires_grad=True)
tensor([ 1.2522, -0.3244, -2.8295, -3.3114], requires_grad=True)
tensor([ 1.2491, -0.3301, -2.8297, -3.3116], requires_grad=True)
tensor([ 1.2503, -0.3281, -2.8298, -3.3118], requires_grad=True)
tensor([ 1.2507, -0.3272, -2.8300, -3.3119], requires_grad=True)
tensor([ 1.2526, -0.3247, -2.8303, -3.3122], requires_grad=True)
tensor([ 1.2514, -0.3276, -2.8304, -3.3124], requires_grad=True)
tensor([ 1.2510, -0.3281, -2.8306, -3.3126], requires_grad=True)
tensor([ 1.2518, -0.3266, -2.8308, -3.3127], requires_grad=True)
tensor([ 1.2531, -0.3244, -2.8308, -3.3129], requires_grad=True)
tensor([ 1.2570, -0.3176, -2.8310, -3.3131], requires_grad=True)
tensor([ 1.2552, -0.3214, -2.8311, -3.3131], requires_grad=True)
tensor([ 1.2568, -0.3189, -2.8314, -3.3134], requires_grad=True)
tensor([ 1.2526, -0.3276, -2.8314, -3.3137], requires_grad=True)
tensor([ 1.2516, -0.3289, -2.8316, -3.3139], requires_grad=True)
tensor([ 1.2514, -0.3287,

tensor([ 1.2494, -0.3343, -2.8508, -3.3391], requires_grad=True)
tensor([ 1.2520, -0.3292, -2.8509, -3.3392], requires_grad=True)
tensor([ 1.2563, -0.3220, -2.8510, -3.3393], requires_grad=True)
tensor([ 1.2545, -0.3255, -2.8512, -3.3396], requires_grad=True)
tensor([ 1.2544, -0.3258, -2.8514, -3.3398], requires_grad=True)
tensor([ 1.2538, -0.3267, -2.8515, -3.3400], requires_grad=True)
tensor([ 1.2558, -0.3227, -2.8518, -3.3402], requires_grad=True)
tensor([ 1.2555, -0.3231, -2.8520, -3.3405], requires_grad=True)
tensor([ 1.2553, -0.3230, -2.8521, -3.3406], requires_grad=True)
tensor([ 1.2564, -0.3220, -2.8522, -3.3408], requires_grad=True)
tensor([ 1.2527, -0.3288, -2.8523, -3.3410], requires_grad=True)
tensor([ 1.2508, -0.3319, -2.8526, -3.3413], requires_grad=True)
tensor([ 1.2505, -0.3328, -2.8527, -3.3414], requires_grad=True)
tensor([ 1.2510, -0.3320, -2.8529, -3.3415], requires_grad=True)
tensor([ 1.2562, -0.3226, -2.8532, -3.3419], requires_grad=True)
tensor([ 1.2569, -0.3204,

tensor([ 1.2550, -0.3241, -2.8721, -3.3658], requires_grad=True)
tensor([ 1.2575, -0.3201, -2.8724, -3.3662], requires_grad=True)
tensor([ 1.2593, -0.3176, -2.8725, -3.3664], requires_grad=True)
tensor([ 1.2605, -0.3156, -2.8727, -3.3666], requires_grad=True)
tensor([ 1.2598, -0.3177, -2.8728, -3.3667], requires_grad=True)
tensor([ 1.2584, -0.3196, -2.8729, -3.3669], requires_grad=True)
tensor([ 1.2596, -0.3174, -2.8732, -3.3672], requires_grad=True)
tensor([ 1.2593, -0.3179, -2.8734, -3.3673], requires_grad=True)
tensor([ 1.2569, -0.3221, -2.8735, -3.3675], requires_grad=True)
tensor([ 1.2533, -0.3282, -2.8737, -3.3677], requires_grad=True)
tensor([ 1.2555, -0.3243, -2.8739, -3.3679], requires_grad=True)
tensor([ 1.2532, -0.3277, -2.8740, -3.3680], requires_grad=True)
tensor([ 1.2515, -0.3301, -2.8741, -3.3681], requires_grad=True)
tensor([ 1.2550, -0.3235, -2.8741, -3.3684], requires_grad=True)
tensor([ 1.2572, -0.3190, -2.8743, -3.3687], requires_grad=True)
tensor([ 1.2530, -0.3269,

tensor([ 1.2529, -0.3244, -2.8910, -3.3901], requires_grad=True)
tensor([ 1.2500, -0.3293, -2.8912, -3.3903], requires_grad=True)
tensor([ 1.2491, -0.3304, -2.8913, -3.3905], requires_grad=True)
tensor([ 1.2510, -0.3280, -2.8915, -3.3906], requires_grad=True)
tensor([ 1.2529, -0.3246, -2.8916, -3.3908], requires_grad=True)
tensor([ 1.2526, -0.3243, -2.8917, -3.3909], requires_grad=True)
tensor([ 1.2533, -0.3228, -2.8918, -3.3911], requires_grad=True)
tensor([ 1.2495, -0.3286, -2.8920, -3.3913], requires_grad=True)
tensor([ 1.2521, -0.3241, -2.8922, -3.3914], requires_grad=True)
tensor([ 1.2558, -0.3184, -2.8924, -3.3916], requires_grad=True)
tensor([ 1.2538, -0.3228, -2.8925, -3.3918], requires_grad=True)
tensor([ 1.2543, -0.3232, -2.8926, -3.3919], requires_grad=True)
tensor([ 1.2560, -0.3198, -2.8927, -3.3922], requires_grad=True)
tensor([ 1.2550, -0.3218, -2.8929, -3.3924], requires_grad=True)
tensor([ 1.2536, -0.3245, -2.8931, -3.3926], requires_grad=True)
tensor([ 1.2530, -0.3256,

tensor([ 1.2544, -0.3246, -2.9106, -3.4142], requires_grad=True)
tensor([ 1.2530, -0.3268, -2.9106, -3.4141], requires_grad=True)
tensor([ 1.2501, -0.3316, -2.9106, -3.4143], requires_grad=True)
tensor([ 1.2531, -0.3268, -2.9108, -3.4144], requires_grad=True)
tensor([ 1.2522, -0.3278, -2.9109, -3.4146], requires_grad=True)
tensor([ 1.2538, -0.3253, -2.9111, -3.4148], requires_grad=True)
tensor([ 1.2520, -0.3294, -2.9112, -3.4149], requires_grad=True)
tensor([ 1.2500, -0.3328, -2.9113, -3.4151], requires_grad=True)
tensor([ 1.2529, -0.3277, -2.9115, -3.4152], requires_grad=True)
tensor([ 1.2551, -0.3233, -2.9116, -3.4153], requires_grad=True)
tensor([ 1.2573, -0.3199, -2.9117, -3.4155], requires_grad=True)
tensor([ 1.2539, -0.3268, -2.9120, -3.4158], requires_grad=True)
tensor([ 1.2517, -0.3301, -2.9122, -3.4160], requires_grad=True)
tensor([ 1.2549, -0.3240, -2.9123, -3.4162], requires_grad=True)
tensor([ 1.2553, -0.3234, -2.9125, -3.4164], requires_grad=True)
tensor([ 1.2576, -0.3187,

tensor([ 1.2558, -0.3188, -2.9283, -3.4356], requires_grad=True)
tensor([ 1.2539, -0.3225, -2.9284, -3.4357], requires_grad=True)
tensor([ 1.2535, -0.3226, -2.9284, -3.4358], requires_grad=True)
tensor([ 1.2502, -0.3282, -2.9286, -3.4360], requires_grad=True)
tensor([ 1.2514, -0.3250, -2.9288, -3.4362], requires_grad=True)
tensor([ 1.2521, -0.3247, -2.9290, -3.4364], requires_grad=True)
tensor([ 1.2515, -0.3253, -2.9291, -3.4365], requires_grad=True)
tensor([ 1.2541, -0.3222, -2.9292, -3.4366], requires_grad=True)
tensor([ 1.2569, -0.3184, -2.9292, -3.4367], requires_grad=True)
tensor([ 1.2561, -0.3203, -2.9293, -3.4368], requires_grad=True)
tensor([ 1.2569, -0.3190, -2.9294, -3.4370], requires_grad=True)
tensor([ 1.2546, -0.3231, -2.9295, -3.4371], requires_grad=True)
tensor([ 1.2541, -0.3238, -2.9296, -3.4373], requires_grad=True)
tensor([ 1.2541, -0.3236, -2.9297, -3.4373], requires_grad=True)
tensor([ 1.2530, -0.3260, -2.9299, -3.4375], requires_grad=True)
tensor([ 1.2524, -0.3271,

tensor([ 1.2535, -0.3248, -2.9443, -3.4548], requires_grad=True)
tensor([ 1.2505, -0.3297, -2.9445, -3.4550], requires_grad=True)
tensor([ 1.2519, -0.3268, -2.9447, -3.4551], requires_grad=True)
tensor([ 1.2521, -0.3261, -2.9448, -3.4553], requires_grad=True)
tensor([ 1.2539, -0.3238, -2.9450, -3.4555], requires_grad=True)
tensor([ 1.2548, -0.3222, -2.9451, -3.4556], requires_grad=True)
tensor([ 1.2519, -0.3283, -2.9453, -3.4558], requires_grad=True)
tensor([ 1.2537, -0.3243, -2.9453, -3.4559], requires_grad=True)
tensor([ 1.2540, -0.3236, -2.9455, -3.4561], requires_grad=True)
tensor([ 1.2530, -0.3252, -2.9454, -3.4561], requires_grad=True)
tensor([ 1.2524, -0.3268, -2.9455, -3.4562], requires_grad=True)
tensor([ 1.2536, -0.3251, -2.9457, -3.4564], requires_grad=True)
tensor([ 1.2551, -0.3225, -2.9456, -3.4564], requires_grad=True)
tensor([ 1.2547, -0.3229, -2.9457, -3.4565], requires_grad=True)
tensor([ 1.2551, -0.3222, -2.9458, -3.4566], requires_grad=True)
tensor([ 1.2520, -0.3273,

tensor([ 1.2509, -0.3285, -2.9587, -3.4720], requires_grad=True)
tensor([ 1.2510, -0.3283, -2.9588, -3.4722], requires_grad=True)
tensor([ 1.2483, -0.3320, -2.9589, -3.4723], requires_grad=True)
tensor([ 1.2509, -0.3276, -2.9590, -3.4724], requires_grad=True)
tensor([ 1.2494, -0.3299, -2.9591, -3.4725], requires_grad=True)
tensor([ 1.2486, -0.3308, -2.9592, -3.4727], requires_grad=True)
tensor([ 1.2479, -0.3317, -2.9593, -3.4728], requires_grad=True)
tensor([ 1.2493, -0.3287, -2.9594, -3.4729], requires_grad=True)
tensor([ 1.2524, -0.3227, -2.9595, -3.4731], requires_grad=True)
tensor([ 1.2516, -0.3236, -2.9595, -3.4732], requires_grad=True)
tensor([ 1.2530, -0.3219, -2.9596, -3.4733], requires_grad=True)
tensor([ 1.2573, -0.3146, -2.9598, -3.4734], requires_grad=True)
tensor([ 1.2551, -0.3189, -2.9599, -3.4736], requires_grad=True)
tensor([ 1.2510, -0.3264, -2.9601, -3.4738], requires_grad=True)
tensor([ 1.2521, -0.3248, -2.9602, -3.4740], requires_grad=True)
tensor([ 1.2517, -0.3261,

tensor([ 1.2530, -0.3283, -2.9722, -3.4885], requires_grad=True)
tensor([ 1.2523, -0.3291, -2.9725, -3.4887], requires_grad=True)
tensor([ 1.2556, -0.3243, -2.9726, -3.4888], requires_grad=True)
tensor([ 1.2558, -0.3239, -2.9726, -3.4888], requires_grad=True)
tensor([ 1.2518, -0.3308, -2.9727, -3.4890], requires_grad=True)
tensor([ 1.2512, -0.3318, -2.9728, -3.4891], requires_grad=True)
tensor([ 1.2505, -0.3328, -2.9729, -3.4893], requires_grad=True)
tensor([ 1.2541, -0.3259, -2.9730, -3.4894], requires_grad=True)
tensor([ 1.2528, -0.3271, -2.9730, -3.4895], requires_grad=True)
tensor([ 1.2550, -0.3231, -2.9731, -3.4896], requires_grad=True)
tensor([ 1.2564, -0.3202, -2.9732, -3.4897], requires_grad=True)
tensor([ 1.2547, -0.3231, -2.9733, -3.4898], requires_grad=True)
tensor([ 1.2538, -0.3255, -2.9732, -3.4898], requires_grad=True)
tensor([ 1.2519, -0.3295, -2.9734, -3.4899], requires_grad=True)
tensor([ 1.2539, -0.3264, -2.9736, -3.4901], requires_grad=True)
tensor([ 1.2545, -0.3254,

tensor([ 1.2543, -0.3256, -2.9860, -3.5048], requires_grad=True)
tensor([ 1.2532, -0.3275, -2.9861, -3.5050], requires_grad=True)
tensor([ 1.2555, -0.3233, -2.9862, -3.5050], requires_grad=True)
tensor([ 1.2570, -0.3207, -2.9862, -3.5051], requires_grad=True)
tensor([ 1.2562, -0.3214, -2.9863, -3.5052], requires_grad=True)
tensor([ 1.2549, -0.3228, -2.9864, -3.5053], requires_grad=True)
tensor([ 1.2545, -0.3232, -2.9865, -3.5054], requires_grad=True)
tensor([ 1.2516, -0.3276, -2.9867, -3.5055], requires_grad=True)
tensor([ 1.2512, -0.3283, -2.9867, -3.5056], requires_grad=True)
tensor([ 1.2515, -0.3277, -2.9869, -3.5058], requires_grad=True)
tensor([ 1.2517, -0.3269, -2.9870, -3.5059], requires_grad=True)
tensor([ 1.2518, -0.3260, -2.9870, -3.5060], requires_grad=True)
tensor([ 1.2543, -0.3219, -2.9872, -3.5062], requires_grad=True)
tensor([ 1.2544, -0.3217, -2.9873, -3.5063], requires_grad=True)
tensor([ 1.2542, -0.3218, -2.9873, -3.5063], requires_grad=True)
tensor([ 1.2528, -0.3251,

tensor([ 1.2512, -0.3288, -2.9999, -3.5208], requires_grad=True)
tensor([ 1.2498, -0.3308, -3.0000, -3.5209], requires_grad=True)
tensor([ 1.2504, -0.3298, -3.0000, -3.5210], requires_grad=True)
tensor([ 1.2525, -0.3255, -3.0001, -3.5211], requires_grad=True)
tensor([ 1.2534, -0.3238, -3.0003, -3.5213], requires_grad=True)
tensor([ 1.2513, -0.3269, -3.0005, -3.5215], requires_grad=True)
tensor([ 1.2516, -0.3269, -3.0005, -3.5216], requires_grad=True)
tensor([ 1.2498, -0.3305, -3.0006, -3.5216], requires_grad=True)
tensor([ 1.2504, -0.3302, -3.0007, -3.5217], requires_grad=True)
tensor([ 1.2506, -0.3297, -3.0007, -3.5218], requires_grad=True)
tensor([ 1.2507, -0.3291, -3.0008, -3.5219], requires_grad=True)
tensor([ 1.2490, -0.3325, -3.0008, -3.5219], requires_grad=True)
tensor([ 1.2501, -0.3310, -3.0008, -3.5219], requires_grad=True)
tensor([ 1.2508, -0.3296, -3.0009, -3.5219], requires_grad=True)
tensor([ 1.2502, -0.3308, -3.0010, -3.5220], requires_grad=True)
tensor([ 1.2531, -0.3253,

tensor([ 1.2564, -0.3223, -3.0116, -3.5344], requires_grad=True)
tensor([ 1.2573, -0.3202, -3.0117, -3.5346], requires_grad=True)
tensor([ 1.2581, -0.3194, -3.0117, -3.5346], requires_grad=True)
tensor([ 1.2585, -0.3188, -3.0118, -3.5347], requires_grad=True)
tensor([ 1.2574, -0.3221, -3.0118, -3.5348], requires_grad=True)
tensor([ 1.2571, -0.3230, -3.0119, -3.5349], requires_grad=True)
tensor([ 1.2557, -0.3254, -3.0120, -3.5351], requires_grad=True)
tensor([ 1.2537, -0.3289, -3.0121, -3.5351], requires_grad=True)
tensor([ 1.2546, -0.3279, -3.0122, -3.5352], requires_grad=True)
tensor([ 1.2545, -0.3273, -3.0123, -3.5353], requires_grad=True)
tensor([ 1.2524, -0.3306, -3.0124, -3.5355], requires_grad=True)
tensor([ 1.2528, -0.3291, -3.0124, -3.5355], requires_grad=True)
tensor([ 1.2536, -0.3271, -3.0124, -3.5356], requires_grad=True)
tensor([ 1.2556, -0.3233, -3.0125, -3.5357], requires_grad=True)
tensor([ 1.2562, -0.3223, -3.0125, -3.5357], requires_grad=True)
tensor([ 1.2579, -0.3194,

tensor([ 1.2571, -0.3258, -3.0235, -3.5484], requires_grad=True)
tensor([ 1.2577, -0.3251, -3.0236, -3.5485], requires_grad=True)
tensor([ 1.2575, -0.3247, -3.0236, -3.5486], requires_grad=True)
tensor([ 1.2576, -0.3238, -3.0237, -3.5487], requires_grad=True)
tensor([ 1.2576, -0.3238, -3.0238, -3.5488], requires_grad=True)
tensor([ 1.2555, -0.3283, -3.0238, -3.5488], requires_grad=True)
tensor([ 1.2558, -0.3278, -3.0239, -3.5489], requires_grad=True)
tensor([ 1.2556, -0.3278, -3.0240, -3.5490], requires_grad=True)
tensor([ 1.2546, -0.3289, -3.0240, -3.5490], requires_grad=True)
tensor([ 1.2562, -0.3258, -3.0241, -3.5492], requires_grad=True)
tensor([ 1.2563, -0.3253, -3.0242, -3.5493], requires_grad=True)
tensor([ 1.2538, -0.3291, -3.0243, -3.5494], requires_grad=True)
tensor([ 1.2534, -0.3293, -3.0244, -3.5496], requires_grad=True)
tensor([ 1.2523, -0.3310, -3.0245, -3.5496], requires_grad=True)
tensor([ 1.2533, -0.3294, -3.0245, -3.5497], requires_grad=True)
tensor([ 1.2562, -0.3242,

tensor([ 1.2520, -0.3281, -3.0337, -3.5605], requires_grad=True)
tensor([ 1.2549, -0.3226, -3.0338, -3.5606], requires_grad=True)
tensor([ 1.2557, -0.3218, -3.0339, -3.5607], requires_grad=True)
tensor([ 1.2580, -0.3179, -3.0340, -3.5608], requires_grad=True)
tensor([ 1.2597, -0.3158, -3.0340, -3.5609], requires_grad=True)
tensor([ 1.2592, -0.3156, -3.0341, -3.5609], requires_grad=True)
tensor([ 1.2604, -0.3134, -3.0342, -3.5609], requires_grad=True)
tensor([ 1.2611, -0.3127, -3.0343, -3.5611], requires_grad=True)
tensor([ 1.2599, -0.3148, -3.0343, -3.5611], requires_grad=True)
tensor([ 1.2559, -0.3220, -3.0344, -3.5612], requires_grad=True)
tensor([ 1.2543, -0.3247, -3.0345, -3.5614], requires_grad=True)
tensor([ 1.2539, -0.3254, -3.0346, -3.5614], requires_grad=True)
tensor([ 1.2540, -0.3255, -3.0347, -3.5615], requires_grad=True)
tensor([ 1.2575, -0.3195, -3.0348, -3.5616], requires_grad=True)
tensor([ 1.2591, -0.3169, -3.0348, -3.5616], requires_grad=True)
tensor([ 1.2563, -0.3225,

tensor([ 1.2551, -0.3246, -3.0431, -3.5713], requires_grad=True)
tensor([ 1.2521, -0.3293, -3.0432, -3.5714], requires_grad=True)
tensor([ 1.2505, -0.3324, -3.0433, -3.5715], requires_grad=True)
tensor([ 1.2496, -0.3332, -3.0434, -3.5716], requires_grad=True)
tensor([ 1.2503, -0.3319, -3.0434, -3.5717], requires_grad=True)
tensor([ 1.2526, -0.3275, -3.0435, -3.5718], requires_grad=True)
tensor([ 1.2528, -0.3266, -3.0435, -3.5718], requires_grad=True)
tensor([ 1.2539, -0.3251, -3.0436, -3.5719], requires_grad=True)
tensor([ 1.2548, -0.3235, -3.0437, -3.5720], requires_grad=True)
tensor([ 1.2544, -0.3239, -3.0437, -3.5720], requires_grad=True)
tensor([ 1.2549, -0.3239, -3.0437, -3.5720], requires_grad=True)
tensor([ 1.2554, -0.3232, -3.0438, -3.5722], requires_grad=True)
tensor([ 1.2551, -0.3235, -3.0439, -3.5722], requires_grad=True)
tensor([ 1.2519, -0.3293, -3.0440, -3.5724], requires_grad=True)
tensor([ 1.2527, -0.3272, -3.0441, -3.5725], requires_grad=True)
tensor([ 1.2512, -0.3299,

tensor([ 1.2573, -0.3192, -3.0540, -3.5836], requires_grad=True)
tensor([ 1.2543, -0.3247, -3.0540, -3.5836], requires_grad=True)
tensor([ 1.2519, -0.3289, -3.0541, -3.5838], requires_grad=True)
tensor([ 1.2548, -0.3233, -3.0541, -3.5838], requires_grad=True)
tensor([ 1.2550, -0.3236, -3.0541, -3.5839], requires_grad=True)
tensor([ 1.2533, -0.3269, -3.0542, -3.5840], requires_grad=True)
tensor([ 1.2522, -0.3288, -3.0543, -3.5841], requires_grad=True)
tensor([ 1.2538, -0.3258, -3.0544, -3.5841], requires_grad=True)
tensor([ 1.2554, -0.3228, -3.0545, -3.5843], requires_grad=True)
tensor([ 1.2586, -0.3174, -3.0546, -3.5844], requires_grad=True)
tensor([ 1.2555, -0.3233, -3.0547, -3.5845], requires_grad=True)
tensor([ 1.2542, -0.3260, -3.0548, -3.5846], requires_grad=True)
tensor([ 1.2557, -0.3236, -3.0548, -3.5846], requires_grad=True)
tensor([ 1.2561, -0.3229, -3.0549, -3.5847], requires_grad=True)
tensor([ 1.2530, -0.3284, -3.0550, -3.5848], requires_grad=True)
tensor([ 1.2532, -0.3283,

tensor([ 1.2531, -0.3249, -3.0631, -3.5943], requires_grad=True)
tensor([ 1.2518, -0.3267, -3.0631, -3.5944], requires_grad=True)
tensor([ 1.2494, -0.3309, -3.0632, -3.5945], requires_grad=True)
tensor([ 1.2517, -0.3264, -3.0632, -3.5945], requires_grad=True)
tensor([ 1.2510, -0.3281, -3.0632, -3.5945], requires_grad=True)
tensor([ 1.2514, -0.3267, -3.0633, -3.5946], requires_grad=True)
tensor([ 1.2532, -0.3232, -3.0633, -3.5946], requires_grad=True)
tensor([ 1.2540, -0.3218, -3.0633, -3.5947], requires_grad=True)
tensor([ 1.2547, -0.3206, -3.0634, -3.5948], requires_grad=True)
tensor([ 1.2540, -0.3218, -3.0635, -3.5949], requires_grad=True)
tensor([ 1.2542, -0.3225, -3.0636, -3.5951], requires_grad=True)
tensor([ 1.2523, -0.3262, -3.0637, -3.5951], requires_grad=True)
tensor([ 1.2501, -0.3297, -3.0637, -3.5952], requires_grad=True)
tensor([ 1.2500, -0.3291, -3.0638, -3.5953], requires_grad=True)
tensor([ 1.2503, -0.3285, -3.0637, -3.5953], requires_grad=True)
tensor([ 1.2484, -0.3310,

tensor([ 1.2510, -0.3244, -3.0726, -3.6053], requires_grad=True)
tensor([ 1.2519, -0.3227, -3.0726, -3.6054], requires_grad=True)
tensor([ 1.2522, -0.3223, -3.0727, -3.6055], requires_grad=True)
tensor([ 1.2519, -0.3229, -3.0728, -3.6055], requires_grad=True)
tensor([ 1.2523, -0.3219, -3.0728, -3.6055], requires_grad=True)
tensor([ 1.2512, -0.3238, -3.0729, -3.6057], requires_grad=True)
tensor([ 1.2505, -0.3255, -3.0730, -3.6058], requires_grad=True)
tensor([ 1.2510, -0.3247, -3.0730, -3.6058], requires_grad=True)
tensor([ 1.2513, -0.3237, -3.0732, -3.6060], requires_grad=True)
tensor([ 1.2520, -0.3231, -3.0733, -3.6061], requires_grad=True)
tensor([ 1.2552, -0.3174, -3.0734, -3.6062], requires_grad=True)
tensor([ 1.2588, -0.3111, -3.0736, -3.6063], requires_grad=True)
tensor([ 1.2571, -0.3143, -3.0736, -3.6064], requires_grad=True)
tensor([ 1.2567, -0.3149, -3.0736, -3.6065], requires_grad=True)
tensor([ 1.2562, -0.3162, -3.0737, -3.6065], requires_grad=True)
tensor([ 1.2547, -0.3195,

tensor([ 1.2543, -0.3247, -3.0815, -3.6161], requires_grad=True)
tensor([ 1.2547, -0.3243, -3.0815, -3.6161], requires_grad=True)
tensor([ 1.2526, -0.3283, -3.0816, -3.6162], requires_grad=True)
tensor([ 1.2541, -0.3255, -3.0816, -3.6162], requires_grad=True)
tensor([ 1.2551, -0.3237, -3.0817, -3.6163], requires_grad=True)
tensor([ 1.2545, -0.3246, -3.0818, -3.6164], requires_grad=True)
tensor([ 1.2547, -0.3241, -3.0819, -3.6165], requires_grad=True)
tensor([ 1.2527, -0.3274, -3.0820, -3.6166], requires_grad=True)
tensor([ 1.2538, -0.3260, -3.0821, -3.6167], requires_grad=True)
tensor([ 1.2556, -0.3231, -3.0821, -3.6167], requires_grad=True)
tensor([ 1.2568, -0.3214, -3.0821, -3.6168], requires_grad=True)
tensor([ 1.2576, -0.3200, -3.0823, -3.6169], requires_grad=True)
tensor([ 1.2572, -0.3213, -3.0824, -3.6170], requires_grad=True)
tensor([ 1.2564, -0.3230, -3.0824, -3.6171], requires_grad=True)
tensor([ 1.2575, -0.3217, -3.0825, -3.6171], requires_grad=True)
tensor([ 1.2576, -0.3217,

tensor([ 1.2538, -0.3266, -3.0892, -3.6249], requires_grad=True)
tensor([ 1.2536, -0.3270, -3.0893, -3.6250], requires_grad=True)
tensor([ 1.2555, -0.3244, -3.0894, -3.6252], requires_grad=True)
tensor([ 1.2526, -0.3296, -3.0894, -3.6252], requires_grad=True)
tensor([ 1.2527, -0.3294, -3.0895, -3.6253], requires_grad=True)
tensor([ 1.2522, -0.3301, -3.0895, -3.6254], requires_grad=True)
tensor([ 1.2516, -0.3313, -3.0896, -3.6254], requires_grad=True)
tensor([ 1.2527, -0.3294, -3.0896, -3.6254], requires_grad=True)
tensor([ 1.2539, -0.3273, -3.0897, -3.6255], requires_grad=True)
tensor([ 1.2518, -0.3304, -3.0897, -3.6255], requires_grad=True)
tensor([ 1.2517, -0.3301, -3.0898, -3.6256], requires_grad=True)
tensor([ 1.2490, -0.3344, -3.0898, -3.6257], requires_grad=True)
tensor([ 1.2514, -0.3307, -3.0899, -3.6257], requires_grad=True)
tensor([ 1.2526, -0.3283, -3.0900, -3.6258], requires_grad=True)
tensor([ 1.2544, -0.3259, -3.0901, -3.6258], requires_grad=True)
tensor([ 1.2522, -0.3295,

tensor([ 1.2499, -0.3291, -3.0980, -3.6350], requires_grad=True)
tensor([ 1.2491, -0.3306, -3.0980, -3.6351], requires_grad=True)
tensor([ 1.2493, -0.3299, -3.0981, -3.6352], requires_grad=True)
tensor([ 1.2500, -0.3284, -3.0982, -3.6353], requires_grad=True)
tensor([ 1.2509, -0.3272, -3.0983, -3.6354], requires_grad=True)
tensor([ 1.2497, -0.3297, -3.0984, -3.6354], requires_grad=True)
tensor([ 1.2482, -0.3324, -3.0984, -3.6355], requires_grad=True)
tensor([ 1.2496, -0.3294, -3.0985, -3.6355], requires_grad=True)
tensor([ 1.2460, -0.3358, -3.0985, -3.6356], requires_grad=True)
tensor([ 1.2505, -0.3268, -3.0985, -3.6357], requires_grad=True)
tensor([ 1.2520, -0.3241, -3.0986, -3.6358], requires_grad=True)
tensor([ 1.2539, -0.3213, -3.0987, -3.6359], requires_grad=True)
tensor([ 1.2527, -0.3226, -3.0987, -3.6359], requires_grad=True)
tensor([ 1.2520, -0.3242, -3.0988, -3.6359], requires_grad=True)
tensor([ 1.2540, -0.3205, -3.0988, -3.6360], requires_grad=True)
tensor([ 1.2518, -0.3248,

tensor([ 1.2593, -0.3203, -3.1057, -3.6444], requires_grad=True)
tensor([ 1.2582, -0.3216, -3.1057, -3.6443], requires_grad=True)
tensor([ 1.2591, -0.3195, -3.1057, -3.6443], requires_grad=True)
tensor([ 1.2606, -0.3172, -3.1058, -3.6444], requires_grad=True)
tensor([ 1.2608, -0.3171, -3.1059, -3.6445], requires_grad=True)
tensor([ 1.2589, -0.3206, -3.1059, -3.6446], requires_grad=True)
tensor([ 1.2566, -0.3247, -3.1060, -3.6447], requires_grad=True)
tensor([ 1.2526, -0.3316, -3.1062, -3.6448], requires_grad=True)
tensor([ 1.2572, -0.3231, -3.1063, -3.6450], requires_grad=True)
tensor([ 1.2547, -0.3272, -3.1064, -3.6451], requires_grad=True)
tensor([ 1.2568, -0.3235, -3.1064, -3.6451], requires_grad=True)
tensor([ 1.2547, -0.3266, -3.1065, -3.6452], requires_grad=True)
tensor([ 1.2545, -0.3267, -3.1066, -3.6452], requires_grad=True)
tensor([ 1.2556, -0.3253, -3.1066, -3.6452], requires_grad=True)
tensor([ 1.2579, -0.3211, -3.1067, -3.6453], requires_grad=True)
tensor([ 1.2602, -0.3174,

tensor([ 1.2568, -0.3222, -3.1137, -3.6526], requires_grad=True)
tensor([ 1.2541, -0.3269, -3.1139, -3.6528], requires_grad=True)
tensor([ 1.2547, -0.3257, -3.1139, -3.6528], requires_grad=True)
tensor([ 1.2546, -0.3255, -3.1140, -3.6529], requires_grad=True)
tensor([ 1.2563, -0.3219, -3.1140, -3.6529], requires_grad=True)
tensor([ 1.2545, -0.3254, -3.1140, -3.6529], requires_grad=True)
tensor([ 1.2547, -0.3252, -3.1141, -3.6530], requires_grad=True)
tensor([ 1.2532, -0.3273, -3.1141, -3.6531], requires_grad=True)
tensor([ 1.2549, -0.3243, -3.1142, -3.6531], requires_grad=True)
tensor([ 1.2568, -0.3215, -3.1143, -3.6532], requires_grad=True)
tensor([ 1.2549, -0.3243, -3.1143, -3.6532], requires_grad=True)
tensor([ 1.2580, -0.3195, -3.1142, -3.6533], requires_grad=True)
tensor([ 1.2587, -0.3189, -3.1143, -3.6533], requires_grad=True)
tensor([ 1.2611, -0.3148, -3.1143, -3.6534], requires_grad=True)
tensor([ 1.2584, -0.3201, -3.1145, -3.6535], requires_grad=True)
tensor([ 1.2578, -0.3210,

tensor([ 1.2542, -0.3264, -3.1206, -3.6602], requires_grad=True)
tensor([ 1.2569, -0.3220, -3.1207, -3.6603], requires_grad=True)
tensor([ 1.2539, -0.3275, -3.1208, -3.6604], requires_grad=True)
tensor([ 1.2528, -0.3297, -3.1209, -3.6605], requires_grad=True)
tensor([ 1.2533, -0.3287, -3.1209, -3.6605], requires_grad=True)
tensor([ 1.2549, -0.3258, -3.1210, -3.6606], requires_grad=True)
tensor([ 1.2555, -0.3253, -3.1210, -3.6607], requires_grad=True)
tensor([ 1.2544, -0.3273, -3.1210, -3.6607], requires_grad=True)
tensor([ 1.2556, -0.3247, -3.1211, -3.6608], requires_grad=True)
tensor([ 1.2542, -0.3269, -3.1212, -3.6609], requires_grad=True)
tensor([ 1.2542, -0.3269, -3.1212, -3.6611], requires_grad=True)
tensor([ 1.2550, -0.3250, -3.1213, -3.6611], requires_grad=True)
tensor([ 1.2521, -0.3298, -3.1214, -3.6612], requires_grad=True)
tensor([ 1.2518, -0.3290, -3.1213, -3.6612], requires_grad=True)
tensor([ 1.2517, -0.3291, -3.1214, -3.6613], requires_grad=True)
tensor([ 1.2553, -0.3220,

tensor([ 1.2505, -0.3307, -3.1277, -3.6680], requires_grad=True)
tensor([ 1.2526, -0.3272, -3.1277, -3.6680], requires_grad=True)
tensor([ 1.2513, -0.3294, -3.1277, -3.6681], requires_grad=True)
tensor([ 1.2504, -0.3307, -3.1277, -3.6682], requires_grad=True)
tensor([ 1.2513, -0.3287, -3.1278, -3.6682], requires_grad=True)
tensor([ 1.2546, -0.3227, -3.1279, -3.6683], requires_grad=True)
tensor([ 1.2559, -0.3210, -3.1279, -3.6683], requires_grad=True)
tensor([ 1.2537, -0.3246, -3.1280, -3.6684], requires_grad=True)
tensor([ 1.2535, -0.3249, -3.1281, -3.6685], requires_grad=True)
tensor([ 1.2521, -0.3275, -3.1282, -3.6686], requires_grad=True)
tensor([ 1.2544, -0.3241, -3.1282, -3.6686], requires_grad=True)
tensor([ 1.2558, -0.3214, -3.1283, -3.6686], requires_grad=True)
tensor([ 1.2553, -0.3220, -3.1283, -3.6686], requires_grad=True)
tensor([ 1.2516, -0.3288, -3.1284, -3.6687], requires_grad=True)
tensor([ 1.2504, -0.3314, -3.1285, -3.6688], requires_grad=True)
tensor([ 1.2487, -0.3344,

tensor([ 1.2549, -0.3247, -3.1340, -3.6750], requires_grad=True)
tensor([ 1.2562, -0.3220, -3.1340, -3.6751], requires_grad=True)
tensor([ 1.2547, -0.3250, -3.1341, -3.6752], requires_grad=True)
tensor([ 1.2519, -0.3292, -3.1341, -3.6752], requires_grad=True)
tensor([ 1.2525, -0.3280, -3.1341, -3.6752], requires_grad=True)
tensor([ 1.2529, -0.3270, -3.1342, -3.6753], requires_grad=True)
tensor([ 1.2523, -0.3283, -3.1343, -3.6753], requires_grad=True)
tensor([ 1.2552, -0.3233, -3.1343, -3.6754], requires_grad=True)
tensor([ 1.2541, -0.3244, -3.1343, -3.6754], requires_grad=True)
tensor([ 1.2553, -0.3218, -3.1343, -3.6755], requires_grad=True)
tensor([ 1.2540, -0.3249, -3.1343, -3.6755], requires_grad=True)
tensor([ 1.2555, -0.3223, -3.1344, -3.6755], requires_grad=True)
tensor([ 1.2553, -0.3222, -3.1343, -3.6755], requires_grad=True)
tensor([ 1.2538, -0.3245, -3.1344, -3.6756], requires_grad=True)
tensor([ 1.2519, -0.3278, -3.1346, -3.6757], requires_grad=True)
tensor([ 1.2516, -0.3286,

tensor([ 1.2557, -0.3231, -3.1408, -3.6826], requires_grad=True)
tensor([ 1.2541, -0.3263, -3.1409, -3.6827], requires_grad=True)
tensor([ 1.2543, -0.3258, -3.1409, -3.6828], requires_grad=True)
tensor([ 1.2557, -0.3232, -3.1409, -3.6828], requires_grad=True)
tensor([ 1.2553, -0.3239, -3.1410, -3.6829], requires_grad=True)
tensor([ 1.2547, -0.3249, -3.1410, -3.6829], requires_grad=True)
tensor([ 1.2556, -0.3231, -3.1411, -3.6830], requires_grad=True)
tensor([ 1.2561, -0.3221, -3.1412, -3.6831], requires_grad=True)
tensor([ 1.2557, -0.3231, -3.1412, -3.6831], requires_grad=True)
tensor([ 1.2572, -0.3203, -3.1413, -3.6831], requires_grad=True)
tensor([ 1.2580, -0.3197, -3.1413, -3.6832], requires_grad=True)
tensor([ 1.2559, -0.3230, -3.1412, -3.6832], requires_grad=True)
tensor([ 1.2564, -0.3222, -3.1413, -3.6832], requires_grad=True)
tensor([ 1.2581, -0.3197, -3.1413, -3.6833], requires_grad=True)
tensor([ 1.2558, -0.3240, -3.1413, -3.6834], requires_grad=True)
tensor([ 1.2540, -0.3280,

tensor([ 1.2554, -0.3230, -3.1462, -3.6887], requires_grad=True)
tensor([ 1.2531, -0.3268, -3.1462, -3.6887], requires_grad=True)
tensor([ 1.2534, -0.3267, -3.1463, -3.6888], requires_grad=True)
tensor([ 1.2516, -0.3293, -3.1464, -3.6889], requires_grad=True)
tensor([ 1.2525, -0.3280, -3.1464, -3.6889], requires_grad=True)
tensor([ 1.2536, -0.3263, -3.1464, -3.6889], requires_grad=True)
tensor([ 1.2543, -0.3249, -3.1464, -3.6890], requires_grad=True)
tensor([ 1.2553, -0.3230, -3.1465, -3.6891], requires_grad=True)
tensor([ 1.2553, -0.3240, -3.1465, -3.6891], requires_grad=True)
tensor([ 1.2557, -0.3234, -3.1466, -3.6892], requires_grad=True)
tensor([ 1.2553, -0.3235, -3.1466, -3.6892], requires_grad=True)
tensor([ 1.2549, -0.3243, -3.1466, -3.6892], requires_grad=True)
tensor([ 1.2557, -0.3228, -3.1466, -3.6892], requires_grad=True)
tensor([ 1.2538, -0.3265, -3.1467, -3.6893], requires_grad=True)
tensor([ 1.2549, -0.3249, -3.1468, -3.6894], requires_grad=True)
tensor([ 1.2532, -0.3275,

tensor([ 1.2584, -0.3220, -3.1528, -3.6960], requires_grad=True)
tensor([ 1.2575, -0.3237, -3.1529, -3.6960], requires_grad=True)
tensor([ 1.2596, -0.3204, -3.1529, -3.6960], requires_grad=True)
tensor([ 1.2579, -0.3232, -3.1530, -3.6961], requires_grad=True)
tensor([ 1.2563, -0.3259, -3.1530, -3.6962], requires_grad=True)
tensor([ 1.2558, -0.3265, -3.1531, -3.6962], requires_grad=True)
tensor([ 1.2565, -0.3247, -3.1531, -3.6962], requires_grad=True)
tensor([ 1.2549, -0.3272, -3.1531, -3.6962], requires_grad=True)
tensor([ 1.2591, -0.3205, -3.1531, -3.6963], requires_grad=True)
tensor([ 1.2568, -0.3242, -3.1532, -3.6964], requires_grad=True)
tensor([ 1.2557, -0.3266, -3.1531, -3.6964], requires_grad=True)
tensor([ 1.2535, -0.3303, -3.1532, -3.6964], requires_grad=True)
tensor([ 1.2534, -0.3309, -3.1532, -3.6964], requires_grad=True)
tensor([ 1.2535, -0.3312, -3.1532, -3.6965], requires_grad=True)
tensor([ 1.2535, -0.3311, -3.1533, -3.6965], requires_grad=True)
tensor([ 1.2551, -0.3283,

tensor([ 1.2530, -0.3268, -3.1584, -3.7020], requires_grad=True)
tensor([ 1.2529, -0.3269, -3.1586, -3.7021], requires_grad=True)
tensor([ 1.2531, -0.3263, -3.1586, -3.7022], requires_grad=True)
tensor([ 1.2520, -0.3288, -3.1587, -3.7023], requires_grad=True)
tensor([ 1.2534, -0.3259, -3.1588, -3.7023], requires_grad=True)
tensor([ 1.2545, -0.3242, -3.1588, -3.7024], requires_grad=True)
tensor([ 1.2544, -0.3245, -3.1589, -3.7025], requires_grad=True)
tensor([ 1.2572, -0.3196, -3.1589, -3.7025], requires_grad=True)
tensor([ 1.2571, -0.3194, -3.1590, -3.7026], requires_grad=True)
tensor([ 1.2555, -0.3222, -3.1591, -3.7027], requires_grad=True)
tensor([ 1.2561, -0.3206, -3.1592, -3.7027], requires_grad=True)
tensor([ 1.2535, -0.3252, -3.1592, -3.7029], requires_grad=True)
tensor([ 1.2525, -0.3270, -3.1592, -3.7029], requires_grad=True)
tensor([ 1.2521, -0.3266, -3.1592, -3.7030], requires_grad=True)
tensor([ 1.2531, -0.3247, -3.1592, -3.7030], requires_grad=True)
tensor([ 1.2511, -0.3287,

tensor([ 1.2534, -0.3249, -3.1644, -3.7089], requires_grad=True)
tensor([ 1.2527, -0.3263, -3.1645, -3.7090], requires_grad=True)
tensor([ 1.2508, -0.3290, -3.1645, -3.7091], requires_grad=True)
tensor([ 1.2516, -0.3271, -3.1645, -3.7092], requires_grad=True)
tensor([ 1.2534, -0.3244, -3.1646, -3.7092], requires_grad=True)
tensor([ 1.2517, -0.3269, -3.1646, -3.7093], requires_grad=True)
tensor([ 1.2534, -0.3247, -3.1646, -3.7093], requires_grad=True)
tensor([ 1.2518, -0.3273, -3.1647, -3.7094], requires_grad=True)
tensor([ 1.2544, -0.3228, -3.1648, -3.7095], requires_grad=True)
tensor([ 1.2540, -0.3239, -3.1648, -3.7095], requires_grad=True)
tensor([ 1.2519, -0.3276, -3.1648, -3.7095], requires_grad=True)
tensor([ 1.2529, -0.3261, -3.1648, -3.7095], requires_grad=True)
tensor([ 1.2508, -0.3292, -3.1648, -3.7096], requires_grad=True)
tensor([ 1.2489, -0.3325, -3.1649, -3.7096], requires_grad=True)
tensor([ 1.2505, -0.3293, -3.1649, -3.7097], requires_grad=True)
tensor([ 1.2503, -0.3291,

tensor([ 1.2469, -0.3344, -3.1694, -3.7150], requires_grad=True)
tensor([ 1.2493, -0.3302, -3.1695, -3.7150], requires_grad=True)
tensor([ 1.2520, -0.3254, -3.1695, -3.7150], requires_grad=True)
tensor([ 1.2511, -0.3274, -3.1696, -3.7151], requires_grad=True)
tensor([ 1.2512, -0.3259, -3.1695, -3.7150], requires_grad=True)
tensor([ 1.2518, -0.3247, -3.1696, -3.7150], requires_grad=True)
tensor([ 1.2542, -0.3206, -3.1696, -3.7152], requires_grad=True)
tensor([ 1.2526, -0.3235, -3.1697, -3.7152], requires_grad=True)
tensor([ 1.2531, -0.3225, -3.1697, -3.7153], requires_grad=True)
tensor([ 1.2525, -0.3240, -3.1698, -3.7153], requires_grad=True)
tensor([ 1.2517, -0.3255, -3.1698, -3.7153], requires_grad=True)
tensor([ 1.2523, -0.3236, -3.1698, -3.7153], requires_grad=True)
tensor([ 1.2527, -0.3229, -3.1698, -3.7153], requires_grad=True)
tensor([ 1.2546, -0.3199, -3.1698, -3.7153], requires_grad=True)
tensor([ 1.2533, -0.3224, -3.1698, -3.7153], requires_grad=True)
tensor([ 1.2515, -0.3260,

tensor([ 1.2538, -0.3254, -3.1738, -3.7199], requires_grad=True)
tensor([ 1.2541, -0.3246, -3.1739, -3.7199], requires_grad=True)
tensor([ 1.2531, -0.3259, -3.1739, -3.7200], requires_grad=True)
tensor([ 1.2526, -0.3264, -3.1740, -3.7200], requires_grad=True)
tensor([ 1.2543, -0.3240, -3.1740, -3.7200], requires_grad=True)
tensor([ 1.2557, -0.3217, -3.1741, -3.7201], requires_grad=True)
tensor([ 1.2573, -0.3191, -3.1741, -3.7201], requires_grad=True)
tensor([ 1.2574, -0.3201, -3.1741, -3.7202], requires_grad=True)
tensor([ 1.2543, -0.3254, -3.1741, -3.7202], requires_grad=True)
tensor([ 1.2530, -0.3278, -3.1741, -3.7202], requires_grad=True)
tensor([ 1.2518, -0.3300, -3.1741, -3.7202], requires_grad=True)
tensor([ 1.2517, -0.3306, -3.1742, -3.7203], requires_grad=True)
tensor([ 1.2536, -0.3266, -3.1742, -3.7203], requires_grad=True)
tensor([ 1.2525, -0.3287, -3.1743, -3.7204], requires_grad=True)
tensor([ 1.2547, -0.3249, -3.1743, -3.7204], requires_grad=True)
tensor([ 1.2529, -0.3277,

tensor([ 1.2553, -0.3243, -3.1788, -3.7250], requires_grad=True)
tensor([ 1.2536, -0.3272, -3.1788, -3.7250], requires_grad=True)
tensor([ 1.2549, -0.3246, -3.1789, -3.7251], requires_grad=True)
tensor([ 1.2536, -0.3269, -3.1789, -3.7252], requires_grad=True)
tensor([ 1.2530, -0.3282, -3.1790, -3.7253], requires_grad=True)
tensor([ 1.2514, -0.3304, -3.1790, -3.7253], requires_grad=True)
tensor([ 1.2517, -0.3301, -3.1791, -3.7254], requires_grad=True)
tensor([ 1.2529, -0.3277, -3.1791, -3.7254], requires_grad=True)
tensor([ 1.2526, -0.3273, -3.1791, -3.7254], requires_grad=True)
tensor([ 1.2544, -0.3241, -3.1792, -3.7255], requires_grad=True)
tensor([ 1.2553, -0.3220, -3.1793, -3.7256], requires_grad=True)
tensor([ 1.2535, -0.3253, -3.1794, -3.7257], requires_grad=True)
tensor([ 1.2534, -0.3257, -3.1795, -3.7258], requires_grad=True)
tensor([ 1.2549, -0.3228, -3.1795, -3.7259], requires_grad=True)
tensor([ 1.2550, -0.3228, -3.1796, -3.7259], requires_grad=True)
tensor([ 1.2561, -0.3209,

tensor([ 1.2562, -0.3202, -3.1837, -3.7312], requires_grad=True)
tensor([ 1.2528, -0.3265, -3.1837, -3.7312], requires_grad=True)
tensor([ 1.2518, -0.3281, -3.1838, -3.7313], requires_grad=True)
tensor([ 1.2542, -0.3238, -3.1839, -3.7314], requires_grad=True)
tensor([ 1.2524, -0.3277, -3.1838, -3.7313], requires_grad=True)
tensor([ 1.2548, -0.3240, -3.1838, -3.7313], requires_grad=True)
tensor([ 1.2560, -0.3217, -3.1839, -3.7314], requires_grad=True)
tensor([ 1.2546, -0.3239, -3.1840, -3.7314], requires_grad=True)
tensor([ 1.2547, -0.3232, -3.1841, -3.7315], requires_grad=True)
tensor([ 1.2561, -0.3212, -3.1841, -3.7315], requires_grad=True)
tensor([ 1.2558, -0.3213, -3.1841, -3.7315], requires_grad=True)
tensor([ 1.2557, -0.3226, -3.1840, -3.7315], requires_grad=True)
tensor([ 1.2555, -0.3228, -3.1840, -3.7315], requires_grad=True)
tensor([ 1.2544, -0.3243, -3.1840, -3.7315], requires_grad=True)
tensor([ 1.2536, -0.3262, -3.1840, -3.7315], requires_grad=True)
tensor([ 1.2534, -0.3265,

tensor([ 1.2532, -0.3248, -3.1885, -3.7359], requires_grad=True)
tensor([ 1.2536, -0.3237, -3.1885, -3.7360], requires_grad=True)
tensor([ 1.2537, -0.3232, -3.1886, -3.7359], requires_grad=True)
tensor([ 1.2544, -0.3218, -3.1887, -3.7360], requires_grad=True)
tensor([ 1.2541, -0.3231, -3.1888, -3.7361], requires_grad=True)
tensor([ 1.2543, -0.3231, -3.1888, -3.7362], requires_grad=True)
tensor([ 1.2525, -0.3262, -3.1889, -3.7363], requires_grad=True)
tensor([ 1.2533, -0.3246, -3.1889, -3.7364], requires_grad=True)
tensor([ 1.2548, -0.3221, -3.1890, -3.7364], requires_grad=True)
tensor([ 1.2561, -0.3197, -3.1891, -3.7364], requires_grad=True)
tensor([ 1.2559, -0.3201, -3.1891, -3.7364], requires_grad=True)
tensor([ 1.2558, -0.3209, -3.1891, -3.7364], requires_grad=True)
tensor([ 1.2533, -0.3248, -3.1891, -3.7364], requires_grad=True)
tensor([ 1.2524, -0.3259, -3.1891, -3.7365], requires_grad=True)
tensor([ 1.2508, -0.3288, -3.1892, -3.7365], requires_grad=True)
tensor([ 1.2529, -0.3254,

tensor([ 1.2566, -0.3211, -3.1935, -3.7416], requires_grad=True)
tensor([ 1.2573, -0.3202, -3.1935, -3.7416], requires_grad=True)
tensor([ 1.2570, -0.3208, -3.1935, -3.7416], requires_grad=True)
tensor([ 1.2568, -0.3213, -3.1934, -3.7416], requires_grad=True)
tensor([ 1.2569, -0.3207, -3.1935, -3.7415], requires_grad=True)
tensor([ 1.2555, -0.3229, -3.1936, -3.7416], requires_grad=True)
tensor([ 1.2544, -0.3253, -3.1936, -3.7417], requires_grad=True)
tensor([ 1.2554, -0.3239, -3.1936, -3.7418], requires_grad=True)
tensor([ 1.2561, -0.3220, -3.1937, -3.7418], requires_grad=True)
tensor([ 1.2563, -0.3223, -3.1937, -3.7419], requires_grad=True)
tensor([ 1.2569, -0.3215, -3.1937, -3.7419], requires_grad=True)
tensor([ 1.2599, -0.3169, -3.1938, -3.7420], requires_grad=True)
tensor([ 1.2601, -0.3170, -3.1938, -3.7421], requires_grad=True)
tensor([ 1.2599, -0.3174, -3.1938, -3.7421], requires_grad=True)
tensor([ 1.2573, -0.3219, -3.1940, -3.7422], requires_grad=True)
tensor([ 1.2573, -0.3219,

tensor([ 1.2534, -0.3262, -3.1989, -3.7475], requires_grad=True)
tensor([ 1.2558, -0.3226, -3.1990, -3.7475], requires_grad=True)
tensor([ 1.2564, -0.3218, -3.1990, -3.7476], requires_grad=True)
tensor([ 1.2516, -0.3301, -3.1991, -3.7476], requires_grad=True)
tensor([ 1.2526, -0.3288, -3.1992, -3.7477], requires_grad=True)
tensor([ 1.2507, -0.3329, -3.1992, -3.7477], requires_grad=True)
tensor([ 1.2506, -0.3325, -3.1992, -3.7477], requires_grad=True)
tensor([ 1.2522, -0.3298, -3.1993, -3.7477], requires_grad=True)
tensor([ 1.2521, -0.3289, -3.1993, -3.7477], requires_grad=True)
tensor([ 1.2515, -0.3296, -3.1994, -3.7477], requires_grad=True)
tensor([ 1.2520, -0.3279, -3.1994, -3.7478], requires_grad=True)
tensor([ 1.2516, -0.3280, -3.1995, -3.7478], requires_grad=True)
tensor([ 1.2543, -0.3238, -3.1995, -3.7479], requires_grad=True)
tensor([ 1.2528, -0.3267, -3.1995, -3.7480], requires_grad=True)
tensor([ 1.2533, -0.3260, -3.1996, -3.7480], requires_grad=True)
tensor([ 1.2545, -0.3242,

tensor([ 1.2568, -0.3213, -3.2036, -3.7517], requires_grad=True)
tensor([ 1.2557, -0.3231, -3.2035, -3.7518], requires_grad=True)
tensor([ 1.2540, -0.3251, -3.2035, -3.7517], requires_grad=True)
tensor([ 1.2551, -0.3231, -3.2036, -3.7517], requires_grad=True)
tensor([ 1.2560, -0.3217, -3.2036, -3.7518], requires_grad=True)
tensor([ 1.2542, -0.3253, -3.2037, -3.7519], requires_grad=True)
tensor([ 1.2540, -0.3256, -3.2037, -3.7519], requires_grad=True)
tensor([ 1.2531, -0.3274, -3.2038, -3.7520], requires_grad=True)
tensor([ 1.2529, -0.3277, -3.2039, -3.7521], requires_grad=True)
tensor([ 1.2533, -0.3269, -3.2039, -3.7521], requires_grad=True)
tensor([ 1.2526, -0.3278, -3.2039, -3.7521], requires_grad=True)
tensor([ 1.2525, -0.3272, -3.2039, -3.7521], requires_grad=True)
tensor([ 1.2536, -0.3253, -3.2039, -3.7522], requires_grad=True)
tensor([ 1.2533, -0.3256, -3.2040, -3.7522], requires_grad=True)
tensor([ 1.2539, -0.3244, -3.2041, -3.7523], requires_grad=True)
tensor([ 1.2544, -0.3235,

tensor([ 1.2538, -0.3257, -3.2082, -3.7560], requires_grad=True)
tensor([ 1.2555, -0.3233, -3.2081, -3.7559], requires_grad=True)
tensor([ 1.2548, -0.3242, -3.2081, -3.7560], requires_grad=True)
tensor([ 1.2548, -0.3246, -3.2082, -3.7560], requires_grad=True)
tensor([ 1.2552, -0.3234, -3.2082, -3.7560], requires_grad=True)
tensor([ 1.2560, -0.3220, -3.2082, -3.7561], requires_grad=True)
tensor([ 1.2559, -0.3217, -3.2083, -3.7561], requires_grad=True)
tensor([ 1.2554, -0.3226, -3.2084, -3.7562], requires_grad=True)
tensor([ 1.2551, -0.3233, -3.2083, -3.7562], requires_grad=True)
tensor([ 1.2526, -0.3276, -3.2084, -3.7563], requires_grad=True)
tensor([ 1.2554, -0.3229, -3.2085, -3.7564], requires_grad=True)
tensor([ 1.2562, -0.3216, -3.2084, -3.7564], requires_grad=True)
tensor([ 1.2532, -0.3264, -3.2085, -3.7564], requires_grad=True)
tensor([ 1.2513, -0.3295, -3.2085, -3.7565], requires_grad=True)
tensor([ 1.2521, -0.3282, -3.2085, -3.7564], requires_grad=True)
tensor([ 1.2545, -0.3244,

tensor([ 1.2557, -0.3242, -3.2124, -3.7603], requires_grad=True)
tensor([ 1.2554, -0.3253, -3.2124, -3.7603], requires_grad=True)
tensor([ 1.2550, -0.3253, -3.2123, -3.7603], requires_grad=True)
tensor([ 1.2549, -0.3253, -3.2123, -3.7602], requires_grad=True)
tensor([ 1.2547, -0.3262, -3.2124, -3.7602], requires_grad=True)
tensor([ 1.2551, -0.3254, -3.2124, -3.7603], requires_grad=True)
tensor([ 1.2546, -0.3262, -3.2125, -3.7603], requires_grad=True)
tensor([ 1.2554, -0.3246, -3.2124, -3.7603], requires_grad=True)
tensor([ 1.2572, -0.3211, -3.2125, -3.7603], requires_grad=True)
tensor([ 1.2551, -0.3249, -3.2126, -3.7605], requires_grad=True)
tensor([ 1.2559, -0.3232, -3.2126, -3.7605], requires_grad=True)
tensor([ 1.2552, -0.3247, -3.2127, -3.7605], requires_grad=True)
tensor([ 1.2573, -0.3215, -3.2127, -3.7606], requires_grad=True)
tensor([ 1.2561, -0.3233, -3.2126, -3.7606], requires_grad=True)
tensor([ 1.2552, -0.3243, -3.2127, -3.7606], requires_grad=True)
tensor([ 1.2547, -0.3249,

tensor([ 1.2553, -0.3245, -3.2164, -3.7651], requires_grad=True)
tensor([ 1.2546, -0.3260, -3.2164, -3.7652], requires_grad=True)
tensor([ 1.2551, -0.3252, -3.2164, -3.7652], requires_grad=True)
tensor([ 1.2549, -0.3253, -3.2164, -3.7652], requires_grad=True)
tensor([ 1.2573, -0.3216, -3.2165, -3.7652], requires_grad=True)
tensor([ 1.2580, -0.3199, -3.2166, -3.7652], requires_grad=True)
tensor([ 1.2572, -0.3220, -3.2166, -3.7652], requires_grad=True)
tensor([ 1.2555, -0.3252, -3.2166, -3.7652], requires_grad=True)
tensor([ 1.2566, -0.3231, -3.2166, -3.7652], requires_grad=True)
tensor([ 1.2560, -0.3236, -3.2166, -3.7652], requires_grad=True)
tensor([ 1.2546, -0.3264, -3.2167, -3.7653], requires_grad=True)
tensor([ 1.2555, -0.3245, -3.2167, -3.7652], requires_grad=True)
tensor([ 1.2552, -0.3251, -3.2167, -3.7652], requires_grad=True)
tensor([ 1.2558, -0.3238, -3.2168, -3.7652], requires_grad=True)
tensor([ 1.2537, -0.3273, -3.2168, -3.7653], requires_grad=True)
tensor([ 1.2517, -0.3307,

KeyboardInterrupt: 

In [170]:
rho_to_sigma(torch.tensor(0.5488))

tensor(1.0047)