In [2]:
import numpy as np
import torch


In [5]:
def load_data(txt):

#    data = np.loadtxt(txt + '/' + txt + '.txt')
    data = np.genfromtxt(txt + '/' + txt + '.csv', delimiter='')

    # Les targets sont à la fin. 
    X = data[:, range(data.shape[1] - 1) ]
    y = data[:, data.shape[1] - 1]
    
    # Les targets sont au début. 
#    X = data[:, 0:]
#    y = data[:, 0]
    data=X,y
    torch.save(data, txt + '/data.pt' )
    return data

X,y=load_data('energy')
X.shape, y.shape

((768, 8), (768,))

In [6]:
X[0], y[0]

(array([  0.98, 514.5 , 294.  , 110.25,   7.  ,   2.  ,   0.  ,   0.  ]),
 15.55)

In [5]:
data=torch.load('concrete/data.pt')

In [6]:
data

(array([[ 540. ,    0. ,    0. , ..., 1040. ,  676. ,   28. ],
        [ 540. ,    0. ,    0. , ..., 1055. ,  676. ,   28. ],
        [ 332.5,  142.5,    0. , ...,  932. ,  594. ,  270. ],
        ...,
        [ 148.5,  139.4,  108.6, ...,  892.4,  780. ,   28. ],
        [ 159.1,  186.7,    0. , ...,  989.6,  788.9,   28. ],
        [ 260.9,  100.5,   78.3, ...,  864.5,  761.5,   28. ]]),
 array([79.99, 61.89, 40.27, ..., 23.7 , 32.77, 32.4 ]))