In [1]:
import pandas as pd
import os
import numpy as np
import scipy as sp
import torch

In [2]:
from scipy.stats import uniform, norm
import seaborn as sns; sns.set()
import matplotlib.pyplot as plt

In [3]:
A = 1.2
b = -0.3
sigma = 0.2
N = 100

In [4]:
X = torch.from_numpy(uniform.rvs(size=N))
X.detach()
X = X.float()

In [5]:
e = torch.from_numpy(norm.rvs(loc=0, scale=sigma, size=N)).float()

In [6]:
y = A*X + b + e

In [7]:
y.detach()
y = y.float()

In [8]:
def sigma_to_rho(sigma):
    rho = torch.log(torch.exp(sigma) - 1)
    return rho

In [9]:
def rho_to_sigma(rho):
    sigma = torch.log(1 + torch.exp(rho))
    return sigma

In [10]:
def log_q_pdf(w, theta):
    (mu_A, mu_b, rho_A, rho_b) = theta 
    
    sigma_A = rho_to_sigma(rho_A)
    qA = torch.distributions.normal.Normal(mu_A, sigma_A)
    
    sigma_b = rho_to_sigma(rho_b)
    qb = torch.distributions.normal.Normal(mu_b, sigma_b)
    
    lp = qA.log_prob(w[0]) + qb.log_prob(w[1])
    return lp

In [11]:
def log_p_pdf(w):
    prior_mu_A = torch.tensor(0.0) 
    prior_sigma_A = torch.tensor(1.0)
    pA = torch.distributions.normal.Normal(prior_mu_A, prior_sigma_A)
    
    prior_mu_b = torch.tensor(0.0) 
    prior_sigma_b = torch.tensor(1.0)
    pb = torch.distributions.normal.Normal(prior_mu_b, prior_sigma_b)
    
    lp = pA.log_prob(w[0]) + pb.log_prob(w[1])
    return lp

In [12]:
def likelihood(y,X,w):
    A = w[0]
    b = w[1]
    
    y_pred = A*X + b
    lp = torch.distributions.normal.Normal(y_pred, 0.2).log_prob(y).sum()
    return lp

In [13]:
def f(w, theta):
    v = log_q_pdf(w, theta) - log_p_pdf(w) - likelihood(y,X,w)
    return v

In [14]:
mu_A = torch.tensor(0.0)
sigma_A = torch.tensor(0.1)
rho_A = sigma_to_rho(sigma_A)
mu_b = torch.tensor(0.0)
sigma_b = torch.tensor(0.1)
rho_b = sigma_to_rho(sigma_b)

theta = torch.tensor([mu_A, mu_b, rho_A, rho_b], requires_grad=True)

In [15]:

lst_grad_mu = []
lst_grad_rho = []
for j in range(0,5000):
    epsilon = torch.distributions.normal.Normal(torch.tensor(0.0) , torch.tensor(1.0)).sample(torch.Size([2,]))

    with torch.no_grad():
        w = theta[0:2].clone().detach() + torch.log(1 + torch.exp(theta[2:4].clone().detach()))*epsilon
    w.requires_grad = True

    v = f(w, theta)   
    v.backward()
    v = torch.tensor([])

    with torch.no_grad():
        grad_mu = w.grad + theta.grad[0:2]
        grad_rho = w.grad*epsilon/(1 + torch.exp(-theta[2:4])) + -theta.grad[2:4]


    lst_grad_mu.append(grad_mu)
    lst_grad_rho.append(grad_rho)

    theta.grad.zero_()
    w.grad.zero_()
    v.detach()
grad_mu = torch.stack(lst_grad_mu).mean(dim=0)
grad_rho = torch.stack(lst_grad_rho).mean(dim=0)
        
 



In [16]:
grad_mu

tensor([-724.3985, -863.2999])

In [17]:
grad_rho

tensor([ 6.9006, 22.5250])

In [18]:
alpha = torch.tensor(10e-5)

In [19]:
for i in range(0,10000):
    lst_grad_mu = []
    lst_grad_rho = []
    for j in range(0,10):
        epsilon = torch.distributions.normal.Normal(torch.tensor(0.0) , torch.tensor(1.0)).sample(torch.Size([2,]))

        with torch.no_grad():
            w = theta[0:2].clone().detach() + torch.log(1 + torch.exp(theta[2:4].clone().detach()))*epsilon
        w.requires_grad = True

        v = f(w, theta)   
        v.backward()
        v = torch.tensor([])

        with torch.no_grad():
            grad_mu = w.grad + theta.grad[0:2]
            grad_rho = w.grad*epsilon/(1 + torch.exp(-theta[2:4])) + -theta.grad[2:4]


        lst_grad_mu.append(grad_mu)
        lst_grad_rho.append(grad_rho)

        theta.grad.zero_()
        w.grad.zero_()
        v.detach()
    grad_mu = torch.stack(lst_grad_mu).mean(dim=0)
    grad_rho = torch.stack(lst_grad_rho).mean(dim=0)
    
    #print(grad_mu)
    #print(grad_rho)
        
    with torch.no_grad():
        theta[0:2] -= alpha*grad_mu
        theta[2:4] -= alpha*grad_rho
    
    print(theta)



tensor([ 0.0751,  0.0924, -2.2519, -2.2588], requires_grad=True)
tensor([ 0.1250,  0.1379, -2.2537, -2.2600], requires_grad=True)
tensor([ 0.1666,  0.1711, -2.2534, -2.2613], requires_grad=True)
tensor([ 0.1999,  0.1885, -2.2540, -2.2631], requires_grad=True)
tensor([ 0.2330,  0.2100, -2.2526, -2.2660], requires_grad=True)
tensor([ 0.2591,  0.2170, -2.2524, -2.2705], requires_grad=True)
tensor([ 0.2815,  0.2162, -2.2536, -2.2731], requires_grad=True)
tensor([ 0.2981,  0.2067, -2.2535, -2.2749], requires_grad=True)
tensor([ 0.3182,  0.2056, -2.2541, -2.2773], requires_grad=True)
tensor([ 0.3310,  0.1914, -2.2546, -2.2798], requires_grad=True)
tensor([ 0.3452,  0.1801, -2.2550, -2.2818], requires_grad=True)
tensor([ 0.3635,  0.1773, -2.2551, -2.2828], requires_grad=True)
tensor([ 0.3740,  0.1606, -2.2565, -2.2853], requires_grad=True)
tensor([ 0.4006,  0.1726, -2.2587, -2.2868], requires_grad=True)
tensor([ 0.4155,  0.1648, -2.2594, -2.2878], requires_grad=True)
tensor([ 0.4360,  0.1670,

tensor([ 1.1135, -0.2207, -2.3387, -2.4876], requires_grad=True)
tensor([ 1.1194, -0.2139, -2.3402, -2.4903], requires_grad=True)
tensor([ 1.1185, -0.2201, -2.3405, -2.4923], requires_grad=True)
tensor([ 1.1199, -0.2224, -2.3411, -2.4933], requires_grad=True)
tensor([ 1.1201, -0.2267, -2.3416, -2.4944], requires_grad=True)
tensor([ 1.1178, -0.2327, -2.3423, -2.4953], requires_grad=True)
tensor([ 1.1224, -0.2284, -2.3427, -2.4956], requires_grad=True)
tensor([ 1.1277, -0.2234, -2.3436, -2.4970], requires_grad=True)
tensor([ 1.1329, -0.2171, -2.3440, -2.4982], requires_grad=True)
tensor([ 1.1325, -0.2213, -2.3447, -2.5002], requires_grad=True)
tensor([ 1.1315, -0.2259, -2.3452, -2.5017], requires_grad=True)
tensor([ 1.1287, -0.2332, -2.3456, -2.5029], requires_grad=True)
tensor([ 1.1311, -0.2330, -2.3465, -2.5053], requires_grad=True)
tensor([ 1.1297, -0.2384, -2.3468, -2.5057], requires_grad=True)
tensor([ 1.1304, -0.2411, -2.3473, -2.5061], requires_grad=True)
tensor([ 1.1383, -0.2310,

tensor([ 1.2003, -0.2636, -2.4224, -2.6451], requires_grad=True)
tensor([ 1.1950, -0.2747, -2.4230, -2.6474], requires_grad=True)
tensor([ 1.2011, -0.2654, -2.4243, -2.6491], requires_grad=True)
tensor([ 1.1969, -0.2718, -2.4255, -2.6504], requires_grad=True)
tensor([ 1.1934, -0.2773, -2.4259, -2.6517], requires_grad=True)
tensor([ 1.1899, -0.2830, -2.4265, -2.6523], requires_grad=True)
tensor([ 1.1933, -0.2767, -2.4263, -2.6529], requires_grad=True)
tensor([ 1.1941, -0.2766, -2.4266, -2.6536], requires_grad=True)
tensor([ 1.1857, -0.2914, -2.4273, -2.6547], requires_grad=True)
tensor([ 1.1920, -0.2792, -2.4279, -2.6553], requires_grad=True)
tensor([ 1.1920, -0.2806, -2.4282, -2.6563], requires_grad=True)
tensor([ 1.1974, -0.2720, -2.4293, -2.6572], requires_grad=True)
tensor([ 1.1936, -0.2785, -2.4300, -2.6583], requires_grad=True)
tensor([ 1.1931, -0.2805, -2.4302, -2.6589], requires_grad=True)
tensor([ 1.2014, -0.2671, -2.4307, -2.6595], requires_grad=True)
tensor([ 1.1976, -0.2736,

tensor([ 1.2008, -0.2747, -2.4878, -2.7690], requires_grad=True)
tensor([ 1.2035, -0.2695, -2.4882, -2.7700], requires_grad=True)
tensor([ 1.2035, -0.2698, -2.4885, -2.7706], requires_grad=True)
tensor([ 1.2057, -0.2664, -2.4890, -2.7714], requires_grad=True)
tensor([ 1.2098, -0.2604, -2.4891, -2.7718], requires_grad=True)
tensor([ 1.2072, -0.2657, -2.4893, -2.7725], requires_grad=True)
tensor([ 1.2038, -0.2719, -2.4896, -2.7730], requires_grad=True)
tensor([ 1.2084, -0.2639, -2.4901, -2.7735], requires_grad=True)
tensor([ 1.2046, -0.2717, -2.4904, -2.7751], requires_grad=True)
tensor([ 1.2011, -0.2760, -2.4911, -2.7760], requires_grad=True)
tensor([ 1.2010, -0.2755, -2.4915, -2.7763], requires_grad=True)
tensor([ 1.2020, -0.2741, -2.4922, -2.7780], requires_grad=True)
tensor([ 1.2084, -0.2620, -2.4933, -2.7797], requires_grad=True)
tensor([ 1.2064, -0.2649, -2.4940, -2.7812], requires_grad=True)
tensor([ 1.2022, -0.2721, -2.4948, -2.7824], requires_grad=True)
tensor([ 1.2057, -0.2655,

tensor([ 1.2009, -0.2735, -2.5406, -2.8594], requires_grad=True)
tensor([ 1.2023, -0.2706, -2.5410, -2.8601], requires_grad=True)
tensor([ 1.2021, -0.2704, -2.5411, -2.8606], requires_grad=True)
tensor([ 1.2045, -0.2654, -2.5418, -2.8619], requires_grad=True)
tensor([ 1.2054, -0.2633, -2.5418, -2.8630], requires_grad=True)
tensor([ 1.2096, -0.2548, -2.5418, -2.8635], requires_grad=True)
tensor([ 1.2092, -0.2565, -2.5421, -2.8639], requires_grad=True)
tensor([ 1.2123, -0.2508, -2.5425, -2.8647], requires_grad=True)
tensor([ 1.2118, -0.2496, -2.5425, -2.8650], requires_grad=True)
tensor([ 1.2068, -0.2595, -2.5428, -2.8656], requires_grad=True)
tensor([ 1.1990, -0.2713, -2.5436, -2.8666], requires_grad=True)
tensor([ 1.1979, -0.2722, -2.5439, -2.8676], requires_grad=True)
tensor([ 1.1954, -0.2768, -2.5442, -2.8683], requires_grad=True)
tensor([ 1.2000, -0.2677, -2.5446, -2.8694], requires_grad=True)
tensor([ 1.1976, -0.2718, -2.5449, -2.8703], requires_grad=True)
tensor([ 1.1939, -0.2785,

tensor([ 1.2014, -0.2683, -2.5888, -2.9401], requires_grad=True)
tensor([ 1.1976, -0.2749, -2.5891, -2.9405], requires_grad=True)
tensor([ 1.2008, -0.2687, -2.5893, -2.9414], requires_grad=True)
tensor([ 1.2031, -0.2656, -2.5897, -2.9420], requires_grad=True)
tensor([ 1.2037, -0.2641, -2.5901, -2.9429], requires_grad=True)
tensor([ 1.2013, -0.2666, -2.5907, -2.9434], requires_grad=True)
tensor([ 1.2022, -0.2638, -2.5907, -2.9439], requires_grad=True)
tensor([ 1.2004, -0.2672, -2.5908, -2.9446], requires_grad=True)
tensor([ 1.1992, -0.2677, -2.5909, -2.9450], requires_grad=True)
tensor([ 1.2010, -0.2648, -2.5916, -2.9460], requires_grad=True)
tensor([ 1.1992, -0.2680, -2.5918, -2.9464], requires_grad=True)
tensor([ 1.1962, -0.2722, -2.5921, -2.9468], requires_grad=True)
tensor([ 1.1950, -0.2738, -2.5924, -2.9475], requires_grad=True)
tensor([ 1.1929, -0.2769, -2.5928, -2.9479], requires_grad=True)
tensor([ 1.1951, -0.2731, -2.5933, -2.9484], requires_grad=True)
tensor([ 1.1966, -0.2695,

tensor([ 1.1982, -0.2667, -2.6325, -3.0080], requires_grad=True)
tensor([ 1.2005, -0.2636, -2.6326, -3.0085], requires_grad=True)
tensor([ 1.2048, -0.2561, -2.6332, -3.0091], requires_grad=True)
tensor([ 1.2023, -0.2603, -2.6336, -3.0094], requires_grad=True)
tensor([ 1.1950, -0.2722, -2.6341, -3.0099], requires_grad=True)
tensor([ 1.1924, -0.2761, -2.6347, -3.0105], requires_grad=True)
tensor([ 1.1948, -0.2723, -2.6350, -3.0109], requires_grad=True)
tensor([ 1.1935, -0.2739, -2.6351, -3.0112], requires_grad=True)
tensor([ 1.1917, -0.2770, -2.6353, -3.0118], requires_grad=True)
tensor([ 1.1975, -0.2674, -2.6359, -3.0124], requires_grad=True)
tensor([ 1.1979, -0.2671, -2.6362, -3.0125], requires_grad=True)
tensor([ 1.1955, -0.2715, -2.6369, -3.0136], requires_grad=True)
tensor([ 1.1996, -0.2638, -2.6371, -3.0142], requires_grad=True)
tensor([ 1.1962, -0.2698, -2.6376, -3.0146], requires_grad=True)
tensor([ 1.2001, -0.2638, -2.6380, -3.0151], requires_grad=True)
tensor([ 1.1988, -0.2666,

tensor([ 1.2080, -0.2603, -2.6742, -3.0661], requires_grad=True)
tensor([ 1.2102, -0.2565, -2.6745, -3.0665], requires_grad=True)
tensor([ 1.2112, -0.2561, -2.6747, -3.0669], requires_grad=True)
tensor([ 1.2053, -0.2654, -2.6753, -3.0672], requires_grad=True)
tensor([ 1.2073, -0.2638, -2.6757, -3.0675], requires_grad=True)
tensor([ 1.2111, -0.2582, -2.6761, -3.0679], requires_grad=True)
tensor([ 1.2108, -0.2589, -2.6763, -3.0682], requires_grad=True)
tensor([ 1.2101, -0.2598, -2.6766, -3.0687], requires_grad=True)
tensor([ 1.2085, -0.2620, -2.6771, -3.0692], requires_grad=True)
tensor([ 1.2094, -0.2605, -2.6774, -3.0701], requires_grad=True)
tensor([ 1.2114, -0.2564, -2.6779, -3.0704], requires_grad=True)
tensor([ 1.2062, -0.2653, -2.6781, -3.0706], requires_grad=True)
tensor([ 1.2067, -0.2646, -2.6783, -3.0711], requires_grad=True)
tensor([ 1.2090, -0.2616, -2.6786, -3.0717], requires_grad=True)
tensor([ 1.2032, -0.2711, -2.6791, -3.0720], requires_grad=True)
tensor([ 1.2013, -0.2740,

tensor([ 1.2012, -0.2656, -2.7102, -3.1164], requires_grad=True)
tensor([ 1.2014, -0.2659, -2.7105, -3.1166], requires_grad=True)
tensor([ 1.2017, -0.2658, -2.7108, -3.1170], requires_grad=True)
tensor([ 1.2067, -0.2567, -2.7111, -3.1173], requires_grad=True)
tensor([ 1.2045, -0.2609, -2.7112, -3.1176], requires_grad=True)
tensor([ 1.2013, -0.2671, -2.7115, -3.1181], requires_grad=True)
tensor([ 1.1986, -0.2712, -2.7119, -3.1186], requires_grad=True)
tensor([ 1.2023, -0.2650, -2.7121, -3.1191], requires_grad=True)
tensor([ 1.2018, -0.2653, -2.7126, -3.1195], requires_grad=True)
tensor([ 1.2000, -0.2677, -2.7127, -3.1196], requires_grad=True)
tensor([ 1.1997, -0.2677, -2.7128, -3.1197], requires_grad=True)
tensor([ 1.1977, -0.2696, -2.7136, -3.1202], requires_grad=True)
tensor([ 1.1987, -0.2681, -2.7136, -3.1204], requires_grad=True)
tensor([ 1.1988, -0.2698, -2.7139, -3.1209], requires_grad=True)
tensor([ 1.2004, -0.2678, -2.7143, -3.1214], requires_grad=True)
tensor([ 1.1981, -0.2715,

tensor([ 1.2014, -0.2683, -2.7445, -3.1629], requires_grad=True)
tensor([ 1.1994, -0.2719, -2.7448, -3.1633], requires_grad=True)
tensor([ 1.2037, -0.2639, -2.7450, -3.1638], requires_grad=True)
tensor([ 1.1994, -0.2708, -2.7452, -3.1639], requires_grad=True)
tensor([ 1.1971, -0.2749, -2.7453, -3.1643], requires_grad=True)
tensor([ 1.1968, -0.2752, -2.7456, -3.1647], requires_grad=True)
tensor([ 1.1974, -0.2736, -2.7457, -3.1649], requires_grad=True)
tensor([ 1.2013, -0.2654, -2.7457, -3.1650], requires_grad=True)
tensor([ 1.1998, -0.2668, -2.7458, -3.1651], requires_grad=True)
tensor([ 1.2003, -0.2660, -2.7462, -3.1654], requires_grad=True)
tensor([ 1.1988, -0.2692, -2.7462, -3.1655], requires_grad=True)
tensor([ 1.2014, -0.2648, -2.7464, -3.1658], requires_grad=True)
tensor([ 1.2019, -0.2644, -2.7466, -3.1661], requires_grad=True)
tensor([ 1.1978, -0.2716, -2.7470, -3.1665], requires_grad=True)
tensor([ 1.1969, -0.2732, -2.7474, -3.1671], requires_grad=True)
tensor([ 1.1991, -0.2696,

tensor([ 1.2032, -0.2697, -2.7762, -3.2058], requires_grad=True)
tensor([ 1.1996, -0.2759, -2.7766, -3.2062], requires_grad=True)
tensor([ 1.2032, -0.2695, -2.7768, -3.2064], requires_grad=True)
tensor([ 1.1993, -0.2764, -2.7773, -3.2069], requires_grad=True)
tensor([ 1.2003, -0.2757, -2.7777, -3.2072], requires_grad=True)
tensor([ 1.2003, -0.2743, -2.7778, -3.2076], requires_grad=True)
tensor([ 1.2002, -0.2744, -2.7780, -3.2078], requires_grad=True)
tensor([ 1.2032, -0.2693, -2.7781, -3.2080], requires_grad=True)
tensor([ 1.2011, -0.2724, -2.7783, -3.2082], requires_grad=True)
tensor([ 1.2024, -0.2709, -2.7785, -3.2083], requires_grad=True)
tensor([ 1.2038, -0.2688, -2.7787, -3.2086], requires_grad=True)
tensor([ 1.2009, -0.2735, -2.7789, -3.2087], requires_grad=True)
tensor([ 1.2040, -0.2676, -2.7791, -3.2091], requires_grad=True)
tensor([ 1.2062, -0.2633, -2.7793, -3.2095], requires_grad=True)
tensor([ 1.2031, -0.2679, -2.7794, -3.2098], requires_grad=True)
tensor([ 1.2071, -0.2625,

tensor([ 1.1986, -0.2676, -2.8034, -3.2411], requires_grad=True)
tensor([ 1.1967, -0.2711, -2.8035, -3.2413], requires_grad=True)
tensor([ 1.2005, -0.2654, -2.8038, -3.2416], requires_grad=True)
tensor([ 1.1965, -0.2721, -2.8041, -3.2418], requires_grad=True)
tensor([ 1.1965, -0.2722, -2.8044, -3.2421], requires_grad=True)
tensor([ 1.1960, -0.2731, -2.8046, -3.2423], requires_grad=True)
tensor([ 1.1977, -0.2704, -2.8048, -3.2426], requires_grad=True)
tensor([ 1.2000, -0.2662, -2.8050, -3.2428], requires_grad=True)
tensor([ 1.1959, -0.2727, -2.8051, -3.2429], requires_grad=True)
tensor([ 1.1946, -0.2747, -2.8052, -3.2430], requires_grad=True)
tensor([ 1.1964, -0.2709, -2.8054, -3.2432], requires_grad=True)
tensor([ 1.1989, -0.2682, -2.8056, -3.2435], requires_grad=True)
tensor([ 1.2005, -0.2668, -2.8058, -3.2436], requires_grad=True)
tensor([ 1.2029, -0.2632, -2.8060, -3.2438], requires_grad=True)
tensor([ 1.2016, -0.2653, -2.8062, -3.2442], requires_grad=True)
tensor([ 1.2019, -0.2652,

tensor([ 1.2017, -0.2690, -2.8294, -3.2742], requires_grad=True)
tensor([ 1.2033, -0.2657, -2.8295, -3.2745], requires_grad=True)
tensor([ 1.2052, -0.2626, -2.8296, -3.2746], requires_grad=True)
tensor([ 1.2033, -0.2658, -2.8299, -3.2750], requires_grad=True)
tensor([ 1.2034, -0.2661, -2.8299, -3.2750], requires_grad=True)
tensor([ 1.2060, -0.2614, -2.8300, -3.2751], requires_grad=True)
tensor([ 1.2036, -0.2659, -2.8301, -3.2752], requires_grad=True)
tensor([ 1.2048, -0.2637, -2.8303, -3.2754], requires_grad=True)
tensor([ 1.1984, -0.2748, -2.8305, -3.2757], requires_grad=True)
tensor([ 1.1977, -0.2763, -2.8305, -3.2759], requires_grad=True)
tensor([ 1.2015, -0.2691, -2.8306, -3.2762], requires_grad=True)
tensor([ 1.2011, -0.2691, -2.8307, -3.2763], requires_grad=True)
tensor([ 1.2015, -0.2682, -2.8308, -3.2766], requires_grad=True)
tensor([ 1.2049, -0.2618, -2.8310, -3.2768], requires_grad=True)
tensor([ 1.2044, -0.2621, -2.8312, -3.2770], requires_grad=True)
tensor([ 1.2045, -0.2628,

tensor([ 1.2063, -0.2710, -2.8538, -3.3049], requires_grad=True)
tensor([ 1.2013, -0.2796, -2.8540, -3.3051], requires_grad=True)
tensor([ 1.2029, -0.2766, -2.8541, -3.3053], requires_grad=True)
tensor([ 1.1997, -0.2815, -2.8544, -3.3056], requires_grad=True)
tensor([ 1.1966, -0.2867, -2.8548, -3.3058], requires_grad=True)
tensor([ 1.1976, -0.2844, -2.8549, -3.3060], requires_grad=True)
tensor([ 1.1987, -0.2822, -2.8550, -3.3060], requires_grad=True)
tensor([ 1.2008, -0.2781, -2.8551, -3.3062], requires_grad=True)
tensor([ 1.2056, -0.2694, -2.8554, -3.3065], requires_grad=True)
tensor([ 1.2040, -0.2724, -2.8555, -3.3066], requires_grad=True)
tensor([ 1.2082, -0.2663, -2.8558, -3.3068], requires_grad=True)
tensor([ 1.2081, -0.2662, -2.8559, -3.3071], requires_grad=True)
tensor([ 1.2075, -0.2670, -2.8561, -3.3072], requires_grad=True)
tensor([ 1.2102, -0.2622, -2.8562, -3.3075], requires_grad=True)
tensor([ 1.2052, -0.2707, -2.8565, -3.3077], requires_grad=True)
tensor([ 1.2023, -0.2757,

tensor([ 1.2033, -0.2685, -2.8771, -3.3327], requires_grad=True)
tensor([ 1.2025, -0.2700, -2.8773, -3.3329], requires_grad=True)
tensor([ 1.2018, -0.2712, -2.8774, -3.3329], requires_grad=True)
tensor([ 1.2036, -0.2685, -2.8776, -3.3330], requires_grad=True)
tensor([ 1.2032, -0.2688, -2.8778, -3.3334], requires_grad=True)
tensor([ 1.2010, -0.2720, -2.8779, -3.3335], requires_grad=True)
tensor([ 1.2033, -0.2683, -2.8781, -3.3338], requires_grad=True)
tensor([ 1.2003, -0.2743, -2.8782, -3.3341], requires_grad=True)
tensor([ 1.2001, -0.2747, -2.8783, -3.3342], requires_grad=True)
tensor([ 1.2031, -0.2689, -2.8783, -3.3345], requires_grad=True)
tensor([ 1.2026, -0.2700, -2.8784, -3.3346], requires_grad=True)
tensor([ 1.2030, -0.2698, -2.8786, -3.3347], requires_grad=True)
tensor([ 1.2059, -0.2651, -2.8789, -3.3350], requires_grad=True)
tensor([ 1.2086, -0.2601, -2.8790, -3.3352], requires_grad=True)
tensor([ 1.2096, -0.2585, -2.8792, -3.3355], requires_grad=True)
tensor([ 1.2050, -0.2659,

tensor([ 1.2030, -0.2707, -2.8982, -3.3590], requires_grad=True)
tensor([ 1.2043, -0.2684, -2.8983, -3.3591], requires_grad=True)
tensor([ 1.2057, -0.2668, -2.8984, -3.3592], requires_grad=True)
tensor([ 1.2030, -0.2713, -2.8986, -3.3595], requires_grad=True)
tensor([ 1.2049, -0.2682, -2.8987, -3.3597], requires_grad=True)
tensor([ 1.2086, -0.2617, -2.8990, -3.3600], requires_grad=True)
tensor([ 1.2061, -0.2662, -2.8991, -3.3602], requires_grad=True)
tensor([ 1.2056, -0.2665, -2.8992, -3.3603], requires_grad=True)
tensor([ 1.2080, -0.2629, -2.8995, -3.3606], requires_grad=True)
tensor([ 1.2046, -0.2690, -2.8997, -3.3608], requires_grad=True)
tensor([ 1.2039, -0.2702, -2.8999, -3.3610], requires_grad=True)
tensor([ 1.2016, -0.2745, -2.9001, -3.3614], requires_grad=True)
tensor([ 1.2033, -0.2715, -2.9001, -3.3614], requires_grad=True)
tensor([ 1.2004, -0.2764, -2.9002, -3.3616], requires_grad=True)
tensor([ 1.2002, -0.2770, -2.9004, -3.3618], requires_grad=True)
tensor([ 1.2031, -0.2727,

tensor([ 1.2012, -0.2683, -2.9183, -3.3832], requires_grad=True)
tensor([ 1.2003, -0.2698, -2.9185, -3.3834], requires_grad=True)
tensor([ 1.2024, -0.2662, -2.9188, -3.3838], requires_grad=True)
tensor([ 1.2031, -0.2657, -2.9189, -3.3839], requires_grad=True)
tensor([ 1.2020, -0.2675, -2.9190, -3.3840], requires_grad=True)
tensor([ 1.2041, -0.2647, -2.9191, -3.3842], requires_grad=True)
tensor([ 1.2040, -0.2648, -2.9193, -3.3844], requires_grad=True)
tensor([ 1.1994, -0.2718, -2.9196, -3.3847], requires_grad=True)
tensor([ 1.1992, -0.2729, -2.9198, -3.3848], requires_grad=True)
tensor([ 1.2029, -0.2670, -2.9199, -3.3850], requires_grad=True)
tensor([ 1.2006, -0.2710, -2.9201, -3.3853], requires_grad=True)
tensor([ 1.1988, -0.2744, -2.9202, -3.3855], requires_grad=True)
tensor([ 1.2013, -0.2692, -2.9204, -3.3858], requires_grad=True)
tensor([ 1.2054, -0.2622, -2.9207, -3.3861], requires_grad=True)
tensor([ 1.2055, -0.2623, -2.9208, -3.3863], requires_grad=True)
tensor([ 1.2040, -0.2649,

tensor([ 1.1993, -0.2698, -2.9369, -3.4062], requires_grad=True)
tensor([ 1.2050, -0.2596, -2.9371, -3.4065], requires_grad=True)
tensor([ 1.1984, -0.2711, -2.9374, -3.4068], requires_grad=True)
tensor([ 1.2008, -0.2675, -2.9376, -3.4071], requires_grad=True)
tensor([ 1.2009, -0.2683, -2.9377, -3.4072], requires_grad=True)
tensor([ 1.2016, -0.2674, -2.9378, -3.4073], requires_grad=True)
tensor([ 1.2028, -0.2654, -2.9381, -3.4077], requires_grad=True)
tensor([ 1.2048, -0.2624, -2.9383, -3.4079], requires_grad=True)
tensor([ 1.2043, -0.2627, -2.9384, -3.4080], requires_grad=True)
tensor([ 1.2009, -0.2681, -2.9385, -3.4081], requires_grad=True)
tensor([ 1.2019, -0.2665, -2.9386, -3.4082], requires_grad=True)
tensor([ 1.1998, -0.2705, -2.9386, -3.4083], requires_grad=True)
tensor([ 1.1992, -0.2715, -2.9388, -3.4085], requires_grad=True)
tensor([ 1.2000, -0.2701, -2.9389, -3.4086], requires_grad=True)
tensor([ 1.1965, -0.2761, -2.9390, -3.4087], requires_grad=True)
tensor([ 1.1986, -0.2728,

tensor([ 1.1969, -0.2726, -2.9545, -3.4265], requires_grad=True)
tensor([ 1.1974, -0.2727, -2.9546, -3.4266], requires_grad=True)
tensor([ 1.1977, -0.2723, -2.9547, -3.4267], requires_grad=True)
tensor([ 1.1960, -0.2755, -2.9549, -3.4269], requires_grad=True)
tensor([ 1.1970, -0.2744, -2.9549, -3.4269], requires_grad=True)
tensor([ 1.1998, -0.2699, -2.9552, -3.4272], requires_grad=True)
tensor([ 1.2013, -0.2671, -2.9553, -3.4273], requires_grad=True)
tensor([ 1.2029, -0.2641, -2.9555, -3.4275], requires_grad=True)
tensor([ 1.2052, -0.2607, -2.9555, -3.4276], requires_grad=True)
tensor([ 1.2044, -0.2616, -2.9557, -3.4277], requires_grad=True)
tensor([ 1.2042, -0.2621, -2.9558, -3.4278], requires_grad=True)
tensor([ 1.2020, -0.2659, -2.9559, -3.4280], requires_grad=True)
tensor([ 1.2016, -0.2663, -2.9560, -3.4281], requires_grad=True)
tensor([ 1.2006, -0.2683, -2.9562, -3.4283], requires_grad=True)
tensor([ 1.2024, -0.2657, -2.9563, -3.4284], requires_grad=True)
tensor([ 1.2055, -0.2603,

tensor([ 1.1977, -0.2738, -2.9714, -3.4470], requires_grad=True)
tensor([ 1.1958, -0.2768, -2.9715, -3.4472], requires_grad=True)
tensor([ 1.1964, -0.2759, -2.9716, -3.4474], requires_grad=True)
tensor([ 1.1952, -0.2783, -2.9717, -3.4475], requires_grad=True)
tensor([ 1.1979, -0.2731, -2.9718, -3.4476], requires_grad=True)
tensor([ 1.1979, -0.2726, -2.9719, -3.4477], requires_grad=True)
tensor([ 1.1982, -0.2721, -2.9720, -3.4479], requires_grad=True)
tensor([ 1.1968, -0.2746, -2.9722, -3.4480], requires_grad=True)
tensor([ 1.1956, -0.2770, -2.9724, -3.4482], requires_grad=True)
tensor([ 1.1973, -0.2740, -2.9725, -3.4484], requires_grad=True)
tensor([ 1.1957, -0.2756, -2.9725, -3.4486], requires_grad=True)
tensor([ 1.1910, -0.2826, -2.9727, -3.4487], requires_grad=True)
tensor([ 1.1950, -0.2753, -2.9729, -3.4490], requires_grad=True)
tensor([ 1.1961, -0.2718, -2.9729, -3.4491], requires_grad=True)
tensor([ 1.1950, -0.2730, -2.9731, -3.4494], requires_grad=True)
tensor([ 1.1978, -0.2694,

tensor([ 1.2008, -0.2694, -2.9862, -3.4649], requires_grad=True)
tensor([ 1.1986, -0.2736, -2.9862, -3.4650], requires_grad=True)
tensor([ 1.1973, -0.2757, -2.9864, -3.4652], requires_grad=True)
tensor([ 1.1981, -0.2742, -2.9865, -3.4653], requires_grad=True)
tensor([ 1.1996, -0.2713, -2.9865, -3.4654], requires_grad=True)
tensor([ 1.2009, -0.2693, -2.9866, -3.4655], requires_grad=True)
tensor([ 1.2010, -0.2687, -2.9867, -3.4656], requires_grad=True)
tensor([ 1.2003, -0.2711, -2.9868, -3.4657], requires_grad=True)
tensor([ 1.2002, -0.2698, -2.9869, -3.4658], requires_grad=True)
tensor([ 1.1987, -0.2720, -2.9870, -3.4659], requires_grad=True)
tensor([ 1.1967, -0.2756, -2.9871, -3.4660], requires_grad=True)
tensor([ 1.1980, -0.2741, -2.9872, -3.4661], requires_grad=True)
tensor([ 1.2022, -0.2672, -2.9873, -3.4662], requires_grad=True)
tensor([ 1.2015, -0.2682, -2.9874, -3.4663], requires_grad=True)
tensor([ 1.2053, -0.2615, -2.9876, -3.4666], requires_grad=True)
tensor([ 1.2039, -0.2639,

tensor([ 1.2085, -0.2600, -3.0000, -3.4813], requires_grad=True)
tensor([ 1.2053, -0.2650, -3.0002, -3.4814], requires_grad=True)
tensor([ 1.2060, -0.2637, -3.0002, -3.4815], requires_grad=True)
tensor([ 1.2045, -0.2660, -3.0003, -3.4815], requires_grad=True)
tensor([ 1.2051, -0.2653, -3.0003, -3.4816], requires_grad=True)
tensor([ 1.2052, -0.2656, -3.0004, -3.4817], requires_grad=True)
tensor([ 1.2020, -0.2713, -3.0005, -3.4818], requires_grad=True)
tensor([ 1.2024, -0.2701, -3.0006, -3.4820], requires_grad=True)
tensor([ 1.2016, -0.2713, -3.0007, -3.4821], requires_grad=True)
tensor([ 1.2019, -0.2705, -3.0008, -3.4823], requires_grad=True)
tensor([ 1.2012, -0.2715, -3.0009, -3.4824], requires_grad=True)
tensor([ 1.2004, -0.2724, -3.0010, -3.4825], requires_grad=True)
tensor([ 1.1994, -0.2739, -3.0011, -3.4826], requires_grad=True)
tensor([ 1.2037, -0.2663, -3.0012, -3.4828], requires_grad=True)
tensor([ 1.2026, -0.2677, -3.0014, -3.4830], requires_grad=True)
tensor([ 1.2018, -0.2687,

tensor([ 1.2028, -0.2705, -3.0142, -3.4982], requires_grad=True)
tensor([ 1.2022, -0.2716, -3.0143, -3.4983], requires_grad=True)
tensor([ 1.2025, -0.2710, -3.0145, -3.4985], requires_grad=True)
tensor([ 1.2018, -0.2723, -3.0146, -3.4986], requires_grad=True)
tensor([ 1.2008, -0.2734, -3.0147, -3.4987], requires_grad=True)
tensor([ 1.1982, -0.2780, -3.0148, -3.4989], requires_grad=True)
tensor([ 1.1989, -0.2767, -3.0149, -3.4990], requires_grad=True)
tensor([ 1.2018, -0.2720, -3.0151, -3.4992], requires_grad=True)
tensor([ 1.1974, -0.2789, -3.0153, -3.4994], requires_grad=True)
tensor([ 1.1996, -0.2758, -3.0153, -3.4994], requires_grad=True)
tensor([ 1.1986, -0.2777, -3.0155, -3.4996], requires_grad=True)
tensor([ 1.1990, -0.2772, -3.0156, -3.4997], requires_grad=True)
tensor([ 1.1997, -0.2758, -3.0156, -3.4997], requires_grad=True)
tensor([ 1.2025, -0.2709, -3.0157, -3.4998], requires_grad=True)
tensor([ 1.2047, -0.2675, -3.0158, -3.4999], requires_grad=True)
tensor([ 1.2059, -0.2662,

tensor([ 1.2043, -0.2640, -3.0284, -3.5144], requires_grad=True)
tensor([ 1.2008, -0.2697, -3.0285, -3.5145], requires_grad=True)
tensor([ 1.2020, -0.2680, -3.0286, -3.5146], requires_grad=True)
tensor([ 1.2029, -0.2667, -3.0286, -3.5147], requires_grad=True)
tensor([ 1.2007, -0.2699, -3.0287, -3.5148], requires_grad=True)
tensor([ 1.2043, -0.2632, -3.0288, -3.5149], requires_grad=True)
tensor([ 1.2018, -0.2677, -3.0289, -3.5150], requires_grad=True)
tensor([ 1.2036, -0.2645, -3.0290, -3.5152], requires_grad=True)
tensor([ 1.2045, -0.2627, -3.0291, -3.5153], requires_grad=True)
tensor([ 1.2046, -0.2621, -3.0292, -3.5153], requires_grad=True)
tensor([ 1.2040, -0.2625, -3.0293, -3.5154], requires_grad=True)
tensor([ 1.2036, -0.2633, -3.0294, -3.5155], requires_grad=True)
tensor([ 1.1993, -0.2699, -3.0295, -3.5156], requires_grad=True)
tensor([ 1.2006, -0.2676, -3.0296, -3.5157], requires_grad=True)
tensor([ 1.2031, -0.2643, -3.0297, -3.5158], requires_grad=True)
tensor([ 1.2042, -0.2625,

tensor([ 1.2023, -0.2675, -3.0405, -3.5283], requires_grad=True)
tensor([ 1.2031, -0.2651, -3.0405, -3.5283], requires_grad=True)
tensor([ 1.2015, -0.2684, -3.0406, -3.5284], requires_grad=True)
tensor([ 1.2001, -0.2709, -3.0408, -3.5286], requires_grad=True)
tensor([ 1.2024, -0.2674, -3.0409, -3.5287], requires_grad=True)
tensor([ 1.2020, -0.2683, -3.0410, -3.5288], requires_grad=True)
tensor([ 1.2032, -0.2668, -3.0411, -3.5290], requires_grad=True)
tensor([ 1.2024, -0.2688, -3.0412, -3.5291], requires_grad=True)
tensor([ 1.2063, -0.2614, -3.0414, -3.5293], requires_grad=True)
tensor([ 1.2049, -0.2638, -3.0415, -3.5294], requires_grad=True)
tensor([ 1.2042, -0.2655, -3.0415, -3.5294], requires_grad=True)
tensor([ 1.2048, -0.2646, -3.0417, -3.5297], requires_grad=True)
tensor([ 1.2011, -0.2709, -3.0418, -3.5298], requires_grad=True)
tensor([ 1.2022, -0.2685, -3.0419, -3.5299], requires_grad=True)
tensor([ 1.2028, -0.2677, -3.0420, -3.5301], requires_grad=True)
tensor([ 1.2037, -0.2655,

tensor([ 1.1975, -0.2760, -3.0533, -3.5432], requires_grad=True)
tensor([ 1.2005, -0.2703, -3.0535, -3.5434], requires_grad=True)
tensor([ 1.1988, -0.2740, -3.0536, -3.5435], requires_grad=True)
tensor([ 1.1996, -0.2726, -3.0536, -3.5435], requires_grad=True)
tensor([ 1.2000, -0.2723, -3.0537, -3.5436], requires_grad=True)
tensor([ 1.2018, -0.2685, -3.0538, -3.5438], requires_grad=True)
tensor([ 1.2038, -0.2656, -3.0540, -3.5440], requires_grad=True)
tensor([ 1.2030, -0.2666, -3.0541, -3.5441], requires_grad=True)
tensor([ 1.1994, -0.2735, -3.0542, -3.5441], requires_grad=True)
tensor([ 1.1995, -0.2732, -3.0542, -3.5442], requires_grad=True)
tensor([ 1.1988, -0.2742, -3.0543, -3.5443], requires_grad=True)
tensor([ 1.2022, -0.2685, -3.0544, -3.5444], requires_grad=True)
tensor([ 1.2017, -0.2689, -3.0544, -3.5445], requires_grad=True)
tensor([ 1.2033, -0.2659, -3.0545, -3.5446], requires_grad=True)
tensor([ 1.2014, -0.2692, -3.0546, -3.5447], requires_grad=True)
tensor([ 1.2017, -0.2689,

tensor([ 1.1960, -0.2748, -3.0651, -3.5569], requires_grad=True)
tensor([ 1.1968, -0.2732, -3.0651, -3.5570], requires_grad=True)
tensor([ 1.1957, -0.2754, -3.0652, -3.5570], requires_grad=True)
tensor([ 1.1996, -0.2693, -3.0653, -3.5572], requires_grad=True)
tensor([ 1.1983, -0.2711, -3.0653, -3.5572], requires_grad=True)
tensor([ 1.2013, -0.2658, -3.0654, -3.5573], requires_grad=True)
tensor([ 1.2020, -0.2641, -3.0654, -3.5573], requires_grad=True)
tensor([ 1.2044, -0.2601, -3.0655, -3.5574], requires_grad=True)
tensor([ 1.2024, -0.2638, -3.0656, -3.5575], requires_grad=True)
tensor([ 1.1982, -0.2707, -3.0657, -3.5576], requires_grad=True)
tensor([ 1.1992, -0.2688, -3.0658, -3.5577], requires_grad=True)
tensor([ 1.2011, -0.2662, -3.0659, -3.5578], requires_grad=True)
tensor([ 1.2021, -0.2655, -3.0659, -3.5579], requires_grad=True)
tensor([ 1.1994, -0.2702, -3.0661, -3.5580], requires_grad=True)
tensor([ 1.1999, -0.2703, -3.0661, -3.5580], requires_grad=True)
tensor([ 1.1999, -0.2697,

tensor([ 1.1998, -0.2725, -3.0768, -3.5703], requires_grad=True)
tensor([ 1.2004, -0.2723, -3.0768, -3.5703], requires_grad=True)
tensor([ 1.2010, -0.2709, -3.0769, -3.5704], requires_grad=True)
tensor([ 1.2000, -0.2733, -3.0769, -3.5704], requires_grad=True)
tensor([ 1.2016, -0.2710, -3.0770, -3.5705], requires_grad=True)
tensor([ 1.2022, -0.2704, -3.0771, -3.5706], requires_grad=True)
tensor([ 1.2022, -0.2705, -3.0772, -3.5707], requires_grad=True)
tensor([ 1.2032, -0.2684, -3.0772, -3.5708], requires_grad=True)
tensor([ 1.2024, -0.2694, -3.0773, -3.5708], requires_grad=True)
tensor([ 1.2005, -0.2717, -3.0773, -3.5709], requires_grad=True)
tensor([ 1.2000, -0.2725, -3.0774, -3.5710], requires_grad=True)
tensor([ 1.2004, -0.2717, -3.0775, -3.5711], requires_grad=True)
tensor([ 1.1975, -0.2762, -3.0776, -3.5713], requires_grad=True)
tensor([ 1.1992, -0.2735, -3.0777, -3.5713], requires_grad=True)
tensor([ 1.2007, -0.2720, -3.0777, -3.5713], requires_grad=True)
tensor([ 1.2022, -0.2695,

tensor([ 1.1984, -0.2686, -3.0868, -3.5820], requires_grad=True)
tensor([ 1.1998, -0.2665, -3.0868, -3.5820], requires_grad=True)
tensor([ 1.1997, -0.2664, -3.0868, -3.5820], requires_grad=True)
tensor([ 1.1985, -0.2690, -3.0869, -3.5821], requires_grad=True)
tensor([ 1.1992, -0.2685, -3.0869, -3.5821], requires_grad=True)
tensor([ 1.2006, -0.2664, -3.0870, -3.5822], requires_grad=True)
tensor([ 1.2013, -0.2654, -3.0870, -3.5822], requires_grad=True)
tensor([ 1.1972, -0.2722, -3.0872, -3.5824], requires_grad=True)
tensor([ 1.1987, -0.2692, -3.0873, -3.5825], requires_grad=True)
tensor([ 1.1956, -0.2743, -3.0874, -3.5826], requires_grad=True)
tensor([ 1.1974, -0.2711, -3.0873, -3.5826], requires_grad=True)
tensor([ 1.2002, -0.2664, -3.0874, -3.5827], requires_grad=True)
tensor([ 1.1960, -0.2744, -3.0876, -3.5829], requires_grad=True)
tensor([ 1.2001, -0.2677, -3.0877, -3.5830], requires_grad=True)
tensor([ 1.1993, -0.2686, -3.0877, -3.5830], requires_grad=True)
tensor([ 1.1995, -0.2683,

tensor([ 1.2041, -0.2660, -3.0965, -3.5931], requires_grad=True)
tensor([ 1.2039, -0.2668, -3.0965, -3.5931], requires_grad=True)
tensor([ 1.2020, -0.2704, -3.0965, -3.5932], requires_grad=True)
tensor([ 1.2037, -0.2678, -3.0965, -3.5932], requires_grad=True)
tensor([ 1.2053, -0.2653, -3.0967, -3.5934], requires_grad=True)
tensor([ 1.2039, -0.2680, -3.0968, -3.5935], requires_grad=True)
tensor([ 1.2042, -0.2670, -3.0968, -3.5935], requires_grad=True)
tensor([ 1.2037, -0.2680, -3.0969, -3.5936], requires_grad=True)
tensor([ 1.2022, -0.2704, -3.0969, -3.5937], requires_grad=True)
tensor([ 1.2003, -0.2739, -3.0970, -3.5937], requires_grad=True)
tensor([ 1.1987, -0.2768, -3.0971, -3.5938], requires_grad=True)
tensor([ 1.1998, -0.2746, -3.0971, -3.5938], requires_grad=True)
tensor([ 1.2033, -0.2689, -3.0971, -3.5939], requires_grad=True)
tensor([ 1.2039, -0.2679, -3.0972, -3.5939], requires_grad=True)
tensor([ 1.2020, -0.2705, -3.0972, -3.5940], requires_grad=True)
tensor([ 1.2031, -0.2689,

tensor([ 1.2011, -0.2701, -3.1062, -3.6042], requires_grad=True)
tensor([ 1.2013, -0.2694, -3.1063, -3.6043], requires_grad=True)
tensor([ 1.2019, -0.2686, -3.1063, -3.6043], requires_grad=True)
tensor([ 1.1995, -0.2721, -3.1064, -3.6045], requires_grad=True)
tensor([ 1.1989, -0.2727, -3.1065, -3.6045], requires_grad=True)
tensor([ 1.2015, -0.2682, -3.1066, -3.6047], requires_grad=True)
tensor([ 1.2010, -0.2694, -3.1068, -3.6048], requires_grad=True)
tensor([ 1.2008, -0.2697, -3.1069, -3.6049], requires_grad=True)
tensor([ 1.2021, -0.2678, -3.1069, -3.6049], requires_grad=True)
tensor([ 1.2035, -0.2652, -3.1069, -3.6050], requires_grad=True)
tensor([ 1.2028, -0.2671, -3.1069, -3.6050], requires_grad=True)
tensor([ 1.2003, -0.2713, -3.1070, -3.6051], requires_grad=True)
tensor([ 1.2020, -0.2689, -3.1071, -3.6052], requires_grad=True)
tensor([ 1.2006, -0.2712, -3.1072, -3.6053], requires_grad=True)
tensor([ 1.2003, -0.2720, -3.1073, -3.6054], requires_grad=True)
tensor([ 1.2002, -0.2725,

tensor([ 1.2014, -0.2669, -3.1149, -3.6141], requires_grad=True)
tensor([ 1.2024, -0.2654, -3.1148, -3.6141], requires_grad=True)
tensor([ 1.2028, -0.2650, -3.1149, -3.6142], requires_grad=True)
tensor([ 1.2024, -0.2659, -3.1149, -3.6143], requires_grad=True)
tensor([ 1.2016, -0.2668, -3.1150, -3.6143], requires_grad=True)
tensor([ 1.2027, -0.2647, -3.1151, -3.6144], requires_grad=True)
tensor([ 1.2031, -0.2646, -3.1151, -3.6144], requires_grad=True)
tensor([ 1.2000, -0.2697, -3.1152, -3.6146], requires_grad=True)
tensor([ 1.1990, -0.2717, -3.1153, -3.6147], requires_grad=True)
tensor([ 1.2007, -0.2686, -3.1154, -3.6148], requires_grad=True)
tensor([ 1.1995, -0.2702, -3.1155, -3.6149], requires_grad=True)
tensor([ 1.1996, -0.2697, -3.1156, -3.6150], requires_grad=True)
tensor([ 1.2006, -0.2677, -3.1156, -3.6151], requires_grad=True)
tensor([ 1.2041, -0.2620, -3.1158, -3.6153], requires_grad=True)
tensor([ 1.2016, -0.2666, -3.1159, -3.6154], requires_grad=True)
tensor([ 1.2005, -0.2687,

tensor([ 1.2023, -0.2662, -3.1240, -3.6248], requires_grad=True)
tensor([ 1.1990, -0.2719, -3.1241, -3.6249], requires_grad=True)
tensor([ 1.2011, -0.2689, -3.1241, -3.6250], requires_grad=True)
tensor([ 1.1997, -0.2717, -3.1242, -3.6250], requires_grad=True)
tensor([ 1.1994, -0.2720, -3.1243, -3.6250], requires_grad=True)
tensor([ 1.2024, -0.2673, -3.1243, -3.6251], requires_grad=True)
tensor([ 1.2009, -0.2696, -3.1244, -3.6252], requires_grad=True)
tensor([ 1.2017, -0.2680, -3.1245, -3.6253], requires_grad=True)
tensor([ 1.2001, -0.2703, -3.1246, -3.6254], requires_grad=True)
tensor([ 1.2017, -0.2679, -3.1247, -3.6255], requires_grad=True)
tensor([ 1.2015, -0.2684, -3.1248, -3.6256], requires_grad=True)
tensor([ 1.2007, -0.2691, -3.1248, -3.6256], requires_grad=True)
tensor([ 1.2025, -0.2656, -3.1249, -3.6257], requires_grad=True)
tensor([ 1.2036, -0.2633, -3.1250, -3.6258], requires_grad=True)
tensor([ 1.2012, -0.2674, -3.1250, -3.6259], requires_grad=True)
tensor([ 1.2007, -0.2679,

tensor([ 1.1982, -0.2696, -3.1323, -3.6345], requires_grad=True)
tensor([ 1.1989, -0.2684, -3.1324, -3.6346], requires_grad=True)
tensor([ 1.2020, -0.2638, -3.1323, -3.6345], requires_grad=True)
tensor([ 1.2010, -0.2657, -3.1324, -3.6346], requires_grad=True)
tensor([ 1.1967, -0.2723, -3.1325, -3.6346], requires_grad=True)
tensor([ 1.1998, -0.2670, -3.1326, -3.6348], requires_grad=True)
tensor([ 1.2012, -0.2649, -3.1327, -3.6349], requires_grad=True)
tensor([ 1.2028, -0.2620, -3.1328, -3.6350], requires_grad=True)
tensor([ 1.2018, -0.2635, -3.1329, -3.6350], requires_grad=True)
tensor([ 1.1989, -0.2684, -3.1329, -3.6350], requires_grad=True)
tensor([ 1.1995, -0.2674, -3.1330, -3.6351], requires_grad=True)
tensor([ 1.2024, -0.2628, -3.1331, -3.6352], requires_grad=True)
tensor([ 1.2003, -0.2669, -3.1330, -3.6352], requires_grad=True)
tensor([ 1.2040, -0.2607, -3.1331, -3.6353], requires_grad=True)
tensor([ 1.2031, -0.2618, -3.1332, -3.6353], requires_grad=True)
tensor([ 1.2009, -0.2655,

tensor([ 1.2024, -0.2641, -3.1403, -3.6432], requires_grad=True)
tensor([ 1.2056, -0.2580, -3.1405, -3.6432], requires_grad=True)
tensor([ 1.2051, -0.2589, -3.1406, -3.6433], requires_grad=True)
tensor([ 1.2049, -0.2598, -3.1407, -3.6434], requires_grad=True)
tensor([ 1.2039, -0.2615, -3.1408, -3.6435], requires_grad=True)
tensor([ 1.1997, -0.2690, -3.1409, -3.6436], requires_grad=True)
tensor([ 1.1978, -0.2727, -3.1409, -3.6436], requires_grad=True)
tensor([ 1.1998, -0.2688, -3.1410, -3.6437], requires_grad=True)
tensor([ 1.1994, -0.2699, -3.1410, -3.6436], requires_grad=True)
tensor([ 1.2015, -0.2666, -3.1411, -3.6437], requires_grad=True)
tensor([ 1.2023, -0.2653, -3.1411, -3.6437], requires_grad=True)
tensor([ 1.2026, -0.2648, -3.1412, -3.6438], requires_grad=True)
tensor([ 1.2014, -0.2671, -3.1413, -3.6439], requires_grad=True)
tensor([ 1.1989, -0.2714, -3.1414, -3.6440], requires_grad=True)
tensor([ 1.1990, -0.2713, -3.1415, -3.6441], requires_grad=True)
tensor([ 1.2005, -0.2684,

tensor([ 1.2003, -0.2704, -3.1485, -3.6520], requires_grad=True)
tensor([ 1.2018, -0.2683, -3.1486, -3.6520], requires_grad=True)
tensor([ 1.2020, -0.2679, -3.1486, -3.6521], requires_grad=True)
tensor([ 1.2006, -0.2704, -3.1487, -3.6522], requires_grad=True)
tensor([ 1.2001, -0.2717, -3.1487, -3.6522], requires_grad=True)
tensor([ 1.2030, -0.2674, -3.1486, -3.6521], requires_grad=True)
tensor([ 1.2033, -0.2671, -3.1487, -3.6522], requires_grad=True)
tensor([ 1.2045, -0.2648, -3.1487, -3.6522], requires_grad=True)
tensor([ 1.2050, -0.2643, -3.1488, -3.6522], requires_grad=True)
tensor([ 1.2024, -0.2685, -3.1489, -3.6524], requires_grad=True)
tensor([ 1.2026, -0.2681, -3.1490, -3.6525], requires_grad=True)
tensor([ 1.2034, -0.2671, -3.1491, -3.6526], requires_grad=True)
tensor([ 1.2028, -0.2683, -3.1491, -3.6526], requires_grad=True)
tensor([ 1.2037, -0.2668, -3.1492, -3.6528], requires_grad=True)
tensor([ 1.2037, -0.2668, -3.1493, -3.6528], requires_grad=True)
tensor([ 1.2017, -0.2701,

tensor([ 1.2059, -0.2613, -3.1550, -3.6592], requires_grad=True)
tensor([ 1.2049, -0.2632, -3.1551, -3.6593], requires_grad=True)
tensor([ 1.2057, -0.2622, -3.1551, -3.6593], requires_grad=True)
tensor([ 1.2013, -0.2693, -3.1552, -3.6594], requires_grad=True)
tensor([ 1.2053, -0.2629, -3.1553, -3.6595], requires_grad=True)
tensor([ 1.2022, -0.2685, -3.1554, -3.6596], requires_grad=True)
tensor([ 1.2006, -0.2708, -3.1554, -3.6597], requires_grad=True)
tensor([ 1.2008, -0.2705, -3.1554, -3.6597], requires_grad=True)
tensor([ 1.2002, -0.2721, -3.1555, -3.6597], requires_grad=True)
tensor([ 1.1985, -0.2750, -3.1556, -3.6598], requires_grad=True)
tensor([ 1.2001, -0.2722, -3.1557, -3.6599], requires_grad=True)
tensor([ 1.2011, -0.2706, -3.1558, -3.6600], requires_grad=True)
tensor([ 1.2018, -0.2689, -3.1559, -3.6600], requires_grad=True)
tensor([ 1.2031, -0.2666, -3.1559, -3.6600], requires_grad=True)
tensor([ 1.2003, -0.2716, -3.1560, -3.6601], requires_grad=True)
tensor([ 1.2029, -0.2671,

tensor([ 1.2012, -0.2671, -3.1629, -3.6675], requires_grad=True)
tensor([ 1.2031, -0.2643, -3.1629, -3.6676], requires_grad=True)
tensor([ 1.2029, -0.2644, -3.1630, -3.6676], requires_grad=True)
tensor([ 1.2009, -0.2678, -3.1630, -3.6676], requires_grad=True)
tensor([ 1.1998, -0.2688, -3.1630, -3.6676], requires_grad=True)
tensor([ 1.1979, -0.2730, -3.1630, -3.6675], requires_grad=True)
tensor([ 1.1967, -0.2746, -3.1629, -3.6675], requires_grad=True)
tensor([ 1.1988, -0.2708, -3.1630, -3.6676], requires_grad=True)
tensor([ 1.1996, -0.2695, -3.1630, -3.6677], requires_grad=True)
tensor([ 1.2007, -0.2683, -3.1631, -3.6678], requires_grad=True)
tensor([ 1.2004, -0.2681, -3.1632, -3.6679], requires_grad=True)
tensor([ 1.2018, -0.2657, -3.1633, -3.6680], requires_grad=True)
tensor([ 1.2019, -0.2656, -3.1633, -3.6680], requires_grad=True)
tensor([ 1.2027, -0.2644, -3.1634, -3.6682], requires_grad=True)
tensor([ 1.2016, -0.2665, -3.1635, -3.6682], requires_grad=True)
tensor([ 1.2005, -0.2684,

tensor([ 1.2057, -0.2634, -3.1691, -3.6746], requires_grad=True)
tensor([ 1.2074, -0.2598, -3.1692, -3.6746], requires_grad=True)
tensor([ 1.2071, -0.2605, -3.1693, -3.6747], requires_grad=True)
tensor([ 1.2062, -0.2625, -3.1693, -3.6748], requires_grad=True)
tensor([ 1.2049, -0.2646, -3.1694, -3.6748], requires_grad=True)
tensor([ 1.2019, -0.2698, -3.1695, -3.6750], requires_grad=True)
tensor([ 1.1996, -0.2732, -3.1696, -3.6750], requires_grad=True)
tensor([ 1.2029, -0.2678, -3.1697, -3.6751], requires_grad=True)
tensor([ 1.2013, -0.2699, -3.1698, -3.6752], requires_grad=True)
tensor([ 1.2027, -0.2675, -3.1698, -3.6753], requires_grad=True)
tensor([ 1.2008, -0.2704, -3.1699, -3.6753], requires_grad=True)
tensor([ 1.2003, -0.2713, -3.1699, -3.6754], requires_grad=True)
tensor([ 1.1999, -0.2718, -3.1699, -3.6754], requires_grad=True)
tensor([ 1.1992, -0.2733, -3.1700, -3.6755], requires_grad=True)
tensor([ 1.1983, -0.2749, -3.1701, -3.6756], requires_grad=True)
tensor([ 1.1990, -0.2740,

tensor([ 1.1969, -0.2730, -3.1759, -3.6811], requires_grad=True)
tensor([ 1.1960, -0.2753, -3.1759, -3.6811], requires_grad=True)
tensor([ 1.1990, -0.2702, -3.1759, -3.6811], requires_grad=True)
tensor([ 1.2009, -0.2672, -3.1760, -3.6812], requires_grad=True)
tensor([ 1.2002, -0.2681, -3.1760, -3.6813], requires_grad=True)
tensor([ 1.2046, -0.2611, -3.1760, -3.6813], requires_grad=True)
tensor([ 1.2025, -0.2651, -3.1760, -3.6813], requires_grad=True)
tensor([ 1.2018, -0.2662, -3.1761, -3.6814], requires_grad=True)
tensor([ 1.2019, -0.2658, -3.1762, -3.6815], requires_grad=True)
tensor([ 1.2007, -0.2677, -3.1762, -3.6816], requires_grad=True)
tensor([ 1.2023, -0.2645, -3.1763, -3.6816], requires_grad=True)
tensor([ 1.2022, -0.2646, -3.1764, -3.6817], requires_grad=True)
tensor([ 1.2013, -0.2656, -3.1764, -3.6817], requires_grad=True)
tensor([ 1.2013, -0.2660, -3.1764, -3.6817], requires_grad=True)
tensor([ 1.2026, -0.2638, -3.1765, -3.6818], requires_grad=True)
tensor([ 1.2000, -0.2680,

tensor([ 1.2030, -0.2648, -3.1817, -3.6879], requires_grad=True)
tensor([ 1.2039, -0.2641, -3.1817, -3.6879], requires_grad=True)
tensor([ 1.2066, -0.2596, -3.1817, -3.6880], requires_grad=True)
tensor([ 1.2065, -0.2600, -3.1818, -3.6880], requires_grad=True)
tensor([ 1.2041, -0.2637, -3.1818, -3.6881], requires_grad=True)
tensor([ 1.2052, -0.2619, -3.1819, -3.6881], requires_grad=True)
tensor([ 1.2041, -0.2638, -3.1819, -3.6882], requires_grad=True)
tensor([ 1.2039, -0.2643, -3.1819, -3.6882], requires_grad=True)
tensor([ 1.2047, -0.2629, -3.1819, -3.6882], requires_grad=True)
tensor([ 1.2032, -0.2657, -3.1820, -3.6883], requires_grad=True)
tensor([ 1.2023, -0.2673, -3.1821, -3.6883], requires_grad=True)
tensor([ 1.2054, -0.2626, -3.1821, -3.6884], requires_grad=True)
tensor([ 1.2029, -0.2669, -3.1822, -3.6884], requires_grad=True)
tensor([ 1.2061, -0.2620, -3.1822, -3.6885], requires_grad=True)
tensor([ 1.2026, -0.2678, -3.1822, -3.6885], requires_grad=True)
tensor([ 1.2028, -0.2679,

tensor([ 1.2044, -0.2651, -3.1878, -3.6951], requires_grad=True)
tensor([ 1.2032, -0.2670, -3.1878, -3.6951], requires_grad=True)
tensor([ 1.2008, -0.2716, -3.1879, -3.6951], requires_grad=True)
tensor([ 1.1999, -0.2722, -3.1878, -3.6951], requires_grad=True)
tensor([ 1.2007, -0.2710, -3.1879, -3.6952], requires_grad=True)
tensor([ 1.2009, -0.2707, -3.1879, -3.6952], requires_grad=True)
tensor([ 1.2011, -0.2709, -3.1880, -3.6953], requires_grad=True)
tensor([ 1.2022, -0.2692, -3.1880, -3.6954], requires_grad=True)
tensor([ 1.2020, -0.2701, -3.1880, -3.6953], requires_grad=True)
tensor([ 1.2035, -0.2670, -3.1880, -3.6953], requires_grad=True)
tensor([ 1.2030, -0.2680, -3.1880, -3.6954], requires_grad=True)
tensor([ 1.2019, -0.2700, -3.1880, -3.6954], requires_grad=True)
tensor([ 1.2061, -0.2626, -3.1881, -3.6956], requires_grad=True)
tensor([ 1.2065, -0.2621, -3.1882, -3.6956], requires_grad=True)
tensor([ 1.2058, -0.2632, -3.1882, -3.6956], requires_grad=True)
tensor([ 1.2063, -0.2625,

tensor([ 1.2008, -0.2712, -3.1940, -3.7014], requires_grad=True)
tensor([ 1.2008, -0.2714, -3.1939, -3.7014], requires_grad=True)
tensor([ 1.1995, -0.2738, -3.1940, -3.7014], requires_grad=True)
tensor([ 1.2007, -0.2715, -3.1941, -3.7014], requires_grad=True)
tensor([ 1.1994, -0.2736, -3.1941, -3.7015], requires_grad=True)
tensor([ 1.2013, -0.2703, -3.1942, -3.7016], requires_grad=True)
tensor([ 1.2026, -0.2679, -3.1942, -3.7015], requires_grad=True)
tensor([ 1.2013, -0.2703, -3.1943, -3.7016], requires_grad=True)
tensor([ 1.2011, -0.2711, -3.1943, -3.7017], requires_grad=True)
tensor([ 1.2004, -0.2716, -3.1943, -3.7017], requires_grad=True)
tensor([ 1.1993, -0.2736, -3.1944, -3.7018], requires_grad=True)
tensor([ 1.1999, -0.2716, -3.1943, -3.7017], requires_grad=True)
tensor([ 1.2010, -0.2698, -3.1944, -3.7018], requires_grad=True)
tensor([ 1.2028, -0.2671, -3.1944, -3.7018], requires_grad=True)
tensor([ 1.2013, -0.2696, -3.1944, -3.7018], requires_grad=True)
tensor([ 1.1988, -0.2739,

tensor([ 1.2048, -0.2627, -3.2000, -3.7076], requires_grad=True)
tensor([ 1.2027, -0.2670, -3.2001, -3.7076], requires_grad=True)
tensor([ 1.2026, -0.2676, -3.2001, -3.7077], requires_grad=True)
tensor([ 1.2023, -0.2682, -3.2002, -3.7078], requires_grad=True)
tensor([ 1.2024, -0.2675, -3.2003, -3.7078], requires_grad=True)
tensor([ 1.2043, -0.2643, -3.2003, -3.7079], requires_grad=True)
tensor([ 1.2027, -0.2676, -3.2003, -3.7078], requires_grad=True)
tensor([ 1.2010, -0.2707, -3.2003, -3.7079], requires_grad=True)
tensor([ 1.2010, -0.2716, -3.2003, -3.7078], requires_grad=True)
tensor([ 1.2033, -0.2681, -3.2004, -3.7079], requires_grad=True)
tensor([ 1.2019, -0.2706, -3.2004, -3.7079], requires_grad=True)
tensor([ 1.2016, -0.2715, -3.2005, -3.7080], requires_grad=True)
tensor([ 1.2035, -0.2679, -3.2005, -3.7080], requires_grad=True)
tensor([ 1.2044, -0.2663, -3.2006, -3.7080], requires_grad=True)
tensor([ 1.2028, -0.2687, -3.2006, -3.7081], requires_grad=True)
tensor([ 1.2027, -0.2682,

tensor([ 1.1999, -0.2699, -3.2046, -3.7130], requires_grad=True)
tensor([ 1.1982, -0.2723, -3.2047, -3.7131], requires_grad=True)
tensor([ 1.1990, -0.2714, -3.2047, -3.7131], requires_grad=True)
tensor([ 1.1968, -0.2750, -3.2048, -3.7132], requires_grad=True)
tensor([ 1.1956, -0.2767, -3.2048, -3.7132], requires_grad=True)
tensor([ 1.1965, -0.2747, -3.2048, -3.7132], requires_grad=True)
tensor([ 1.1969, -0.2739, -3.2048, -3.7132], requires_grad=True)
tensor([ 1.1972, -0.2733, -3.2048, -3.7133], requires_grad=True)
tensor([ 1.1965, -0.2745, -3.2049, -3.7134], requires_grad=True)
tensor([ 1.1988, -0.2701, -3.2049, -3.7135], requires_grad=True)
tensor([ 1.2022, -0.2643, -3.2050, -3.7136], requires_grad=True)
tensor([ 1.2016, -0.2659, -3.2050, -3.7136], requires_grad=True)
tensor([ 1.2013, -0.2658, -3.2051, -3.7137], requires_grad=True)
tensor([ 1.2014, -0.2659, -3.2052, -3.7137], requires_grad=True)
tensor([ 1.1997, -0.2685, -3.2052, -3.7138], requires_grad=True)
tensor([ 1.2012, -0.2661,

tensor([ 1.1976, -0.2736, -3.2099, -3.7188], requires_grad=True)
tensor([ 1.2010, -0.2684, -3.2099, -3.7188], requires_grad=True)
tensor([ 1.1981, -0.2726, -3.2100, -3.7190], requires_grad=True)
tensor([ 1.1986, -0.2719, -3.2099, -3.7189], requires_grad=True)
tensor([ 1.2005, -0.2688, -3.2099, -3.7189], requires_grad=True)
tensor([ 1.1980, -0.2732, -3.2100, -3.7189], requires_grad=True)
tensor([ 1.1993, -0.2708, -3.2100, -3.7190], requires_grad=True)
tensor([ 1.2002, -0.2692, -3.2101, -3.7191], requires_grad=True)
tensor([ 1.1987, -0.2719, -3.2102, -3.7192], requires_grad=True)
tensor([ 1.1982, -0.2726, -3.2102, -3.7192], requires_grad=True)
tensor([ 1.2017, -0.2667, -3.2103, -3.7193], requires_grad=True)
tensor([ 1.1990, -0.2715, -3.2103, -3.7194], requires_grad=True)
tensor([ 1.1996, -0.2697, -3.2103, -3.7193], requires_grad=True)
tensor([ 1.1977, -0.2727, -3.2104, -3.7194], requires_grad=True)
tensor([ 1.2011, -0.2669, -3.2104, -3.7194], requires_grad=True)
tensor([ 1.1995, -0.2691,

tensor([ 1.1998, -0.2725, -3.2156, -3.7247], requires_grad=True)
tensor([ 1.1992, -0.2728, -3.2156, -3.7247], requires_grad=True)
tensor([ 1.2005, -0.2701, -3.2157, -3.7248], requires_grad=True)
tensor([ 1.2008, -0.2692, -3.2157, -3.7248], requires_grad=True)
tensor([ 1.2010, -0.2692, -3.2158, -3.7249], requires_grad=True)
tensor([ 1.1991, -0.2722, -3.2158, -3.7249], requires_grad=True)
tensor([ 1.1982, -0.2732, -3.2159, -3.7250], requires_grad=True)
tensor([ 1.1976, -0.2740, -3.2159, -3.7251], requires_grad=True)
tensor([ 1.1981, -0.2732, -3.2159, -3.7251], requires_grad=True)
tensor([ 1.1984, -0.2732, -3.2158, -3.7250], requires_grad=True)
tensor([ 1.2012, -0.2688, -3.2159, -3.7251], requires_grad=True)
tensor([ 1.2014, -0.2693, -3.2159, -3.7251], requires_grad=True)
tensor([ 1.2021, -0.2685, -3.2159, -3.7251], requires_grad=True)
tensor([ 1.2010, -0.2701, -3.2159, -3.7252], requires_grad=True)
tensor([ 1.2010, -0.2706, -3.2159, -3.7252], requires_grad=True)
tensor([ 1.2041, -0.2648,

tensor([ 1.1981, -0.2744, -3.2211, -3.7302], requires_grad=True)
tensor([ 1.1983, -0.2744, -3.2212, -3.7303], requires_grad=True)
tensor([ 1.1976, -0.2747, -3.2212, -3.7304], requires_grad=True)
tensor([ 1.1997, -0.2713, -3.2213, -3.7305], requires_grad=True)
tensor([ 1.2004, -0.2702, -3.2214, -3.7305], requires_grad=True)
tensor([ 1.2012, -0.2691, -3.2214, -3.7306], requires_grad=True)
tensor([ 1.2017, -0.2683, -3.2215, -3.7306], requires_grad=True)
tensor([ 1.2008, -0.2696, -3.2214, -3.7305], requires_grad=True)
tensor([ 1.2003, -0.2706, -3.2214, -3.7306], requires_grad=True)
tensor([ 1.1983, -0.2737, -3.2214, -3.7306], requires_grad=True)
tensor([ 1.2032, -0.2659, -3.2213, -3.7306], requires_grad=True)
tensor([ 1.1998, -0.2713, -3.2214, -3.7307], requires_grad=True)
tensor([ 1.2002, -0.2707, -3.2214, -3.7308], requires_grad=True)
tensor([ 1.2015, -0.2687, -3.2214, -3.7307], requires_grad=True)
tensor([ 1.2020, -0.2681, -3.2213, -3.7307], requires_grad=True)
tensor([ 1.2012, -0.2695,

tensor([ 1.2030, -0.2687, -3.2256, -3.7363], requires_grad=True)
tensor([ 1.2035, -0.2681, -3.2257, -3.7364], requires_grad=True)
tensor([ 1.2019, -0.2704, -3.2257, -3.7363], requires_grad=True)
tensor([ 1.2030, -0.2685, -3.2257, -3.7364], requires_grad=True)
tensor([ 1.2018, -0.2707, -3.2257, -3.7364], requires_grad=True)
tensor([ 1.2032, -0.2683, -3.2258, -3.7364], requires_grad=True)
tensor([ 1.2013, -0.2707, -3.2258, -3.7365], requires_grad=True)
tensor([ 1.2010, -0.2714, -3.2259, -3.7366], requires_grad=True)
tensor([ 1.2019, -0.2700, -3.2259, -3.7367], requires_grad=True)
tensor([ 1.2037, -0.2671, -3.2260, -3.7367], requires_grad=True)
tensor([ 1.2041, -0.2665, -3.2260, -3.7368], requires_grad=True)
tensor([ 1.2042, -0.2667, -3.2261, -3.7369], requires_grad=True)
tensor([ 1.2022, -0.2703, -3.2262, -3.7370], requires_grad=True)
tensor([ 1.2018, -0.2708, -3.2262, -3.7371], requires_grad=True)
tensor([ 1.1997, -0.2749, -3.2263, -3.7371], requires_grad=True)
tensor([ 1.2002, -0.2744,

tensor([ 1.2028, -0.2647, -3.2299, -3.7420], requires_grad=True)
tensor([ 1.2054, -0.2609, -3.2299, -3.7421], requires_grad=True)
tensor([ 1.2010, -0.2689, -3.2300, -3.7421], requires_grad=True)
tensor([ 1.2000, -0.2704, -3.2300, -3.7422], requires_grad=True)
tensor([ 1.2006, -0.2703, -3.2301, -3.7422], requires_grad=True)
tensor([ 1.2022, -0.2675, -3.2301, -3.7422], requires_grad=True)
tensor([ 1.2017, -0.2684, -3.2301, -3.7422], requires_grad=True)
tensor([ 1.2019, -0.2688, -3.2301, -3.7423], requires_grad=True)
tensor([ 1.2008, -0.2703, -3.2302, -3.7423], requires_grad=True)
tensor([ 1.2030, -0.2668, -3.2303, -3.7424], requires_grad=True)
tensor([ 1.2016, -0.2690, -3.2303, -3.7425], requires_grad=True)
tensor([ 1.2019, -0.2690, -3.2304, -3.7425], requires_grad=True)
tensor([ 1.2015, -0.2701, -3.2304, -3.7426], requires_grad=True)
tensor([ 1.2031, -0.2679, -3.2305, -3.7426], requires_grad=True)
tensor([ 1.2023, -0.2694, -3.2306, -3.7427], requires_grad=True)
tensor([ 1.2027, -0.2684,

tensor([ 1.1985, -0.2744, -3.2344, -3.7464], requires_grad=True)
tensor([ 1.2003, -0.2719, -3.2343, -3.7464], requires_grad=True)
tensor([ 1.1989, -0.2740, -3.2343, -3.7464], requires_grad=True)
tensor([ 1.2018, -0.2687, -3.2344, -3.7465], requires_grad=True)
tensor([ 1.2031, -0.2666, -3.2344, -3.7465], requires_grad=True)
tensor([ 1.2017, -0.2695, -3.2345, -3.7466], requires_grad=True)
tensor([ 1.2026, -0.2680, -3.2345, -3.7467], requires_grad=True)
tensor([ 1.2016, -0.2700, -3.2345, -3.7467], requires_grad=True)
tensor([ 1.2028, -0.2685, -3.2346, -3.7468], requires_grad=True)
tensor([ 1.2021, -0.2701, -3.2345, -3.7467], requires_grad=True)
tensor([ 1.2012, -0.2716, -3.2345, -3.7468], requires_grad=True)
tensor([ 1.1991, -0.2756, -3.2346, -3.7468], requires_grad=True)
tensor([ 1.2024, -0.2699, -3.2346, -3.7469], requires_grad=True)
tensor([ 1.2033, -0.2673, -3.2346, -3.7469], requires_grad=True)
tensor([ 1.2024, -0.2685, -3.2347, -3.7469], requires_grad=True)
tensor([ 1.2021, -0.2687,

tensor([ 1.2010, -0.2693, -3.2395, -3.7510], requires_grad=True)
tensor([ 1.1997, -0.2719, -3.2395, -3.7510], requires_grad=True)
tensor([ 1.1991, -0.2732, -3.2395, -3.7509], requires_grad=True)
tensor([ 1.1994, -0.2726, -3.2396, -3.7510], requires_grad=True)
tensor([ 1.1992, -0.2727, -3.2396, -3.7510], requires_grad=True)
tensor([ 1.1976, -0.2751, -3.2396, -3.7511], requires_grad=True)
tensor([ 1.1976, -0.2744, -3.2396, -3.7511], requires_grad=True)
tensor([ 1.2004, -0.2694, -3.2397, -3.7512], requires_grad=True)
tensor([ 1.2008, -0.2691, -3.2397, -3.7513], requires_grad=True)
tensor([ 1.1991, -0.2718, -3.2397, -3.7513], requires_grad=True)
tensor([ 1.2000, -0.2702, -3.2397, -3.7513], requires_grad=True)
tensor([ 1.1987, -0.2725, -3.2397, -3.7513], requires_grad=True)
tensor([ 1.2001, -0.2702, -3.2398, -3.7513], requires_grad=True)
tensor([ 1.1993, -0.2712, -3.2399, -3.7513], requires_grad=True)
tensor([ 1.2000, -0.2698, -3.2399, -3.7514], requires_grad=True)
tensor([ 1.2009, -0.2679,

tensor([ 1.1979, -0.2729, -3.2429, -3.7553], requires_grad=True)
tensor([ 1.2005, -0.2685, -3.2430, -3.7554], requires_grad=True)
tensor([ 1.2003, -0.2685, -3.2429, -3.7554], requires_grad=True)
tensor([ 1.2007, -0.2673, -3.2429, -3.7553], requires_grad=True)
tensor([ 1.1989, -0.2702, -3.2429, -3.7554], requires_grad=True)
tensor([ 1.2006, -0.2678, -3.2429, -3.7555], requires_grad=True)
tensor([ 1.1988, -0.2710, -3.2430, -3.7555], requires_grad=True)
tensor([ 1.1999, -0.2688, -3.2430, -3.7555], requires_grad=True)
tensor([ 1.2001, -0.2683, -3.2431, -3.7556], requires_grad=True)
tensor([ 1.2004, -0.2681, -3.2431, -3.7556], requires_grad=True)
tensor([ 1.2030, -0.2640, -3.2432, -3.7557], requires_grad=True)
tensor([ 1.2026, -0.2642, -3.2431, -3.7557], requires_grad=True)
tensor([ 1.2042, -0.2616, -3.2431, -3.7557], requires_grad=True)
tensor([ 1.2025, -0.2646, -3.2431, -3.7557], requires_grad=True)
tensor([ 1.2027, -0.2650, -3.2432, -3.7557], requires_grad=True)
tensor([ 1.2055, -0.2599,

tensor([ 1.2001, -0.2687, -3.2460, -3.7592], requires_grad=True)
tensor([ 1.2002, -0.2685, -3.2460, -3.7592], requires_grad=True)
tensor([ 1.1977, -0.2726, -3.2461, -3.7592], requires_grad=True)
tensor([ 1.1980, -0.2722, -3.2461, -3.7592], requires_grad=True)
tensor([ 1.1971, -0.2740, -3.2461, -3.7592], requires_grad=True)
tensor([ 1.1986, -0.2719, -3.2462, -3.7592], requires_grad=True)
tensor([ 1.2013, -0.2679, -3.2462, -3.7593], requires_grad=True)
tensor([ 1.2028, -0.2650, -3.2463, -3.7593], requires_grad=True)
tensor([ 1.2014, -0.2676, -3.2463, -3.7593], requires_grad=True)
tensor([ 1.2018, -0.2669, -3.2464, -3.7593], requires_grad=True)
tensor([ 1.2018, -0.2675, -3.2464, -3.7593], requires_grad=True)
tensor([ 1.2010, -0.2690, -3.2464, -3.7593], requires_grad=True)
tensor([ 1.2014, -0.2682, -3.2464, -3.7594], requires_grad=True)
tensor([ 1.2032, -0.2655, -3.2465, -3.7594], requires_grad=True)
tensor([ 1.2036, -0.2650, -3.2465, -3.7595], requires_grad=True)
tensor([ 1.2030, -0.2657,

tensor([ 1.2028, -0.2655, -3.2483, -3.7622], requires_grad=True)
tensor([ 1.2013, -0.2685, -3.2484, -3.7623], requires_grad=True)
tensor([ 1.2016, -0.2687, -3.2483, -3.7623], requires_grad=True)
tensor([ 1.2008, -0.2703, -3.2483, -3.7624], requires_grad=True)
tensor([ 1.2009, -0.2699, -3.2483, -3.7624], requires_grad=True)
tensor([ 1.2016, -0.2689, -3.2483, -3.7625], requires_grad=True)
tensor([ 1.2018, -0.2682, -3.2483, -3.7625], requires_grad=True)
tensor([ 1.2019, -0.2682, -3.2484, -3.7625], requires_grad=True)
tensor([ 1.2018, -0.2685, -3.2483, -3.7624], requires_grad=True)
tensor([ 1.2018, -0.2683, -3.2484, -3.7624], requires_grad=True)
tensor([ 1.2030, -0.2666, -3.2485, -3.7624], requires_grad=True)
tensor([ 1.2036, -0.2656, -3.2485, -3.7624], requires_grad=True)
tensor([ 1.2028, -0.2668, -3.2484, -3.7624], requires_grad=True)
tensor([ 1.2003, -0.2706, -3.2485, -3.7625], requires_grad=True)
tensor([ 1.2010, -0.2699, -3.2485, -3.7625], requires_grad=True)
tensor([ 1.2025, -0.2675,

tensor([ 1.2012, -0.2686, -3.2531, -3.7667], requires_grad=True)
tensor([ 1.2008, -0.2696, -3.2530, -3.7666], requires_grad=True)
tensor([ 1.2027, -0.2664, -3.2531, -3.7667], requires_grad=True)
tensor([ 1.2036, -0.2650, -3.2532, -3.7667], requires_grad=True)
tensor([ 1.2037, -0.2647, -3.2532, -3.7667], requires_grad=True)
tensor([ 1.2042, -0.2639, -3.2533, -3.7666], requires_grad=True)
tensor([ 1.2057, -0.2617, -3.2533, -3.7666], requires_grad=True)
tensor([ 1.2053, -0.2628, -3.2533, -3.7667], requires_grad=True)
tensor([ 1.2060, -0.2614, -3.2533, -3.7666], requires_grad=True)
tensor([ 1.2049, -0.2638, -3.2533, -3.7667], requires_grad=True)
tensor([ 1.2051, -0.2638, -3.2534, -3.7668], requires_grad=True)
tensor([ 1.2051, -0.2637, -3.2535, -3.7668], requires_grad=True)
tensor([ 1.2043, -0.2651, -3.2535, -3.7668], requires_grad=True)
tensor([ 1.2062, -0.2626, -3.2534, -3.7670], requires_grad=True)
tensor([ 1.2031, -0.2676, -3.2535, -3.7670], requires_grad=True)
tensor([ 1.2008, -0.2714,

tensor([ 1.1982, -0.2705, -3.2572, -3.7704], requires_grad=True)
tensor([ 1.1988, -0.2692, -3.2572, -3.7704], requires_grad=True)
tensor([ 1.1966, -0.2723, -3.2572, -3.7705], requires_grad=True)
tensor([ 1.1954, -0.2738, -3.2573, -3.7705], requires_grad=True)
tensor([ 1.1958, -0.2735, -3.2573, -3.7705], requires_grad=True)
tensor([ 1.1986, -0.2685, -3.2573, -3.7705], requires_grad=True)
tensor([ 1.1973, -0.2713, -3.2574, -3.7706], requires_grad=True)
tensor([ 1.1979, -0.2704, -3.2575, -3.7706], requires_grad=True)
tensor([ 1.1981, -0.2701, -3.2575, -3.7706], requires_grad=True)
tensor([ 1.1989, -0.2685, -3.2575, -3.7706], requires_grad=True)
tensor([ 1.1992, -0.2685, -3.2575, -3.7706], requires_grad=True)
tensor([ 1.1996, -0.2681, -3.2575, -3.7707], requires_grad=True)
tensor([ 1.2020, -0.2646, -3.2575, -3.7707], requires_grad=True)
tensor([ 1.2012, -0.2661, -3.2576, -3.7708], requires_grad=True)
tensor([ 1.2028, -0.2629, -3.2576, -3.7708], requires_grad=True)
tensor([ 1.2017, -0.2649,

tensor([ 1.1977, -0.2719, -3.2612, -3.7741], requires_grad=True)
tensor([ 1.1984, -0.2705, -3.2612, -3.7742], requires_grad=True)
tensor([ 1.1981, -0.2717, -3.2613, -3.7741], requires_grad=True)
tensor([ 1.1974, -0.2730, -3.2614, -3.7742], requires_grad=True)
tensor([ 1.1978, -0.2719, -3.2614, -3.7741], requires_grad=True)
tensor([ 1.1968, -0.2742, -3.2614, -3.7741], requires_grad=True)
tensor([ 1.1979, -0.2726, -3.2615, -3.7742], requires_grad=True)
tensor([ 1.2010, -0.2668, -3.2615, -3.7742], requires_grad=True)
tensor([ 1.1967, -0.2742, -3.2615, -3.7743], requires_grad=True)
tensor([ 1.1973, -0.2728, -3.2615, -3.7743], requires_grad=True)
tensor([ 1.1974, -0.2720, -3.2615, -3.7743], requires_grad=True)
tensor([ 1.1956, -0.2750, -3.2616, -3.7744], requires_grad=True)
tensor([ 1.1959, -0.2747, -3.2616, -3.7745], requires_grad=True)
tensor([ 1.1986, -0.2699, -3.2616, -3.7744], requires_grad=True)
tensor([ 1.2004, -0.2675, -3.2617, -3.7745], requires_grad=True)
tensor([ 1.1999, -0.2683,

tensor([ 1.2013, -0.2681, -3.2644, -3.7787], requires_grad=True)
tensor([ 1.2005, -0.2693, -3.2644, -3.7787], requires_grad=True)
tensor([ 1.2016, -0.2675, -3.2644, -3.7788], requires_grad=True)
tensor([ 1.2009, -0.2688, -3.2645, -3.7788], requires_grad=True)
tensor([ 1.2016, -0.2678, -3.2644, -3.7789], requires_grad=True)
tensor([ 1.1989, -0.2723, -3.2644, -3.7789], requires_grad=True)
tensor([ 1.1988, -0.2724, -3.2644, -3.7790], requires_grad=True)
tensor([ 1.2006, -0.2692, -3.2645, -3.7790], requires_grad=True)
tensor([ 1.2030, -0.2651, -3.2646, -3.7790], requires_grad=True)
tensor([ 1.2001, -0.2701, -3.2646, -3.7791], requires_grad=True)
tensor([ 1.1977, -0.2739, -3.2647, -3.7792], requires_grad=True)
tensor([ 1.1966, -0.2756, -3.2647, -3.7792], requires_grad=True)
tensor([ 1.1995, -0.2713, -3.2647, -3.7793], requires_grad=True)
tensor([ 1.1964, -0.2761, -3.2648, -3.7793], requires_grad=True)
tensor([ 1.1989, -0.2721, -3.2649, -3.7793], requires_grad=True)
tensor([ 1.1995, -0.2706,

tensor([ 1.2007, -0.2712, -3.2684, -3.7832], requires_grad=True)
tensor([ 1.2015, -0.2699, -3.2684, -3.7833], requires_grad=True)
tensor([ 1.2023, -0.2687, -3.2684, -3.7833], requires_grad=True)
tensor([ 1.2011, -0.2710, -3.2685, -3.7833], requires_grad=True)
tensor([ 1.2029, -0.2681, -3.2686, -3.7834], requires_grad=True)
tensor([ 1.2029, -0.2680, -3.2686, -3.7834], requires_grad=True)
tensor([ 1.2012, -0.2701, -3.2687, -3.7834], requires_grad=True)
tensor([ 1.2017, -0.2691, -3.2687, -3.7835], requires_grad=True)
tensor([ 1.2016, -0.2688, -3.2685, -3.7834], requires_grad=True)
tensor([ 1.1993, -0.2733, -3.2686, -3.7834], requires_grad=True)
tensor([ 1.2017, -0.2688, -3.2686, -3.7834], requires_grad=True)
tensor([ 1.2014, -0.2698, -3.2685, -3.7834], requires_grad=True)
tensor([ 1.1983, -0.2751, -3.2686, -3.7835], requires_grad=True)
tensor([ 1.1996, -0.2723, -3.2687, -3.7835], requires_grad=True)
tensor([ 1.2010, -0.2699, -3.2687, -3.7836], requires_grad=True)
tensor([ 1.2016, -0.2683,

tensor([ 1.2000, -0.2701, -3.2709, -3.7863], requires_grad=True)
tensor([ 1.2011, -0.2691, -3.2708, -3.7863], requires_grad=True)
tensor([ 1.2030, -0.2663, -3.2708, -3.7864], requires_grad=True)
tensor([ 1.2031, -0.2659, -3.2708, -3.7864], requires_grad=True)
tensor([ 1.2017, -0.2680, -3.2707, -3.7865], requires_grad=True)
tensor([ 1.2009, -0.2690, -3.2707, -3.7865], requires_grad=True)
tensor([ 1.2003, -0.2703, -3.2707, -3.7865], requires_grad=True)
tensor([ 1.2003, -0.2706, -3.2707, -3.7865], requires_grad=True)
tensor([ 1.1991, -0.2724, -3.2707, -3.7866], requires_grad=True)
tensor([ 1.2011, -0.2688, -3.2707, -3.7867], requires_grad=True)
tensor([ 1.2014, -0.2687, -3.2708, -3.7867], requires_grad=True)
tensor([ 1.2003, -0.2702, -3.2708, -3.7867], requires_grad=True)
tensor([ 1.2001, -0.2702, -3.2708, -3.7868], requires_grad=True)
tensor([ 1.1990, -0.2719, -3.2708, -3.7868], requires_grad=True)
tensor([ 1.1996, -0.2706, -3.2707, -3.7868], requires_grad=True)
tensor([ 1.1996, -0.2705,

tensor([ 1.2032, -0.2663, -3.2739, -3.7901], requires_grad=True)
tensor([ 1.2039, -0.2647, -3.2739, -3.7901], requires_grad=True)
tensor([ 1.2038, -0.2651, -3.2739, -3.7901], requires_grad=True)
tensor([ 1.2023, -0.2672, -3.2740, -3.7902], requires_grad=True)
tensor([ 1.2021, -0.2673, -3.2740, -3.7902], requires_grad=True)
tensor([ 1.2028, -0.2659, -3.2740, -3.7903], requires_grad=True)
tensor([ 1.2015, -0.2679, -3.2741, -3.7903], requires_grad=True)
tensor([ 1.2011, -0.2692, -3.2741, -3.7903], requires_grad=True)
tensor([ 1.2022, -0.2671, -3.2741, -3.7903], requires_grad=True)
tensor([ 1.2020, -0.2671, -3.2741, -3.7903], requires_grad=True)
tensor([ 1.2025, -0.2657, -3.2741, -3.7903], requires_grad=True)
tensor([ 1.2028, -0.2649, -3.2741, -3.7903], requires_grad=True)
tensor([ 1.2033, -0.2641, -3.2742, -3.7903], requires_grad=True)
tensor([ 1.2020, -0.2664, -3.2743, -3.7904], requires_grad=True)
tensor([ 1.2020, -0.2660, -3.2742, -3.7903], requires_grad=True)
tensor([ 1.2040, -0.2627,

tensor([ 1.2010, -0.2731, -3.2766, -3.7924], requires_grad=True)
tensor([ 1.2016, -0.2726, -3.2766, -3.7924], requires_grad=True)
tensor([ 1.1992, -0.2764, -3.2767, -3.7924], requires_grad=True)
tensor([ 1.1997, -0.2755, -3.2768, -3.7925], requires_grad=True)
tensor([ 1.2007, -0.2741, -3.2768, -3.7925], requires_grad=True)
tensor([ 1.2016, -0.2725, -3.2768, -3.7925], requires_grad=True)
tensor([ 1.2015, -0.2725, -3.2768, -3.7925], requires_grad=True)
tensor([ 1.2002, -0.2736, -3.2768, -3.7925], requires_grad=True)
tensor([ 1.2017, -0.2710, -3.2768, -3.7925], requires_grad=True)
tensor([ 1.2000, -0.2732, -3.2769, -3.7925], requires_grad=True)
tensor([ 1.2007, -0.2723, -3.2769, -3.7926], requires_grad=True)
tensor([ 1.2004, -0.2728, -3.2769, -3.7926], requires_grad=True)
tensor([ 1.2028, -0.2687, -3.2770, -3.7926], requires_grad=True)
tensor([ 1.2025, -0.2692, -3.2771, -3.7927], requires_grad=True)
tensor([ 1.2029, -0.2682, -3.2771, -3.7927], requires_grad=True)
tensor([ 1.2009, -0.2723,

tensor([ 1.2003, -0.2712, -3.2797, -3.7951], requires_grad=True)
tensor([ 1.2005, -0.2706, -3.2797, -3.7952], requires_grad=True)
tensor([ 1.2024, -0.2675, -3.2797, -3.7952], requires_grad=True)
tensor([ 1.2036, -0.2655, -3.2798, -3.7952], requires_grad=True)
tensor([ 1.2035, -0.2660, -3.2798, -3.7953], requires_grad=True)
tensor([ 1.2023, -0.2677, -3.2798, -3.7953], requires_grad=True)
tensor([ 1.2038, -0.2653, -3.2797, -3.7952], requires_grad=True)
tensor([ 1.2015, -0.2690, -3.2798, -3.7952], requires_grad=True)
tensor([ 1.2035, -0.2662, -3.2797, -3.7952], requires_grad=True)
tensor([ 1.2042, -0.2648, -3.2798, -3.7953], requires_grad=True)
tensor([ 1.2035, -0.2671, -3.2796, -3.7952], requires_grad=True)
tensor([ 1.2043, -0.2665, -3.2796, -3.7953], requires_grad=True)
tensor([ 1.2048, -0.2654, -3.2797, -3.7953], requires_grad=True)
tensor([ 1.2041, -0.2671, -3.2797, -3.7954], requires_grad=True)
tensor([ 1.2032, -0.2686, -3.2798, -3.7955], requires_grad=True)
tensor([ 1.2027, -0.2691,

tensor([ 1.2029, -0.2676, -3.2831, -3.7991], requires_grad=True)
tensor([ 1.2039, -0.2658, -3.2832, -3.7991], requires_grad=True)
tensor([ 1.2042, -0.2649, -3.2832, -3.7991], requires_grad=True)
tensor([ 1.2014, -0.2704, -3.2833, -3.7991], requires_grad=True)
tensor([ 1.2031, -0.2673, -3.2834, -3.7991], requires_grad=True)
tensor([ 1.2026, -0.2681, -3.2834, -3.7991], requires_grad=True)
tensor([ 1.2028, -0.2684, -3.2834, -3.7992], requires_grad=True)
tensor([ 1.2023, -0.2695, -3.2833, -3.7991], requires_grad=True)
tensor([ 1.2030, -0.2688, -3.2834, -3.7992], requires_grad=True)
tensor([ 1.2028, -0.2693, -3.2835, -3.7993], requires_grad=True)
tensor([ 1.2012, -0.2724, -3.2835, -3.7993], requires_grad=True)
tensor([ 1.2025, -0.2700, -3.2835, -3.7993], requires_grad=True)
tensor([ 1.2028, -0.2697, -3.2836, -3.7993], requires_grad=True)
tensor([ 1.2020, -0.2716, -3.2836, -3.7993], requires_grad=True)
tensor([ 1.2008, -0.2742, -3.2835, -3.7992], requires_grad=True)
tensor([ 1.2024, -0.2705,

tensor([ 1.2054, -0.2636, -3.2852, -3.8016], requires_grad=True)
tensor([ 1.2051, -0.2642, -3.2852, -3.8016], requires_grad=True)
tensor([ 1.2021, -0.2695, -3.2853, -3.8016], requires_grad=True)
tensor([ 1.2046, -0.2651, -3.2853, -3.8017], requires_grad=True)
tensor([ 1.2052, -0.2644, -3.2854, -3.8018], requires_grad=True)
tensor([ 1.2038, -0.2668, -3.2855, -3.8018], requires_grad=True)
tensor([ 1.2016, -0.2701, -3.2855, -3.8019], requires_grad=True)
tensor([ 1.2014, -0.2704, -3.2856, -3.8019], requires_grad=True)
tensor([ 1.2027, -0.2682, -3.2856, -3.8019], requires_grad=True)
tensor([ 1.2001, -0.2725, -3.2857, -3.8020], requires_grad=True)
tensor([ 1.2002, -0.2726, -3.2857, -3.8020], requires_grad=True)
tensor([ 1.2025, -0.2683, -3.2858, -3.8021], requires_grad=True)
tensor([ 1.2016, -0.2696, -3.2857, -3.8021], requires_grad=True)
tensor([ 1.2011, -0.2708, -3.2857, -3.8021], requires_grad=True)
tensor([ 1.2034, -0.2668, -3.2858, -3.8022], requires_grad=True)
tensor([ 1.2031, -0.2678,

tensor([ 1.2048, -0.2683, -3.2875, -3.8045], requires_grad=True)
tensor([ 1.2033, -0.2716, -3.2875, -3.8045], requires_grad=True)
tensor([ 1.2035, -0.2711, -3.2876, -3.8045], requires_grad=True)
tensor([ 1.2041, -0.2693, -3.2876, -3.8045], requires_grad=True)
tensor([ 1.2025, -0.2715, -3.2877, -3.8046], requires_grad=True)
tensor([ 1.2037, -0.2692, -3.2876, -3.8045], requires_grad=True)
tensor([ 1.2010, -0.2742, -3.2876, -3.8045], requires_grad=True)
tensor([ 1.1996, -0.2768, -3.2877, -3.8045], requires_grad=True)
tensor([ 1.2008, -0.2744, -3.2877, -3.8045], requires_grad=True)
tensor([ 1.1997, -0.2760, -3.2877, -3.8046], requires_grad=True)
tensor([ 1.2022, -0.2715, -3.2878, -3.8046], requires_grad=True)
tensor([ 1.2036, -0.2689, -3.2878, -3.8046], requires_grad=True)
tensor([ 1.2030, -0.2701, -3.2879, -3.8047], requires_grad=True)
tensor([ 1.2047, -0.2667, -3.2878, -3.8046], requires_grad=True)
tensor([ 1.2041, -0.2681, -3.2878, -3.8047], requires_grad=True)
tensor([ 1.2057, -0.2647,

tensor([ 1.2031, -0.2645, -3.2902, -3.8071], requires_grad=True)
tensor([ 1.2025, -0.2662, -3.2902, -3.8071], requires_grad=True)
tensor([ 1.2019, -0.2672, -3.2902, -3.8072], requires_grad=True)
tensor([ 1.2033, -0.2647, -3.2902, -3.8072], requires_grad=True)
tensor([ 1.2035, -0.2638, -3.2903, -3.8072], requires_grad=True)
tensor([ 1.2022, -0.2652, -3.2903, -3.8072], requires_grad=True)
tensor([ 1.2035, -0.2629, -3.2904, -3.8072], requires_grad=True)
tensor([ 1.2032, -0.2642, -3.2904, -3.8072], requires_grad=True)
tensor([ 1.2038, -0.2638, -3.2904, -3.8072], requires_grad=True)
tensor([ 1.2035, -0.2648, -3.2903, -3.8072], requires_grad=True)
tensor([ 1.2039, -0.2641, -3.2903, -3.8072], requires_grad=True)
tensor([ 1.2011, -0.2691, -3.2903, -3.8073], requires_grad=True)
tensor([ 1.1987, -0.2732, -3.2904, -3.8073], requires_grad=True)
tensor([ 1.2009, -0.2694, -3.2904, -3.8074], requires_grad=True)
tensor([ 1.2020, -0.2678, -3.2904, -3.8074], requires_grad=True)
tensor([ 1.2038, -0.2648,

tensor([ 1.2020, -0.2659, -3.2923, -3.8093], requires_grad=True)
tensor([ 1.2007, -0.2681, -3.2923, -3.8094], requires_grad=True)
tensor([ 1.2004, -0.2691, -3.2923, -3.8094], requires_grad=True)
tensor([ 1.1997, -0.2701, -3.2924, -3.8094], requires_grad=True)
tensor([ 1.1984, -0.2715, -3.2923, -3.8094], requires_grad=True)
tensor([ 1.1980, -0.2719, -3.2923, -3.8095], requires_grad=True)
tensor([ 1.1986, -0.2711, -3.2923, -3.8094], requires_grad=True)
tensor([ 1.1978, -0.2724, -3.2923, -3.8094], requires_grad=True)
tensor([ 1.1988, -0.2711, -3.2923, -3.8094], requires_grad=True)
tensor([ 1.1974, -0.2735, -3.2924, -3.8094], requires_grad=True)
tensor([ 1.1989, -0.2706, -3.2924, -3.8095], requires_grad=True)
tensor([ 1.1970, -0.2740, -3.2925, -3.8095], requires_grad=True)
tensor([ 1.1977, -0.2723, -3.2925, -3.8095], requires_grad=True)
tensor([ 1.2008, -0.2670, -3.2926, -3.8097], requires_grad=True)
tensor([ 1.1998, -0.2690, -3.2926, -3.8097], requires_grad=True)
tensor([ 1.2010, -0.2662,

tensor([ 1.2028, -0.2703, -3.2949, -3.8124], requires_grad=True)
tensor([ 1.2031, -0.2699, -3.2950, -3.8124], requires_grad=True)
tensor([ 1.2035, -0.2694, -3.2950, -3.8124], requires_grad=True)
tensor([ 1.2046, -0.2675, -3.2951, -3.8125], requires_grad=True)
tensor([ 1.2047, -0.2671, -3.2951, -3.8125], requires_grad=True)
tensor([ 1.2066, -0.2639, -3.2951, -3.8126], requires_grad=True)
tensor([ 1.2062, -0.2655, -3.2951, -3.8125], requires_grad=True)
tensor([ 1.2081, -0.2629, -3.2951, -3.8125], requires_grad=True)
tensor([ 1.2064, -0.2663, -3.2951, -3.8125], requires_grad=True)
tensor([ 1.2063, -0.2666, -3.2951, -3.8126], requires_grad=True)
tensor([ 1.2060, -0.2668, -3.2952, -3.8126], requires_grad=True)
tensor([ 1.2050, -0.2683, -3.2953, -3.8126], requires_grad=True)
tensor([ 1.2049, -0.2684, -3.2953, -3.8127], requires_grad=True)
tensor([ 1.2020, -0.2735, -3.2953, -3.8127], requires_grad=True)
tensor([ 1.2011, -0.2750, -3.2953, -3.8127], requires_grad=True)
tensor([ 1.2013, -0.2746,

tensor([ 1.2014, -0.2692, -3.2966, -3.8140], requires_grad=True)
tensor([ 1.2014, -0.2691, -3.2967, -3.8140], requires_grad=True)
tensor([ 1.1999, -0.2720, -3.2967, -3.8139], requires_grad=True)
tensor([ 1.2020, -0.2686, -3.2967, -3.8139], requires_grad=True)
tensor([ 1.2009, -0.2702, -3.2968, -3.8140], requires_grad=True)
tensor([ 1.2011, -0.2689, -3.2967, -3.8139], requires_grad=True)
tensor([ 1.2020, -0.2680, -3.2967, -3.8139], requires_grad=True)
tensor([ 1.2014, -0.2685, -3.2967, -3.8140], requires_grad=True)
tensor([ 1.1995, -0.2722, -3.2967, -3.8140], requires_grad=True)
tensor([ 1.2010, -0.2697, -3.2968, -3.8140], requires_grad=True)
tensor([ 1.1999, -0.2716, -3.2968, -3.8141], requires_grad=True)
tensor([ 1.1973, -0.2758, -3.2968, -3.8141], requires_grad=True)
tensor([ 1.1964, -0.2770, -3.2968, -3.8141], requires_grad=True)
tensor([ 1.1974, -0.2753, -3.2969, -3.8142], requires_grad=True)
tensor([ 1.1971, -0.2754, -3.2969, -3.8141], requires_grad=True)
tensor([ 1.1978, -0.2739,

tensor([ 1.2011, -0.2703, -3.3002, -3.8172], requires_grad=True)
tensor([ 1.2008, -0.2709, -3.3002, -3.8172], requires_grad=True)
tensor([ 1.1997, -0.2731, -3.3003, -3.8172], requires_grad=True)
tensor([ 1.2006, -0.2721, -3.3003, -3.8172], requires_grad=True)
tensor([ 1.2016, -0.2702, -3.3003, -3.8172], requires_grad=True)
tensor([ 1.2016, -0.2701, -3.3003, -3.8172], requires_grad=True)
tensor([ 1.2038, -0.2666, -3.3003, -3.8173], requires_grad=True)
tensor([ 1.2034, -0.2675, -3.3003, -3.8174], requires_grad=True)
tensor([ 1.2019, -0.2701, -3.3004, -3.8174], requires_grad=True)
tensor([ 1.2015, -0.2711, -3.3005, -3.8174], requires_grad=True)
tensor([ 1.2017, -0.2712, -3.3004, -3.8174], requires_grad=True)
tensor([ 1.2018, -0.2710, -3.3005, -3.8174], requires_grad=True)
tensor([ 1.2033, -0.2682, -3.3005, -3.8173], requires_grad=True)
tensor([ 1.2015, -0.2713, -3.3005, -3.8173], requires_grad=True)
tensor([ 1.2038, -0.2680, -3.3005, -3.8173], requires_grad=True)
tensor([ 1.2025, -0.2697,

tensor([ 1.1993, -0.2740, -3.3026, -3.8193], requires_grad=True)
tensor([ 1.2006, -0.2720, -3.3025, -3.8193], requires_grad=True)
tensor([ 1.2002, -0.2720, -3.3026, -3.8192], requires_grad=True)
tensor([ 1.2002, -0.2718, -3.3025, -3.8193], requires_grad=True)
tensor([ 1.1995, -0.2730, -3.3026, -3.8194], requires_grad=True)
tensor([ 1.2013, -0.2699, -3.3026, -3.8194], requires_grad=True)
tensor([ 1.1994, -0.2727, -3.3025, -3.8193], requires_grad=True)
tensor([ 1.1997, -0.2720, -3.3025, -3.8194], requires_grad=True)
tensor([ 1.2004, -0.2709, -3.3025, -3.8194], requires_grad=True)
tensor([ 1.1996, -0.2720, -3.3025, -3.8195], requires_grad=True)
tensor([ 1.2000, -0.2705, -3.3025, -3.8194], requires_grad=True)
tensor([ 1.1994, -0.2713, -3.3025, -3.8195], requires_grad=True)
tensor([ 1.2017, -0.2671, -3.3024, -3.8194], requires_grad=True)
tensor([ 1.2018, -0.2673, -3.3025, -3.8194], requires_grad=True)
tensor([ 1.2020, -0.2663, -3.3025, -3.8194], requires_grad=True)
tensor([ 1.2023, -0.2657,

tensor([ 1.1967, -0.2751, -3.3041, -3.8212], requires_grad=True)
tensor([ 1.1972, -0.2744, -3.3042, -3.8212], requires_grad=True)
tensor([ 1.1978, -0.2735, -3.3042, -3.8212], requires_grad=True)
tensor([ 1.1949, -0.2778, -3.3042, -3.8212], requires_grad=True)
tensor([ 1.1946, -0.2785, -3.3043, -3.8212], requires_grad=True)
tensor([ 1.1987, -0.2715, -3.3043, -3.8213], requires_grad=True)
tensor([ 1.1987, -0.2712, -3.3043, -3.8214], requires_grad=True)
tensor([ 1.1983, -0.2719, -3.3043, -3.8213], requires_grad=True)
tensor([ 1.2004, -0.2688, -3.3044, -3.8212], requires_grad=True)
tensor([ 1.2004, -0.2692, -3.3044, -3.8212], requires_grad=True)
tensor([ 1.2003, -0.2692, -3.3045, -3.8213], requires_grad=True)
tensor([ 1.2013, -0.2676, -3.3044, -3.8213], requires_grad=True)
tensor([ 1.1997, -0.2706, -3.3045, -3.8214], requires_grad=True)
tensor([ 1.2005, -0.2686, -3.3045, -3.8214], requires_grad=True)
tensor([ 1.2005, -0.2691, -3.3045, -3.8215], requires_grad=True)
tensor([ 1.2018, -0.2675,

tensor([ 1.2015, -0.2675, -3.3068, -3.8232], requires_grad=True)
tensor([ 1.1991, -0.2717, -3.3069, -3.8231], requires_grad=True)
tensor([ 1.2003, -0.2697, -3.3069, -3.8231], requires_grad=True)
tensor([ 1.1994, -0.2719, -3.3070, -3.8232], requires_grad=True)
tensor([ 1.1992, -0.2723, -3.3070, -3.8231], requires_grad=True)
tensor([ 1.1998, -0.2710, -3.3070, -3.8232], requires_grad=True)
tensor([ 1.2004, -0.2696, -3.3070, -3.8232], requires_grad=True)
tensor([ 1.2003, -0.2695, -3.3070, -3.8232], requires_grad=True)
tensor([ 1.2011, -0.2681, -3.3071, -3.8232], requires_grad=True)
tensor([ 1.2027, -0.2660, -3.3071, -3.8232], requires_grad=True)
tensor([ 1.2014, -0.2681, -3.3071, -3.8232], requires_grad=True)
tensor([ 1.2007, -0.2695, -3.3071, -3.8232], requires_grad=True)
tensor([ 1.2023, -0.2672, -3.3072, -3.8233], requires_grad=True)
tensor([ 1.2001, -0.2712, -3.3073, -3.8234], requires_grad=True)
tensor([ 1.2006, -0.2704, -3.3073, -3.8234], requires_grad=True)
tensor([ 1.2023, -0.2675,

In [20]:
rho_to_sigma(torch.tensor(0.5488))

tensor(1.0047)

In [21]:
rho_to_sigma(torch.tensor(-3.2))

tensor(0.0486)

In [22]:
0.0486*0.0486

0.0023619599999999998