In [1]:
import pandas as pd
import os
import numpy as np
import scipy as sp
import torch

In [2]:
from scipy.stats import uniform, norm
import seaborn as sns; sns.set()
import matplotlib.pyplot as plt

In [8]:
def sigma_to_rho(sigma):
    rho = torch.log(torch.exp(sigma) - 1)
    return rho

In [9]:
def rho_to_sigma(rho):
    sigma = torch.log(1 + torch.exp(rho))
    return sigma

In [10]:
def log_q_pdf(w, theta):
    (mu_A, mu_b, rho_A, rho_b) = theta 
    
    sigma_A = rho_to_sigma(rho_A)
    qA = torch.distributions.normal.Normal(mu_A, sigma_A)
    
    sigma_b = rho_to_sigma(rho_b)
    qb = torch.distributions.normal.Normal(mu_b, sigma_b)
    
    lp = qA.log_prob(w[0]) + qb.log_prob(w[1])
    return lp

In [11]:
def log_p_pdf(w):
    prior_mu_A = torch.tensor(0.0) 
    prior_sigma_A = torch.tensor(1.0)
    pA = torch.distributions.normal.Normal(prior_mu_A, prior_sigma_A)
    
    prior_mu_b = torch.tensor(0.0) 
    prior_sigma_b = torch.tensor(1.0)
    pb = torch.distributions.normal.Normal(prior_mu_b, prior_sigma_b)
    
    lp = pA.log_prob(w[0]) + pb.log_prob(w[1])
    return lp

In [131]:
def f(w, theta):
    v = log_q_pdf(w, theta) - log_p_pdf(w)
    return v

In [82]:
def approximate_KL(theta):
    prior_mu_A = torch.tensor(0.0) 
    prior_sigma_A = torch.tensor(1.0)
    pA = torch.distributions.normal.Normal(prior_mu_A, prior_sigma_A)
    prior_mu_b = torch.tensor(0.0) 
    prior_sigma_b = torch.tensor(1.0)
    pb = torch.distributions.normal.Normal(prior_mu_b, prior_sigma_b)    
    
    (mu_A, mu_b, rho_A, rho_b) = theta
    
    sigma_A = rho_to_sigma(rho_A)
    qA = torch.distributions.normal.Normal(mu_A, sigma_A)
    sigma_b = rho_to_sigma(rho_b)
    qb = torch.distributions.normal.Normal(mu_b, sigma_b)
    
    lst_lp2 = []
    for j in range(0,100000):
        A = qA.sample()
        b = qb.sample()

        lp = 0
        lp += qA.log_prob(A) + qb.log_prob(b)
        lp -= pA.log_prob(A) + pb.log_prob(b)
        

        lst_lp2.append(lp)
    return torch.stack(lst_lp2).mean()

In [84]:
def prior_KL(theta):
    prior_mu_A = torch.tensor(0.0) 
    prior_sigma_A = torch.tensor(1.0)
    pA = torch.distributions.normal.Normal(prior_mu_A, prior_sigma_A)
    prior_mu_b = torch.tensor(0.0) 
    prior_sigma_b = torch.tensor(1.0)
    pb = torch.distributions.normal.Normal(prior_mu_b, prior_sigma_b)    
    
    (mu_A, mu_b, rho_A, rho_b) = theta
    
    sigma_A = rho_to_sigma(rho_A)
    qA = torch.distributions.normal.Normal(mu_A, sigma_A)
    sigma_b = rho_to_sigma(rho_b)
    qb = torch.distributions.normal.Normal(mu_b, sigma_b)
    return torch.distributions.kl_divergence(qA, pA) + torch.distributions.kl_divergence(qb, pb)

In [154]:
prior_mu_A = torch.tensor(0.0) 
prior_sigma_A = torch.tensor(1.0)
pA = torch.distributions.normal.Normal(prior_mu_A, prior_sigma_A)
prior_mu_b = torch.tensor(0.0) 
prior_sigma_b = torch.tensor(1.0)
pb = torch.distributions.normal.Normal(prior_mu_b, prior_sigma_b)   

In [155]:
mu_A = torch.tensor(1.0)
sigma_A = torch.tensor(0.1)
rho_A = sigma_to_rho(sigma_A)
mu_b = torch.tensor(-0.4)
sigma_b = torch.tensor(0.1)
rho_b = sigma_to_rho(sigma_b)

theta = torch.tensor([mu_A, mu_b, rho_A, rho_b], requires_grad=True)

In [156]:
KL = prior_KL(theta)

In [157]:
KL.backward()

In [158]:
theta.grad

tensor([ 1.0000, -0.4000, -0.9421, -0.9421])

In [159]:

lst_grad_mu = []
lst_grad_rho = []
for j in range(0,5000):
    epsilon = torch.distributions.normal.Normal(torch.tensor(0.0) , torch.tensor(1.0)).sample(torch.Size([2,]))

    with torch.no_grad():
        w = theta[0:2].clone().detach() + torch.log(1 + torch.exp(theta[2:4].clone().detach()))*epsilon
    w.requires_grad = True

    v = f(w, theta)   
    v.backward()
    v = torch.tensor([])

    with torch.no_grad():
        grad_mu = w.grad + theta.grad[0:2]
        grad_rho = w.grad*epsilon/(1 + torch.exp(-theta[2:4])) + -theta.grad[2:4]


    lst_grad_mu.append(grad_mu)
    lst_grad_rho.append(grad_rho)

    theta.grad.zero_()
    w.grad.zero_()
    v.detach()
grad_mu = torch.stack(lst_grad_mu).mean(dim=0)
grad_rho = torch.stack(lst_grad_rho).mean(dim=0)
        
 



In [160]:
grad_mu

tensor([ 0.9999, -0.3989])

In [161]:
grad_rho

tensor([-1.0426, -0.9716])

In [ ]:
alpha = torch.tensor(10e-5)

In [169]:
for i in range(0,10000):
    lst_grad_mu = []
    lst_grad_rho = []
    for j in range(0,10):
        epsilon = torch.distributions.normal.Normal(torch.tensor(0.0) , torch.tensor(1.0)).sample(torch.Size([2,]))

        with torch.no_grad():
            w = theta[0:2].clone().detach() + torch.log(1 + torch.exp(theta[2:4].clone().detach()))*epsilon
        w.requires_grad = True

        v = f(w, theta)   
        v.backward()
        v = torch.tensor([])

        with torch.no_grad():
            grad_mu = w.grad + theta.grad[0:2]
            grad_rho = w.grad*epsilon/(1 + torch.exp(-theta[2:4])) + -theta.grad[2:4]


        lst_grad_mu.append(grad_mu)
        lst_grad_rho.append(grad_rho)

        theta.grad.zero_()
        w.grad.zero_()
        v.detach()
    grad_mu = torch.stack(lst_grad_mu).mean(dim=0)
    grad_rho = torch.stack(lst_grad_rho).mean(dim=0)
    
    #print(grad_mu)
    #print(grad_rho)
        
    with torch.no_grad():
        theta[0:2] -= alpha*grad_mu
        theta[2:4] -= alpha*grad_rho
    
    print(theta)



tensor([ 0.1563, -0.0649, -0.6995, -0.6748], requires_grad=True)
tensor([ 0.1559, -0.0649, -0.6988, -0.6735], requires_grad=True)
tensor([ 0.1557, -0.0650, -0.6973, -0.6724], requires_grad=True)
tensor([ 0.1557, -0.0650, -0.6972, -0.6723], requires_grad=True)
tensor([ 0.1553, -0.0650, -0.6972, -0.6716], requires_grad=True)
tensor([ 0.1551, -0.0651, -0.6973, -0.6709], requires_grad=True)
tensor([ 0.1552, -0.0652, -0.6963, -0.6691], requires_grad=True)
tensor([ 0.1549, -0.0652, -0.6955, -0.6689], requires_grad=True)
tensor([ 0.1546, -0.0651, -0.6939, -0.6681], requires_grad=True)
tensor([ 0.1544, -0.0649, -0.6934, -0.6680], requires_grad=True)
tensor([ 0.1543, -0.0650, -0.6930, -0.6677], requires_grad=True)
tensor([ 0.1542, -0.0651, -0.6929, -0.6676], requires_grad=True)
tensor([ 0.1540, -0.0652, -0.6933, -0.6676], requires_grad=True)
tensor([ 0.1538, -0.0650, -0.6932, -0.6666], requires_grad=True)
tensor([ 0.1536, -0.0648, -0.6933, -0.6646], requires_grad=True)
tensor([ 0.1534, -0.0646,

tensor([ 0.1362, -0.0559, -0.6088, -0.5811], requires_grad=True)
tensor([ 0.1361, -0.0560, -0.6073, -0.5810], requires_grad=True)
tensor([ 0.1357, -0.0560, -0.6068, -0.5807], requires_grad=True)
tensor([ 0.1355, -0.0559, -0.6070, -0.5803], requires_grad=True)
tensor([ 0.1354, -0.0558, -0.6074, -0.5795], requires_grad=True)
tensor([ 0.1353, -0.0556, -0.6074, -0.5792], requires_grad=True)
tensor([ 0.1350, -0.0556, -0.6068, -0.5785], requires_grad=True)
tensor([ 0.1349, -0.0558, -0.6063, -0.5778], requires_grad=True)
tensor([ 0.1346, -0.0556, -0.6059, -0.5762], requires_grad=True)
tensor([ 0.1346, -0.0556, -0.6052, -0.5766], requires_grad=True)
tensor([ 0.1344, -0.0556, -0.6045, -0.5755], requires_grad=True)
tensor([ 0.1343, -0.0555, -0.6047, -0.5754], requires_grad=True)
tensor([ 0.1342, -0.0555, -0.6048, -0.5749], requires_grad=True)
tensor([ 0.1341, -0.0554, -0.6046, -0.5737], requires_grad=True)
tensor([ 0.1343, -0.0555, -0.6032, -0.5733], requires_grad=True)
tensor([ 0.1341, -0.0555,

tensor([ 0.1187, -0.0491, -0.5323, -0.4860], requires_grad=True)
tensor([ 0.1186, -0.0488, -0.5320, -0.4853], requires_grad=True)
tensor([ 0.1182, -0.0490, -0.5300, -0.4842], requires_grad=True)
tensor([ 0.1181, -0.0487, -0.5303, -0.4834], requires_grad=True)
tensor([ 0.1181, -0.0487, -0.5304, -0.4819], requires_grad=True)
tensor([ 0.1179, -0.0486, -0.5287, -0.4816], requires_grad=True)
tensor([ 0.1178, -0.0486, -0.5278, -0.4811], requires_grad=True)
tensor([ 0.1176, -0.0486, -0.5280, -0.4812], requires_grad=True)
tensor([ 0.1175, -0.0483, -0.5263, -0.4807], requires_grad=True)
tensor([ 0.1174, -0.0484, -0.5256, -0.4800], requires_grad=True)
tensor([ 0.1173, -0.0487, -0.5244, -0.4791], requires_grad=True)
tensor([ 0.1169, -0.0486, -0.5238, -0.4784], requires_grad=True)
tensor([ 0.1166, -0.0484, -0.5242, -0.4781], requires_grad=True)
tensor([ 0.1167, -0.0485, -0.5242, -0.4773], requires_grad=True)
tensor([ 0.1164, -0.0483, -0.5236, -0.4768], requires_grad=True)
tensor([ 0.1164, -0.0483,

tensor([ 0.1035, -0.0422, -0.4462, -0.4136], requires_grad=True)
tensor([ 0.1032, -0.0422, -0.4457, -0.4113], requires_grad=True)
tensor([ 0.1031, -0.0424, -0.4450, -0.4101], requires_grad=True)
tensor([ 0.1029, -0.0425, -0.4444, -0.4102], requires_grad=True)
tensor([ 0.1029, -0.0427, -0.4446, -0.4092], requires_grad=True)
tensor([ 0.1030, -0.0429, -0.4440, -0.4075], requires_grad=True)
tensor([ 0.1026, -0.0426, -0.4427, -0.4067], requires_grad=True)
tensor([ 0.1022, -0.0423, -0.4422, -0.4057], requires_grad=True)
tensor([ 0.1021, -0.0420, -0.4413, -0.4052], requires_grad=True)
tensor([ 0.1019, -0.0421, -0.4397, -0.4045], requires_grad=True)
tensor([ 0.1019, -0.0421, -0.4389, -0.4031], requires_grad=True)
tensor([ 0.1018, -0.0421, -0.4388, -0.4021], requires_grad=True)
tensor([ 0.1016, -0.0420, -0.4388, -0.4020], requires_grad=True)
tensor([ 0.1013, -0.0418, -0.4381, -0.4013], requires_grad=True)
tensor([ 0.1011, -0.0415, -0.4372, -0.4007], requires_grad=True)
tensor([ 0.1009, -0.0414,

tensor([ 0.0887, -0.0364, -0.3634, -0.3269], requires_grad=True)
tensor([ 0.0886, -0.0364, -0.3630, -0.3262], requires_grad=True)
tensor([ 0.0886, -0.0364, -0.3624, -0.3259], requires_grad=True)
tensor([ 0.0884, -0.0364, -0.3623, -0.3256], requires_grad=True)
tensor([ 0.0883, -0.0366, -0.3619, -0.3255], requires_grad=True)
tensor([ 0.0882, -0.0369, -0.3620, -0.3248], requires_grad=True)
tensor([ 0.0883, -0.0371, -0.3620, -0.3246], requires_grad=True)
tensor([ 0.0879, -0.0368, -0.3611, -0.3239], requires_grad=True)
tensor([ 0.0876, -0.0364, -0.3610, -0.3233], requires_grad=True)
tensor([ 0.0874, -0.0363, -0.3607, -0.3227], requires_grad=True)
tensor([ 0.0873, -0.0362, -0.3610, -0.3228], requires_grad=True)
tensor([ 0.0874, -0.0360, -0.3607, -0.3220], requires_grad=True)
tensor([ 0.0876, -0.0358, -0.3593, -0.3212], requires_grad=True)
tensor([ 0.0875, -0.0358, -0.3592, -0.3197], requires_grad=True)
tensor([ 0.0876, -0.0360, -0.3591, -0.3196], requires_grad=True)
tensor([ 0.0875, -0.0360,

tensor([ 0.0782, -0.0314, -0.2935, -0.2624], requires_grad=True)
tensor([ 0.0783, -0.0315, -0.2935, -0.2625], requires_grad=True)
tensor([ 0.0781, -0.0318, -0.2935, -0.2622], requires_grad=True)
tensor([ 0.0782, -0.0319, -0.2933, -0.2620], requires_grad=True)
tensor([ 0.0781, -0.0320, -0.2923, -0.2616], requires_grad=True)
tensor([ 0.0779, -0.0319, -0.2925, -0.2608], requires_grad=True)
tensor([ 0.0778, -0.0317, -0.2921, -0.2597], requires_grad=True)
tensor([ 0.0776, -0.0316, -0.2919, -0.2591], requires_grad=True)
tensor([ 0.0774, -0.0314, -0.2920, -0.2588], requires_grad=True)
tensor([ 0.0772, -0.0315, -0.2917, -0.2591], requires_grad=True)
tensor([ 0.0772, -0.0315, -0.2919, -0.2590], requires_grad=True)
tensor([ 0.0772, -0.0314, -0.2922, -0.2585], requires_grad=True)
tensor([ 0.0769, -0.0313, -0.2923, -0.2578], requires_grad=True)
tensor([ 0.0768, -0.0313, -0.2921, -0.2583], requires_grad=True)
tensor([ 0.0766, -0.0309, -0.2922, -0.2569], requires_grad=True)
tensor([ 0.0764, -0.0309,

tensor([ 0.0660, -0.0293, -0.2278, -0.1913], requires_grad=True)
tensor([ 0.0659, -0.0295, -0.2279, -0.1897], requires_grad=True)
tensor([ 0.0656, -0.0296, -0.2276, -0.1896], requires_grad=True)
tensor([ 0.0656, -0.0298, -0.2271, -0.1898], requires_grad=True)
tensor([ 0.0658, -0.0295, -0.2263, -0.1899], requires_grad=True)
tensor([ 0.0657, -0.0298, -0.2257, -0.1898], requires_grad=True)
tensor([ 0.0654, -0.0300, -0.2252, -0.1889], requires_grad=True)
tensor([ 0.0651, -0.0298, -0.2241, -0.1880], requires_grad=True)
tensor([ 0.0651, -0.0297, -0.2244, -0.1877], requires_grad=True)
tensor([ 0.0649, -0.0299, -0.2232, -0.1856], requires_grad=True)
tensor([ 0.0651, -0.0296, -0.2231, -0.1847], requires_grad=True)
tensor([ 0.0649, -0.0295, -0.2231, -0.1842], requires_grad=True)
tensor([ 0.0652, -0.0291, -0.2225, -0.1838], requires_grad=True)
tensor([ 0.0653, -0.0293, -0.2214, -0.1836], requires_grad=True)
tensor([ 0.0653, -0.0290, -0.2213, -0.1832], requires_grad=True)
tensor([ 0.0654, -0.0288,

tensor([ 0.0585, -0.0260, -0.1548, -0.1263], requires_grad=True)
tensor([ 0.0583, -0.0260, -0.1544, -0.1258], requires_grad=True)
tensor([ 0.0584, -0.0261, -0.1548, -0.1250], requires_grad=True)
tensor([ 0.0580, -0.0258, -0.1544, -0.1248], requires_grad=True)
tensor([ 0.0580, -0.0260, -0.1540, -0.1245], requires_grad=True)
tensor([ 0.0578, -0.0260, -0.1531, -0.1243], requires_grad=True)
tensor([ 0.0584, -0.0258, -0.1520, -0.1226], requires_grad=True)
tensor([ 0.0582, -0.0256, -0.1522, -0.1221], requires_grad=True)
tensor([ 0.0584, -0.0259, -0.1521, -0.1218], requires_grad=True)
tensor([ 0.0584, -0.0262, -0.1517, -0.1206], requires_grad=True)
tensor([ 0.0586, -0.0263, -0.1511, -0.1208], requires_grad=True)
tensor([ 0.0587, -0.0266, -0.1512, -0.1199], requires_grad=True)
tensor([ 0.0591, -0.0265, -0.1500, -0.1188], requires_grad=True)
tensor([ 0.0590, -0.0267, -0.1500, -0.1181], requires_grad=True)
tensor([ 0.0591, -0.0268, -0.1494, -0.1173], requires_grad=True)
tensor([ 0.0587, -0.0267,

tensor([ 0.0506, -0.0262, -0.0967, -0.0668], requires_grad=True)
tensor([ 0.0500, -0.0259, -0.0952, -0.0669], requires_grad=True)
tensor([ 0.0499, -0.0256, -0.0953, -0.0661], requires_grad=True)
tensor([ 0.0497, -0.0260, -0.0944, -0.0649], requires_grad=True)
tensor([ 0.0498, -0.0258, -0.0941, -0.0648], requires_grad=True)
tensor([ 0.0499, -0.0257, -0.0936, -0.0640], requires_grad=True)
tensor([ 0.0496, -0.0260, -0.0928, -0.0633], requires_grad=True)
tensor([ 0.0495, -0.0255, -0.0926, -0.0633], requires_grad=True)
tensor([ 0.0495, -0.0254, -0.0927, -0.0630], requires_grad=True)
tensor([ 0.0495, -0.0253, -0.0926, -0.0623], requires_grad=True)
tensor([ 0.0494, -0.0254, -0.0916, -0.0615], requires_grad=True)
tensor([ 0.0489, -0.0256, -0.0906, -0.0612], requires_grad=True)
tensor([ 0.0492, -0.0258, -0.0897, -0.0610], requires_grad=True)
tensor([ 0.0491, -0.0261, -0.0896, -0.0602], requires_grad=True)
tensor([ 0.0491, -0.0260, -0.0896, -0.0601], requires_grad=True)
tensor([ 0.0490, -0.0257,

tensor([ 0.0403, -0.0203, -0.0443, -0.0096], requires_grad=True)
tensor([ 0.0404, -0.0202, -0.0443, -0.0096], requires_grad=True)
tensor([ 0.0407, -0.0200, -0.0442, -0.0098], requires_grad=True)
tensor([ 0.0403, -0.0205, -0.0440, -0.0090], requires_grad=True)
tensor([ 0.0404, -0.0209, -0.0424, -0.0087], requires_grad=True)
tensor([ 0.0403, -0.0206, -0.0412, -0.0080], requires_grad=True)
tensor([ 0.0405, -0.0204, -0.0413, -0.0079], requires_grad=True)
tensor([ 0.0406, -0.0199, -0.0418, -0.0065], requires_grad=True)
tensor([ 0.0404, -0.0202, -0.0414, -0.0058], requires_grad=True)
tensor([ 0.0401, -0.0202, -0.0404, -0.0055], requires_grad=True)
tensor([ 0.0401, -0.0198, -0.0405, -0.0048], requires_grad=True)
tensor([ 0.0399, -0.0194, -0.0394, -0.0046], requires_grad=True)
tensor([ 0.0396, -0.0196, -0.0392, -0.0044], requires_grad=True)
tensor([ 0.0393, -0.0196, -0.0380, -0.0035], requires_grad=True)
tensor([ 0.0393, -0.0193, -0.0377, -0.0033], requires_grad=True)
tensor([ 0.0395, -0.0193,

tensor([ 0.0346, -0.0177,  0.0111,  0.0367], requires_grad=True)
tensor([ 0.0345, -0.0176,  0.0116,  0.0369], requires_grad=True)
tensor([ 0.0348, -0.0177,  0.0127,  0.0378], requires_grad=True)
tensor([ 0.0347, -0.0175,  0.0128,  0.0382], requires_grad=True)
tensor([ 0.0347, -0.0172,  0.0128,  0.0389], requires_grad=True)
tensor([ 0.0340, -0.0171,  0.0149,  0.0404], requires_grad=True)
tensor([ 0.0344, -0.0170,  0.0154,  0.0412], requires_grad=True)
tensor([ 0.0342, -0.0172,  0.0160,  0.0422], requires_grad=True)
tensor([ 0.0345, -0.0169,  0.0173,  0.0428], requires_grad=True)
tensor([ 0.0348, -0.0171,  0.0176,  0.0442], requires_grad=True)
tensor([ 0.0349, -0.0174,  0.0180,  0.0445], requires_grad=True)
tensor([ 0.0347, -0.0172,  0.0187,  0.0444], requires_grad=True)
tensor([ 0.0347, -0.0170,  0.0184,  0.0445], requires_grad=True)
tensor([ 0.0348, -0.0169,  0.0180,  0.0446], requires_grad=True)
tensor([ 0.0347, -0.0168,  0.0183,  0.0446], requires_grad=True)
tensor([ 0.0347, -0.0167,

tensor([ 0.0363, -0.0131,  0.0687,  0.0885], requires_grad=True)
tensor([ 0.0363, -0.0131,  0.0689,  0.0880], requires_grad=True)
tensor([ 0.0361, -0.0129,  0.0694,  0.0888], requires_grad=True)
tensor([ 0.0362, -0.0129,  0.0704,  0.0890], requires_grad=True)
tensor([ 0.0359, -0.0124,  0.0714,  0.0906], requires_grad=True)
tensor([ 0.0359, -0.0127,  0.0721,  0.0914], requires_grad=True)
tensor([ 0.0356, -0.0129,  0.0722,  0.0923], requires_grad=True)
tensor([ 0.0351, -0.0132,  0.0727,  0.0928], requires_grad=True)
tensor([ 0.0347, -0.0132,  0.0730,  0.0927], requires_grad=True)
tensor([ 0.0349, -0.0130,  0.0738,  0.0934], requires_grad=True)
tensor([ 0.0351, -0.0129,  0.0743,  0.0939], requires_grad=True)
tensor([ 0.0348, -0.0131,  0.0745,  0.0942], requires_grad=True)
tensor([ 0.0345, -0.0133,  0.0743,  0.0949], requires_grad=True)
tensor([ 0.0347, -0.0130,  0.0749,  0.0952], requires_grad=True)
tensor([ 0.0343, -0.0133,  0.0751,  0.0959], requires_grad=True)
tensor([ 0.0343, -0.0129,

tensor([ 0.0372, -0.0086,  0.1101,  0.1269], requires_grad=True)
tensor([ 0.0371, -0.0085,  0.1097,  0.1274], requires_grad=True)
tensor([ 0.0374, -0.0086,  0.1105,  0.1274], requires_grad=True)
tensor([ 0.0377, -0.0086,  0.1117,  0.1279], requires_grad=True)
tensor([ 0.0379, -0.0093,  0.1121,  0.1285], requires_grad=True)
tensor([ 0.0381, -0.0093,  0.1122,  0.1289], requires_grad=True)
tensor([ 0.0379, -0.0088,  0.1129,  0.1293], requires_grad=True)
tensor([ 0.0379, -0.0089,  0.1131,  0.1291], requires_grad=True)
tensor([ 0.0380, -0.0088,  0.1135,  0.1292], requires_grad=True)
tensor([ 0.0385, -0.0085,  0.1138,  0.1303], requires_grad=True)
tensor([ 0.0386, -0.0088,  0.1141,  0.1303], requires_grad=True)
tensor([ 0.0385, -0.0087,  0.1144,  0.1307], requires_grad=True)
tensor([ 0.0385, -0.0087,  0.1142,  0.1304], requires_grad=True)
tensor([ 0.0384, -0.0084,  0.1143,  0.1305], requires_grad=True)
tensor([ 0.0379, -0.0084,  0.1146,  0.1301], requires_grad=True)
tensor([ 0.0373, -0.0085,

tensor([ 0.0316, -0.0040,  0.1594,  0.1657], requires_grad=True)
tensor([ 0.0314, -0.0043,  0.1591,  0.1659], requires_grad=True)
tensor([ 0.0313, -0.0046,  0.1589,  0.1657], requires_grad=True)
tensor([ 0.0313, -0.0047,  0.1591,  0.1654], requires_grad=True)
tensor([ 0.0310, -0.0048,  0.1594,  0.1660], requires_grad=True)
tensor([ 0.0311, -0.0049,  0.1597,  0.1658], requires_grad=True)
tensor([ 0.0314, -0.0052,  0.1606,  0.1658], requires_grad=True)
tensor([ 0.0315, -0.0048,  0.1605,  0.1658], requires_grad=True)
tensor([ 0.0314, -0.0046,  0.1602,  0.1655], requires_grad=True)
tensor([ 0.0315, -0.0040,  0.1599,  0.1660], requires_grad=True)
tensor([ 0.0309, -0.0036,  0.1613,  0.1664], requires_grad=True)
tensor([ 0.0308, -0.0033,  0.1628,  0.1664], requires_grad=True)
tensor([ 0.0308, -0.0036,  0.1628,  0.1662], requires_grad=True)
tensor([ 0.0306, -0.0037,  0.1628,  0.1666], requires_grad=True)
tensor([ 0.0306, -0.0037,  0.1629,  0.1663], requires_grad=True)
tensor([ 0.0305, -0.0039,

tensor([ 0.0254, -0.0044,  0.1958,  0.1956], requires_grad=True)
tensor([ 0.0257, -0.0042,  0.1961,  0.1956], requires_grad=True)
tensor([ 0.0257, -0.0039,  0.1956,  0.1960], requires_grad=True)
tensor([ 0.0254, -0.0039,  0.1970,  0.1959], requires_grad=True)
tensor([ 0.0254, -0.0040,  0.1974,  0.1956], requires_grad=True)
tensor([ 0.0256, -0.0040,  0.1973,  0.1957], requires_grad=True)
tensor([ 0.0257, -0.0041,  0.1982,  0.1960], requires_grad=True)
tensor([ 0.0258, -0.0039,  0.1982,  0.1960], requires_grad=True)
tensor([ 0.0255, -0.0036,  0.1981,  0.1957], requires_grad=True)
tensor([ 0.0257, -0.0036,  0.1985,  0.1956], requires_grad=True)
tensor([ 0.0256, -0.0036,  0.1982,  0.1962], requires_grad=True)
tensor([ 0.0255, -0.0040,  0.1992,  0.1967], requires_grad=True)
tensor([ 0.0253, -0.0043,  0.1994,  0.1970], requires_grad=True)
tensor([ 0.0251, -0.0043,  0.1992,  0.1972], requires_grad=True)
tensor([ 0.0247, -0.0045,  0.1994,  0.1971], requires_grad=True)
tensor([ 0.0242, -0.0046,

tensor([ 0.0251, -0.0051,  0.2308,  0.2206], requires_grad=True)
tensor([ 0.0255, -0.0050,  0.2312,  0.2209], requires_grad=True)
tensor([ 0.0254, -0.0048,  0.2312,  0.2205], requires_grad=True)
tensor([ 0.0252, -0.0050,  0.2315,  0.2207], requires_grad=True)
tensor([ 0.0252, -0.0050,  0.2317,  0.2210], requires_grad=True)
tensor([ 0.0255, -0.0046,  0.2317,  0.2208], requires_grad=True)
tensor([ 0.0251, -0.0046,  0.2317,  0.2207], requires_grad=True)
tensor([ 0.0248, -0.0046,  0.2316,  0.2209], requires_grad=True)
tensor([ 0.0249, -0.0052,  0.2326,  0.2212], requires_grad=True)
tensor([ 0.0252, -0.0052,  0.2325,  0.2209], requires_grad=True)
tensor([ 0.0256, -0.0053,  0.2333,  0.2206], requires_grad=True)
tensor([ 0.0259, -0.0049,  0.2335,  0.2213], requires_grad=True)
tensor([ 0.0261, -0.0049,  0.2339,  0.2216], requires_grad=True)
tensor([ 0.0259, -0.0048,  0.2340,  0.2218], requires_grad=True)
tensor([ 0.0257, -0.0048,  0.2353,  0.2219], requires_grad=True)
tensor([ 0.0258, -0.0047,

tensor([ 0.0197, -0.0061,  0.2660,  0.2464], requires_grad=True)
tensor([ 0.0194, -0.0063,  0.2660,  0.2485], requires_grad=True)
tensor([ 0.0193, -0.0062,  0.2663,  0.2489], requires_grad=True)
tensor([ 0.0193, -0.0057,  0.2667,  0.2490], requires_grad=True)
tensor([ 0.0196, -0.0057,  0.2664,  0.2499], requires_grad=True)
tensor([ 0.0194, -0.0057,  0.2661,  0.2504], requires_grad=True)
tensor([ 0.0190, -0.0057,  0.2667,  0.2507], requires_grad=True)
tensor([ 0.0190, -0.0057,  0.2667,  0.2512], requires_grad=True)
tensor([ 0.0189, -0.0056,  0.2665,  0.2513], requires_grad=True)
tensor([ 0.0190, -0.0060,  0.2668,  0.2519], requires_grad=True)
tensor([ 0.0187, -0.0060,  0.2668,  0.2515], requires_grad=True)
tensor([ 0.0188, -0.0057,  0.2670,  0.2514], requires_grad=True)
tensor([ 0.0190, -0.0054,  0.2669,  0.2521], requires_grad=True)
tensor([ 0.0192, -0.0054,  0.2672,  0.2520], requires_grad=True)
tensor([ 0.0196, -0.0058,  0.2675,  0.2526], requires_grad=True)
tensor([ 0.0198, -0.0055,

tensor([1.8998e-02, 1.4019e-04, 2.8914e-01, 2.7086e-01], requires_grad=True)
tensor([0.0187, 0.0004, 0.2891, 0.2712], requires_grad=True)
tensor([0.0189, 0.0006, 0.2893, 0.2713], requires_grad=True)
tensor([0.0189, 0.0009, 0.2897, 0.2711], requires_grad=True)
tensor([0.0185, 0.0009, 0.2903, 0.2711], requires_grad=True)
tensor([0.0185, 0.0012, 0.2900, 0.2712], requires_grad=True)
tensor([0.0180, 0.0013, 0.2903, 0.2713], requires_grad=True)
tensor([0.0181, 0.0015, 0.2902, 0.2710], requires_grad=True)
tensor([0.0177, 0.0016, 0.2906, 0.2720], requires_grad=True)
tensor([0.0175, 0.0017, 0.2906, 0.2718], requires_grad=True)
tensor([0.0172, 0.0019, 0.2911, 0.2717], requires_grad=True)
tensor([0.0175, 0.0020, 0.2915, 0.2720], requires_grad=True)
tensor([0.0172, 0.0017, 0.2916, 0.2720], requires_grad=True)
tensor([0.0169, 0.0017, 0.2916, 0.2717], requires_grad=True)
tensor([0.0166, 0.0012, 0.2920, 0.2713], requires_grad=True)
tensor([0.0163, 0.0015, 0.2919, 0.2715], requires_grad=True)
tensor([

tensor([0.0145, 0.0036, 0.3195, 0.2930], requires_grad=True)
tensor([0.0153, 0.0037, 0.3203, 0.2927], requires_grad=True)
tensor([0.0152, 0.0031, 0.3210, 0.2935], requires_grad=True)
tensor([0.0149, 0.0034, 0.3210, 0.2938], requires_grad=True)
tensor([0.0150, 0.0033, 0.3214, 0.2946], requires_grad=True)
tensor([0.0150, 0.0039, 0.3218, 0.2954], requires_grad=True)
tensor([0.0149, 0.0038, 0.3215, 0.2965], requires_grad=True)
tensor([0.0146, 0.0038, 0.3218, 0.2964], requires_grad=True)
tensor([0.0151, 0.0042, 0.3222, 0.2970], requires_grad=True)
tensor([0.0151, 0.0042, 0.3221, 0.2967], requires_grad=True)
tensor([0.0152, 0.0047, 0.3218, 0.2984], requires_grad=True)
tensor([0.0152, 0.0046, 0.3227, 0.2983], requires_grad=True)
tensor([0.0152, 0.0044, 0.3222, 0.2985], requires_grad=True)
tensor([0.0148, 0.0043, 0.3226, 0.2981], requires_grad=True)
tensor([0.0152, 0.0038, 0.3226, 0.2981], requires_grad=True)
tensor([0.0154, 0.0040, 0.3230, 0.2982], requires_grad=True)
tensor([0.0152, 0.0036, 

tensor([ 0.0141, -0.0018,  0.3482,  0.3193], requires_grad=True)
tensor([ 0.0144, -0.0017,  0.3482,  0.3196], requires_grad=True)
tensor([ 0.0141, -0.0020,  0.3478,  0.3200], requires_grad=True)
tensor([ 0.0139, -0.0022,  0.3485,  0.3199], requires_grad=True)
tensor([ 0.0138, -0.0017,  0.3485,  0.3211], requires_grad=True)
tensor([ 0.0141, -0.0023,  0.3484,  0.3221], requires_grad=True)
tensor([ 0.0142, -0.0020,  0.3488,  0.3222], requires_grad=True)
tensor([ 0.0139, -0.0019,  0.3485,  0.3218], requires_grad=True)
tensor([ 0.0140, -0.0020,  0.3481,  0.3213], requires_grad=True)
tensor([ 0.0143, -0.0026,  0.3481,  0.3218], requires_grad=True)
tensor([ 0.0143, -0.0028,  0.3479,  0.3223], requires_grad=True)
tensor([ 0.0142, -0.0027,  0.3477,  0.3224], requires_grad=True)
tensor([ 0.0135, -0.0033,  0.3478,  0.3233], requires_grad=True)
tensor([ 0.0135, -0.0031,  0.3484,  0.3237], requires_grad=True)
tensor([ 0.0138, -0.0028,  0.3483,  0.3237], requires_grad=True)
tensor([ 0.0138, -0.0027,

tensor([ 0.0140, -0.0041,  0.3674,  0.3437], requires_grad=True)
tensor([ 0.0136, -0.0038,  0.3676,  0.3437], requires_grad=True)
tensor([ 0.0136, -0.0036,  0.3676,  0.3436], requires_grad=True)
tensor([ 0.0136, -0.0032,  0.3687,  0.3433], requires_grad=True)
tensor([ 0.0133, -0.0034,  0.3691,  0.3431], requires_grad=True)
tensor([ 0.0135, -0.0030,  0.3708,  0.3432], requires_grad=True)
tensor([ 0.0138, -0.0026,  0.3706,  0.3435], requires_grad=True)
tensor([ 0.0136, -0.0021,  0.3702,  0.3436], requires_grad=True)
tensor([ 0.0139, -0.0016,  0.3702,  0.3440], requires_grad=True)
tensor([ 0.0141, -0.0016,  0.3704,  0.3445], requires_grad=True)
tensor([ 0.0144, -0.0015,  0.3707,  0.3449], requires_grad=True)
tensor([ 0.0138, -0.0017,  0.3708,  0.3445], requires_grad=True)
tensor([ 0.0139, -0.0016,  0.3705,  0.3444], requires_grad=True)
tensor([ 0.0141, -0.0010,  0.3714,  0.3449], requires_grad=True)
tensor([ 0.0141, -0.0015,  0.3714,  0.3453], requires_grad=True)
tensor([ 0.0141, -0.0013,

tensor([ 0.0060, -0.0044,  0.3892,  0.3589], requires_grad=True)
tensor([ 0.0063, -0.0044,  0.3891,  0.3588], requires_grad=True)
tensor([ 0.0063, -0.0046,  0.3896,  0.3590], requires_grad=True)
tensor([ 0.0064, -0.0049,  0.3903,  0.3586], requires_grad=True)
tensor([ 0.0067, -0.0050,  0.3914,  0.3590], requires_grad=True)
tensor([ 0.0065, -0.0055,  0.3919,  0.3596], requires_grad=True)
tensor([ 0.0065, -0.0050,  0.3917,  0.3605], requires_grad=True)
tensor([ 0.0069, -0.0054,  0.3925,  0.3606], requires_grad=True)
tensor([ 0.0068, -0.0056,  0.3926,  0.3606], requires_grad=True)
tensor([ 0.0067, -0.0055,  0.3927,  0.3611], requires_grad=True)
tensor([ 0.0064, -0.0051,  0.3926,  0.3617], requires_grad=True)
tensor([ 0.0065, -0.0051,  0.3923,  0.3620], requires_grad=True)
tensor([ 0.0071, -0.0049,  0.3926,  0.3619], requires_grad=True)
tensor([ 0.0070, -0.0049,  0.3922,  0.3619], requires_grad=True)
tensor([ 0.0070, -0.0044,  0.3929,  0.3624], requires_grad=True)
tensor([ 0.0066, -0.0047,

tensor([ 0.0077, -0.0056,  0.4007,  0.3778], requires_grad=True)
tensor([ 0.0077, -0.0057,  0.4004,  0.3782], requires_grad=True)
tensor([ 0.0080, -0.0061,  0.4008,  0.3783], requires_grad=True)
tensor([ 0.0084, -0.0060,  0.4008,  0.3781], requires_grad=True)
tensor([ 0.0085, -0.0060,  0.4007,  0.3781], requires_grad=True)
tensor([ 0.0082, -0.0061,  0.4005,  0.3777], requires_grad=True)
tensor([ 0.0081, -0.0062,  0.4003,  0.3779], requires_grad=True)
tensor([ 0.0082, -0.0060,  0.4007,  0.3784], requires_grad=True)
tensor([ 0.0081, -0.0060,  0.4010,  0.3786], requires_grad=True)
tensor([ 0.0074, -0.0063,  0.4014,  0.3785], requires_grad=True)
tensor([ 0.0073, -0.0059,  0.4014,  0.3783], requires_grad=True)
tensor([ 0.0071, -0.0060,  0.4011,  0.3791], requires_grad=True)
tensor([ 0.0072, -0.0061,  0.4018,  0.3791], requires_grad=True)
tensor([ 0.0069, -0.0066,  0.4019,  0.3790], requires_grad=True)
tensor([ 0.0070, -0.0067,  0.4023,  0.3786], requires_grad=True)
tensor([ 0.0067, -0.0072,

tensor([0.0134, 0.0007, 0.4159, 0.3941], requires_grad=True)
tensor([0.0135, 0.0009, 0.4161, 0.3942], requires_grad=True)
tensor([0.0136, 0.0007, 0.4160, 0.3952], requires_grad=True)
tensor([ 1.3469e-02, -1.2216e-04,  4.1564e-01,  3.9582e-01],
       requires_grad=True)
tensor([ 0.0137, -0.0007,  0.4153,  0.3959], requires_grad=True)
tensor([ 0.0135, -0.0011,  0.4150,  0.3968], requires_grad=True)
tensor([ 0.0138, -0.0006,  0.4151,  0.3967], requires_grad=True)
tensor([ 0.0136, -0.0006,  0.4154,  0.3965], requires_grad=True)
tensor([ 0.0132, -0.0011,  0.4161,  0.3969], requires_grad=True)
tensor([ 0.0135, -0.0009,  0.4164,  0.3968], requires_grad=True)
tensor([ 0.0135, -0.0010,  0.4166,  0.3968], requires_grad=True)
tensor([ 0.0128, -0.0007,  0.4170,  0.3968], requires_grad=True)
tensor([ 0.0122, -0.0012,  0.4173,  0.3971], requires_grad=True)
tensor([ 0.0119, -0.0016,  0.4170,  0.3977], requires_grad=True)
tensor([ 0.0116, -0.0014,  0.4170,  0.3980], requires_grad=True)
tensor([ 0.011

tensor([ 0.0124, -0.0059,  0.4283,  0.4120], requires_grad=True)
tensor([ 0.0125, -0.0055,  0.4287,  0.4120], requires_grad=True)
tensor([ 0.0124, -0.0054,  0.4287,  0.4116], requires_grad=True)
tensor([ 0.0126, -0.0055,  0.4285,  0.4115], requires_grad=True)
tensor([ 0.0129, -0.0056,  0.4293,  0.4113], requires_grad=True)
tensor([ 0.0125, -0.0058,  0.4294,  0.4116], requires_grad=True)
tensor([ 0.0120, -0.0061,  0.4294,  0.4117], requires_grad=True)
tensor([ 0.0117, -0.0057,  0.4299,  0.4115], requires_grad=True)
tensor([ 0.0118, -0.0056,  0.4296,  0.4111], requires_grad=True)
tensor([ 0.0118, -0.0059,  0.4292,  0.4116], requires_grad=True)
tensor([ 0.0122, -0.0056,  0.4298,  0.4115], requires_grad=True)
tensor([ 0.0123, -0.0053,  0.4294,  0.4116], requires_grad=True)
tensor([ 0.0125, -0.0047,  0.4296,  0.4119], requires_grad=True)
tensor([ 0.0125, -0.0048,  0.4294,  0.4123], requires_grad=True)
tensor([ 0.0126, -0.0047,  0.4297,  0.4133], requires_grad=True)
tensor([ 0.0125, -0.0047,

tensor([ 0.0131, -0.0069,  0.4409,  0.4208], requires_grad=True)
tensor([ 0.0133, -0.0069,  0.4405,  0.4210], requires_grad=True)
tensor([ 0.0131, -0.0070,  0.4410,  0.4210], requires_grad=True)
tensor([ 0.0132, -0.0071,  0.4411,  0.4208], requires_grad=True)
tensor([ 0.0130, -0.0073,  0.4414,  0.4207], requires_grad=True)
tensor([ 0.0128, -0.0071,  0.4416,  0.4211], requires_grad=True)
tensor([ 0.0129, -0.0072,  0.4423,  0.4213], requires_grad=True)
tensor([ 0.0128, -0.0067,  0.4423,  0.4213], requires_grad=True)
tensor([ 0.0133, -0.0061,  0.4422,  0.4213], requires_grad=True)
tensor([ 0.0136, -0.0059,  0.4425,  0.4214], requires_grad=True)
tensor([ 0.0142, -0.0058,  0.4425,  0.4211], requires_grad=True)
tensor([ 0.0136, -0.0065,  0.4428,  0.4211], requires_grad=True)
tensor([ 0.0133, -0.0065,  0.4428,  0.4209], requires_grad=True)
tensor([ 0.0134, -0.0065,  0.4427,  0.4208], requires_grad=True)
tensor([ 0.0137, -0.0070,  0.4435,  0.4208], requires_grad=True)
tensor([ 0.0135, -0.0068,

tensor([ 0.0059, -0.0089,  0.4486,  0.4340], requires_grad=True)
tensor([ 0.0061, -0.0086,  0.4489,  0.4345], requires_grad=True)
tensor([ 0.0059, -0.0082,  0.4494,  0.4343], requires_grad=True)
tensor([ 0.0059, -0.0084,  0.4494,  0.4338], requires_grad=True)
tensor([ 0.0059, -0.0087,  0.4491,  0.4340], requires_grad=True)
tensor([ 0.0061, -0.0083,  0.4488,  0.4344], requires_grad=True)
tensor([ 0.0063, -0.0086,  0.4486,  0.4346], requires_grad=True)
tensor([ 0.0064, -0.0084,  0.4486,  0.4346], requires_grad=True)
tensor([ 0.0065, -0.0081,  0.4485,  0.4346], requires_grad=True)
tensor([ 0.0065, -0.0074,  0.4484,  0.4352], requires_grad=True)
tensor([ 0.0063, -0.0067,  0.4481,  0.4356], requires_grad=True)
tensor([ 0.0059, -0.0065,  0.4487,  0.4360], requires_grad=True)
tensor([ 0.0058, -0.0063,  0.4488,  0.4363], requires_grad=True)
tensor([ 0.0060, -0.0061,  0.4487,  0.4365], requires_grad=True)
tensor([ 0.0063, -0.0062,  0.4486,  0.4368], requires_grad=True)
tensor([ 0.0061, -0.0056,

tensor([ 0.0057, -0.0051,  0.4547,  0.4519], requires_grad=True)
tensor([ 0.0061, -0.0056,  0.4544,  0.4519], requires_grad=True)
tensor([ 0.0065, -0.0055,  0.4544,  0.4520], requires_grad=True)
tensor([ 0.0063, -0.0057,  0.4540,  0.4522], requires_grad=True)
tensor([ 0.0063, -0.0063,  0.4536,  0.4522], requires_grad=True)
tensor([ 0.0054, -0.0065,  0.4546,  0.4521], requires_grad=True)
tensor([ 0.0055, -0.0067,  0.4546,  0.4518], requires_grad=True)
tensor([ 0.0057, -0.0068,  0.4546,  0.4516], requires_grad=True)
tensor([ 0.0060, -0.0065,  0.4553,  0.4513], requires_grad=True)
tensor([ 0.0061, -0.0066,  0.4554,  0.4511], requires_grad=True)
tensor([ 0.0065, -0.0064,  0.4559,  0.4507], requires_grad=True)
tensor([ 0.0064, -0.0066,  0.4558,  0.4505], requires_grad=True)
tensor([ 0.0061, -0.0069,  0.4555,  0.4503], requires_grad=True)
tensor([ 0.0059, -0.0073,  0.4560,  0.4500], requires_grad=True)
tensor([ 0.0059, -0.0074,  0.4565,  0.4496], requires_grad=True)
tensor([ 0.0054, -0.0072,

tensor([ 0.0106, -0.0026,  0.4701,  0.4547], requires_grad=True)
tensor([ 0.0107, -0.0025,  0.4700,  0.4545], requires_grad=True)
tensor([ 0.0107, -0.0026,  0.4699,  0.4542], requires_grad=True)
tensor([ 0.0107, -0.0025,  0.4700,  0.4550], requires_grad=True)
tensor([ 0.0107, -0.0024,  0.4703,  0.4552], requires_grad=True)
tensor([ 0.0105, -0.0025,  0.4700,  0.4555], requires_grad=True)
tensor([ 0.0100, -0.0026,  0.4699,  0.4555], requires_grad=True)
tensor([ 0.0106, -0.0024,  0.4702,  0.4552], requires_grad=True)
tensor([ 0.0111, -0.0021,  0.4701,  0.4553], requires_grad=True)
tensor([ 0.0113, -0.0024,  0.4699,  0.4553], requires_grad=True)
tensor([ 0.0111, -0.0024,  0.4697,  0.4552], requires_grad=True)
tensor([ 0.0107, -0.0025,  0.4697,  0.4552], requires_grad=True)
tensor([ 0.0114, -0.0027,  0.4700,  0.4550], requires_grad=True)
tensor([ 0.0124, -0.0026,  0.4707,  0.4548], requires_grad=True)
tensor([ 0.0121, -0.0023,  0.4704,  0.4548], requires_grad=True)
tensor([ 0.0123, -0.0020,

tensor([0.0066, 0.0038, 0.4789, 0.4643], requires_grad=True)
tensor([0.0065, 0.0040, 0.4787, 0.4650], requires_grad=True)
tensor([0.0066, 0.0037, 0.4783, 0.4648], requires_grad=True)
tensor([0.0067, 0.0037, 0.4783, 0.4655], requires_grad=True)
tensor([0.0068, 0.0034, 0.4782, 0.4652], requires_grad=True)
tensor([0.0067, 0.0029, 0.4778, 0.4656], requires_grad=True)
tensor([0.0066, 0.0031, 0.4778, 0.4656], requires_grad=True)
tensor([0.0067, 0.0032, 0.4776, 0.4655], requires_grad=True)
tensor([0.0065, 0.0034, 0.4778, 0.4654], requires_grad=True)
tensor([0.0060, 0.0036, 0.4786, 0.4651], requires_grad=True)
tensor([0.0057, 0.0037, 0.4790, 0.4649], requires_grad=True)
tensor([0.0051, 0.0038, 0.4795, 0.4647], requires_grad=True)
tensor([0.0053, 0.0037, 0.4798, 0.4645], requires_grad=True)
tensor([0.0052, 0.0042, 0.4795, 0.4643], requires_grad=True)
tensor([0.0050, 0.0040, 0.4794, 0.4640], requires_grad=True)
tensor([0.0056, 0.0042, 0.4796, 0.4647], requires_grad=True)
tensor([0.0052, 0.0041, 

tensor([0.0025, 0.0065, 0.4814, 0.4736], requires_grad=True)
tensor([0.0022, 0.0068, 0.4822, 0.4738], requires_grad=True)
tensor([0.0024, 0.0067, 0.4818, 0.4741], requires_grad=True)
tensor([0.0027, 0.0065, 0.4815, 0.4738], requires_grad=True)
tensor([0.0032, 0.0066, 0.4816, 0.4740], requires_grad=True)
tensor([0.0032, 0.0072, 0.4816, 0.4743], requires_grad=True)
tensor([0.0028, 0.0066, 0.4822, 0.4745], requires_grad=True)
tensor([0.0026, 0.0066, 0.4822, 0.4746], requires_grad=True)
tensor([0.0025, 0.0063, 0.4822, 0.4745], requires_grad=True)
tensor([0.0023, 0.0062, 0.4827, 0.4744], requires_grad=True)
tensor([0.0026, 0.0060, 0.4824, 0.4744], requires_grad=True)
tensor([0.0029, 0.0053, 0.4821, 0.4748], requires_grad=True)
tensor([0.0031, 0.0051, 0.4817, 0.4746], requires_grad=True)
tensor([0.0038, 0.0055, 0.4821, 0.4744], requires_grad=True)
tensor([0.0038, 0.0057, 0.4819, 0.4742], requires_grad=True)
tensor([0.0035, 0.0057, 0.4818, 0.4747], requires_grad=True)
tensor([0.0037, 0.0062, 

tensor([0.0058, 0.0061, 0.4858, 0.4777], requires_grad=True)
tensor([0.0059, 0.0065, 0.4859, 0.4779], requires_grad=True)
tensor([0.0061, 0.0061, 0.4857, 0.4776], requires_grad=True)
tensor([0.0062, 0.0067, 0.4854, 0.4776], requires_grad=True)
tensor([0.0057, 0.0074, 0.4854, 0.4778], requires_grad=True)
tensor([0.0058, 0.0071, 0.4855, 0.4777], requires_grad=True)
tensor([0.0062, 0.0069, 0.4854, 0.4776], requires_grad=True)
tensor([0.0067, 0.0069, 0.4853, 0.4775], requires_grad=True)
tensor([0.0070, 0.0068, 0.4852, 0.4777], requires_grad=True)
tensor([0.0065, 0.0071, 0.4852, 0.4773], requires_grad=True)
tensor([0.0066, 0.0068, 0.4847, 0.4777], requires_grad=True)
tensor([0.0065, 0.0072, 0.4844, 0.4783], requires_grad=True)
tensor([0.0067, 0.0067, 0.4851, 0.4786], requires_grad=True)
tensor([0.0067, 0.0060, 0.4856, 0.4788], requires_grad=True)
tensor([0.0069, 0.0061, 0.4853, 0.4789], requires_grad=True)
tensor([0.0062, 0.0063, 0.4858, 0.4787], requires_grad=True)
tensor([0.0063, 0.0066, 

tensor([-0.0020,  0.0111,  0.4939,  0.4801], requires_grad=True)
tensor([-0.0022,  0.0111,  0.4937,  0.4805], requires_grad=True)
tensor([-0.0022,  0.0107,  0.4938,  0.4806], requires_grad=True)
tensor([-0.0022,  0.0104,  0.4936,  0.4806], requires_grad=True)
tensor([-0.0022,  0.0112,  0.4936,  0.4808], requires_grad=True)
tensor([-0.0020,  0.0111,  0.4940,  0.4805], requires_grad=True)
tensor([-0.0021,  0.0109,  0.4941,  0.4809], requires_grad=True)
tensor([-0.0020,  0.0113,  0.4940,  0.4806], requires_grad=True)
tensor([-0.0019,  0.0118,  0.4944,  0.4808], requires_grad=True)
tensor([-0.0020,  0.0123,  0.4945,  0.4813], requires_grad=True)
tensor([-0.0021,  0.0121,  0.4945,  0.4814], requires_grad=True)
tensor([-0.0027,  0.0122,  0.4948,  0.4812], requires_grad=True)
tensor([-0.0024,  0.0115,  0.4952,  0.4813], requires_grad=True)
tensor([-0.0024,  0.0115,  0.4950,  0.4817], requires_grad=True)
tensor([-0.0018,  0.0114,  0.4951,  0.4814], requires_grad=True)
tensor([-0.0015,  0.0116,

tensor([-0.0053,  0.0136,  0.4994,  0.4872], requires_grad=True)
tensor([-0.0052,  0.0132,  0.4993,  0.4873], requires_grad=True)
tensor([-0.0049,  0.0133,  0.4992,  0.4870], requires_grad=True)
tensor([-0.0050,  0.0133,  0.4990,  0.4872], requires_grad=True)
tensor([-0.0052,  0.0129,  0.4985,  0.4874], requires_grad=True)
tensor([-0.0054,  0.0129,  0.4988,  0.4870], requires_grad=True)
tensor([-0.0052,  0.0131,  0.4988,  0.4866], requires_grad=True)
tensor([-0.0051,  0.0133,  0.4986,  0.4866], requires_grad=True)
tensor([-0.0047,  0.0137,  0.4981,  0.4865], requires_grad=True)
tensor([-0.0050,  0.0138,  0.4981,  0.4868], requires_grad=True)
tensor([-0.0052,  0.0137,  0.4981,  0.4866], requires_grad=True)
tensor([-0.0052,  0.0142,  0.4984,  0.4869], requires_grad=True)
tensor([-0.0048,  0.0145,  0.4988,  0.4867], requires_grad=True)
tensor([-0.0046,  0.0148,  0.4988,  0.4868], requires_grad=True)
tensor([-0.0047,  0.0146,  0.4984,  0.4873], requires_grad=True)
tensor([-0.0046,  0.0148,

tensor([-0.0091,  0.0137,  0.5018,  0.4905], requires_grad=True)
tensor([-0.0091,  0.0143,  0.5013,  0.4910], requires_grad=True)
tensor([-0.0093,  0.0136,  0.5013,  0.4910], requires_grad=True)
tensor([-0.0092,  0.0136,  0.5015,  0.4908], requires_grad=True)
tensor([-0.0094,  0.0137,  0.5013,  0.4905], requires_grad=True)
tensor([-0.0093,  0.0139,  0.5009,  0.4908], requires_grad=True)
tensor([-0.0090,  0.0141,  0.5015,  0.4909], requires_grad=True)
tensor([-0.0091,  0.0143,  0.5014,  0.4911], requires_grad=True)
tensor([-0.0092,  0.0142,  0.5013,  0.4909], requires_grad=True)
tensor([-0.0098,  0.0140,  0.5016,  0.4909], requires_grad=True)
tensor([-0.0099,  0.0142,  0.5014,  0.4905], requires_grad=True)
tensor([-0.0103,  0.0139,  0.5012,  0.4901], requires_grad=True)
tensor([-0.0100,  0.0137,  0.5011,  0.4901], requires_grad=True)
tensor([-0.0096,  0.0131,  0.5009,  0.4904], requires_grad=True)
tensor([-0.0095,  0.0132,  0.5009,  0.4908], requires_grad=True)
tensor([-0.0099,  0.0130,

tensor([-0.0078,  0.0081,  0.5055,  0.4955], requires_grad=True)
tensor([-0.0078,  0.0081,  0.5054,  0.4953], requires_grad=True)
tensor([-0.0081,  0.0080,  0.5055,  0.4949], requires_grad=True)
tensor([-0.0083,  0.0081,  0.5053,  0.4950], requires_grad=True)
tensor([-0.0085,  0.0080,  0.5054,  0.4946], requires_grad=True)
tensor([-0.0085,  0.0083,  0.5050,  0.4944], requires_grad=True)
tensor([-0.0082,  0.0084,  0.5051,  0.4950], requires_grad=True)
tensor([-0.0082,  0.0088,  0.5053,  0.4955], requires_grad=True)
tensor([-0.0083,  0.0087,  0.5049,  0.4959], requires_grad=True)
tensor([-0.0083,  0.0085,  0.5049,  0.4956], requires_grad=True)
tensor([-0.0079,  0.0082,  0.5052,  0.4958], requires_grad=True)
tensor([-0.0080,  0.0087,  0.5052,  0.4961], requires_grad=True)
tensor([-0.0083,  0.0090,  0.5056,  0.4958], requires_grad=True)
tensor([-0.0082,  0.0090,  0.5054,  0.4964], requires_grad=True)
tensor([-0.0087,  0.0091,  0.5055,  0.4965], requires_grad=True)
tensor([-0.0092,  0.0091,

tensor([-0.0101,  0.0035,  0.5038,  0.5107], requires_grad=True)
tensor([-0.0100,  0.0034,  0.5042,  0.5103], requires_grad=True)
tensor([-0.0102,  0.0027,  0.5042,  0.5107], requires_grad=True)
tensor([-0.0100,  0.0030,  0.5045,  0.5105], requires_grad=True)
tensor([-0.0098,  0.0036,  0.5046,  0.5105], requires_grad=True)
tensor([-0.0092,  0.0039,  0.5048,  0.5104], requires_grad=True)
tensor([-0.0091,  0.0041,  0.5051,  0.5103], requires_grad=True)
tensor([-0.0092,  0.0046,  0.5052,  0.5103], requires_grad=True)
tensor([-0.0091,  0.0051,  0.5058,  0.5102], requires_grad=True)
tensor([-0.0091,  0.0050,  0.5059,  0.5100], requires_grad=True)
tensor([-0.0093,  0.0053,  0.5063,  0.5105], requires_grad=True)
tensor([-0.0094,  0.0057,  0.5063,  0.5112], requires_grad=True)
tensor([-0.0097,  0.0057,  0.5062,  0.5109], requires_grad=True)
tensor([-0.0098,  0.0058,  0.5062,  0.5106], requires_grad=True)
tensor([-0.0096,  0.0053,  0.5060,  0.5104], requires_grad=True)
tensor([-0.0095,  0.0056,

tensor([-0.0109,  0.0064,  0.5113,  0.5141], requires_grad=True)
tensor([-0.0106,  0.0064,  0.5110,  0.5140], requires_grad=True)
tensor([-0.0101,  0.0064,  0.5112,  0.5142], requires_grad=True)
tensor([-0.0104,  0.0062,  0.5116,  0.5139], requires_grad=True)
tensor([-0.0102,  0.0069,  0.5114,  0.5143], requires_grad=True)
tensor([-0.0107,  0.0068,  0.5115,  0.5145], requires_grad=True)
tensor([-0.0104,  0.0072,  0.5117,  0.5148], requires_grad=True)
tensor([-0.0098,  0.0073,  0.5124,  0.5144], requires_grad=True)
tensor([-0.0100,  0.0073,  0.5129,  0.5143], requires_grad=True)
tensor([-0.0098,  0.0075,  0.5126,  0.5142], requires_grad=True)
tensor([-0.0100,  0.0071,  0.5129,  0.5138], requires_grad=True)
tensor([-0.0103,  0.0072,  0.5131,  0.5137], requires_grad=True)
tensor([-0.0105,  0.0073,  0.5135,  0.5134], requires_grad=True)
tensor([-0.0108,  0.0075,  0.5135,  0.5130], requires_grad=True)
tensor([-0.0113,  0.0070,  0.5133,  0.5129], requires_grad=True)
tensor([-0.0110,  0.0066,

tensor([-0.0087,  0.0056,  0.5139,  0.5170], requires_grad=True)
tensor([-0.0082,  0.0056,  0.5139,  0.5171], requires_grad=True)
tensor([-0.0087,  0.0059,  0.5139,  0.5171], requires_grad=True)
tensor([-0.0084,  0.0060,  0.5136,  0.5179], requires_grad=True)
tensor([-0.0080,  0.0062,  0.5134,  0.5183], requires_grad=True)
tensor([-0.0074,  0.0063,  0.5136,  0.5182], requires_grad=True)
tensor([-0.0074,  0.0064,  0.5136,  0.5185], requires_grad=True)
tensor([-0.0069,  0.0064,  0.5140,  0.5180], requires_grad=True)
tensor([-0.0070,  0.0059,  0.5135,  0.5179], requires_grad=True)
tensor([-0.0070,  0.0060,  0.5132,  0.5176], requires_grad=True)
tensor([-0.0070,  0.0061,  0.5132,  0.5176], requires_grad=True)
tensor([-0.0071,  0.0057,  0.5133,  0.5176], requires_grad=True)
tensor([-0.0069,  0.0060,  0.5137,  0.5173], requires_grad=True)
tensor([-0.0074,  0.0063,  0.5139,  0.5174], requires_grad=True)
tensor([-0.0072,  0.0063,  0.5138,  0.5169], requires_grad=True)
tensor([-0.0077,  0.0068,

tensor([-8.1930e-03,  4.3691e-04,  5.1482e-01,  5.1983e-01],
       requires_grad=True)
tensor([-0.0085,  0.0007,  0.5146,  0.5199], requires_grad=True)
tensor([-0.0087,  0.0009,  0.5146,  0.5196], requires_grad=True)
tensor([-0.0090,  0.0010,  0.5148,  0.5196], requires_grad=True)
tensor([-0.0096,  0.0010,  0.5148,  0.5194], requires_grad=True)
tensor([-0.0096,  0.0009,  0.5154,  0.5196], requires_grad=True)
tensor([-0.0095,  0.0010,  0.5158,  0.5194], requires_grad=True)
tensor([-0.0093,  0.0008,  0.5157,  0.5193], requires_grad=True)
tensor([-0.0097,  0.0012,  0.5160,  0.5191], requires_grad=True)
tensor([-0.0092,  0.0014,  0.5158,  0.5197], requires_grad=True)
tensor([-0.0097,  0.0013,  0.5163,  0.5202], requires_grad=True)
tensor([-0.0096,  0.0014,  0.5160,  0.5201], requires_grad=True)
tensor([-0.0095,  0.0009,  0.5161,  0.5199], requires_grad=True)
tensor([-0.0095,  0.0006,  0.5157,  0.5196], requires_grad=True)
tensor([-0.0091,  0.0006,  0.5154,  0.5196], requires_grad=True)
te

tensor([-0.0062,  0.0030,  0.5147,  0.5188], requires_grad=True)
tensor([-0.0055,  0.0034,  0.5154,  0.5188], requires_grad=True)
tensor([-0.0059,  0.0027,  0.5151,  0.5191], requires_grad=True)
tensor([-0.0058,  0.0029,  0.5149,  0.5195], requires_grad=True)
tensor([-0.0061,  0.0027,  0.5150,  0.5191], requires_grad=True)
tensor([-0.0062,  0.0027,  0.5151,  0.5190], requires_grad=True)
tensor([-0.0058,  0.0026,  0.5149,  0.5190], requires_grad=True)
tensor([-0.0055,  0.0029,  0.5147,  0.5187], requires_grad=True)
tensor([-0.0053,  0.0031,  0.5149,  0.5187], requires_grad=True)
tensor([-0.0056,  0.0036,  0.5146,  0.5190], requires_grad=True)
tensor([-0.0056,  0.0034,  0.5145,  0.5190], requires_grad=True)
tensor([-0.0058,  0.0033,  0.5144,  0.5187], requires_grad=True)
tensor([-0.0058,  0.0028,  0.5143,  0.5190], requires_grad=True)
tensor([-0.0059,  0.0028,  0.5141,  0.5186], requires_grad=True)
tensor([-0.0057,  0.0025,  0.5142,  0.5190], requires_grad=True)
tensor([-0.0059,  0.0024,

tensor([-0.0091,  0.0040,  0.5190,  0.5170], requires_grad=True)
tensor([-0.0088,  0.0044,  0.5188,  0.5168], requires_grad=True)
tensor([-0.0083,  0.0046,  0.5186,  0.5166], requires_grad=True)
tensor([-0.0092,  0.0046,  0.5191,  0.5164], requires_grad=True)
tensor([-0.0085,  0.0042,  0.5192,  0.5164], requires_grad=True)
tensor([-0.0093,  0.0041,  0.5193,  0.5160], requires_grad=True)
tensor([-0.0088,  0.0038,  0.5196,  0.5157], requires_grad=True)
tensor([-0.0094,  0.0040,  0.5197,  0.5157], requires_grad=True)
tensor([-0.0100,  0.0043,  0.5199,  0.5160], requires_grad=True)
tensor([-0.0105,  0.0045,  0.5199,  0.5160], requires_grad=True)
tensor([-0.0105,  0.0042,  0.5196,  0.5156], requires_grad=True)
tensor([-0.0104,  0.0040,  0.5195,  0.5156], requires_grad=True)
tensor([-0.0102,  0.0040,  0.5190,  0.5156], requires_grad=True)
tensor([-0.0101,  0.0039,  0.5192,  0.5161], requires_grad=True)
tensor([-0.0103,  0.0038,  0.5192,  0.5161], requires_grad=True)
tensor([-0.0096,  0.0037,

tensor([-0.0051,  0.0016,  0.5254,  0.5226], requires_grad=True)
tensor([-0.0047,  0.0012,  0.5257,  0.5228], requires_grad=True)
tensor([-0.0048,  0.0010,  0.5254,  0.5229], requires_grad=True)
tensor([-0.0047,  0.0011,  0.5259,  0.5230], requires_grad=True)
tensor([-0.0049,  0.0009,  0.5262,  0.5228], requires_grad=True)
tensor([-0.0052,  0.0009,  0.5263,  0.5228], requires_grad=True)
tensor([-0.0049,  0.0014,  0.5264,  0.5232], requires_grad=True)
tensor([-0.0052,  0.0015,  0.5265,  0.5234], requires_grad=True)
tensor([-0.0057,  0.0019,  0.5265,  0.5236], requires_grad=True)
tensor([-0.0057,  0.0014,  0.5267,  0.5236], requires_grad=True)
tensor([-0.0056,  0.0012,  0.5264,  0.5239], requires_grad=True)
tensor([-0.0057,  0.0019,  0.5260,  0.5244], requires_grad=True)
tensor([-0.0060,  0.0021,  0.5260,  0.5243], requires_grad=True)
tensor([-0.0060,  0.0019,  0.5258,  0.5238], requires_grad=True)
tensor([-0.0060,  0.0023,  0.5253,  0.5238], requires_grad=True)
tensor([-0.0061,  0.0025,

tensor([-0.0014,  0.0028,  0.5234,  0.5209], requires_grad=True)
tensor([-0.0009,  0.0026,  0.5233,  0.5208], requires_grad=True)
tensor([-0.0014,  0.0019,  0.5233,  0.5211], requires_grad=True)
tensor([-0.0021,  0.0018,  0.5233,  0.5208], requires_grad=True)
tensor([-0.0022,  0.0015,  0.5233,  0.5210], requires_grad=True)
tensor([-0.0026,  0.0023,  0.5240,  0.5216], requires_grad=True)
tensor([-0.0027,  0.0025,  0.5242,  0.5215], requires_grad=True)
tensor([-0.0024,  0.0023,  0.5241,  0.5213], requires_grad=True)
tensor([-0.0025,  0.0028,  0.5241,  0.5211], requires_grad=True)
tensor([-0.0028,  0.0026,  0.5241,  0.5210], requires_grad=True)
tensor([-0.0028,  0.0029,  0.5238,  0.5214], requires_grad=True)
tensor([-0.0035,  0.0026,  0.5238,  0.5226], requires_grad=True)
tensor([-0.0027,  0.0028,  0.5240,  0.5224], requires_grad=True)
tensor([-0.0028,  0.0029,  0.5238,  0.5222], requires_grad=True)
tensor([-0.0026,  0.0024,  0.5237,  0.5227], requires_grad=True)
tensor([-0.0026,  0.0023,

tensor([-0.0013,  0.0038,  0.5216,  0.5276], requires_grad=True)
tensor([-0.0015,  0.0045,  0.5221,  0.5282], requires_grad=True)
tensor([-0.0017,  0.0042,  0.5222,  0.5285], requires_grad=True)
tensor([-0.0016,  0.0040,  0.5223,  0.5288], requires_grad=True)
tensor([-0.0017,  0.0044,  0.5225,  0.5286], requires_grad=True)
tensor([-0.0017,  0.0043,  0.5228,  0.5286], requires_grad=True)
tensor([-0.0022,  0.0043,  0.5228,  0.5285], requires_grad=True)
tensor([-0.0020,  0.0049,  0.5232,  0.5285], requires_grad=True)
tensor([-0.0021,  0.0047,  0.5232,  0.5284], requires_grad=True)
tensor([-0.0026,  0.0048,  0.5231,  0.5286], requires_grad=True)
tensor([-0.0028,  0.0052,  0.5235,  0.5282], requires_grad=True)
tensor([-0.0023,  0.0053,  0.5237,  0.5278], requires_grad=True)
tensor([-0.0015,  0.0056,  0.5237,  0.5279], requires_grad=True)
tensor([-0.0019,  0.0059,  0.5236,  0.5283], requires_grad=True)
tensor([-0.0012,  0.0060,  0.5240,  0.5281], requires_grad=True)
tensor([-0.0011,  0.0056,

tensor([0.0031, 0.0078, 0.5224, 0.5278], requires_grad=True)
tensor([0.0033, 0.0078, 0.5224, 0.5277], requires_grad=True)
tensor([0.0040, 0.0079, 0.5228, 0.5277], requires_grad=True)
tensor([0.0034, 0.0085, 0.5231, 0.5277], requires_grad=True)
tensor([0.0030, 0.0086, 0.5229, 0.5276], requires_grad=True)
tensor([0.0033, 0.0082, 0.5230, 0.5275], requires_grad=True)
tensor([0.0031, 0.0087, 0.5229, 0.5276], requires_grad=True)
tensor([0.0028, 0.0083, 0.5232, 0.5273], requires_grad=True)
tensor([0.0031, 0.0078, 0.5228, 0.5272], requires_grad=True)
tensor([0.0033, 0.0078, 0.5230, 0.5270], requires_grad=True)
tensor([0.0032, 0.0076, 0.5233, 0.5270], requires_grad=True)
tensor([0.0030, 0.0078, 0.5230, 0.5270], requires_grad=True)
tensor([0.0028, 0.0075, 0.5226, 0.5270], requires_grad=True)
tensor([0.0029, 0.0065, 0.5227, 0.5277], requires_grad=True)
tensor([0.0031, 0.0063, 0.5225, 0.5275], requires_grad=True)
tensor([0.0035, 0.0066, 0.5228, 0.5274], requires_grad=True)
tensor([0.0036, 0.0062, 

tensor([0.0037, 0.0049, 0.5256, 0.5306], requires_grad=True)
tensor([0.0035, 0.0051, 0.5259, 0.5303], requires_grad=True)
tensor([0.0039, 0.0053, 0.5256, 0.5309], requires_grad=True)
tensor([0.0040, 0.0056, 0.5259, 0.5310], requires_grad=True)
tensor([0.0041, 0.0058, 0.5255, 0.5314], requires_grad=True)
tensor([0.0042, 0.0057, 0.5252, 0.5313], requires_grad=True)
tensor([0.0040, 0.0056, 0.5255, 0.5315], requires_grad=True)
tensor([0.0041, 0.0056, 0.5254, 0.5312], requires_grad=True)
tensor([0.0035, 0.0056, 0.5258, 0.5309], requires_grad=True)
tensor([0.0038, 0.0053, 0.5262, 0.5309], requires_grad=True)
tensor([0.0039, 0.0059, 0.5258, 0.5308], requires_grad=True)
tensor([0.0041, 0.0060, 0.5259, 0.5309], requires_grad=True)
tensor([0.0038, 0.0067, 0.5260, 0.5310], requires_grad=True)
tensor([0.0039, 0.0066, 0.5265, 0.5312], requires_grad=True)
tensor([0.0038, 0.0065, 0.5264, 0.5312], requires_grad=True)
tensor([0.0037, 0.0064, 0.5261, 0.5313], requires_grad=True)
tensor([0.0036, 0.0064, 

tensor([7.3353e-06, 4.1777e-03, 5.2743e-01, 5.3518e-01], requires_grad=True)
tensor([-4.7423e-04,  4.2724e-03,  5.2744e-01,  5.3518e-01],
       requires_grad=True)
tensor([-0.0006,  0.0045,  0.5275,  0.5353], requires_grad=True)
tensor([-0.0009,  0.0039,  0.5272,  0.5355], requires_grad=True)
tensor([-0.0011,  0.0043,  0.5274,  0.5358], requires_grad=True)
tensor([-0.0008,  0.0038,  0.5270,  0.5365], requires_grad=True)
tensor([-0.0009,  0.0037,  0.5267,  0.5368], requires_grad=True)
tensor([-0.0008,  0.0041,  0.5262,  0.5367], requires_grad=True)
tensor([-0.0011,  0.0040,  0.5265,  0.5366], requires_grad=True)
tensor([-0.0011,  0.0038,  0.5272,  0.5364], requires_grad=True)
tensor([-0.0015,  0.0041,  0.5270,  0.5367], requires_grad=True)
tensor([-0.0014,  0.0040,  0.5274,  0.5365], requires_grad=True)
tensor([-0.0012,  0.0040,  0.5272,  0.5361], requires_grad=True)
tensor([-0.0009,  0.0042,  0.5269,  0.5359], requires_grad=True)
tensor([-0.0009,  0.0038,  0.5269,  0.5359], requires_g

       requires_grad=True)
tensor([-3.1590e-04,  3.1814e-03,  5.2720e-01,  5.3776e-01],
       requires_grad=True)
tensor([-5.3117e-04,  2.6906e-03,  5.2749e-01,  5.3784e-01],
       requires_grad=True)
tensor([1.3624e-04, 3.0885e-03, 5.2745e-01, 5.3775e-01], requires_grad=True)
tensor([2.9786e-04, 2.9573e-03, 5.2727e-01, 5.3788e-01], requires_grad=True)
tensor([-0.0006,  0.0029,  0.5277,  0.5377], requires_grad=True)
tensor([-4.9691e-04,  2.9445e-03,  5.2740e-01,  5.3756e-01],
       requires_grad=True)
tensor([-1.6488e-04,  2.9184e-03,  5.2696e-01,  5.3730e-01],
       requires_grad=True)
tensor([-6.6714e-05,  2.5945e-03,  5.2703e-01,  5.3713e-01],
       requires_grad=True)
tensor([-0.0008,  0.0029,  0.5276,  0.5368], requires_grad=True)
tensor([-4.3303e-04,  3.1465e-03,  5.2788e-01,  5.3712e-01],
       requires_grad=True)
tensor([-0.0006,  0.0030,  0.5276,  0.5371], requires_grad=True)
tensor([-0.0006,  0.0030,  0.5276,  0.5375], requires_grad=True)
tensor([-2.4056e-04,  3.3470e-0

tensor([-2.6196e-03, -1.3315e-04,  5.2684e-01,  5.3312e-01],
       requires_grad=True)
tensor([-2.7038e-03, -3.1499e-05,  5.2732e-01,  5.3284e-01],
       requires_grad=True)
tensor([-2.9061e-03, -2.0444e-04,  5.2731e-01,  5.3317e-01],
       requires_grad=True)
tensor([-1.9496e-03, -4.0978e-04,  5.2814e-01,  5.3329e-01],
       requires_grad=True)
tensor([-2.0058e-03,  6.1415e-05,  5.2791e-01,  5.3310e-01],
       requires_grad=True)
tensor([-2.5129e-03, -1.6889e-04,  5.2790e-01,  5.3310e-01],
       requires_grad=True)
tensor([-2.1478e-03,  1.4641e-04,  5.2817e-01,  5.3355e-01],
       requires_grad=True)
tensor([-2.0510e-03,  3.7604e-04,  5.2830e-01,  5.3309e-01],
       requires_grad=True)
tensor([-0.0014,  0.0007,  0.5283,  0.5332], requires_grad=True)
tensor([-0.0010,  0.0009,  0.5285,  0.5332], requires_grad=True)
tensor([-0.0011,  0.0006,  0.5283,  0.5332], requires_grad=True)
tensor([-0.0016,  0.0008,  0.5285,  0.5330], requires_grad=True)
tensor([-8.9285e-04,  4.4130e-04,  5

tensor([-2.6132e-03,  4.4640e-04,  5.2355e-01,  5.3206e-01],
       requires_grad=True)
tensor([-0.0026,  0.0008,  0.5233,  0.5321], requires_grad=True)
tensor([-2.5278e-03,  3.2749e-04,  5.2319e-01,  5.3203e-01],
       requires_grad=True)
tensor([-2.2678e-03,  8.7650e-05,  5.2397e-01,  5.3179e-01],
       requires_grad=True)
tensor([-0.0023,  0.0006,  0.5238,  0.5320], requires_grad=True)
tensor([-0.0026,  0.0009,  0.5235,  0.5318], requires_grad=True)
tensor([-0.0028,  0.0008,  0.5236,  0.5315], requires_grad=True)
tensor([-0.0023,  0.0009,  0.5234,  0.5315], requires_grad=True)
tensor([-0.0022,  0.0007,  0.5230,  0.5314], requires_grad=True)
tensor([-2.3869e-03,  4.5362e-04,  5.2323e-01,  5.3165e-01],
       requires_grad=True)
tensor([-0.0027,  0.0005,  0.5233,  0.5317], requires_grad=True)
tensor([-0.0025,  0.0007,  0.5233,  0.5317], requires_grad=True)
tensor([-0.0021,  0.0006,  0.5233,  0.5315], requires_grad=True)
tensor([-0.0020,  0.0010,  0.5233,  0.5315], requires_grad=True

tensor([-0.0021, -0.0036,  0.5188,  0.5276], requires_grad=True)
tensor([-0.0019, -0.0036,  0.5185,  0.5273], requires_grad=True)
tensor([-0.0013, -0.0033,  0.5187,  0.5271], requires_grad=True)
tensor([-0.0010, -0.0032,  0.5185,  0.5272], requires_grad=True)
tensor([-0.0013, -0.0028,  0.5185,  0.5273], requires_grad=True)
tensor([-0.0013, -0.0032,  0.5189,  0.5270], requires_grad=True)
tensor([-0.0015, -0.0034,  0.5188,  0.5270], requires_grad=True)
tensor([-0.0017, -0.0032,  0.5187,  0.5271], requires_grad=True)
tensor([-0.0019, -0.0034,  0.5193,  0.5270], requires_grad=True)
tensor([-0.0023, -0.0032,  0.5192,  0.5269], requires_grad=True)
tensor([-0.0023, -0.0027,  0.5191,  0.5268], requires_grad=True)
tensor([-0.0025, -0.0024,  0.5192,  0.5269], requires_grad=True)
tensor([-0.0023, -0.0022,  0.5192,  0.5268], requires_grad=True)
tensor([-0.0022, -0.0022,  0.5190,  0.5265], requires_grad=True)
tensor([-0.0026, -0.0022,  0.5197,  0.5263], requires_grad=True)
tensor([-0.0025, -0.0020,

tensor([-0.0014, -0.0031,  0.5220,  0.5259], requires_grad=True)
tensor([-0.0015, -0.0027,  0.5221,  0.5255], requires_grad=True)
tensor([-0.0012, -0.0029,  0.5221,  0.5255], requires_grad=True)
tensor([-0.0013, -0.0029,  0.5219,  0.5263], requires_grad=True)
tensor([-0.0017, -0.0029,  0.5222,  0.5265], requires_grad=True)
tensor([-0.0014, -0.0024,  0.5219,  0.5268], requires_grad=True)
tensor([-0.0015, -0.0024,  0.5217,  0.5273], requires_grad=True)
tensor([-0.0012, -0.0021,  0.5220,  0.5271], requires_grad=True)
tensor([-0.0019, -0.0020,  0.5223,  0.5269], requires_grad=True)
tensor([-0.0015, -0.0018,  0.5224,  0.5270], requires_grad=True)
tensor([-0.0012, -0.0019,  0.5223,  0.5270], requires_grad=True)
tensor([-0.0011, -0.0022,  0.5219,  0.5267], requires_grad=True)
tensor([-0.0010, -0.0020,  0.5215,  0.5263], requires_grad=True)
tensor([-5.0239e-04, -2.3157e-03,  5.2175e-01,  5.2599e-01],
       requires_grad=True)
tensor([-0.0009, -0.0031,  0.5219,  0.5262], requires_grad=True)
te

tensor([ 0.0026, -0.0028,  0.5249,  0.5273], requires_grad=True)
tensor([ 0.0027, -0.0028,  0.5248,  0.5269], requires_grad=True)
tensor([ 0.0026, -0.0023,  0.5247,  0.5271], requires_grad=True)
tensor([ 0.0023, -0.0018,  0.5244,  0.5269], requires_grad=True)
tensor([ 0.0027, -0.0021,  0.5244,  0.5274], requires_grad=True)
tensor([ 0.0032, -0.0021,  0.5246,  0.5269], requires_grad=True)
tensor([ 0.0034, -0.0016,  0.5246,  0.5271], requires_grad=True)
tensor([ 0.0036, -0.0013,  0.5241,  0.5273], requires_grad=True)
tensor([ 0.0035, -0.0015,  0.5242,  0.5272], requires_grad=True)
tensor([ 0.0037, -0.0019,  0.5243,  0.5271], requires_grad=True)
tensor([ 0.0038, -0.0017,  0.5241,  0.5270], requires_grad=True)
tensor([ 0.0041, -0.0023,  0.5239,  0.5272], requires_grad=True)
tensor([ 0.0040, -0.0020,  0.5241,  0.5268], requires_grad=True)
tensor([ 0.0043, -0.0020,  0.5238,  0.5264], requires_grad=True)
tensor([ 0.0037, -0.0016,  0.5240,  0.5262], requires_grad=True)
tensor([ 0.0039, -0.0018,

tensor([-0.0014, -0.0091,  0.5273,  0.5284], requires_grad=True)
tensor([-0.0012, -0.0093,  0.5274,  0.5282], requires_grad=True)
tensor([-0.0016, -0.0083,  0.5274,  0.5290], requires_grad=True)
tensor([-0.0011, -0.0079,  0.5275,  0.5291], requires_grad=True)
tensor([-0.0011, -0.0077,  0.5286,  0.5291], requires_grad=True)
tensor([-0.0011, -0.0080,  0.5291,  0.5292], requires_grad=True)
tensor([-0.0016, -0.0084,  0.5290,  0.5296], requires_grad=True)
tensor([-0.0014, -0.0082,  0.5291,  0.5296], requires_grad=True)
tensor([-0.0019, -0.0082,  0.5289,  0.5299], requires_grad=True)
tensor([-0.0020, -0.0078,  0.5287,  0.5297], requires_grad=True)
tensor([-0.0031, -0.0078,  0.5293,  0.5295], requires_grad=True)
tensor([-0.0029, -0.0076,  0.5289,  0.5298], requires_grad=True)
tensor([-0.0028, -0.0074,  0.5286,  0.5294], requires_grad=True)
tensor([-0.0027, -0.0072,  0.5286,  0.5291], requires_grad=True)
tensor([-0.0027, -0.0073,  0.5283,  0.5297], requires_grad=True)
tensor([-0.0030, -0.0077,

tensor([-0.0066, -0.0086,  0.5302,  0.5292], requires_grad=True)
tensor([-0.0065, -0.0086,  0.5302,  0.5293], requires_grad=True)
tensor([-0.0070, -0.0086,  0.5305,  0.5290], requires_grad=True)
tensor([-0.0076, -0.0085,  0.5310,  0.5289], requires_grad=True)
tensor([-0.0076, -0.0085,  0.5313,  0.5288], requires_grad=True)
tensor([-0.0073, -0.0084,  0.5309,  0.5286], requires_grad=True)
tensor([-0.0074, -0.0081,  0.5309,  0.5289], requires_grad=True)
tensor([-0.0074, -0.0088,  0.5309,  0.5294], requires_grad=True)
tensor([-0.0071, -0.0091,  0.5309,  0.5293], requires_grad=True)
tensor([-0.0071, -0.0093,  0.5308,  0.5293], requires_grad=True)
tensor([-0.0077, -0.0093,  0.5310,  0.5297], requires_grad=True)
tensor([-0.0080, -0.0097,  0.5311,  0.5298], requires_grad=True)
tensor([-0.0082, -0.0096,  0.5312,  0.5294], requires_grad=True)
tensor([-0.0078, -0.0102,  0.5319,  0.5297], requires_grad=True)
tensor([-0.0077, -0.0102,  0.5319,  0.5297], requires_grad=True)
tensor([-0.0078, -0.0102,

tensor([-0.0088, -0.0096,  0.5345,  0.5303], requires_grad=True)
tensor([-0.0088, -0.0106,  0.5345,  0.5308], requires_grad=True)
tensor([-0.0085, -0.0107,  0.5345,  0.5306], requires_grad=True)
tensor([-0.0081, -0.0108,  0.5343,  0.5303], requires_grad=True)
tensor([-0.0084, -0.0103,  0.5341,  0.5305], requires_grad=True)
tensor([-0.0081, -0.0104,  0.5341,  0.5303], requires_grad=True)
tensor([-0.0085, -0.0102,  0.5338,  0.5301], requires_grad=True)
tensor([-0.0080, -0.0101,  0.5340,  0.5299], requires_grad=True)
tensor([-0.0082, -0.0106,  0.5342,  0.5310], requires_grad=True)
tensor([-0.0087, -0.0103,  0.5345,  0.5312], requires_grad=True)
tensor([-0.0085, -0.0105,  0.5349,  0.5308], requires_grad=True)
tensor([-0.0081, -0.0109,  0.5349,  0.5308], requires_grad=True)
tensor([-0.0076, -0.0104,  0.5352,  0.5312], requires_grad=True)
tensor([-0.0071, -0.0107,  0.5348,  0.5312], requires_grad=True)
tensor([-0.0071, -0.0107,  0.5346,  0.5310], requires_grad=True)
tensor([-0.0071, -0.0102,

tensor([-0.0100, -0.0075,  0.5375,  0.5292], requires_grad=True)
tensor([-0.0100, -0.0074,  0.5373,  0.5292], requires_grad=True)
tensor([-0.0100, -0.0076,  0.5371,  0.5297], requires_grad=True)
tensor([-0.0103, -0.0078,  0.5373,  0.5297], requires_grad=True)
tensor([-0.0099, -0.0079,  0.5373,  0.5294], requires_grad=True)
tensor([-0.0102, -0.0081,  0.5371,  0.5302], requires_grad=True)
tensor([-0.0097, -0.0083,  0.5371,  0.5302], requires_grad=True)
tensor([-0.0103, -0.0078,  0.5372,  0.5305], requires_grad=True)
tensor([-0.0103, -0.0079,  0.5372,  0.5318], requires_grad=True)
tensor([-0.0104, -0.0079,  0.5368,  0.5317], requires_grad=True)
tensor([-0.0101, -0.0087,  0.5368,  0.5322], requires_grad=True)
tensor([-0.0103, -0.0092,  0.5364,  0.5319], requires_grad=True)
tensor([-0.0102, -0.0090,  0.5361,  0.5322], requires_grad=True)
tensor([-0.0106, -0.0089,  0.5358,  0.5322], requires_grad=True)
tensor([-0.0105, -0.0082,  0.5356,  0.5328], requires_grad=True)
tensor([-0.0109, -0.0087,

tensor([-0.0105, -0.0098,  0.5390,  0.5316], requires_grad=True)
tensor([-0.0099, -0.0096,  0.5390,  0.5314], requires_grad=True)
tensor([-0.0099, -0.0093,  0.5388,  0.5314], requires_grad=True)
tensor([-0.0099, -0.0091,  0.5388,  0.5314], requires_grad=True)
tensor([-0.0098, -0.0095,  0.5387,  0.5315], requires_grad=True)
tensor([-0.0100, -0.0098,  0.5383,  0.5315], requires_grad=True)
tensor([-0.0102, -0.0094,  0.5380,  0.5314], requires_grad=True)
tensor([-0.0108, -0.0094,  0.5381,  0.5311], requires_grad=True)
tensor([-0.0102, -0.0099,  0.5385,  0.5310], requires_grad=True)
tensor([-0.0098, -0.0102,  0.5385,  0.5307], requires_grad=True)
tensor([-0.0093, -0.0106,  0.5386,  0.5312], requires_grad=True)
tensor([-0.0096, -0.0103,  0.5383,  0.5319], requires_grad=True)
tensor([-0.0092, -0.0105,  0.5379,  0.5317], requires_grad=True)
tensor([-0.0093, -0.0104,  0.5377,  0.5316], requires_grad=True)
tensor([-0.0097, -0.0103,  0.5381,  0.5319], requires_grad=True)
tensor([-0.0096, -0.0102,

tensor([-0.0065, -0.0162,  0.5375,  0.5364], requires_grad=True)
tensor([-0.0061, -0.0160,  0.5372,  0.5364], requires_grad=True)
tensor([-0.0059, -0.0161,  0.5370,  0.5362], requires_grad=True)
tensor([-0.0060, -0.0161,  0.5373,  0.5360], requires_grad=True)
tensor([-0.0060, -0.0164,  0.5371,  0.5358], requires_grad=True)
tensor([-0.0059, -0.0165,  0.5369,  0.5358], requires_grad=True)
tensor([-0.0061, -0.0162,  0.5373,  0.5359], requires_grad=True)
tensor([-0.0063, -0.0160,  0.5371,  0.5358], requires_grad=True)
tensor([-0.0063, -0.0159,  0.5369,  0.5359], requires_grad=True)
tensor([-0.0063, -0.0158,  0.5365,  0.5356], requires_grad=True)
tensor([-0.0062, -0.0161,  0.5366,  0.5357], requires_grad=True)
tensor([-0.0053, -0.0162,  0.5372,  0.5360], requires_grad=True)
tensor([-0.0053, -0.0159,  0.5372,  0.5360], requires_grad=True)
tensor([-0.0056, -0.0163,  0.5373,  0.5361], requires_grad=True)
tensor([-0.0051, -0.0165,  0.5374,  0.5362], requires_grad=True)
tensor([-0.0050, -0.0167,

tensor([ 0.0039, -0.0160,  0.5353,  0.5316], requires_grad=True)
tensor([ 0.0041, -0.0163,  0.5351,  0.5313], requires_grad=True)
tensor([ 0.0040, -0.0161,  0.5349,  0.5310], requires_grad=True)
tensor([ 0.0041, -0.0165,  0.5348,  0.5309], requires_grad=True)
tensor([ 0.0045, -0.0161,  0.5350,  0.5307], requires_grad=True)
tensor([ 0.0045, -0.0158,  0.5347,  0.5306], requires_grad=True)
tensor([ 0.0043, -0.0158,  0.5350,  0.5309], requires_grad=True)
tensor([ 0.0043, -0.0156,  0.5350,  0.5306], requires_grad=True)
tensor([ 0.0041, -0.0158,  0.5349,  0.5301], requires_grad=True)
tensor([ 0.0041, -0.0157,  0.5347,  0.5305], requires_grad=True)
tensor([ 0.0038, -0.0155,  0.5346,  0.5310], requires_grad=True)
tensor([ 0.0033, -0.0156,  0.5354,  0.5315], requires_grad=True)
tensor([ 0.0033, -0.0153,  0.5351,  0.5320], requires_grad=True)
tensor([ 0.0034, -0.0154,  0.5352,  0.5320], requires_grad=True)
tensor([ 0.0041, -0.0148,  0.5355,  0.5320], requires_grad=True)
tensor([ 0.0041, -0.0148,

tensor([ 0.0094, -0.0168,  0.5340,  0.5350], requires_grad=True)
tensor([ 0.0095, -0.0169,  0.5337,  0.5351], requires_grad=True)
tensor([ 0.0097, -0.0172,  0.5339,  0.5350], requires_grad=True)
tensor([ 0.0091, -0.0172,  0.5339,  0.5348], requires_grad=True)
tensor([ 0.0096, -0.0168,  0.5339,  0.5348], requires_grad=True)
tensor([ 0.0098, -0.0167,  0.5344,  0.5346], requires_grad=True)
tensor([ 0.0098, -0.0168,  0.5343,  0.5346], requires_grad=True)
tensor([ 0.0101, -0.0168,  0.5344,  0.5355], requires_grad=True)
tensor([ 0.0105, -0.0169,  0.5344,  0.5352], requires_grad=True)
tensor([ 0.0107, -0.0166,  0.5340,  0.5352], requires_grad=True)
tensor([ 0.0107, -0.0161,  0.5340,  0.5359], requires_grad=True)
tensor([ 0.0101, -0.0164,  0.5339,  0.5356], requires_grad=True)
tensor([ 0.0099, -0.0161,  0.5342,  0.5356], requires_grad=True)
tensor([ 0.0098, -0.0166,  0.5344,  0.5357], requires_grad=True)
tensor([ 0.0098, -0.0163,  0.5346,  0.5358], requires_grad=True)
tensor([ 0.0097, -0.0162,

tensor([ 0.0115, -0.0125,  0.5330,  0.5360], requires_grad=True)
tensor([ 0.0115, -0.0131,  0.5331,  0.5358], requires_grad=True)
tensor([ 0.0114, -0.0128,  0.5326,  0.5355], requires_grad=True)
tensor([ 0.0112, -0.0130,  0.5326,  0.5356], requires_grad=True)
tensor([ 0.0115, -0.0130,  0.5325,  0.5360], requires_grad=True)
tensor([ 0.0115, -0.0125,  0.5321,  0.5358], requires_grad=True)
tensor([ 0.0117, -0.0130,  0.5321,  0.5357], requires_grad=True)
tensor([ 0.0118, -0.0129,  0.5319,  0.5356], requires_grad=True)
tensor([ 0.0117, -0.0128,  0.5317,  0.5357], requires_grad=True)
tensor([ 0.0118, -0.0121,  0.5315,  0.5360], requires_grad=True)
tensor([ 0.0120, -0.0118,  0.5313,  0.5359], requires_grad=True)
tensor([ 0.0118, -0.0113,  0.5317,  0.5358], requires_grad=True)
tensor([ 0.0115, -0.0119,  0.5321,  0.5359], requires_grad=True)
tensor([ 0.0118, -0.0117,  0.5320,  0.5355], requires_grad=True)
tensor([ 0.0123, -0.0116,  0.5325,  0.5353], requires_grad=True)
tensor([ 0.0125, -0.0116,

tensor([ 0.0138, -0.0098,  0.5346,  0.5361], requires_grad=True)
tensor([ 0.0141, -0.0099,  0.5356,  0.5362], requires_grad=True)
tensor([ 0.0142, -0.0098,  0.5367,  0.5358], requires_grad=True)
tensor([ 0.0150, -0.0095,  0.5371,  0.5355], requires_grad=True)
tensor([ 0.0151, -0.0092,  0.5370,  0.5353], requires_grad=True)
tensor([ 0.0153, -0.0086,  0.5367,  0.5358], requires_grad=True)
tensor([ 0.0154, -0.0089,  0.5368,  0.5361], requires_grad=True)
tensor([ 0.0149, -0.0089,  0.5375,  0.5360], requires_grad=True)
tensor([ 0.0147, -0.0089,  0.5374,  0.5363], requires_grad=True)
tensor([ 0.0147, -0.0093,  0.5373,  0.5364], requires_grad=True)
tensor([ 0.0148, -0.0093,  0.5374,  0.5362], requires_grad=True)
tensor([ 0.0145, -0.0096,  0.5374,  0.5364], requires_grad=True)
tensor([ 0.0143, -0.0095,  0.5375,  0.5360], requires_grad=True)
tensor([ 0.0139, -0.0089,  0.5373,  0.5363], requires_grad=True)
tensor([ 0.0145, -0.0091,  0.5378,  0.5361], requires_grad=True)
tensor([ 0.0148, -0.0091,

tensor([ 0.0107, -0.0057,  0.5387,  0.5350], requires_grad=True)
tensor([ 0.0111, -0.0059,  0.5390,  0.5351], requires_grad=True)
tensor([ 0.0114, -0.0060,  0.5391,  0.5352], requires_grad=True)
tensor([ 0.0115, -0.0059,  0.5386,  0.5350], requires_grad=True)
tensor([ 0.0111, -0.0058,  0.5387,  0.5351], requires_grad=True)
tensor([ 0.0106, -0.0054,  0.5393,  0.5353], requires_grad=True)
tensor([ 0.0103, -0.0056,  0.5393,  0.5352], requires_grad=True)
tensor([ 0.0102, -0.0060,  0.5395,  0.5350], requires_grad=True)
tensor([ 0.0104, -0.0054,  0.5398,  0.5356], requires_grad=True)
tensor([ 0.0106, -0.0059,  0.5399,  0.5357], requires_grad=True)
tensor([ 0.0112, -0.0059,  0.5398,  0.5357], requires_grad=True)
tensor([ 0.0117, -0.0063,  0.5397,  0.5361], requires_grad=True)
tensor([ 0.0120, -0.0055,  0.5398,  0.5364], requires_grad=True)
tensor([ 0.0120, -0.0052,  0.5392,  0.5363], requires_grad=True)
tensor([ 0.0119, -0.0054,  0.5392,  0.5362], requires_grad=True)
tensor([ 0.0117, -0.0055,

tensor([ 0.0063, -0.0055,  0.5393,  0.5299], requires_grad=True)
tensor([ 0.0062, -0.0055,  0.5394,  0.5297], requires_grad=True)
tensor([ 0.0064, -0.0058,  0.5399,  0.5299], requires_grad=True)
tensor([ 0.0067, -0.0061,  0.5396,  0.5299], requires_grad=True)
tensor([ 0.0068, -0.0062,  0.5394,  0.5299], requires_grad=True)
tensor([ 0.0072, -0.0062,  0.5395,  0.5294], requires_grad=True)
tensor([ 0.0070, -0.0063,  0.5398,  0.5294], requires_grad=True)
tensor([ 0.0074, -0.0066,  0.5400,  0.5289], requires_grad=True)
tensor([ 0.0068, -0.0065,  0.5401,  0.5289], requires_grad=True)
tensor([ 0.0064, -0.0061,  0.5403,  0.5290], requires_grad=True)
tensor([ 0.0063, -0.0061,  0.5401,  0.5287], requires_grad=True)
tensor([ 0.0063, -0.0060,  0.5400,  0.5286], requires_grad=True)
tensor([ 0.0058, -0.0060,  0.5399,  0.5286], requires_grad=True)
tensor([ 0.0054, -0.0061,  0.5396,  0.5284], requires_grad=True)
tensor([ 0.0053, -0.0058,  0.5393,  0.5280], requires_grad=True)
tensor([ 0.0054, -0.0061,

tensor([0.0034, 0.0011, 0.5396, 0.5272], requires_grad=True)
tensor([0.0032, 0.0010, 0.5392, 0.5269], requires_grad=True)
tensor([0.0032, 0.0006, 0.5394, 0.5275], requires_grad=True)
tensor([0.0036, 0.0008, 0.5393, 0.5279], requires_grad=True)
tensor([0.0041, 0.0009, 0.5400, 0.5278], requires_grad=True)
tensor([0.0045, 0.0012, 0.5404, 0.5281], requires_grad=True)
tensor([0.0041, 0.0011, 0.5405, 0.5281], requires_grad=True)
tensor([0.0039, 0.0011, 0.5401, 0.5285], requires_grad=True)
tensor([0.0041, 0.0012, 0.5402, 0.5282], requires_grad=True)
tensor([0.0039, 0.0011, 0.5402, 0.5282], requires_grad=True)
tensor([0.0042, 0.0010, 0.5402, 0.5278], requires_grad=True)
tensor([0.0042, 0.0009, 0.5401, 0.5276], requires_grad=True)
tensor([0.0042, 0.0009, 0.5403, 0.5276], requires_grad=True)
tensor([0.0053, 0.0012, 0.5412, 0.5272], requires_grad=True)
tensor([0.0055, 0.0014, 0.5415, 0.5277], requires_grad=True)
tensor([0.0054, 0.0011, 0.5414, 0.5273], requires_grad=True)
tensor([0.0058, 0.0010, 

tensor([ 0.0039, -0.0038,  0.5428,  0.5307], requires_grad=True)
tensor([ 0.0040, -0.0038,  0.5433,  0.5307], requires_grad=True)
tensor([ 0.0044, -0.0039,  0.5434,  0.5308], requires_grad=True)
tensor([ 0.0045, -0.0038,  0.5436,  0.5305], requires_grad=True)
tensor([ 0.0044, -0.0033,  0.5436,  0.5306], requires_grad=True)
tensor([ 0.0046, -0.0035,  0.5436,  0.5304], requires_grad=True)
tensor([ 0.0042, -0.0039,  0.5432,  0.5310], requires_grad=True)
tensor([ 0.0045, -0.0046,  0.5432,  0.5310], requires_grad=True)
tensor([ 0.0046, -0.0049,  0.5428,  0.5317], requires_grad=True)
tensor([ 0.0046, -0.0047,  0.5429,  0.5318], requires_grad=True)
tensor([ 0.0044, -0.0042,  0.5430,  0.5319], requires_grad=True)
tensor([ 0.0048, -0.0043,  0.5432,  0.5318], requires_grad=True)
tensor([ 0.0048, -0.0045,  0.5429,  0.5319], requires_grad=True)
tensor([ 0.0054, -0.0051,  0.5427,  0.5318], requires_grad=True)
tensor([ 0.0056, -0.0050,  0.5422,  0.5317], requires_grad=True)
tensor([ 0.0052, -0.0050,

tensor([ 0.0020, -0.0035,  0.5453,  0.5317], requires_grad=True)
tensor([ 0.0020, -0.0032,  0.5452,  0.5317], requires_grad=True)
tensor([ 0.0020, -0.0030,  0.5449,  0.5319], requires_grad=True)
tensor([ 0.0018, -0.0021,  0.5446,  0.5324], requires_grad=True)
tensor([ 0.0014, -0.0018,  0.5444,  0.5325], requires_grad=True)
tensor([ 0.0014, -0.0015,  0.5447,  0.5326], requires_grad=True)
tensor([ 0.0013, -0.0015,  0.5445,  0.5333], requires_grad=True)
tensor([ 0.0012, -0.0020,  0.5440,  0.5331], requires_grad=True)
tensor([ 0.0013, -0.0015,  0.5437,  0.5332], requires_grad=True)
tensor([ 0.0019, -0.0012,  0.5440,  0.5330], requires_grad=True)
tensor([ 0.0015, -0.0009,  0.5442,  0.5331], requires_grad=True)
tensor([ 0.0021, -0.0013,  0.5441,  0.5334], requires_grad=True)
tensor([ 0.0021, -0.0010,  0.5445,  0.5336], requires_grad=True)
tensor([ 0.0020, -0.0006,  0.5441,  0.5335], requires_grad=True)
tensor([ 1.8925e-03, -2.8987e-04,  5.4432e-01,  5.3355e-01],
       requires_grad=True)
te

tensor([0.0019, 0.0030, 0.5496, 0.5293], requires_grad=True)
tensor([0.0016, 0.0026, 0.5497, 0.5290], requires_grad=True)
tensor([0.0017, 0.0026, 0.5503, 0.5292], requires_grad=True)
tensor([0.0017, 0.0025, 0.5509, 0.5290], requires_grad=True)
tensor([0.0029, 0.0024, 0.5516, 0.5288], requires_grad=True)
tensor([0.0035, 0.0029, 0.5515, 0.5293], requires_grad=True)
tensor([0.0031, 0.0029, 0.5516, 0.5294], requires_grad=True)
tensor([0.0031, 0.0033, 0.5517, 0.5290], requires_grad=True)
tensor([0.0032, 0.0036, 0.5513, 0.5288], requires_grad=True)
tensor([0.0038, 0.0036, 0.5514, 0.5290], requires_grad=True)
tensor([0.0039, 0.0033, 0.5512, 0.5288], requires_grad=True)
tensor([0.0039, 0.0032, 0.5512, 0.5290], requires_grad=True)
tensor([0.0042, 0.0028, 0.5523, 0.5289], requires_grad=True)
tensor([0.0040, 0.0030, 0.5529, 0.5293], requires_grad=True)
tensor([0.0040, 0.0032, 0.5526, 0.5300], requires_grad=True)
tensor([0.0039, 0.0031, 0.5523, 0.5300], requires_grad=True)
tensor([0.0041, 0.0037, 

tensor([ 0.0078, -0.0046,  0.5509,  0.5319], requires_grad=True)
tensor([ 0.0078, -0.0052,  0.5506,  0.5321], requires_grad=True)
tensor([ 0.0078, -0.0055,  0.5505,  0.5321], requires_grad=True)
tensor([ 0.0071, -0.0051,  0.5511,  0.5320], requires_grad=True)
tensor([ 0.0075, -0.0050,  0.5512,  0.5317], requires_grad=True)
tensor([ 0.0073, -0.0052,  0.5510,  0.5317], requires_grad=True)
tensor([ 0.0076, -0.0052,  0.5511,  0.5315], requires_grad=True)
tensor([ 0.0079, -0.0051,  0.5507,  0.5319], requires_grad=True)
tensor([ 0.0083, -0.0049,  0.5508,  0.5317], requires_grad=True)
tensor([ 0.0083, -0.0045,  0.5508,  0.5316], requires_grad=True)
tensor([ 0.0082, -0.0046,  0.5506,  0.5315], requires_grad=True)
tensor([ 0.0082, -0.0047,  0.5502,  0.5314], requires_grad=True)
tensor([ 0.0075, -0.0043,  0.5508,  0.5317], requires_grad=True)
tensor([ 0.0081, -0.0045,  0.5509,  0.5315], requires_grad=True)
tensor([ 0.0081, -0.0044,  0.5507,  0.5314], requires_grad=True)
tensor([ 0.0082, -0.0045,

tensor([ 0.0116, -0.0056,  0.5545,  0.5331], requires_grad=True)
tensor([ 0.0112, -0.0060,  0.5544,  0.5336], requires_grad=True)
tensor([ 0.0111, -0.0061,  0.5539,  0.5337], requires_grad=True)
tensor([ 0.0110, -0.0056,  0.5541,  0.5337], requires_grad=True)
tensor([ 0.0112, -0.0055,  0.5541,  0.5336], requires_grad=True)
tensor([ 0.0110, -0.0054,  0.5540,  0.5334], requires_grad=True)
tensor([ 0.0121, -0.0054,  0.5544,  0.5333], requires_grad=True)
tensor([ 0.0120, -0.0056,  0.5541,  0.5331], requires_grad=True)
tensor([ 0.0120, -0.0059,  0.5538,  0.5333], requires_grad=True)
tensor([ 0.0122, -0.0063,  0.5535,  0.5340], requires_grad=True)
tensor([ 0.0122, -0.0060,  0.5531,  0.5339], requires_grad=True)
tensor([ 0.0122, -0.0054,  0.5528,  0.5338], requires_grad=True)
tensor([ 0.0122, -0.0061,  0.5527,  0.5341], requires_grad=True)
tensor([ 0.0122, -0.0063,  0.5533,  0.5340], requires_grad=True)
tensor([ 0.0121, -0.0065,  0.5533,  0.5338], requires_grad=True)
tensor([ 0.0124, -0.0066,

tensor([ 0.0126, -0.0068,  0.5496,  0.5365], requires_grad=True)
tensor([ 0.0126, -0.0071,  0.5491,  0.5364], requires_grad=True)
tensor([ 0.0122, -0.0066,  0.5491,  0.5368], requires_grad=True)
tensor([ 0.0125, -0.0069,  0.5491,  0.5369], requires_grad=True)
tensor([ 0.0120, -0.0071,  0.5490,  0.5371], requires_grad=True)
tensor([ 0.0122, -0.0073,  0.5492,  0.5371], requires_grad=True)
tensor([ 0.0122, -0.0069,  0.5491,  0.5369], requires_grad=True)
tensor([ 0.0121, -0.0070,  0.5486,  0.5370], requires_grad=True)
tensor([ 0.0115, -0.0065,  0.5489,  0.5367], requires_grad=True)
tensor([ 0.0115, -0.0064,  0.5487,  0.5372], requires_grad=True)
tensor([ 0.0121, -0.0060,  0.5485,  0.5370], requires_grad=True)
tensor([ 0.0110, -0.0056,  0.5495,  0.5368], requires_grad=True)
tensor([ 0.0113, -0.0062,  0.5500,  0.5372], requires_grad=True)
tensor([ 0.0117, -0.0061,  0.5501,  0.5368], requires_grad=True)
tensor([ 0.0116, -0.0060,  0.5497,  0.5364], requires_grad=True)
tensor([ 0.0120, -0.0058,

tensor([ 0.0085, -0.0052,  0.5515,  0.5396], requires_grad=True)
tensor([ 0.0082, -0.0052,  0.5518,  0.5395], requires_grad=True)
tensor([ 0.0085, -0.0049,  0.5518,  0.5391], requires_grad=True)
tensor([ 0.0085, -0.0049,  0.5515,  0.5394], requires_grad=True)
tensor([ 0.0087, -0.0042,  0.5516,  0.5397], requires_grad=True)
tensor([ 0.0084, -0.0044,  0.5516,  0.5399], requires_grad=True)
tensor([ 0.0081, -0.0043,  0.5517,  0.5398], requires_grad=True)
tensor([ 0.0080, -0.0041,  0.5515,  0.5397], requires_grad=True)
tensor([ 0.0085, -0.0042,  0.5516,  0.5396], requires_grad=True)
tensor([ 0.0083, -0.0036,  0.5517,  0.5400], requires_grad=True)
tensor([ 0.0088, -0.0037,  0.5520,  0.5398], requires_grad=True)
tensor([ 0.0091, -0.0033,  0.5517,  0.5396], requires_grad=True)
tensor([ 0.0088, -0.0035,  0.5516,  0.5394], requires_grad=True)
tensor([ 0.0090, -0.0033,  0.5515,  0.5394], requires_grad=True)
tensor([ 0.0088, -0.0031,  0.5514,  0.5390], requires_grad=True)
tensor([ 0.0088, -0.0026,

tensor([0.0072, 0.0016, 0.5494, 0.5442], requires_grad=True)
tensor([0.0075, 0.0016, 0.5493, 0.5439], requires_grad=True)
tensor([0.0072, 0.0018, 0.5492, 0.5439], requires_grad=True)
tensor([0.0072, 0.0022, 0.5489, 0.5436], requires_grad=True)
tensor([0.0074, 0.0024, 0.5489, 0.5434], requires_grad=True)
tensor([0.0078, 0.0027, 0.5487, 0.5436], requires_grad=True)
tensor([0.0081, 0.0026, 0.5487, 0.5439], requires_grad=True)
tensor([0.0079, 0.0025, 0.5485, 0.5443], requires_grad=True)
tensor([0.0076, 0.0028, 0.5484, 0.5446], requires_grad=True)
tensor([0.0067, 0.0023, 0.5485, 0.5446], requires_grad=True)
tensor([0.0070, 0.0026, 0.5494, 0.5445], requires_grad=True)
tensor([0.0074, 0.0024, 0.5490, 0.5444], requires_grad=True)
tensor([0.0072, 0.0024, 0.5489, 0.5441], requires_grad=True)
tensor([0.0074, 0.0028, 0.5486, 0.5440], requires_grad=True)
tensor([0.0069, 0.0027, 0.5490, 0.5439], requires_grad=True)
tensor([0.0071, 0.0025, 0.5488, 0.5442], requires_grad=True)
tensor([0.0073, 0.0025, 

In [170]:
rho_to_sigma(torch.tensor(0.5488))

tensor(1.0047)